packages/dendron-cli/src/commands/__tests__/__snapshots__/build-site.spec.ts.snap, packages/dendron-cli/src/commands/__tests__/__snapshots__/build-site.v2.spec.ts.snap, packages/engine-server/package.json, packages/engine-server/src/__tests__/__snapshots__/enginev2.spec.ts.snap, packages/engine-server/src/topics/markdown/__snapshots__/markdown.spec.ts.snap, packages/engine-server/src/topics/markdown/__tests__/__snapshots__/utilsv2.spec.ts.snap, packages/engine-server/src/topics/markdown/markdown.spec.ts, packages/engine-server/src/topics/markdown/plugins/__tests__/__snapshots__/dendronRefsPlugin.spec.ts.snap, packages/engine-server/src/topics/markdown/plugins/__tests__/__snapshots__/denronNoteRefPlugin.spec.ts.snap, packages/engine-server/src/topics/markdown/remark-abbr.d.ts, packages/engine-server/src/topics/markdown/utils.ts, packages/engine-server/src/topics/markdown/utilsv2.ts
The Markdown source:
HTML
*[HTML]: HyperText Markup Language
Will now be preserved, allowing renderers (e.g. Jekyll) to emit:
<abbr title="HyperText Markup Language">HTML</abbr>
=> feat(publishing): preserve abbreviations

packages/plugin-core/src/components/lookup/LookupController.ts, packages/plugin-core/src/test/suite-integ/LookupCommand.test.ts, packages/plugin-core/src/utils.ts
Fixes #122
- Don't throw an exception in genNoteNameOnly when called from outside of a note if opts.overrides.domain is passed.
- Call DendronClientUtilsV2 rather than VSCodeUtils when creating a journal or scratch from LookupController
=> Don't throw an exception in genNoteNameOnly when opts are passed

packages/plugin-core/assets/jekyll/Gemfile, packages/plugin-core/assets/jekyll/_config.yml
Hi. While [running the publishing jekyll server locally](https://www.dendron.so/notes/63b184f7-1901-4580-af40-97ef87069a04.html), I noticed two jekyll files were out of date. I think these changes are correct but perhaps I'm mistaken. Cheers
=> Reference dendron gem for publishing

packages/plugin-core/package.json, packages/plugin-core/src/_extension.ts
Hi team!
I started off a bit frustrated and almost requested a feature, but I figured it was simple enough I might be able to figure it out on my own and learn a bit of extension writing.  
Essentially, I did not like "Dendron Tree View" and "Backlinks" in my view pane while working in non-Dendron workspaces.  I know these can be toggled off, but I thought it better if Dendron managed this itself.  This PR enables Dendron view panes selectively (i.e., when Dendron is actually active) [using 'when' contexts](https://code.visualstudio.com/api/extension-guides/command#using-a-custom-when-clause-context).  I am not entirely sure if this covers every place Dendron becomes active, but the manual testing I completed shows the idea works.
I am not sure how to write a test for this.  Ideally, I …
=> Toggle plugin views using 'when' contexts

packages/common-all/src/nodev2.ts, packages/common-test-utils/src/presets/engine-server/write.ts
removed the post-formatting for the title to remain true to the original input casing.
=> fixed note creation not respecting title case issue #344

README.md
replace 
https://github.com/dendronhq/dendron-template/blob/master/vault/dendron.faq.md
with
https://dendron.so/notes/683740e3-70ce-4a47-a1f4-1f140e80b558.html
=> fix broken FAQ link

packages/plugin-core/src/components/lookup/LookupControllerV2.ts, packages/plugin-core/src/test/suite-integ/LookupCommand.test.ts
closes #410 
- Checks source of extracted text when creating a new note using lookup with `selectExtraction` enabled.
- If it does not come from a known vault, do not remove and autosave original selection
- No change in behavior if extracted text comes from a known vault
- Added test for said fix.
=> Check if extracted text comes from known vault when creating a new note with lookup

packages/plugin-core/package.json, packages/plugin-core/src/commands/PasteLink.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/PasteLink.test.ts, packages/plugin-core/src/utils.ts, yarn.lock
- Reduce the effort needed to create a new note about a web resource. See #329 for more details.
- Added the `open-graph-scraper` package + types
- Added and registered a `PasteLink` command without keyboard shortcuts (P and L are both taken, so I didn't want to overthink it). It searches the opengraph meta tags for "titles" to use in markdown
- See https://a.cl.ly/9Zu8yXgr for a demo. 
- Not sure if testing this command is required since we just depends on a network request - should that be mocked? If not, do we need a test for just the "string building" capability?
<details>
<summary>(click to expand)</summary>
As this is my 1st Dendron PR, I saved notes about things I'm likely to look up someday / may be useful to other first time contributors.
- Commands to add new packages
```bash …
```
=> [feature][plugin-core][commands] Add PasteLink Command

packages/engine-server/src/config.ts
Ran into this error today. Fixing the typo in the output.
=> Fix siteUrl typo in cli error throw output

packages/engine-server/src/workspace.ts, packages/plugin-core/src/test/suite-integ/VaultAddCommand.test.ts, packages/plugin-core/src/test/suite-integ/VaultRemoveCommand.test.ts, packages/plugin-core/src/test/testUtilsV3.ts
Closes #505 
- clean up `duplicateNoteBehavior` configuration after vault is removed
- test said fix
- move `stubVaultInput` to test utils. (Sorry if this is introducing noise to the PR, but I needed that stub to write the tests for my fixes 😅 )
=> Clean up config after vault remove command

packages/plugin-core/src/test/suite-integ/BacklinksTreeDataProvider.test.ts, packages/plugin-core/src/test/suite-integ/ConfigurePod.spec.ts, packages/plugin-core/src/test/suite-integ/CopyNoteRef.test.ts, packages/plugin-core/src/test/suite-integ/CreateDailyJournalNote.test.ts, packages/plugin-core/src/test/suite-integ/DefinitionProvider.test.ts, packages/plugin-core/src/test/suite-integ/DeleteNodeCommand.test.ts, packages/plugin-core/src/test/suite-integ/DoctorCommand.test.ts, packages/plugin-core/src/test/suite-integ/DocumentLinkProvider.test.ts, packages/plugin-core/src/test/suite-integ/FileWatcher.test.ts, packages/plugin-core/src/test/suite-integ/GoDownCommand.test.ts, packages/plugin-core/src/test/suite-integ/GoUpCommand.test.ts, packages/plugin-core/src/test/suite-integ/GotoNote.test.ts, packages/plugin-core/src/test/suite-integ/LookupCommand.test.ts, packages/plugin-core/src/test/suite-integ/LookupCommandMulti.test.ts, packages/plugin-core/src/test/suite-integ/RefactorHierarchy.test.ts, packages/plugin-core/src/test/suite-integ/ReloadIndex.test.ts, packages/plugin-core/src/test/suite-integ/SetupDWorkspace.test.ts, packages/plugin-core/src/test/suite-integ/SetupWorkspace.test.ts, packages/plugin-core/src/test/suite-integ/UpgradeWorkspace.spec.ts, packages/plugin-core/src/test/suite-integ/VaultAddCommand.test.ts, packages/plugin-core/src/test/suite-integ/VaultRemoveCommand.test.ts
closes: #520 
- Fix all bare asserts to jest-like expect
- Omit changes to
- test harnesses
- commented test codes that uses bare asserts
- test code in lsp-client
=> Consolidate testing convention

packages/plugin-core/src/components/lookup/LookupControllerV2.ts
When the `go-down` command is executed at `root`, the value for the lookup is set to an empty string (will match everything) instead of `root.` (will match only itself and other notes with `root.` in the name):
https://github.com/dendronhq/dendron/blob/79580cdca8d34d2e8e0e57adc69811ddd8dcc2cc/packages/plugin-core/src/commands/GoDownCommand.ts#L22-L24
In the `LookupControllerV2`, there is a falsy check against the `quickPickValue` and when it matches the empty string, the filename of the active editor is used instead (which is `root.`):
https://github.com/dendronhq/dendron/blob/79580cdca8d34d2e8e0e57adc69811ddd8dcc2cc/packages/plugin-core/src/components/lookup/LookupControllerV2.ts#L272-L275
Seeing how `quickPickValue` is typed to be only `string` or `undefined`, I think the condition …
=> fix: go-down at root matches itself only

packages/common-test-utils/tsconfig.build.json, packages/plugin-core/src/commands/MoveNoteCommand.ts, packages/plugin-core/src/test/suite-integ/MoveNoteCommand.test.ts
This PR:
- Adds a check before prompting a user for vault selection in `MoveNoteCommand`.
- If it's a single vault setup vault selection is skipped.
- If there are multiple vaults the command will prompt the user for a vault selection.
- Adds tests for said changes. 
closes: #470
=> Check before prompting vault selection in `MoveNoteCommand`

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/pod-request-template.md, .github/ISSUE_TEMPLATE/seed-request.md, .github/ISSUE_TEMPLATE/work-item.md, .github/config/issue-labler/labler-v3.yml
Had an irritating issue happen every time I triaged something but then updated the issue, the untriaged label would get added to it again. Figured this would be a good way to address it.
=> triaged bot update

packages/common-all/src/types/typesv2.ts, packages/common-test-utils/src/presets/notes.ts, packages/engine-server/src/markdown/remark/blockAnchors.ts, packages/engine-server/src/markdown/remark/index.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-server/src/markdown/remark/wikiLinks.ts, packages/engine-server/src/markdown/types.ts, packages/engine-server/src/markdown/utils.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/dendronPub.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/backlinks.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/blockAnchors.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/dendronPub.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/wikiLink.spec.ts, packages/plugin-core/src/commands/GotoNote.ts, packages/plugin-core/src/features/DefinitionProvider.ts, packages/plugin-core/src/test/suite-integ/GotoNote.test.ts, packages/plugin-core/src/utils/md.ts
This pull request adds basic functionality for linking to block anchors. This allows links to manually inserted block anchors to function. For example, with the following files:
In `note-alpha.md`:
```
...
Lorem ipsum dolor amet
^my-block-anchor
```
In `note-beta.md`:
```
...
Fuga voluptas veniam ab
[[note-alpha#^my-block-anchor]]
```
Here, using the link in `note-beta` should take the user to `note-alpha` at the line of the block anchor.
The integration into VSCode is not there yet, so the block anchor must be inserted manually, and the anchor portion of the link must be written manually. It should work to place the anchors anywhere in the document, with the only limitations are: they must only contain letters, numbers, dashes, or underscores; they must appear at the end of a line or on …
=> feat: Basic block reference link functionality

packages/dendron-cli/src/commands/doctor.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/doctor.spec.ts, packages/plugin-core/src/commands/Doctor.ts, packages/plugin-core/src/test/suite-integ/DoctorCommand.test.ts
This PR:
- adds a new Doctor command that goes through wikilinks in all notes and create notes that are linked but does not exist yet.
related to: #355
=> Add Doctor command to create missing linked notes

packages/engine-server/src/markdown/remark/dendronPub.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/blockAnchors.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/blockAnchors.spec.ts
Block anchors were hiding their sibling nodes when generating HTML, causing them to hide the paragraph they are located in. This pull request fixes this issue, and adds a test to catch any regressions in the future.
=> fix: Block anchors hide sibling nodes in HTML

packages/common-server/src/filesv2.ts, packages/common-server/src/parser.ts, packages/common-test-utils/src/noteUtils.ts, packages/engine-server/src/drivers/file/schemaParser.ts, packages/engine-test-utils/src/__tests__/common-server/filev2.spec.ts, packages/plugin-core/src/watchers/schemaWatcher.ts
I tested this change on our org repo. With the schema files in disk cache, this is giving me around 5% improvement. The improvement should be much higher in real world conditions when loading from cold (files not in disk cache), with slow disks, and for users with lots of schemas.
=> enhance: Improve startup speed by parallelizing schema loading

packages/common-test-utils/src/utils.ts, packages/engine-server/src/markdown/remark/noteRefsV2.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-server/src/markdown/types.ts, packages/engine-server/src/markdown/utils.ts, packages/engine-server/src/utils.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/noteRefv2.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/remarkUtils.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/noteRefv2.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/remarkUtils.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/utils.ts
This pull request adds support for block references in HTML. It includes support for:
* Single block anchor references `![[note#^anchor]]`
* Range block anchor references `![[note#^anchor1:#^anchor2]]`
* Same file block references `![[#^anchor]]` and `![[#header]]`
Range block anchor references are allowed to be mixed with headers too, so it's possible to do `![[#header:#^anchor]]` or `![[#^anchor:#header]]` to reference only a part of a section.
It's also possible to reference single items in lists, or parts of lists. Consider the following list
```
* Aut id architecto quia.
* Sapiente sed accusamus eum.
* Ullam optio est quia. ^one
* Reprehenderit doloribus.
* Sint minus fuga omnis non. ^two
* Iure neque alias dolorem. ^three
```
The reference `![[#^one]]` would only reference the list …
=> feat: Block reference support in HTML

packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/enginev2.ts, packages/engine-server/src/markdown/remark/blockAnchors.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-server/src/markdown/utils.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/remarkUtils.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/blockAnchors.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/remarkUtils.spec.ts
Block anchors were not being parsed for the following examples:
```
This would get parsed as a block anchor, even though it's part of the wikilink.
[[note#^anchor]]
This would get parsed as part of the paragraph,
even though it's a block anchor inside a paragraph
that spans multiple lines.
Lorem ipsum ^anchor
dolor amet.
```
This pull request fixes both issues, and adds test for them.
=> fix: block anchor parsing in wikilinks and multi-line paragraphs

packages/dendron-cli/src/commands/backfillV2.ts, packages/dendron-cli/src/commands/doctor.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/doctor.spec.ts.snap, packages/engine-test-utils/src/__tests__/dendron-cli/commands/doctor.spec.ts, packages/plugin-core/src/commands/Doctor.ts, packages/plugin-core/src/components/doctor/buttons.ts, packages/plugin-core/src/components/doctor/types.ts, packages/plugin-core/src/test/suite-integ/DoctorCommand.test.ts
This PR:
- Adds a scope toggle button to the Doctor plugin command quickpick.
- Can toggle between `workspace` and `file`.
- Defaults to `workspace` scope.
- `createMissingLinkedNotes` action is disabled for `workspace` scope.
- Above changes are also mirrored in DoctorCLICommand by adding a new command option `candidates` where you can explicitly pass in a list of notes.
- Fixed tests that broke due to above changes.
- Skipped tests for some `createMissingLinkedNotes` that should be re-enabled once we enable workspace scope in the future.
- Added tests to for the scoped behavior.
=> Add scoping capabilities to doctor commands

packages/common-all/src/types/workspace.ts, packages/common-server/src/git.ts, packages/dendron-cli/src/commands/workspaceCLICommand.ts, packages/engine-server/src/topics/git.ts, packages/engine-server/src/workspace.ts, packages/engine-test-utils/src/__tests__/engine-server/workspace.spec.ts, packages/plugin-core/src/commands/AddAndCommit.ts, packages/plugin-core/src/commands/BrowseNoteCommand.ts, packages/plugin-core/src/commands/Sync.ts, packages/plugin-core/src/test/suite-integ/SyncCommand.test.ts
Workspace vault sync is now configurable, so users can choose whether they want workspace vaults to get synchronized, skipped, committed and pulled but not pushed, or pulled and pushed but not committed.
Non-repository vault handling has been improved. It fixes exceptions that would be thrown when:
* If some vaults were in repositories but not others.
* If a vault is not in a repository, but the Dendron workspace is.
=> enhance: Workspace sync improvements

packages/common-all/src/types/workspace.ts, packages/common-test-utils/src/presets/notes.ts, packages/plugin-core/package.json, packages/plugin-core/scripts/genConfig.ts, packages/plugin-core/src/commands/RandomNote.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/RandomNoteCommand.test.ts
Fixes https://github.com/dendronhq/dendron/issues/743 
New Command to navigate to a random note.
=> feat:Random Note Command

dendron-main.code-workspace
Minor fix to add the Prettier extension code formatter to the workspace recommended extensions
=> fix: Adding Prettier to workspace recommendations

packages/common-all/src/types/typesv2.ts, packages/dendron-next-server/components/graph-filter-view.tsx, packages/dendron-next-server/components/graph.tsx, packages/dendron-next-server/hooks/useGraphElements.tsx, packages/dendron-next-server/lib/graph.ts, packages/dendron-next-server/pages/vscode/graph-note.tsx, packages/dendron-next-server/pages/vscode/graph-schema.tsx, packages/dendron-next-server/styles/theme-antd.ts, packages/plugin-core/src/commands/ShowSchemaGraph.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/windowWatcher.ts
Changes made:
- Add Schema Graph V2 from dev mode
- When selecting schema node, open schema in VSCode
- Allow for note graph filtering based on hierarchy and linked note connections
=> Add initial note filtering, schema graph

packages/common-all/src/constants.ts, packages/common-server/src/analytics.ts, packages/common-test-utils/src/fileUtils.ts, packages/engine-test-utils/src/__tests__/engine-server/segmentClient.spec.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/DisableTelemetry.ts, packages/plugin-core/src/commands/EnableTelemetry.ts, packages/plugin-core/src/telemetry.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/test/suite-integ/Telemetry.test.ts, packages/plugin-core/src/utils.ts, packages/plugin-core/src/workspace.ts
If telemetry is disabled in VSCode preferences, it will be respected by Dendron. Additionally, users can force enable Dendron telemetry even when it's disabled in VSCode preferences by running the command `Dendron: Enable Telemetry`.
closes #711 
Also completed the `DisposableStore` stub because I happened to come across it. Let me know if I should avoid it for now and I can pick that commit out.
=> enhance: Telemetry respects VSCode preferences

packages/engine-server/src/markdown/remark/index.ts, packages/plugin-core/src/fileWatcher.ts
Should work for #817, as well as intermittent issues with GoToNote on anchors not working.
=> fix: anchors now update when note is modified

packages/engine-test-utils/src/engine.ts
Fixes the issue with a failing test causing future tests to fail with sinon errors.
=> fix: Ensure `runEngineTestV5` always restores mocks

packages/dendron-next-server/components/graph-filter-view.tsx, packages/dendron-next-server/components/graph.tsx, packages/dendron-next-server/hooks/useApplyGraphConfig.tsx, packages/dendron-next-server/hooks/useGraphElements.tsx, packages/dendron-next-server/hooks/useSyncGraphWithIDE.tsx, packages/dendron-next-server/lib/graph.ts, packages/dendron-next-server/pages/vscode/graph-note.tsx, packages/dendron-next-server/pages/vscode/graph-schema.tsx
Changes/additions made:
- No extra re-render/pan when switching VSCode windows
- On note open, select node in graph and focus in on it
- Add config option to prevent the graph from re-laying out when adjusting config
- Sensible and specified config option order
=> enhance: graph quality-of-life improvements, ability to prevent re-layout on config change

packages/plugin-core/package.json
Making the paste-image extension a part of the Dendron extension pack so that it will automatically install with Dendron
=> chore: including vscode-paste-image in extension pack

packages/plugin-core/src/commands/ImportPod.ts, packages/pods-core/src/basev3.ts, packages/pods-core/src/builtin/JSONPod.ts, packages/pods-core/src/builtin/MarkdownPod.ts, packages/pods-core/src/builtin/SnapshotPod.ts
Improving robustness / user experience in Import Pod:
- If the import configuration has invalid YAML, it shows a helpful error message to the info box.
- If any notes have issues with importation, then it won't block the rest of the import - other notes will get imported, and then an error message will show exactly which notes had issues.
=> fix/import pod YML errors

packages/dendron-next-server/pages/vscode/calendar-view.tsx, packages/engine-server/src/enginev2.ts
When creating an engine (workspace/sync) or accessing configs (config/get) of the engine the defaults defined in `packages/engine-server/src/config.ts` will be merged/used.
=> fix: load config defaults

packages/dendron-next-server/hooks/useApplyGraphConfig.tsx, packages/dendron-next-server/hooks/useGraphElements.tsx
Fixes:
- Issue where stub nodes would not reappear after being hidden
- Issue where edges connected to stub nodes would sometimes not reappear when stub visibility is re-enabled
=> fix: stub filter errors

packages/pods-core/src/builtin/GraphvizPod.ts, test-workspace/dendron.yml
Fixes issue where GraphViz export pod throws an error if the specified export directory does not exist.
=> fix: graphviz export directory error

packages/plugin-core/src/views/CalendarView.ts
[[calendar view popup on save|scratch.2021.06.20.205319.calendar-view-popup-on-save]]
=> fix(calendar-view): prevent calendar-view from popping on safe

packages/dendron-next-server/pages/vscode/calendar-view.tsx
This PR corrects opening today's daily note from the button with the right filename.
It additionally improves 2 things (see commits).
=> fix(calendar-note): correct note name from "Today" btn

packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/enginev2.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/blockAnchors.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/remarkUtils.spec.ts, packages/plugin-core/src/services/NoteSyncService.ts
Migrated block anchor parsing to V5 parsing which seems to have solved the issue.
=> fix: block anchors inside links are parsed as anchors

packages/common-all/package.json, packages/common-all/src/uuid.ts, packages/plugin-core/src/utils/editor.ts, packages/plugin-core/src/windowWatcher.ts, yarn.lock
Note IDs starting with underscores break Github pages, causing 404 errors on existing pages.
For safety, revised the code to avoid underscores and dashes in generated IDs. Also shortened the ID length while keeping it long enough that a collision is still incredibly unlikely.
#945
=> fix: avoid generating IDs containing dashes and underscores

packages/common-frontend/src/features/ide/slice.ts, packages/dendron-next-server/components/graph-filter-view.tsx, packages/dendron-next-server/components/graph.tsx, packages/dendron-next-server/hooks/useGraphElements.tsx, packages/dendron-next-server/hooks/useSyncGraphWithIDE.tsx, packages/dendron-next-server/lib/graph.ts, packages/dendron-next-server/pages/vscode/graph-note.tsx, packages/dendron-next-server/pages/vscode/graph-schema.tsx, packages/plugin-core/src/commands/ShowNoteGraph.ts, packages/plugin-core/src/commands/ShowSchemaGraph.ts, test-workspace/dendron.yml
This is a DRAFT PR 🚧. More testing will be done, as this is a fairly substantial addition to the V2 graph.
Changed/added:
- Added local note graph, a one-level-deep graph with direct hierarchical and linked connections from the current active note
- Made local note graph the default graph, with an option to view the full graph
- Enabled link connections on by default to fill out the local note graph
- Minor styling/rendering tweaks to enable graph switching and ease of use
=> feat: add local note graph

.eslintrc.js, packages/plugin-core/src/features/completionProvider.ts, packages/plugin-core/src/test/suite-integ/CompletionProvider.test.ts, packages/plugin-core/src/windowWatcher.ts
This pull request changes it so that notes from the current vault will appear before notes from other vaults. This order is only initially however, VSCode may change the order as the user types to narrow the selection.
This partially helps #887. I have more features planned to improve it further.
=> feat: wikilink autocomplete sorts current vault notes before other notes

packages/plugin-core/src/logger.ts, packages/plugin-core/src/test/suite-integ/BacklinksTreeDataProvider.test.ts, packages/plugin-core/src/test/suite-integ/ConfigureCommand.test.ts, packages/plugin-core/src/test/suite-integ/CreateHookCommand.test.ts, packages/plugin-core/src/test/suite-integ/DefinitionProvider.test.ts, packages/plugin-core/src/test/suite-integ/GoToSibling.test.ts, packages/plugin-core/src/test/suite-integ/LookupCommand.test.ts, packages/plugin-core/src/test/suite-integ/MoveNoteCommand.test.ts, packages/plugin-core/src/test/suite-integ/SyncCommand.test.ts, packages/plugin-core/src/test/suite-integ/VaultRemoveCommand.test.ts
Fixing test compat issues that prevent the tests from running/succeeding on Windows:
1) Various Path Issues
- Some API's have a lower case vs upper-case for the drive prefix; i.e. `c:\` vs `C:\`.  We need to always  do case-insensitive string comparisons when doing file path checks.
- The usual `\` vs `/` issues.
- Some parameter spacing problems when invoking the Git command
2) Logger Issues - There's a file handle problem that occurs on Windows with fs/fs-extra that prevents a rename on the log file and leads to the following error.  We can just wrap in try/catch as it's not very important where the log ends up during the test:
```log
Error: EPERM: operation not permitted, rename 'C:\Users\jonat\AppData\Local\Temp\tmp-3032-7f5nAzN3323h\dendron.log' -> …
```
=> chore: test compat on windows

.eslintrc.js, packages/plugin-core/src/features/windowDecorations.ts, packages/plugin-core/src/test/suite-integ/WindowDecorations.test.ts, yarn.lock
Wikilinks are now highlighted, with the aliases being italicized. If the note is not found, then these are highlighted differently to make them stand out.
I'm not sure if these are a good way to highlight wikilinks, so I'd like some feedback on what people think.
Dark theme: 
Light theme:
=> feat: editor highlighting for wikilinks & references

packages/common-all/src/analytics.ts, packages/engine-server/src/metadata/service.ts, packages/engine-test-utils/src/engine.ts, packages/plugin-core/package.json, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts
Prompt users with a modal dialog to get started with Dendron under the following conditions:
1) Have not initialized a workspace before
2A) >1 week since install
2B) >1 week since last reminder prompt.
=> feat: lapsed user prompt

packages/engine-server/src/markdown/remark/dendronPreview.ts
This should help us diagnose issues around preview not displaying images in the future. I'm having trouble diagnosing or reproducing #876 and we do not have sufficient logs to figure out what's wrong.
I wasn't sure how to access the logger here, most code that does logging in `engine-server` uses the logger attached to the engine object, but this code doesn't have direct access to the engine. It only has the engine through proc data, which is an engine client type and doesn't have the logger. Just creating a new logger was the easiest option I could come up with, but we could do something more substantial like attaching a logger to proc.
=> chore: log info when previewing images

packages/plugin-core/src/commands/RefactorHierarchyV2.ts
This PR:
- Passes output of `match text` input to prefill `replace prefix` input box.
=> enhance: prefill `replace prefix` input box with output of `match text` input box

packages/plugin-core/src/test/suite-integ/ReferenceProvider.test.ts, packages/plugin-core/src/utils/md.ts
Fixes issues when hovering above the header part of a wikilink.
=> fix: anchors within wikilinks interpreted as hashtags

packages/common-all/src/types/typesv2.ts, packages/common-frontend/src/features/ide/slice.ts, packages/dendron-next-server/components/graph.tsx, packages/dendron-next-server/hooks/useGraphElements.tsx, packages/dendron-next-server/pages/_app.tsx, packages/plugin-core/package.json, packages/plugin-core/src/commands/ConfigureGraphStyles.ts, packages/plugin-core/src/commands/ShowNoteGraph.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/styles.ts, yarn.lock
Additions and changes:
- [d] Support Obsidian.md format
=> feat: add custom graph styling support

packages/plugin-core/assets/dendron-ws/tutorial/tutorial.2-taking-notes.md, packages/plugin-core/assets/dendron-ws/tutorial/tutorial.4-rich-formatting.md
- Delete 404 (and redundant link, it's already shown at the beginning of the tutorial)
- Fix image link
- Temporarily remove ==highlighting== example, as it doesn't work with the new preview.
=> fix:minor tutorial fixes

packages/plugin-core/src/test/suite-integ/CreateDailyJournalNote.test.ts, packages/plugin-core/src/utils.ts
This PR:
- Fixes issue with journal and scratch note creation configuration still using values from deprecated config location.
related to: #944
=> fix: Use new config when creating special notes

packages/dendron-cli/src/commands/doctor.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/doctor.spec.ts, packages/plugin-core/src/commands/Doctor.ts, packages/plugin-core/src/test/suite-integ/DoctorCommand.test.ts
This PR:
- Removes scope restriction that was on `createMissingLinkedNotes` of Doctor command
- Add default behavior said command in multi-vault workspace to ignore missing links that don't specify vault prefix.
- Enable tests that were marked as skipped because of scope restriction
- Add tests for newly added default behavior on multi-vault workspaces.
=> chore: lift scope restriction for doctor command `createMissingLinkedNotes`

packages/engine-server/src/markdown/remark/hashtag.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/hashtag.spec.ts
Fixes an issue with hashtags duplicating the text following them in their links.
=> fix: hashtags links duplicate the text following them

packages/dendron-next-server/components/graph-filter-view.tsx, packages/dendron-next-server/components/graph.tsx, packages/dendron-next-server/package.json, yarn.lock
Adds a small button to the top left of the graph which shows/hides the graph when clicked. Filter view will no longer be shown unless the button is clicked.
=> feat: add hideable graph filter view

packages/engine-server/src/markdown/remark/utils.ts, packages/engine-server/src/markdown/remark/wikiLinks.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/wikiLink.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/wikiLink.spec.ts, packages/plugin-core/src/test/presets/GotoNotePreset.ts, packages/plugin-core/src/test/suite-integ/CopyNoteLink.test.ts, packages/plugin-core/src/test/suite-integ/GotoNote.test.ts, packages/plugin-core/src/utils/editor.ts, test-workspace/vault/dendron.ref.links.md
Wikilinks containing apostrophes were failing to parse, that's now fixed.
Also #958 and #959. The correct links should be generated now, both in the editor and in publishing, and "Copy Note Link" will recognize the link and avoid adding a block anchor.
=> fix: wikilink aliases with apostrophes & headers containing wikilinks

packages/dendron-11ty/raw-assets/sass/_portal.scss, packages/dendron-11ty/raw-assets/sass/support/_functions.scss, packages/dendron-next-server/styles/scss/_portal.scss, packages/dendron-next-server/styles/scss/support/_functions.scss
Division using a slash has been [deprecated in sass](https://sass-lang.com/documentation/breaking-changes/slash-div), updating to use the new syntax.
=> chore: fix deprecated division in sass

packages/plugin-core/src/commands/LookupCommand.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/components/lookup/types.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
This PR:
- Adds modifier buttons for `selection2link` and `selectionExtract`
***
=> feat: add selection modifier buttons to lookup V3

packages/plugin-core/src/features/completionProvider.ts, yarn.lock
Instead of repeated calls to `getNotesByFname` which causes quadratic complexity (for each note, we scan all notes), we just count how many notes by the same fname exist ahead of time.
=> fix: autocomplete quadratic complexity

packages/common-all/src/types/workspace.ts, packages/dendron-next-server/components/graph.tsx, test-workspace/dendron.yml
**Adds:**
Ability to configure zoom speed for the graph.
**To test:**
Add the following property to your `dendron.yml`, reload the window, and open the note or schema graph. The default zoomSpeed is 1.
```
graph:
zoomSpeed: 1
```
=> feat(community issue): graph zoom speed option

packages/plugin-core/src/commands/LookupCommand.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/components/lookup/LookupControllerV3.ts, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/components/lookup/types.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts, yarn.lock
This PR:
- Adds scratch modifier to lookup V3
- Adds tests for scratch modifier
- Adds tests for interaction between the scratch and journal modifier
fyi: this branch is already rebased to be on top of `feat/journal-lookupv3`. See #1009
=> feat: scratch modifier for lookup V3

packages/plugin-core/src/commands/LookupCommand.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
This PR:
- Adds horizontal split modifier to `NoteLookupCommand`
- Adds test for said modifier
=> feat: Add horizontal split modifier to lookup v3

packages/engine-server/src/markdown/remark/hashtag.ts, packages/engine-test-utils/package.json, packages/engine-test-utils/src/__tests__/engine-server/markdown/hashtag.spec.ts, packages/plugin-core/src/test/suite-integ/CompletionProvider.test.ts
Hashtags are now not allowed to contain any punctuation or quotation marks. This allows them to be more easily mixed into text, for example:
```
This issue is #important, and should be prioritized.
This issue is #important. It should be prioritized.
They said "This issue is #important", so it should be prioritized.
```
In all these examples, the tag is `#important` without the following marks.
#1048
=> fix: hashtags include punctuation and quotation marks

packages/plugin-core/src/features/windowDecorations.ts
When only a single wikilink is left, erasing a part of it so that it's no longer a valid wikilink would not update the decoration, leaving the broken wikilink highlighted.
#1039
=> fix: clear out decoration types that have no decorations

packages/api-server/src/routes/note.ts, packages/common-all/src/api.ts, packages/common-all/src/types/typesv2.ts, packages/engine-server/src/engineClient.ts, packages/engine-server/src/enginev2.ts, packages/engine-test-utils/src/presets/engine-server/getNoteBlocks.ts, packages/plugin-core/src/features/completionProvider.ts, test-workspace/scripts/randomNote.js, test-workspace/scripts/random_text_generator_node.js
When doing an existing blocks only autocomplete (`[[#` or `[[#^`) the blocks are filtered on the server side rather than the client side. This improves responsiveness in the editor for long notes since less work is done within the editor.
=> enhance: performance improvement for block/header autocomplete

.all-contributorsrc
- Adding an emoji entry for myself since https://github.com/dendronhq/dendron/pull/512 was shipped before the contributions bot was added to the project
=> docs: Add code contrib tag for @hydrosquall

packages/common-all/src/uuid.ts, packages/dendron-cli/src/commands/doctor.ts, packages/plugin-core/src/test/suite-integ/DoctorCommand.test.ts, packages/plugin-core/src/utils/editor.ts, packages/pods-core/src/builtin/MarkdownPod.ts
Note IDs use 21 character ids, the default for a nanoid.
The insecure generator, which is used in limited cases like block anchors and assets in markdown imports, use much shorter 12 character ids. This is still safe since these are used in limited cases where conflicts are unlikely, e.g. you would need over 9 billion block anchors within the same note before you have just 1% chance of a conflict.
Also adds a Doctor action which regenerates note ids. Users who wish to keep their note ids consistent can use this command to regenerate all ids. 
#1044
=> chore: switch back to 21 character note ids & add doctor action to regenerate note ids

packages/plugin-core/src/commands/CreateDailyJournal.ts, packages/plugin-core/src/commands/LookupCommand.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/components/lookup/LookupControllerV2.ts, packages/plugin-core/src/components/lookup/LookupControllerV3.ts, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/components/lookup/types.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/test/suite-integ/LookupCommand.test.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts, packages/plugin-core/src/utils.ts
This PR:
- Adds horizontal split modifier (#1045)
- Adds copy note link modifier (#1046)
- Adds tests for various modifier interactions
=> feat: add remaining modifiers to NoteLookup

packages/plugin-core/src/features/windowDecorations.ts
In some cases, highlighting would not get displayed. The issue was caused by a bug where unused decorators were being discarded rather than emptied. This would silently break highlighting as any type of highlighting that becomes unused is discarded and no longer can be displayed.
=> fix: highlighting is not displayed

packages/plugin-core/src/scripts/uninstallHook.ts
Attempting a fix on the uninstall hook analytics by forcing a flush. 
Due to lack of a good methodology, this hasn't been tested.
=> fix: uninstall hook force flush

packages/plugin-core/src/_extension.ts
Part 2 of lapsed user change, part 1 is https://github.com/dendronhq/dendron/pull/1002/files
For any user that has never sent an initialize workspace event AND has not opened a Dendron workspace in the past ~3 weeks (since we released the code in https://github.com/dendronhq/dendron/pull/1002/files), then we'll prompt a modal dialog asking them to launch the tutorial experience.
=> feat: re-engage lapsed users with prompt

packages/common-test-utils/src/utils.ts, packages/engine-test-utils/src/presets/engine-server/rename.ts, packages/engine-test-utils/src/utils/index.ts
Tests in `engine-server/rename.ts` were being run in the plugin, which was then failing because the `expect` is not defined. The failed tests would print out errors, but would still pass.
I worked around the failure, another alternative would be to completely strip out the `expect` or avoid the `checkFile` functions in `rename.ts` tests. I haven't investigated why the tests were passing despite the error.
=> chore: bad `expect` in plugin tests

packages/common-all/src/types/typesv2.ts, packages/common-frontend/package.json, packages/common-frontend/src/features/ide/slice.ts, packages/common-frontend/src/features/index.ts, packages/dendron-next-server/pages/_app.tsx, packages/dendron-next-server/pages/vscode/calendar-view.tsx, yarn.lock
This is a follow up issue from https://github.com/dendronhq/dendron/pull/1065#pullrequestreview-721482799
- It includes:
- ~~[ ] journal.addBehavior: change to other add behavior and see if it works~~
- adds `redux-logger` to have redux actions visible inside vscode (redux devtools don't work there)
- fixes:
- issue with `syncNote` which gets called with `note` being `undefined`.
- calendar-view's memo `isEqual` function to rather consider `engine.notes.length`
=> feat(calendar-view): allow journal settings deviating from defaults

packages/common-all/src/analytics.ts, packages/plugin-core/.vscode/launch.json, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/utils.ts
This PR:
- Adds the ability to resolve vim keybinding conflict on initial install ( cmd/ctrl + l )
- Adds tests
- Adds `Extension Integ Tests - File (with extension)`
Note that one of the tests only works if you don't pass in `--disable-extensions` for the integ test. I have added a separate launch configuration for this for now.
=> feat: resolve vim keybinding conflict on initial install

packages/common-all/src/types/workspace.ts, packages/dendron-next-server/pages/workspace/config.tsx, packages/engine-server/src/config.ts, packages/engine-server/src/migrations/migrations.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts
This PR:
- Adds new default configuration for NoteLookupCommand.
- Change `NoteLookupCommand` to respect default configuration.
- Fixes breaking tests that are affected by the new configuration.
- Adds migration (placeholder until release version is confirmed) for new configuration.
=> chore: add note lookupv3 default configs

packages/plugin-core/src/components/lookup/LookupProviderV3.ts
This PR:
- fixes an issue with the debounced picker value updating.
- see [[investigate debounce issue|scratch.2021.08.09.201548.investigate-debounce-issue]]
=> fix: properly debounce picker update

packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts, test-workspace/vault/book.md, test-workspace/vault/book.schema.yml, test-workspace/vault/templates.book.md
This PR:
- Adds the ability to apply schema templates on new note creation in `NoteLookupCommand`
- Adds basic tests for schema template
- Adds example schema and template in test-workspace
=> feat: add schema templating feature to NoteLookupCommand

.gitignore, packages/engine-server/src/config.ts
Like `getProp` also inherits from default values this commit makes the
behavior consistent.
The reason this came up was because calendar-view broke with `dendron.yml` not having a `journal` field.
Inheriting from the default values when getting the config object makes
the `journal` config values available for example in
`CreateDailyJournal.ts` where the error happend.
=> fix: patch `getOrCreate` to inherit from default values

packages/plugin-core/src/components/lookup/LookupControllerV3.ts, packages/plugin-core/src/components/lookup/LookupProviderV2.ts, packages/plugin-core/src/components/lookup/LookupProviderV3.ts, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/components/lookup/types.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts, test-workspace/dendron.code-workspace, test-workspace/dendron.yml, test-workspace/vault/egg.md, test-workspace/vault/egg.one.md, test-workspace/vault2/egg.md, test-workspace/vault2/egg.two.md, test-workspace/vault3/egg.md, test-workspace/vault3/egg.three.md, test-workspace/vault3/root.md, test-workspace/vault3/root.schema.yml
This PR:
- Fixes an issue in Lookup (v2) where the direct child filter would be applied _after_ pagination has happened, which allowed some values to be omitted from the selectable items.
- Adds example notes that demonstrate the fix.
=> fix: issue with direct child filter partially omitting values in quickpick

packages/common-test-utils/src/presets/notes.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-test-utils/src/__tests__/pods-core/MarkdownPod.spec.ts, packages/engine-test-utils/src/__tests__/pods-core/__snapshots__/MarkdownPod.spec.ts.snap
Adds a leading slash during wikilink conversion from dot notation to slash notation. Improves compat with other markdown parsers for wikilinks.
=> fix: leading slash in markdown export pod

packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
This PR:
- Adds title override in note lookup when the journal modifier is pressed.
- Modifies basic test to check override
=> feat: add journal title override to NoteLookupCommand

packages/engine-server/src/markdown/utilsv5.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/utilsv5.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/utilsv5.spec.ts
This PR:
- Fixes issue with note ref rendering in preview where the note ref's title was unnecessarily inserted.
=> fix: don't insert title when rendering note refs in preview

packages/engine-server/src/markdown/remark/noteRefsV2.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/noteRefv2.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/noteRefv2.spec.ts
Allows wildcard anchors at the end of the notes to work. For example,
```
...
something
```
Here, `![[note#foo:#*]]` used to warn about not finding a header, but it will now show the region from "foo" to the end of the note. 
#1131
=> enhance: allow wildcard anchors at the end of note

packages/plugin-core/package.json, packages/plugin-core/src/commands/GoDownCommand.ts, packages/plugin-core/src/commands/GotoNote.ts, packages/plugin-core/src/commands/LookupCommand.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/components/lookup/LookupControllerV2.ts, packages/plugin-core/src/components/lookup/LookupProviderV2.ts, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/components/lookup/types.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/GoDownCommand.test.ts, packages/plugin-core/src/test/suite-integ/LookupCommand.test.ts, packages/plugin-core/src/test/suite-integ/LookupCommandMulti.test.ts, packages/plugin-core/src/test/suite-integ/LookupJournal.test.ts, packages/plugin-core/src/test/suite-integ/LookupScratch.test.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts, packages/plugin-core/src/workspace.ts
This PR:
- Moves exports from v2 related files to respective v3 component modules
- Cleans up all stale imports that reference parts of lookup v2
- Refactor GoDownCommand to use lookup v3
- Refactor LookupJournal / LookupScratch tests to use lookup v3
- Deregister lookup v2 command and related keybindings
NOTE: Test suites related to `LookupCommand`, and the v2 lookup command components are still left but commented out. Once all the test suites are re-written to test respective parts of lookup v3, the components and tests that are commented out will be removed
=> chore: transition lookup to v3

packages/common-all/src/constants.ts, packages/common-all/src/error.ts, packages/common-all/src/types/workspace.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/enginev2.ts, packages/engine-test-utils/src/presets/engine-server/init.ts, test-workspace/scripts/genNote.js
When a note is too large (over 1MiB), Dendron will avoid generating backlinks and parsing anchors. This means:
1. Any outgoing links from the large note are ignored, and will not appear in backlinks
2. Any links into the large note that target an anchor will instead go to the start of the note
Other features will continue to function, the large note can be accessed with "Lookup Note", links to the large note will function, and all other notes are unaffected. The user will be warned during startup about the large note.
=> enhance: avoid parsing links & anchors on very long notes

packages/common-all/src/types/workspace.ts, packages/engine-server/src/markdown/remark/dendronPub.ts, packages/engine-server/src/markdown/remark/noteRefsV2.ts, packages/engine-server/src/markdown/utilsv5.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/utilsv5.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/utilsv5.spec.ts
This PR:
- Fixes internal urls / backlink / children links pointing to wrong url.
- Fixes note refs rendering backlinks and children links when it shouldn't
Tasks:
=> fix: wrong internal links in nextjs publishing

packages/plugin-core/assets/dendron-ws/tutorial/tutorial.2-taking-notes.md, packages/plugin-core/assets/dendron-ws/vault/dendron.md
This PR:
- Updates mentions to `Dendron: Lookup` command to `Dendron: Lookup Note` in preparation of transitioning to lookup v3
=> chore: update mentions to old lookup command to new one

packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/engineClient.ts, packages/engine-server/src/enginev2.ts, packages/engine-test-utils/src/presets/engine-server/rename.ts
This was an [error reported on Twitter](https://twitter.com/wisdomcitynews/status/1420200694921924615), I'm not sure if there is a corresponding issue.
I believe I reproduced the issue: it occurs if some of the renamed notes don't have a frontmatter. I improved the error message to be more informative, and to also tip the user what the issue may be.
=> enhance: better error message when renaming note without id

packages/plugin-core/src/components/lookup/LookupControllerV3.ts, packages/plugin-core/src/components/lookup/LookupProviderV3.ts
This PR:
- fixes issue with direct child filter button not immediately updating picker item on trigger.
- this issue was introduced with the recent fixes to lookup v3 which stopped the update if the picker value hasn't changed since last update.
=> fix: direct child filter button trigger does not immediately update picker items

packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/components/lookup/LookupControllerV3.ts, packages/plugin-core/src/components/lookup/LookupProviderV3.ts, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/components/lookup/types.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
This PR:
- Changes `NoteLookupCommand`'s vault selection behavior to utilze the smart vault selection prompt.
- Changes vault selection behavior to:
- if `lookupConfirmVaultOnCreate`, enable vault selection button. and:
- vault selection button `on` label is changed to `always prompt`, and behavior is mapped to `VaultSelectionMode.alwaysPrompt`
- vault selection button `off` label is changed to `smart`, and behavior is mapped to `VaultSelectionMode.smart`
- if not `lookupConfirmVaultOnCreate`, behave as-is (use current vault)
- Fixes test according to changed vault selection behavior.
=> feat: Add smart vault selection to NoteLookupCommand

packages/plugin-core/src/commands/InsertNoteLink.ts
This PR:
- Handles the case where the history service action `changeState` occurs in `InsertNoteLinkCommand`
- This caused a cryptic error to be displayed on the user's end when the command is cancelled (picker is hidden without the history service being _done_).
- Handles case when user tries to insert note link when no active note is open
Related: https://github.com/dendronhq/dendron/issues/1172
=> fix: unhandled error in insert note link

packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/components/lookup/types.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
This PR:
- Adds copyNoteLink argument for NoteLookupCommand and makes it possible to pass it through custom keybindings
- Fixes copyNoteLink button effect to trigger after onAccept so that it works for new note creation as well 
- Adds tests for new behaviors
=> chore: expose copyNoteLink argument for NoteLookupCommand

packages/plugin-core/src/_extension.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/utils.ts
This PR:
- Fixes issue with lookup v3 keybinding migration so that it preserves comments and also backs up old config
- Also makes vim keybinding resolution preserve comments.
- Adds tests for this behavior
I have spent some time trying to preserve every single comment in the config, but specifically comments that users write in the `args` block of the keybinding is non-trivial to preserve, and is probably not worth the effort. I have opted for backing up the original keybinding and also showing an information message with a button to open both new and old configs instead.
=> fix: preserve keybinding comments and back up old file

packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/noteRefv2.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/noteRefv2.spec.ts
Added a test for the issue reported in #1149.
This seems to be fixed in the upcoming 0.56 version, but added the tests in case of future regression.
=> chore: test that tags section is not included in references

packages/common-all/src/types/workspace.ts, packages/plugin-core/src/components/lookup/types.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
This PR:
- Adds a new selectionType `none`, that can be explicitly set to have no selection type modifier set on lookup.
- Adds tests
NOTE: Currently, the only way to have no selection type modifier set is to define a custom keybinding with an invalid string set for `selectionType` in the `args` block. This is not intuitive, and the ability to do this should also be available for configuration in `dendron.yml`
=> enhance: ability to set selection type to none

packages/plugin-core/assets/dendron-ws/tutorial/tutorial.2-taking-notes.md
Fixes https://github.com/dendronhq/dendron/issues/1230
=> fix: fixing cmd tab typo in tutorial.2

packages/dendron-11ty/raw-assets/sass/content.scss, packages/dendron-next-server/styles/scss/content.scss, packages/engine-server/src/markdown/remark/dendronPub.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/hashtag.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/hashtag.spec.ts, packages/nextjs-template/styles/scss/content.scss, packages/plugin-core/src/features/windowDecorations.ts, packages/plugin-core/src/test/suite-integ/WindowDecorations.test.ts
In both the editor and publishing, the tags now display as small squares next to the tag link. The squares are outlined with the color of the text, which improves readability for all tag colors and all themes.
For publishing, the tag colors use [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) which means users can use the tag color property (`var(--tag-color)`) in their custom themes to adjust how the color shows up. CSS custom properties work on [all browsers except Internet Explorer](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#browser_compatibility), in which case we simply don't display the colored box.
I wasn't able to get this working in Preview V2. You can see the `.scss` file I modified under …
=> enhance: improved tag color display

packages/common-all/src/constants.ts, packages/engine-server/src/markdown/remark/dendronPub.ts, packages/engine-server/src/markdown/remark/hashtag.ts, packages/engine-server/src/markdown/remark/index.ts, packages/engine-server/src/markdown/remark/userTags.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-server/src/markdown/types.ts, packages/engine-server/src/markdown/utils.ts, packages/engine-server/src/markdown/utilsv5.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/userTags.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/userTags.spec.ts, packages/plugin-core/src/features/windowDecorations.ts, packages/plugin-core/src/test/suite-integ/GotoNote.test.ts, packages/plugin-core/src/test/suite-integ/ReferenceProvider.test.ts, packages/plugin-core/src/test/suite-integ/WindowDecorations.test.ts, packages/plugin-core/src/utils/md.ts, test-workspace/vault/dendron.ref.users.md, test-workspace/vault/user.customer.Foo.md, test-workspace/vault/user.username.md
This is a work-in-progress, but usable implementation of user mentions. User notes (notes under `user.`) can be linked to by typing `@user.name`. This is very similar to hashtags.
Features:
=> feat: user tags

hooks/pre-commit.js
Test attempt to commit 
```
import { milliseconds } from "@dendronhq/common-all/lib/timing";
console.log(milliseconds());
```
Error message looks as:
```
The following files contains 'Direct import from a package.
This check catches direct imports such as:
import { milliseconds } from "@dendronhq/common-all/lib/timing";
While the above import should look as:
import { milliseconds } from "@dendronhq/common-all";' in them:
packages/engine-test-utils/src/__tests__/api-server/assets.spec.ts
```
---- 
Was able to commit:
```
import { milliseconds } from "@dendronhq/common-all";
console.log(milliseconds());
```
=> chore: add pre-commit husky check to avoid direct imports from packages

packages/engine-server/src/config.ts, packages/engine-server/src/markdown/remark/dendronPub.ts, packages/engine-server/src/markdown/remark/noteRefsV2.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/dendronPub.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/noteRefv2.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/dendronPub.spec.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts
This PR:
- enables `config.usePrettyRefs` and `config.site.userPrettyRefs` that overrides how note references are rendered in preview and publishing respectively.
- adds tests for both cases
- updates snapshots
=> feat: enable usePrettyRefs for nextJS publishing and preview

packages/engine-server/src/markdown/remark/noteRefsV2.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/noteRefv2.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/noteRefv2.spec.ts, test-workspace/vault/dendron.ref.links.md
Referencing a list item that has children will reference not only that item but it's children as well. This PR allows a single item to be referenced using the syntax `[[#^item:#^item]]`. See following example:
I think this behavior makes sense, someone referencing an item with children likely wants those children as well. A range based reference spanning all child items would create the same result, but it is less ergonomic since the user would have to move the block anchor when adding new items.
#1233
=> enhance: reference a list item without its children

packages/nextjs-template/components/DendronLayout.tsx, packages/nextjs-template/components/DendronTreeMenu.tsx, packages/nextjs-template/styles/constants.ts, packages/nextjs-template/styles/scss/main.scss
Includes:
- shows sider toggle button only in mobile view
- adjust centered layout approach for easier coloring
- adjust tree-menu and side colors to match
Screenshot of how this looks:
)
=> nextjs-template sidebar style improvements

packages/plugin-core/package.json, packages/plugin-core/src/features/BacklinksTreeDataProvider.ts, packages/plugin-core/src/test/suite-integ/BacklinksTreeDataProvider.test.ts, packages/plugin-core/src/workspace.ts
Screenshot of the added button: 
Expand Button is added in the backlink view which will fully expand all the backlinks while the button that is pre-built (collapse all) will fully collapse all the backlinks.
=> enhance: add expandAll functionality to backlink view.

packages/engine-server/src/markdown/remark/blockAnchors.ts, packages/engine-server/src/markdown/remark/dendronPub.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/blockAnchors.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/blockAnchors.spec.ts, test-workspace/vault/dendron.ref.links.block-anchors.md
Block anchors attached to code blocks will now work in publishing. Unfortunately I was not able to attach the block anchor's link to the code block itself, `remark-rehype` simply drops it. As a workaround I place the anchor before the code block, but this causes the block anchor symbol to appear only when hovering over exactly where it should be.
=> fix: block anchors attached to code blocks in publishing

packages/nextjs-template/components/DendronCustomHead.tsx, packages/nextjs-template/package.json, packages/nextjs-template/pages/notes/[id].tsx, packages/nextjs-template/utils/build.ts, yarn.lock
This change adds support for the site configuration `customHeaderPath` to nextjs publishing.
Docs PR: https://wiki.dendron.so/notes/f2ed8639-a604-4a9d-b76c-41e205fb8713.html#customheaderpath
- The current way we do head tags is to use `next/head` to append necessary head tags on each components. (When we are not using that component, the appended elements will be unmounted)
- The built-in `Head` component that `next/head` provides does not currently allow `dangerouslySetInnerHTML` props (most likely because of their appending/unmount behavior).
- Specifically for third party scripts, nextjs recommends that we use their built-in `Script` component provided by `next/script`, which is available in next 11 (we are currently on 10).
- I have opted for introducing `html-react-parser` and …
=> feat: support custom header path in nextjs publishing

packages/plugin-core/src/features/ReferenceHoverProvider.ts, packages/plugin-core/src/test/suite-integ/ReferenceProvider.test.ts
The message for hovering over missing notes would recommend the user to Ctrl+click the link to create the missing note. However, this is only possible if the user has `noAutoCreateOnDefinition` config set to false. Corrected the message so that it only recommends Ctrl+click if this config is set.
```markdown
```
=> fix: incorrect hover missing note message

packages/engine-server/src/markdown/remark/dendronPub.ts, packages/engine-server/src/markdown/remark/hierarchies.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/dendronPub.spec.ts.snap
The main change is that the tags are now displayed in a list (respecting user defined order if it exists), and the separator is added even if there are no children (the second image wouldn't have had it before).
```markdown
```
=> fix: Frontmatter tags display similar to Children

packages/plugin-core/src/commands/MoveNoteCommand.ts, packages/plugin-core/src/workspace.ts
Remove multi select option from note rename. 
Note rename only works with a single note by design, hence multi select does not make sense to be shown on it. It got inadvertly added when adding bulk move for moving notes between vaults. 
- Two unrelated tests fail locally but they also fail on 'master' for me for a clean rebuild, hence deeming as unreleated. 
```
FAIL  src/__tests__/common-server/git.spec.ts (13.174 s)
● GitUtils › getGithubFileUrl › ok - unix separato
```
=> fix: do not show multi select button on note rename

packages/plugin-core/src/commands/MoveNoteCommand.ts
When moving notes: This change adds a progress bar notification with `Refactoring...` message in place of a notification that didn't auto hide by itself.
-- This change does contain a string that is visible to user. This string is previously used by other commands (eg. Refactor Hierarchy). However, I am not sure what this checkpoint is requesting to do. Where in test-workspace should we add the string?
=> enhance: add progress bar that goes away on its own instead of notification when moving notes

packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/components/lookup/LookupProviderV3.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
Fix scratch creation when text is selected within a note.
1. Write out a new string 
> some new string that you want to add to scratch
2. Use the create scratch note shortcut on the string. 
Expected: Just `Create New` is shown.
Actual (prior to the fix): some other scratch entries are shown. Hence, `Create New` is all the way at the bottom (can be even outside the view).
Related description of issue: [[Fix Scratch Creation|scratch.2021.08.31.091837.improve-lookup.fix-scratch-creation]]
- [d] add a [test](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#writing-tests) for the new feature, now new feature …
=> fix: creating scratch when text is selected within a note SHOULD not match scratches just due to prefix

packages/common-all/src/types/typesv2.ts, packages/plugin-core/src/views/CalendarView.ts
Calendar should not auto expand when the last note is closed.
[[1185-The calendar panel expands automatically when the last editor is closed|dendron.github.issues.1185-The calendar panel expands automatically when the last editor is closed]]
https://github.com/dendronhq/dendron/issues/1185
=> fix: stop calendar from auto expanding when the last note is closed

packages/engine-server/src/markdown/remark/backlinks.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/backlinks.spec.ts, test-workspace/vault2/secret.md, test-workspace/vault3/not-secret.md
This fixes issue with backlinks to private vault (`DVault` with visibility set to `private`) being generated when publishing.
Docs PR: N/A
---
- [~] if you are adding a new language feature (graphically visible in vscode/preview/publishing), make sure that it is included in [test-workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96 …
=> fix: exclude private vault backlinks

packages/engine-server/src/markdown/remark/noteRefsV2.ts, packages/engine-server/src/markdown/utils.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/dendronPub.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/dendronPub.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/utilsv5.spec.ts, test-workspace/vault/dendron.ref.links.md
This fixes note ref rendering in preview v2 and publishing so that cross-vault note references without an explicit vault prefix still gets rendered if there is no ambiguity.
- Assume vault of cross-vault note references if there is no vault prefix and only one note with the same name exists.
- Render an error message if there is ambiguity (if `vault1` and `vault2` has the same note `bar`, `![[bar]]` will show an error.
- This will first attempt to handle duplicates if `duplicateNoteBehavior` is set.
- Render an error message if a wildcard note reference has no match.
- Render note reference related error messages in a block quote to make it more visible.
docs: N/A
---
You can go to [dendron pull requests](https://wiki.dendron.so/notes/adc39825-77a6-46cf-9c49-2642fcb4248e.html) to see full …
=> fix: correctly render cross-vault note references in preview v2

packages/plugin-core/src/features/windowDecorations.ts, packages/plugin-core/src/test/suite-integ/WindowDecorations.test.ts
Same file wikilinks and references (`[[#foo]]`) and wildcard references (`![[foo.*]]`) are now highlighted as correct links (although no checks are performed for wildcard references).
Wikilinks and references with anchors (`[[note#foo]]` or `![[note#foo:#bar]]`) are now highlighted as broken if the anchor is broken (for example, `note` has no header `# foo`).
```markdown
```
=> fix: highlight same file wikilinks, wildcard references, links with anchors

packages/plugin-core/src/commands/CreateDailyJournal.ts, packages/plugin-core/src/test/suite-integ/CreateDailyJournalNote.test.ts
```markdown
```
- [n] if your tests changes an existing snaphot, make sure that snapshots are [updated](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#updating-test-snapshots)
- [n] if you are adding a new language feature (graphically visible in vscode/preview/publishing), make sure that it is included in [test-workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace). We use this to manually inspect new changes and for auto regression testiing 
- [n] If your …
=> fix: Ignore lookupConfirm if dailyVault is set

packages/common-all/src/fuse.ts, packages/engine-test-utils/src/__tests__/common-all/fuse.spec.ts, packages/engine-test-utils/src/presets/engine-server/utils.ts, packages/plugin-core/src/components/lookup/LookupProviderV3.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
When special characters are not used bubble up create new entry, and allow queries that are longer than file names searched when special characters are used. For this change allows 'hi world !bye' to match 'hi.world'
* [[ scratch.2021.09.08.121701.lookup-bubble-up-create-new-when-no-exact-match-and-no-special-characters]]
* [[scratch.2021.09.07.213159.improve-look-up-do-not-count-special-chars-for-hiding-results]]
As mentioned in the comments our current & previous behavior allows creation of notes that can be confusing for FuseJS to look up. For example we can create a note 'hi$world' but if we query for just dollar sign '$' FuseJS will not look up 'hi$world' since '$' will be treated as special character according to https://fusejs.io/examples.html#extended-search rules. 'hi$world' can …
=> enhance: conditionally bubble up create new & allow queries longer than fname when special chars are used.

packages/plugin-core/src/commands/MoveNoteCommand.ts, packages/plugin-core/src/components/lookup/LookupProviderV3.ts
Fix move & rename notes to use the exact string provided by the customer .
Fix the issue: https://www.loom.com/share/4e4cacd1de284415a12eef1afa318e0c
Reference note: [[Move Note Lookup Issue|scratch.2021.09.08.115911.move-note-lookup-issue]]
- [d] add a [test](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#writing-tests) for the new feature
- Tried to add a test for the input but all the existing tests for move note use `execute` instead of `run`/`gatherInput`, hence for now didn't add a test which tests note rename input gathering. 
=> fix: fix move note to have exact match

packages/common-all/src/fuse.ts, packages/common-all/src/types/workspace.ts, packages/nextjs-template/components/DendronLookup.tsx, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
Show all root elements and their immediate children on empty query.
This is in regards to @kevinslin comment when querying for empty string:
>  we want to show all domains, so `root` + all top level elements (so `root` notes and all immediate children of `root`)
However, we want to consider the previous behavior of why were we limiting the root elements to roots specified by site.siteHierarchies. Seems like for the look-up showing all the roots as this change does makes sense.
Also note that now the roots are shown first and then their immediate children (prior to this change the roots were after all the children)
Prior to this change empty query look up looked like:
After this change the empty query look up looks like:
- Added assertion to existing test
- NOTE: if you running mac/linux, …
=> fix: show all root results and their children on empty query

hooks/pre-commit.js, packages/plugin-core/package.json
```markdown
This changes updates the vs code compatibility version to match the vscode api version that we're using.
```
Details: It turns out that we've had a mismatch in our compatibility version (was 1.54.0, published in February 2021) and our vs code api version (1.58.0, released in June 2021). This would cause an issue where if a user has opted not to auto-update their VS Code and were on an old version, then certain API calls would fail. The error data revealed that some users were hitting an exception `workspace.onDidGrantWorkspaceTrust is not a function`, which is part of the `_activate()` initialization code.
If set properly, a user's Dendron version will not update to the newer version if their VS Code version doesn't meet the compatibility requirements.
I also added a Husky …
=> fix: update vs code compat version + husky hook check

packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/services/NoteSyncService.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
1. ~~Initialize a blank workspace~~
2. Create a new note `hello`
3. Inside the note, type `bye`
4. Select `bye` and use Lookup Note with "Selection to link" and "create scratch note" options to create a scratch note
5. Rename the scratch note
The link in `hello` doesn't update with the rename.
https://www.loom.com/share/ad626921005b4e9eb91cd099ee287cfc
- Scratch note has no backlink after being created, the previous note's link is not updating.
- This is because the editor switches to the new note before `NoteSyncService` can update the note. `NoteSyncService` relies on having the note still open:
```
// NOTE: it might be worthwile to only do this after checking that the current note is still active
//
// we have this logic currently and it doesn't seem to be causing issues
// this could …
```
=> fix: selection2link doesn't update note with link

packages/common-all/src/fuse.ts, packages/engine-test-utils/src/__tests__/common-all/fuse.spec.ts
Fix single letter look ups.
#retention 
* Before this change: Searching for `big o` would not find `some.note.name.with.big-o` note. 
* After this change: Searching for `big o` looks up `some.note.name.with.big-o` note. 
(same applies to schema lookups, since the setting is used by both).
=> fix: single letter look up matches

packages/common-all/src/error.ts, packages/plugin-core/src/commands/InsertNoteCommand.ts, packages/plugin-core/src/commands/MoveNoteCommand.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/commands/RenameNoteV2a.ts, packages/plugin-core/src/commands/SchemaLookupCommand.ts
Added ErrorFactory to correctly create common errors, the first error being `ErrorFactory.createUnexpectedEventError({ event });` which at times wasn't serialized correctly. 
=> fix: pesky error popup when schema lookup is closed

packages/engine-server/src/markdown/remark/utils.ts, packages/engine-test-utils/src/__tests__/pods-core/MarkdownPod.spec.ts, packages/pods-core/src/builtin/MarkdownPod.ts
```markdown
```
- [n] add a [test](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#writing-tests) for the new feature
- [n] make sure all the existing [tests](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#running-all-tests) pass
- [n] do a spot check by running your feature with our [test workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace)
- [~] if your tests changes an existing snaphot, make sure that snapshots are …
=> fix: resolve relative links on markdown import

packages/plugin-core/src/features/completionProvider.ts
```markdown
This fixes a common exception being thrown in the completion provider, where an attempt to return completion provider results was occurring even in non-Dendron workspaces.
```
---
- [n] add a [test](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#writing-tests) for the new feature
- [n] If your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR
Example PR …
=> fix: no-op completion provider when dendron isn't active

packages/plugin-core/src/utils/analytics.ts
This PR makes the `sentryReportingCallback` well typed. The wrapper will now automatically match the type of the function it's wrapping, giving us type errors if the types don't match. Thanks to type inference, no additional work is needed.
=> chore: well-typed sentry wrapper

packages/plugin-core/src/fileWatcher.ts, packages/plugin-core/src/utils/analytics.ts
Turns out, `sentryReportingCallback` drops the `this` value for wrapped functions. This becomes important for methods that use the `this` value, which was the case for the `FileWatcher`. This would cause these functions to fail immediately, and thus miss added or deleted notes.
I fixed the issue and added a warning for the future.
=> fix: notes added outside Dendron are missed

packages/plugin-core/src/features/ReferenceHoverProvider.ts
```markdown
This changes fixes a common exception thrown in the hover provider when dendron is not in an active workspace. The provider will now no-op in this case.
```
---
```markdown
```
=> fix: no-op on hover provider if dendron non active

packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
Issue prior to change:
https://www.loom.com/share/5d6922668cf34ca687f6af4c170cb89d
Test in workspace after change:
https://www.loom.com/share/f8b8b9d6d17b4509a839c8566e216263
- [x ] add a [test](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#writing-tests) for the new feature
- [ x] make sure all the existing [tests](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#running-all-tests) pass
- [ x] do a spot check by running your feature with our [test workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace)
=> fix: picked schema matching name was not creating the expected note

packages/nextjs-template/components/DendronSEO.tsx
Adds Published, Created, and Tags to each site's SEO metatags. 
I removed the Jest tests from this branch since those will need to be moved over to common-frontend, probably.
=> feat: Support Article Based Seo Props

packages/common-all/src/analytics.ts, packages/plugin-core/package.json, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts
This change attempts to unblock users who are on versions of VS Code < 1.57.0 and are stuck on a version of Dendron that will not activate for them. This change temporarily reverts the compat version to the previous value of 1.54.0.  If a user is on a VS Code version < 1.57.0, then we will not setup the `onDidGrantWorkspaceTrust` callback, which was introduced in 1.57.0 version of the API: https://code.visualstudio.com/updates/v1_57
Not exactly a real product code test, but mimics the functionality:
```log
temporary testing of Dendron version compatibility downgrade sequence
GIVEN the activation sequence of Dendron
WHEN VS Code Version is up to date
✓ THEN onDidGrantWorkspaceTrust will get invoked.
✓ AND onDidGrantWorkspaceTrust can be found in the API.
WHEN VS Code Version is on a …
```
=> fix: activation bypass for users on old vs code

packages/common-all/data/dendron-yml.validator.json, packages/common-all/src/types/workspace.ts, packages/dendron-next-server/data/dendron-yml.validator.json, packages/dendron-next-server/pages/workspace/config.tsx, packages/engine-server/src/config.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
```markdown
```
PR for docs update: https://github.com/dendronhq/dendron-site/pulls
- [~] if you are adding a new language feature (graphically visible in vscode/preview/publishing), make sure that it is included in [test-workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace). We use this to manually …
=> enhance: Leave trace on source note while using selectionExtract

packages/plugin-core/src/commands/OpenLink.ts, packages/plugin-core/src/test/suite-integ/OpenLink.test.ts, packages/plugin-core/src/utils/md.ts
Feat: use Dendron: Open_Link to open both generic URLs and assets found in Dendron vaults.
Further, instead of needing to highlight an asset's relative path, this change allows Open_Link to open the asset path or URI found at the cursor/selection. This also amends for vs-code not handling links with different protocols than https://, http://, or vscode://, allowing users to open other programs more smoothly.
=> Updated OpenLink.ts

packages/plugin-core/src/commands/MoveHeader.ts, packages/plugin-core/src/test/suite-integ/MoveHeader.test.ts
Move header command was set as "parser" which did not involve "compilers". This resulted in an error when using move header with a note that had dendron specific syntax (eg. note reference)
=> fix(commands): move header command compile noterefs

packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
- Added a test assert although it appears it even passes before the fix so its usefullness is quite low. 
```
WHEN cmd+shift+j to activate journal command under root
THEN 'root.journal.2021.10.05' suggestion appears
AND clicked enter
THEN 'root.journal.2021.10.05' note created
WHEN cmd+shift+l to activate look up command
AND typed 'notes.some-new-note-27' 
AND pressed enter
THEN 'notes.some-new-note-27' created. 
GIVEN schema book (with added children: chars)
WHEN created new note 'book.medtations'
AND  went to lookup 'book.meditaions.'
THEN 'book.meditaions.chars' schema suggestion appears
AND clicked on suggestion
THEN …
```
=> fix: fix journal note creation

packages/engine-server/src/workspace/service.ts, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/workspace.spec.ts.snap
This PR
- adds `seeds` to `.gitignore` on workspace creation.
- [~] if you are adding a new language feature (graphically visible in VS Code/preview/publishing), make sure that it is included in [test-workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace). We use this to manually inspect new changes and for auto regression testing
- [~] …
=> chore: add seeds directory to gitignore on workspace creation

packages/plugin-core/src/fileWatcher.ts, packages/plugin-core/src/services/NoteSyncService.ts, packages/plugin-core/src/workspace.ts
Updates the links for notes added by the file watcher, and refreshes the backlinks view. This fixes issues with backlinks not updating when notes are added or removed outside of Dendron, for example with another editor or with git sync.
=> fix: notes added outside Dendron missing backlinks

packages/engine-server/src/markdown/remark/utils.ts, packages/engine-test-utils/src/__tests__/pods-core/MarkdownPod.spec.ts, packages/pods-core/src/builtin/MarkdownPod.ts
- [~] If your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR
=> chore: resolve same level dir wikilinks

packages/nextjs-template/components/DendronNotePage.tsx, packages/nextjs-template/styles/constants.ts
- Adding a Table of contents on the right side. Once the browser reach a small screen size, the table is not displayed anymore.
fix: [[Table of Contents for mobile display|scratch.2021.10.24.214152.table-of-contents-for-mobile-display]]
https://user-images.githubusercontent.com/989826/140085319-37bf348a-4f1a-4ecf-b3c2-14e8f239fd45.mov
=> fix(template): table of contents layout

packages/pods-core/src/builtin/GithubIssuePod.ts
We currently assume all authors have urls. This isn't the case when the
author has deleted their account
=> fix(pods): github import pod handle deleted authors

packages/common-all/src/dnode.ts, packages/common-test-utils/src/noteUtils.ts, packages/engine-test-utils/src/__tests__/engine-server/drivers/file/schemaParser.spec.ts, packages/plugin-core/package.json, packages/plugin-core/src/commands/CreateSchemaFromHierarchyCommand.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/pluginSchemaUtils.ts, packages/plugin-core/src/pluginVaultUtils.ts, packages/plugin-core/src/services/SchemaSyncService.ts, packages/plugin-core/src/test/suite-integ/CreateSchemaFromHierarchyCommand.test.ts, packages/plugin-core/src/test/testUtilsV3.ts, test-workspace/vault/dendron.cmd.create-schema-from-hierarchy.md, test-workspace/vault/languages.python.data.bool.md, test-workspace/vault/languages.python.data.integer.md, test-workspace/vault/languages.python.data.md, test-workspace/vault/languages.python.data.string.md, test-workspace/vault/languages.python.machine-learning.md, test-workspace/vault/languages.python.machine-learning.pandas.md, test-workspace/vault/languages.python.machine-learning.scipy.md
Adding new command: `Dendron: Create Schema From Note Hierarchy` 
[PR Dendron Site Documentation](https://github.com/dendronhq/dendron-site/commit/9aa4870608b1ed189d991514363fc06314eb47e2)  
```
CreateSchemaFromHierarchyCommand tests
HierarchyLevel tests:
GIVEN 'languages.*.data' hierarchy level
✓ THEN have expected label
✓ THEN have expected top id
✓ THEN produce expected default schema name
tokenize tests
✓ WHEN fname is 'languages.python.data' THEN tokenize to '["languages","*","data"]'.
✓ WHEN fname is 'languages.python.data.integer' THEN tokenize to '["languages","*","data","integer"]'.
✓ WHEN fname is 'languages.python.machine-learning' THEN tokenize to '["languages","*","machine-learning"]'.
isCandidateNote tests
✓ WHEN testing 'languages' note THEN do NOT match.
✓ WHEN testing …
```
=> feat: adding new command: create schema from hierarchy

packages/plugin-core/src/survey.ts
This PR
- Fixes a mistyped analytics event name that caused confusing analytics results for survey.
lapsed user survey prompt was tracked as initial survey prompt event and was inflating the actual count of initial surveys being prompted.
- [~] if your tests changes an existing snapshot, make sure that snapshots are [updated](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-9 …
=> fix: mistyped analytics event name

packages/plugin-core/src/commands/CreateSchemaFromHierarchyCommand.ts, packages/plugin-core/src/test/suite-integ/CreateSchemaFromHierarchyCommand.test.ts
Allow creation of schema from hierarchy with '*' at the end.
Example allows creation of schema such as:
```
version: 1
imports: []
schemas:
- id: languages
title: languages
parent: root
children:
- pattern: python
children:
- pattern: data
children:
- pattern: '*'
```
=> enhance: cmd create-schema-from-hierarchy allow schema to end with '*'

.github/workflows/publish-extension-nightly.yml
The reduction to 15 second sleep for waiting for verdaccio to start up was causing failures. 
It appears for some reason npx isn't finding verdaccio in local node_modules? So it does a fetch, which takes some time. 
```
checking verdaccio log
npx: installed 288 in 18.693s
warn --- config file  - /home/runner/.config/verdaccio/config.yaml
warn --- Plugin successfully loaded: verdaccio-htpasswd
warn --- Plugin successfully loaded: verdaccio-audit
warn --- http address - http://localhost:4873/ - verdaccio/5.2.2
```
The extra sleep is a small price to pay for a more consistent build.
---
- NOTE: if you running MacOS or Linux, pay …
=> chore: increase nightly verdaccio timeout

packages/common-test-utils/src/presets/notes.ts, packages/engine-test-utils/src/__mocks__/vscode.ts, packages/engine-test-utils/src/presets/engine-server/utils.ts, packages/plugin-core/src/components/lookup/queryStringTransformer.ts, packages/plugin-core/src/components/lookup/types.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts, packages/plugin-core/src/test/suite-integ/components/lookup/utils.test.ts, packages/plugin-core/src/test/suite-integ/queryStringTransformer.test.ts, test-workspace/vault/data.driven.md, test-workspace/vault/dendron.note-lookup.md, test-workspace/vault/languages.python.data.string.memory.md, test-workspace/vault/languages.with-data.make-sense.md
Having a dot at the end will now look up child & descendant notes (bubbling up the child notes to the top) that match the query but without requiring the full match of the prefix note. 
```
1. Look up `data.` 
Should see results with roughly the following order:
* `data.driven`     
* first show matches with `data.` exact matched and `data.` highest in hierarchy
* `languages.python.data.string`
* then show matches that have `data.` exact matched but lower in hierarchy.
* ...
* `languages.with-data.make-sense` 
* later show matches that are not exact matched `with-data.`
* `languages.python.data.string.memory` 
* lastly show matches that have not just children but grand children etc.
All matches should have `data.` and some value after `data.`
```
In the task note for this task it was …
=> enhance: looks ups with dot at the end now look up hierarchies without having exact postfix

packages/engine-server/src/drivers/file/schemaParser.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-test-utils/src/__tests__/engine-server/drivers/storev2.spec.ts, packages/plugin-core/src/logger.ts, packages/plugin-core/src/services/SchemaSyncService.ts, packages/plugin-core/src/test/suite-integ/logger.test.ts
Adds `Go to File` action on the error message. Improves error message formatting on save of schemas. Adds the error message into status bar. 
=> enhance: add file navigation upon schema malfored when loaded

packages/engine-server/src/workspace/utils.ts, packages/plugin-core/src/commands/SetupWorkspace.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/utils.ts
Docs: https://github.com/dendronhq/dendron-site/pull/276
If the user currently has a non-Dendron workspace open, we now offer to initialize that as a Dendron native workspace.
Fixed a bug with handling existing roots where cancelling the prompt would create a workspace anyway, and also improved the user-friendliness of it.
Finally, also fixed a bug where non-Dendron workspaces are recognized as Native Dendron workspaces.
=> feat: Initialize Workspace command can create native workspaces

packages/plugin-core/src/test/suite-integ/MoveHeader.test.ts, packages/plugin-core/src/test/suite-integ/SeedCommand.test.ts, packages/plugin-core/src/test/testUtilsv2.ts
expect.toContain() used to not actually assert anything prior to this change. 
=> chore: fix expect.toContain to actually assert

packages/common-server/src/parser.ts
Fixed the warning message, and added encapsulation for the ajv to only get instantiated for the first time that its used for good measure. 
- [] Add a [test](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#writing-tests) for the new feature
- parser.spec.ts already has a test which indirectly tests the changes in the code, made sure that if validaton is commented out parser.spec.ts does not pass. 
=> fix: ajv warning messages printed to console

packages/common-all/src/index.ts, packages/common-server/src/analytics.ts, packages/dendron-cli/src/commands/base.ts
This PR:
- Adds a new argument `--devMode` for dendron-cli, to be used for development purposes.
- Make Segment client instantiate with the production stage key if `--devMode` is not explicitly set.
This change fixes an issue where all published `dendron-cli` was tracking analytics data as `ide-dev` because the stage environment was not set at the time of execution. Note that all local testing should be done with `--devMode true` explicitly passed to avoid noise in analytics.
- [~] If your tests involve …
=> chore: add dev mode in cli

packages/plugin-core/src/commands/CreateSchemaFromHierarchyCommand.ts, packages/plugin-core/src/commands/base.ts, packages/plugin-core/src/test/suite-integ/CreateSchemaFromHierarchyCommand.test.ts
Print out of analytics payload from base command in different use cases:
```
Payload: '{"stopReason":"CANCELLED_PATTERN_SELECTION","successfullyCreated":false}'
Payload: '{"stopReason":"DID_NOT_PICK_HIERARCHY_LEVEL","successfullyCreated":false}'
Payload: '{"stopReason":"UNSELECTED_ALL_PATTERNS","successfullyCreated":false}'
Payload: '{"stopReason":"DID_NOT_PICK_SCHEMA_FILE_NAME","successfullyCreated":false}'
Payload: '{"successfullyCreated":true}'
// Example of empty payload is when sanity check is invoked.
Payload: '{}'
Payload: '{"stopReason":"SCHEMA_WITH_TOP_ID_ALREADY_EXISTS","successfullyCreated":false}'
```
=> enhance: adding telemetry to CreateSchemaFromHierarchyCommand

packages/nextjs-template/components/DendronLayout.tsx, packages/nextjs-template/components/DendronNoteFooter.tsx, packages/nextjs-template/components/DendronNotice.tsx, packages/nextjs-template/components/DendronSearch.tsx, packages/nextjs-template/components/DendronTOC.tsx, packages/nextjs-template/styles/scss/main.scss
- Replace runtime CSS rules on DendronLayout with layout components
- Move footer over the navbar [[scratch.2021.11.08.151528.move-footer-over-to-navbar]]
**Improvements**
- The layout takes the full width on screens < 1320px (See [docusaurus](https://docusaurus.io/docs))
- Remove the content layout shifting when the page is being resized.
- Remove runtime calculations
Attachment
https://user-images.githubusercontent.com/989826/141357288-34e36897-4028-41d2-867d-f795101989b1.mov
=> fix:(layout): position sidebar, main content and footer

packages/common-server/src/etc.ts, packages/dendron-plugin-views/scripts/buildIndex.js, packages/dendron-plugin-views/src/components/DendronApp.tsx, packages/dendron-plugin-views/src/components/DendronNotePage.tsx, packages/dendron-plugin-views/src/hooks/index.tsx
Prior, we would default to the light theme which would make dark theme
diagrams hard to read.
Also adds support for setting theme when [[Developing in Browser
Mode|dendron://dendron.dendron-site/pkg.dendron-plugin-views.quickstart#developing-in-browser-mode]].
=> enahnce(views): mermaid diagrams respect color theme

bootstrap/scripts/buildPatch.sh, packages/dendron-cli/src/commands/devCLICommand.ts, packages/dendron-cli/src/utils/build.ts, packages/plugin-core/.vscodeignore, packages/plugin-core/webpack.common.js
This reduces the bundle size of the plugin by +80mb
- chore(build): don't analyze bundle on every build
- chore(build): skip installing dependencies when running `dendron dev prep_package` in `fast` mode
- chore(build): add quiet flag to build step and remove extra build artifact
=> chore(build): multiple build optimizations

packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/test/suite-integ/components/lookup/utils.test.ts, test-workspace/vault/data.schema.yml, test-workspace/vault/dendron.note-lookup.md
Stubs are still visible so they can be easily created, but they are pushed down from the existent notes to interfere less with look up results
=> enhance: show stubs at the end of dot ended lookup

bootstrap/.vscode/tasks.json, packages/api-server/src/index.ts, packages/dendron-cli/src/commands/launchEngineServer.ts, packages/dendron-cli/src/commands/utils.ts, packages/engine-server/src/engineClient.ts, packages/engine-server/src/markdown/remark/dendronPreview.ts, packages/engine-server/src/markdown/utilsv5.ts, packages/engine-server/src/topics/connector.ts, packages/engine-server/src/utils.ts, packages/engine-server/src/workspace/service.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/launchEngineServer.spec.ts, packages/engine-test-utils/src/__tests__/dendron-cli/utils/setupEngine.spec.ts, packages/plugin-core/src/commands/DiagnosticsReport.ts, packages/plugin-core/src/test/suite-integ/DiagnosticsReport.test.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/workspacev2.ts
The Dendron CLI will create its own instance of an API server for most commands. This engine, when spawned, will write a port file at `.dendron.port` so that other processes can discover the port that the engine server is running on.
The issue is that a running workspace has its own port file which will be overridden. This will make commands like `dendron {cmd} --attach` fail as the port is no longer accurate.
This change causes the dendron-cli to write the engine port at `dendron.port.cli` instead.
- enhance: cli write to own path
- enhance(cli): do not overwrite ws dendron port when activating CLI
=> enhance(cli): cli uses separate port file

packages/plugin-core/src/commands/NoteLookupAutoCompleteCommand.ts, packages/plugin-core/src/test/expect.ts, packages/plugin-core/src/test/suite-integ/autoCompleter.test.ts, packages/plugin-core/src/test/testUtilsv2.ts
Added documentation mention on this issue in ![[dendron://dendron.docs/pkg.plugin-core.dev.errors.cmd-is-not-a-constructor-dependency-issue]] 
=> fix: auto completer test dependency issue

packages/common-all/src/error.ts, packages/common-test-utils/src/noteUtils.ts, packages/plugin-core/src/commands/ShowPreview.ts, packages/plugin-core/src/test/expect.ts, packages/plugin-core/src/test/suite-integ/ShowPreview.test.ts, packages/plugin-core/src/test/testUtilsv2.ts, packages/plugin-core/src/utils/quickPick.ts, test-workspace/vault/dendron.ref.links.md, test-workspace/vault2/dendron.ref.links.target-different-vault.md, test-workspace/vault3/dendron.ref.links.target-different-vault.md
Now when clicking on a link in preview that does not specify a vault (but lives in a different) vault we will navigate to the note. IF there are multiple notes in different vaults that match THEN we will choose the note with the oldest create time. 
IF there is a note with same file name in current vault we will choose the note in the same vault above all else. 
=> fix: fixing navigation to notes from preview that do not have vault specified

packages/plugin-core/src/_extension.ts
We now collect analytics when a native workspace is initialized that was really a code workspace.
Docs: https://github.com/dendronhq/dendron-site/pull/309
=> chore: analytics for native workspaces that were actually code workspaces

packages/common-all/src/dnode.ts, packages/engine-test-utils/src/__tests__/common-all/dnode.spec.ts
* Updated tests for dnode.ts
* Minor lint fixes in dnode.spec.ts
* Append template note's body if current note's body is not empty
* See https://github.com/dendronhq/dendron/issues/1675
Unit Test
*  ./node_modules/.bin/jest /Users/tulingma/workspace/dendron/packages/engine-test-utils/src/__tests__/common-all/dnode.spec.ts
Manual Test
* Run "Run:Extension Local (plugin-core) against test workspace
* Test creating note with template
* Test creating note with template with selection extract
=> fix(schema): When applying a schema template, do not override the body but append to the end to it

packages/plugin-core/src/vsCodeUtils.ts
https://github.com/dendronhq/dendron/pull/1813 removed `assets` directory from the final bundle. Update the assetUrl to reflect this
=> chore(build): fix asset url

packages/plugin-core/package.json, packages/plugin-core/src/constants.ts
It looks like preview (and legacy preview) command enablement was removed from the plugin in [this commit](https://github.com/dendronhq/dendron/commit/db092e33cb6295b4d90e60bd4267d2f83f824e7a#diff-677d091422296a09595b79de5736b254846f80b62e155fc33e06773f009b0d19)
This PR
- re-adds the removed enablement clause, and
- relaxes the clause so that it will work even when a markdown file is not currently open.
- [~] If your tests involve running [[manual Testing|dendron://dendron.dendron-site/dendron.dev.qa.test#man …
=> fix: re-introduce preview command enablement

packages/common-all/src/constants/configs/commands.ts, packages/common-all/src/fuse.ts, packages/common-all/src/types/configs/commands/lookup.ts, packages/engine-server/src/engineClient.ts, packages/engine-server/src/enginev2.ts, packages/engine-test-utils/src/__tests__/common-all/fuse.spec.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/nextjs-template/utils/hooks.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts
Allows users to configure the fuzziness threshodl of lookups. 
PR doc: https://github.com/dendronhq/dendron-site/pull/303/files
* Tested with configuration
* Tested without adding new configuration
* Tested with note configuration entirely.
=> enhance: add fuzzy threshold configuration

packages/engine-test-utils/src/__tests__/engine-server/drivers/file/schemaParser.spec.ts, packages/engine-test-utils/src/presets/engine-server/utils.ts, packages/plugin-core/src/test/suite-integ/WorkspaceWatcher.test.ts
Appears as we are able to add inline schema under non inline schema. 
Created a new template in test workspace (there is already note foo.one so named it baz)
```yaml
version: 1
imports: []
schemas:
- id: baz
parent: root
children: 
- one
- journal
- id: one
template: templates.hi
- id: journal
pattern: "[0-2][0-9][0-9][0-9]"
children:
- pattern: "[0-1][0-9]"
children:
- pattern: "[0-3][0-9]"
template: templates.hi 
```
Was able to create note `baz.one` which showed schema icon and created a note with template https://www.loom.com/share/b1ba56eb56d7488281b513bcd9f8f002 
=> chore: adding additional tests for including inline schema in regular schema

packages/common-all/src/types/workspace.ts, packages/common-all/src/utils.ts, packages/nextjs-template/components/DendronSEO.tsx
* Updated image field of DendronSiteConfig to represent default SEO image
* See [[Fallback Seo|dendron://private/task.publish.2021.11.24.fallback-seo]]
Manual Test
* Update dendron.yml to include default image field
* Run NextJs against test workspace. [[Test|dendron://dendron.docs/pkg.nextjs-template.qa.test]]
* Open http://localhost:3000/notes/boy2/ and view page source
* Verified image in meta property="og:image"
=> enhance(publish): Fallback to default SEO image if no image is set for published pages.

packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/SeedBrowseCommand.ts, packages/plugin-core/src/commands/SeedCommandBase.ts, packages/plugin-core/src/commands/ShowNoteGraph.ts, packages/plugin-core/src/commands/ShowPreview.ts, packages/plugin-core/src/commands/ShowSchemaGraph.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/components/views/NoteGraphViewFactory.ts, packages/plugin-core/src/components/views/PreviewViewFactory.ts, packages/plugin-core/src/components/views/SchemaGraphViewFactory.ts, packages/plugin-core/src/services/NoteSyncService.ts, packages/plugin-core/src/test/suite-integ/WindowWatcher.test.ts, packages/plugin-core/src/views/SampleView.ts, packages/plugin-core/src/views/utils.ts, packages/plugin-core/src/windowWatcher.ts, packages/plugin-core/src/workspace.ts, packages/plugin-core/src/workspace/seedBrowserInitializer.ts, packages/plugin-core/src/workspace/tutorialInitializer.ts
This change encapsulates the webviews in `DendronExtension` for better dependency inversion and removal of circular dependencies
- webviews are no longer exposed in `DendronExtension`
- Note Graph, Schema Graph, and Preview webviews no longer rely on `WorkspaceWatcher` and completely own their own lifecycle, including vs code callback disposables.
- `NoteSyncService` has a static dependency on preview - until that can be refactored from being a singleton, I've exposed a temporary static `PreviewProxy` getter for compatibility.
- Fixed a circ dependency in `SampleView`
- The new view factory methods aren't perfect - they should return something more scoped than the entire `vscode.WebPanelView`, but to reduce churn in the refactor for now I'm leaving most of the code intact.
---
You can go …
=> fix(views): encapsulate webviews

packages/common-all/src/utils.ts, packages/common-all/src/vault.ts, packages/common-server/src/filesv2.ts, packages/common-test-utils/src/noteUtils.ts, packages/engine-server/src/workspace/utils.ts, packages/plugin-core/src/WSUtils.ts, packages/plugin-core/src/WorkspaceWatcher.ts, packages/plugin-core/src/commands/GoToSiblingCommand.ts, packages/plugin-core/src/commands/GotoNote.ts, packages/plugin-core/src/commands/PasteFile.ts, packages/plugin-core/src/commands/RenameNoteV2a.ts, packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/features/DefinitionProvider.ts, packages/plugin-core/src/fileWatcher.ts, packages/plugin-core/src/pluginVaultUtils.ts, packages/plugin-core/src/services/NoteSyncService.ts, packages/plugin-core/src/test/suite-integ/GotoNote.test.ts, packages/plugin-core/src/views/DendronTreeView.ts, packages/plugin-core/src/workspace.ts
This works by writing relative paths from the `wsRoot` in wikilinks. For example,
`[[/src/index.js]]` will open `${wsRoot}/src/index.js`.
- `[[/src/index.js]]` and `[[src/index.js]]` will function in the same way to maintain compatibility with how Dendron handles wikilinks.
- If the path starts with `/assets`, then it's handled in a special way where we'll instead search for it in `assets` folders within each vault first. This maintains compatibility with how assets work in publishing.
- This only works for existing files, creating non-existing files is not supported.
- If a note and a file with the same name exist (e.g. there's a `file.txt` under `wsRoot` and `file.txt.md` in some vault, and link is `[[file.txt]]`), then the note gets priority to avoid breaking existing links.
Docs: …
=> feat: Goto Note can open links to non-note files

dendron-main.code-workspace, docs/.gitignore, docs/CONTRIBUTING.md, docs/dendron.yml
This PR adds Dendron's user documentation and developer documentation as part of the workspace.
**Warning**: There seems to be a few problems with running the development version of the extension while also having the release version extension installed:
- If you open the test workspace as a Native Workspace, the lookup never matches any input. You can still create new notes, and existing notes can be opened if you click on an item in the lookup, but typing something into the bar never matches anything.
- If you open the test workspace as a Code Workspace, you get an error `[dendron.@dendronhq/plugin-core]: Cannot register 'dendron.defaultJournalName'. This property is already registered.`. Otherwise everything seems to work.
I'll look into these issues soon, but otherwise I'll leave it …
=> chore: add dendron docs as native ws

.eslintrc.js, dendron-main.code-workspace, packages/common-all/src/types/typesv2.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/plugin-core/.eslintrc.json, packages/plugin-core/src/commands/GotoNote.ts, packages/plugin-core/src/commands/ShowPreview.ts, packages/plugin-core/src/survey.ts, packages/plugin-core/src/test/suite-integ/DeleteHookCommand.test.ts, packages/plugin-core/src/test/suite-integ/DeleteNodeCommand.test.ts, packages/plugin-core/src/test/suite-integ/ShowPreview.test.ts, packages/plugin-core/src/test/suite-integ/md.test.ts, packages/plugin-core/src/utils/md.ts
Header anchors would be parsed and `depth` data for headers would be dropped. That means the following header
```md
```
would be represented as
```json
"use-cases": {
"type": "header",
"text": "Use Cases",
"value": "use-cases",
"line": 24,
"column": 0
}
```
This adds the depth data in.
```diff
"use-cases": {
"type": "header",
"text": "Use Cases",
"value": "use-cases",
"line": 24,
"column": 0,
+   "depth": 2,
}
```
Currently, this effects the output of the [[JSON Pod|pkg.pods-core.ref.json]].
This PR also fixes a few test issues and updates our eslint config to work better with mocha
- chore: update eslint rules to for mocha tests
- chore: remove unused option in workspace
- add depth to header
- fix issues with tests
You can go to [dendron pull …
=> enhance(markdown): add `depth` metadata to header anchors

packages/plugin-core/src/commands/GotoNote.ts, packages/plugin-core/src/features/DefinitionProvider.ts, packages/plugin-core/src/test/suite-integ/DefinitionProvider.test.ts, packages/plugin-core/src/test/testUtilsV3.ts, test-workspace/vault/dendron.ref.links.md
Allows `Ctrl+Click`ing on a link to a non-note file to navigate to that file. This only works inside notes right now.
I'll work on hover & highlighting inside note files next, then look into definition & hover when inside non-note files.
=> feat: implement goto definition for non-note files

packages/common-server/src/etc.ts, packages/plugin-core/src/views/utils.ts, test-workspace/vault/dendron.preview.md, test-workspace/vault/foo.md
Note as mentioned in the comments using the clipboard readText() already strips out the theming. However, that means the headers are written as plain text. 
=> enhance: strip out theming on copy and paste from preview

packages/common-all/data/dendron-yml.validator.json, packages/common-all/src/constants/configs/preview.ts, packages/common-all/src/types/configs/preview/preview.ts, packages/dendron-next-server/data/dendron-yml.validator.json, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/components/views/PreviewViewFactory.ts, packages/plugin-core/src/services/NoteSyncService.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/test/suite-integ/WindowWatcher.test.ts, packages/plugin-core/src/windowWatcher.ts, packages/plugin-core/src/workspace.ts
- Introduce new config automaticallyShowPreview
- When window changes (ie switching between notes), show preview if config is set to true
- When workspace is launched, show preview if config is set to true
- Default to false
Testing
- Manually verified preview behavior against test workspace
- Updated test cases for WindowWatcher.test.ts
=> enhance(views): Support new config to automatically show preview

packages/common-all/src/dnode.ts, packages/plugin-core/src/commands/RefactorHierarchyV2.ts, packages/plugin-core/src/test/suite-integ/RefactorHierarchy.test.ts
This PR:
- Fixes an issue with `Dendron: Refactor Hierarchy` where if any note that is captured with the match text is a stub note, the rename operation fails.
- This only applies to true stub notes (notes that are not in the file system and only virtually exists as a note prop)
- Notes that are in the file system but has frontmatter `stub` property set to true will still be refactored correctly.
- [~] If your tests involve running [[manual Testing|dendron://dendron.dendron-site/dendron.dev.qa.test#manual-testing]], make sure to update [[Test Workspace|dendron://dendron.dendron-site/dendron.dev.ref.test-workspace]] with any …
=> fix: refactor crashes when captured note is a stub

packages/plugin-core/src/_extension.ts, test-workspace/vault/assets/test.js, test-workspace/vault/dendron.journal.2020.07.12.foo.md
This PR allows the definition provider and hover provider to work in all files, including non-note files. This allows users to `Ctrl+click` on wikilinks in non-note files, or hover over them.
=> enhance: go to definition & hover works for wikilinks inside non-note files

packages/plugin-core/package.json, packages/plugin-core/src/commands/SetupWorkspace.ts, packages/plugin-core/src/constants.ts
When there's a lot of files in non-Dendron workspaces, the native workspace creation watcher would cause Dendron to crash.
This PR disables the watcher by default, and instead simply reloads the workspace when a native workspace is created.
#1312
=> fix: extension crash in non-Dendron workspaces when there's many files

packages/pods-core/src/builtin/GithubIssuePod.ts, test-workspace/vault/github.issues.31-lorem-ipsum-101-test.md
This PR adds an `aliasMapping` field in GitHub publish config to support interoperability of github-publish and airtable export pod. 
For Eg config could be: 
```
aliasMapping: {
assignees: { value: {kevin: 'kevinslin'}, alias: 'owner'},
status: { value: {x: 'CLOSED'}}
}
```
- Config for our task Note mappings : [[Pod Configuration|dendron://private/area.team.sop.publish-github-issue#pod-configuration]]
- [loom video](https://www.loom.com/share/a29980086c4b4f8cb1556cacb32f4123)
=> enhance(pods): better-support for github Issue and task Notes

packages/plugin-core/src/WorkspaceWatcher.ts, packages/plugin-core/src/features/windowDecorations.ts, packages/plugin-core/src/services/NoteSyncService.ts, packages/plugin-core/src/windowWatcher.ts
Now that we have the ability to document both in the code and also in Dendron, the question is what to put where.
The pattern I've been using: 
- details should be put in code as regular comments
- high level overviews should be put in Dendron. these details currently are in the form of reference notes of existing packages. See docs [here](https://github.com/dendronhq/dendron-docs/commit/f49a192ad8f58824989bbba7feece38a57704e0f)
The reference notes for these packages can be found [here](https://github.com/dendronhq/dendron-docs/commit/dafc752b99b33697c8872eedf0bf0c195a6c17ed)
One outstanding issue:
- the `Summary` section overlaps with the docstring for a given module. see below for an example. potential solution: use block embeding from file to note to generate summary 
```ts
/**
* …
```
=> Add links to dendron vault for a few dendron components

packages/engine-server/src/markdown/remark/utils.ts, packages/plugin-core/src/commands/Doctor.ts, packages/plugin-core/src/services/NoteSyncService.ts
This PR
- Fixes an issue with the `findBrokenLinks` preview, where the line number of broken links in preview is not offsetted correctly to take into account of the frontmatter.
- Refactors `getFrontmatterPosition` in `NoteSyncService` to use the newly consolidated utility method `RemarkUtils.getNodePositionPastFrontmatter`
- Added docs on the consolidated way to get frontmatter line offset [here](https://github.com/dendronhq/dendron-docs/commit/a91c3d047dddb0e4d844b767ded358c5df2015f4#diff-ac3a7ac11ebfede43f6a3c4885c0253a12f755640dd1bde8b6bbf1de397b3fc3R201)
- [~] Add a [test](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-9 …
=> fix: correctly offset frontmatter line count in doctor preview for `findBrokenLinks`

packages/nextjs-template/components/DendronTreeMenu.tsx
Example:
```yml
siteHierarchies:
- foo
- bar
```
- bar.md
```
---
nav_exclude: true
---
```
The following would throw an error when trying to render the published page because `bar` would be `undefined` in the nav
=> fix(publish): excluding the domain of a published hierarchy will cause publishing to throw an error

packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/NoteLookupAutoCompleteCommand.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/test/suite-integ/AutoCompleterRegistrar.test.ts, packages/plugin-core/src/utils/AutoCompletable.ts, packages/plugin-core/src/utils/autoCompleter.ts, packages/plugin-core/src/utils/registers/AutoCompletableRegistrar.ts
[[dendron://private/task.lookup.2021.12.13.completion-activation-issue]]
Changing to the registration of auto completable commands to make it more robust.
=> fix: move auto completable command registration to be done centrally

packages/dendron-next-server/components/graph.tsx, packages/plugin-core/src/components/views/NoteGraphViewFactory.ts
This PR:
- fixes an issue that occurs with the graph view where actions that change active note / editor group will cause an infinitely looping chain of `Go To Note` calls and graph view rerender.
- Changing active note (or selecting a node in the graph view) fires a series of messages between VSCode and the webview that causes infinitely chained sequence of active note changes because the `onSelect` message first changes the focus to the first editor group (which fires another active note change, which adds onto the chain), and then fires a `Go To Note`.
- To reproduce, 
1. try opening at least three editor groups (one for note graph, two for any other different notes)
2. with the first editor group focused, move focus to the other editor group that has another note open.
3. this causes …
=> fix: infinite looping active note change when note graph is open

packages/common-all/src/util/dateFormatUtil.ts, packages/common-all/src/util/index.ts, packages/plugin-core/package.json, packages/plugin-core/src/constants.ts, packages/plugin-core/src/features/BacklinksTreeDataProvider.ts, packages/plugin-core/src/test/suite-integ/BacklinksTreeDataProvider.test.ts, packages/plugin-core/src/types.ts, packages/plugin-core/src/utils/md.ts, packages/plugin-core/src/vsCodeUtils.ts, packages/plugin-core/src/workspace.ts, test-workspace/vault/dendron.backlinks.md, test-workspace/vault/dendron.backlinks.target-A.md, test-workspace/vault/dendron.backlinks.target-B.md, test-workspace/vault/dendron.backlinks.target-C.md
Note: VSCode command palette does not seem to respect the ordering. So if anyone knows how to order the commands to show in particular order would be really helpful more info in ![[dendron://private/vscode.command-palette]]
As for the docs: I didnt find a separate backlink panel documentation (besides a mention in links documentation that we have such panel), and really hoping that this is self explanatory from the labels that we have. 
Having alot of issues today with tests, in a different commit tests locally pass but centrally do not. This time the tests keep getting 'stuck' (although unit tests mostly pass, (I have 2 tests that historically fail in unit tests and pass centrally something with GitHub related) Anyway hopefully these plugin tests pass, since I have been able to run …
=> enhance: adding last update sort ordering for backlinks

packages/plugin-core/src/commands/CreateTask.ts, packages/plugin-core/src/commands/GoDownCommand.ts, packages/plugin-core/src/test/suite-integ/AutoCompleterRegistrar.test.ts, packages/plugin-core/src/utils/registers/AutoCompletableRegistrar.ts
Instead of creating a new instance of NoteLookupCommand, we are using the UI registered instance of NoteLookupCommand. This allows the OnComplete command to activate.
Note with this change: We are re-using the same instance across multiple commands, appears to work fine, but if there is some tribal knowledge to not do this please comment. 
=> enhance: add auto completion to GoDown command and CreateTask command

packages/engine-server/src/markdown/decorations/frontmatter.ts, packages/plugin-core/src/test/suite-integ/WindowDecorations.test.ts
Fixes a bug where frontmatter tags were not being highlighted. Also updates the tests to prevent further regressions.
=> fix: frontmatter tags are not highlighted

packages/common-all/src/fuse.ts, packages/engine-test-utils/src/__tests__/common-all/fuse.spec.ts
=> fix(lookup): full length word matches should be case insensitive

packages/common-frontend/src/features/ide/slice.ts, packages/dendron-plugin-views/src/components/DendronTreeExplorerPanel.tsx, packages/plugin-core/src/services/NoteSyncService.ts
The tree view wouldn't update when a note's `nav_order`, title, or `updated' changes (these all affect order in the tree). This PR fixes this issue.
#1830
=> fix: update tree order when a note changes order

packages/common-all/src/dnode.ts, packages/common-test-utils/src/presets/notes.ts, packages/engine-server/src/markdown/utilsv5.ts, packages/engine-test-utils/src/__tests__/common-all/dnode.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/utilsv5.spec.ts, packages/engine-test-utils/src/presets/engine-server/utils.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
When applying a schema template, Dendron should support custom date variables.
- Use lodash _.template to apply date variable substitution when we call `applyTemplate`
Testing
- Manually created template with {{ CURRENT_YEAR }}
- Verified new note contains 2021
- Updated unit tests for `applyTemplate` and NoteLookupCommand
See [[Support Custom Date Format When Applying Schema Template|dendron://private/task.2021.11.28.support-custom-date-format-when-applying-schema-template]] for more info
=> enhance(schema): Support date variable substitution for templates

packages/engine-server/src/drivers/file/storev2.ts, packages/engine-test-utils/src/presets/engine-server/rename.ts, packages/plugin-core/src/commands/RenameHeader.ts, packages/plugin-core/src/test/suite-integ/MoveNoteCommand.test.ts, packages/plugin-core/src/test/suite-integ/RenameHeader.test.ts
This PR:
- Fixes an issue with `FileStorage.renameNote` updating notes with link to a renamed note that doesn't actually have changes.
- This bug would change notes that:
- don't have note body changes at all, but is referencing a note that has a header rename.
- e.g. note `foo` has a header that was changed by `Rename Header`, the note `foo`'s name hasn't actually changed, but internally `Rename Header` uses `renameNote` with the same note location to trigger reference updates. The bug here is that all notes that are not referencing the particular header but the note itself will be counted as modified, which add undesirable changes to the file (adding a `\n` at the end, changing `"` to `'`, etc.)
- don't have note body (or frontmatter tag) changes, but used double quotes (`"`) in …
=> fix: rename operations modify unnecessary files

packages/plugin-core/src/commands/MoveHeader.ts, packages/plugin-core/src/test/suite-integ/MoveHeader.test.ts
This PR:
- fixes issue with move header where if the moved text includes block anchors, they get corrupted
- this was caused because we appended to destination after running a proc.stringify on a fake note containing the header and text associated, but this proved to be finicky and dependent on quirks of the processor and now is changed to directly slice off text portion to be appended from origin note. 
- fixes issue with move header refactoring links to remove their vault prefixes.
- now will preserve vault prefix (if it didn't exist, will not be added unless doing so introduces ambiguity. if it did exist, it will always be preserved)
- refactors move header and its test to use the new `getNote(s)ByFNameFromEngine` method and the `IEngineAPIService` interface with a static provider.
If …
=> fix: move header issues

packages/engine-server/src/workspace/utils.ts, packages/plugin-core/src/commands/ChangeWorkspace.ts, packages/plugin-core/src/test/suite-integ/ChangeWorkspace.test.ts
- Use file picker instead of typing out file path
- See [[Use File Picker When Changing Workspace|dendron://private/task.workspace.2022.01.04.use-file-picker-when-changing-workspace]]
Test:
- Run test workspace and run Change Workspace command
=> enhance(workspace): Use file picker when changing workspace

packages/common-all/src/dnode.ts, packages/engine-test-utils/src/__tests__/common-all/dnode.spec.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
Background: https://github.com/dendronhq/dendron/issues/2045
Testing:
Updated unit tests and tested manually using {{ CURRENT_DAY }}
=> fix(schema): Ensure month/day/time has two digits when doing data variable substitution

packages/engine-server/src/util/noteMetadataUtils.ts, packages/engine-test-utils/src/__tests__/pods-core/v2/AirtableExportPodV2.spec.ts, packages/engine-test-utils/src/__tests__/pods-core/v2/__snapshots__/AirtableExportPodV2.spec.ts.snap, packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/pods-core/src/builtin/AirtablePod.ts
When exporting a multi select field, can either export an array frontmatter field or an array of tags
- enhance(pod): support airtable multiselect field
- update commit
=> enhance(pod): support airtable multiselect field

packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
Skipping a failing test introduced with https://github.com/dendronhq/dendron/pull/2064/commits/11835fc847a26c3b29bb28772ce90f49ca80c9d2 to unblock test pass for now.
---
=> fix: skipping single notelookupcommand test

packages/plugin-core/src/commands/ShowPreview.ts, packages/plugin-core/src/commands/base.ts
Fixes the additional analytics for the show preview command, and makes sure any promises are resolved in case `addAnalyticsPayload` is async to prevent issues in the future.
=> fix: analytics for show preview

packages/common-all/src/api.ts, packages/common-all/src/types/typesv2.ts, packages/engine-server/src/markdown/decorations/decorations.ts, packages/plugin-core/src/features/windowDecorations.ts, packages/plugin-core/src/test/suite-integ/WindowDecorations.test.ts
The optimizations for note decorations caused frontmatter warnings to be skipped if the frontmatter is not visible within the editor. This PR fixes this by always checking for frontmatter warnings, even if it's not visible. This is actually preferred because warnings should always be displayed even if not visible, because the user could use something like "go to previous issue" to navigate to them.
=> fix: warn for frontmatter issues even if the frontmatter is not visible

README.md, packages/plugin-core/README.md
- Fixes #2024
- New contributing link: https://docs.dendron.so/notes/3489b652-cd0e-4ac8-a734-08094dc043eb/
- https://wiki.dendron.so will also be updated in upcoming promotion of docs to `master`
=> chore(docs): fix links, add more community info

packages/common-server/src/files.ts, packages/plugin-core/src/commands/ChangeWorkspace.ts, packages/plugin-core/src/commands/SetupWorkspace.ts, packages/plugin-core/src/test/suite-integ/SetupWorkspace.test.ts, packages/plugin-core/src/vsCodeUtils.ts
Use file picker instead of prompting user to manually type file path.
See [[Details|dendron://private/task.workspace.2022.01.04.use-file-picker-when-initializing-workspace#details]]
Manual Testing:
- Run Initialize Workspace and click on Code Workspace
- Verify workspace is created
We also do not prompt continue/delete for empty directories
=> enhance(workspace): Use file picker for code workspace initialization

packages/plugin-core/src/commands/ShowPreview.ts, packages/plugin-core/src/commands/base.ts
There were multiple issues associated with this bug:
1. Base command tries to merge the output from gatherOpts and the direct input to the command together.
2. This destroys any class instances and converts them to regular JS objects.
3. I was confused when implementing ShowPreview as to why my `Uri` object wasn't really a Uri object and didn't have a `uri.fsPath`, but realized `uri.path` worked. Unfortunately, that only works on non-Windows systems.
This PR fixes this problem by allowing commands to override how the inputs are merged, and then adding a new base command that passes the command input to `execute`.
It also fixes a bug where `ShowPreview` would incorrectly give an error message that there's nothing to preview if the user had no note open, but had used show preview through …
=> fix:show preview errors on Windows

packages/api-server/src/modules/notes/index.ts, packages/common-all/package.json, packages/common-all/src/fuse.ts, packages/common-all/src/types/typesv2.ts, packages/common-all/src/util/stringUtil.ts, packages/engine-server/src/doctor/service.ts, packages/engine-server/src/engineClient.ts, packages/engine-server/src/enginev2.ts, packages/engine-server/src/markdown/remark/noteRefsV2.ts, packages/engine-test-utils/src/__tests__/common-all/fuse.spec.ts, packages/engine-test-utils/src/presets/engine-server/query.ts, packages/engine-test-utils/src/presets/engine-server/write.ts, packages/nextjs-template/components/DendronSearch.tsx, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/services/EngineAPIService.ts, packages/plugin-core/src/services/EngineAPIServiceInterface.ts, yarn.lock
Related Doc Update PR:  https://github.com/dendronhq/dendron-site/pull/353
Background/Current state prior to this task is can be found in ![[dendron://private/task.lookup.2022.01.04.lookup-sort-order-inconsistent#notes,1:#*]] 
Using Levenshtein distance instead of referenced Hamming distance since its deemed to be more intuitive (and hence much more widely used), than hamming distance.
Added dependency `fast-levenshtein` to common-all it has an MIT license with 20mil a week downloads, and we already have `fast-levenshtein` dependency in some of the other packages. 
Querying for `task.tem` in test workspace makes `task.temp` show up ahead in the results even if `task.workspace.2022.01.04.sync-missing-template-frontmatter` is modified after `task.temp`
Added the following notes
``` …
```
=> fix: add sort by levenshtein distance prior to sorting by update date to lookup results of the same match score.

packages/plugin-core/package.json, packages/plugin-core/src/constants.ts
This PR:
- fixes enablement of insert note index.
- #2081 cleans up contribution points in `package.json` and properly applies `when` clauses for Dendron commands
- Before the changes, all enablement clauses were not in effect except a few that were explicitly tested to work.
- `Insert Note Index` enablement was set to `editorFocus && dendron:pluginActive`, which will always be false in the command palette because once the command palette is in focus `editorFocus` is not set.
- The proper application of `when` clauses caused `Insert Note Index` to not be enabled.
If this is your first time submitting a pull request to Dendron, copy and paste the full [Dendron Review Checklist](https://docs.dendron.so/notes/1EoNIXzgmhgagqcAo9nDn.html) into this request and check off each item as necessary. …
=> fix: insert note index enablement

packages/plugin-core/src/commands/ShowPreview.ts
This was broken after the last fix.
=> chore: correct how preview analytics "providedFile" is calculated

packages/engine-test-utils/src/__tests__/pods-core/podsv2.spec.ts, packages/pods-core/src/v2/ConfigFileUtils.ts, packages/pods-core/src/v2/PodConfigManager.ts, packages/pods-core/src/v2/podConfig/PodV2Types.ts
```markdown
This PR allows the `export pod V2` command to display a pod config when `exportScope` is omitted from the custom config.
```
=> fix(pods): display all configs on export pod v2

packages/common-all/src/types/foundation.ts, packages/common-all/src/utils.ts, packages/engine-server/src/markdown/remark/noteRefsV2.ts, packages/engine-server/src/markdown/utils.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/dendronPub.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/dendronPub.spec.ts, test-workspace/vault/dendron.ref.note-ref-override-usePrettyRefs.md
Notes are now allowed to override the pretty refs setting for themselves. All references inside that note will be rendered following the override. The override doesn't apply to nested references, the user would need to manually override the nested notes as well if needed.
Docs: https://github.com/dendronhq/dendron-site/pull/354
This PR doesn't change the circular dependency count.
=> enhance: allow notes to override the pretty refs setting

packages/api-server/src/routes/note.ts, packages/common-all/src/api.ts
The issue was caused by the request data being encoded in the query, which meant if there was too much text in the note the query string would be too long for the API client. (note text has to be included in the query because decorations update more frequently than notes in server).
An internal enhancement included in this PR is that the API will now propagate the error if there was an error that happened inside the API client itself, like this error here. Without this, the client simply returns an empty response with no error if that happens.
#1976
=> fix: highlighting breaks when there's too much text

packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/utils.ts, packages/plugin-core/src/commands/RenameNoteV2a.ts, packages/plugin-core/src/test/suite-integ/RefactorHierarchy.test.ts
This PR:
- fixes an issue with refresh note logic where link candidate logic was running even when it was disabled.
=> fix: stop link candidate logic when disabled

packages/common-all/src/util/regex.ts, packages/common-all/src/utils.ts, packages/engine-test-utils/src/__tests__/engine-server/configUtils.spec.ts, packages/nextjs-template/components/DendronLogoOrTitle.tsx, packages/pods-core/src/builtin/NextjsExportPod.ts
Logo will now correctly respect the assets prefix.
Also as an enhancement, if the logo is set as a URL, we preserve that URL identically. This can be useful if the user hosts images on a different subdomain or domain.
This PR doesn't affect the number of cyclic dependencies.
#2161
=> fix(publish): logo doesn't respect assetsPrefix

packages/common-all/src/utils.ts, packages/plugin-core/src/WorkspaceWatcher.ts, packages/plugin-core/src/test/suite-integ/WorkspaceWatcher.test.ts, packages/plugin-core/src/windowWatcher.ts
Fixes an issue where the cursor would get moved to the start of the document if the user opened the document through something like the search window, which is supposed to move the cursor to the matching position.
#2144
=> fix: cursor is moved when opening file through search interface

packages/common-all/src/env.ts, packages/pods-core/src/builtin/NextjsExportPod.ts
Some pages in publishing would fail because they tried to access `process.env`, which was used by `getStage`. `process` doesn't exist in the browser, so this causes a crash.
To fix the issue, I wrapped around `process.env` with a helper function that explicitly accesses each variable, so nextjs can replace the variables. Also added the stage variable to the nextjs export.
Unrelated to the other changes, I also made the exporting of all the JSON data and the env files concurrent. This should lead to a small speedup during exports, but I didn't try to measure the difference.
I still don't know why some pages would crash and others wouldn't in publishing, but I can confirm that this change solves the issue.
=> fix: publishing pages fail

packages/common-all/data/dendron-yml.validator.json, packages/common-all/src/constants/configs/commands.ts, packages/common-all/src/types/configs/commands/lookup.ts, packages/dendron-next-server/data/dendron-yml.validator.json, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/plugin-core/src/commands/CreateNoteWithTraitCommand.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/components/lookup/vaultSelectionModeConfig.ts, packages/plugin-core/src/components/lookup/vaultSelectionModeConfigUtils.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
enhance: add configuration for vault selection behavior, change prompt vault selection default to true
Doc PR: https://github.com/dendronhq/dendron-site/pull/329
=> enhance: add configuration for vault selection behavior, change prompt vault selection default to true

packages/common-all/data/dendron-yml.validator.json, packages/common-all/src/analytics.ts, packages/common-all/src/constants/configs/dev.ts, packages/common-all/src/types/configs/dev/dev.ts, packages/common-all/src/types/workspace.ts, packages/dendron-next-server/data/dendron-yml.validator.json, packages/plugin-core/package.json, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/commands/pods/ExportPodV2Command.ts, packages/plugin-core/src/constants.ts, test-workspace/dendron.yml
This PR adds a dev config option `enableExportPodV2` for the enablement of `Export Pod V2` commands. 
Manually tested this with:
- WHEN enableExportPodV2 is undefined or false
- WHEN enableExportPodV2 is true
=> chore: keep export pods v2 commands behind enableExportPodV2 dev config option

packages/engine-test-utils/src/__tests__/pods-core/MarkdownPod.spec.ts, packages/pods-core/src/builtin/MarkdownPod.ts, test-workspace/other-files/the-book-thief.md, test-workspace/vault2/the-book-thief.md
This PR adds config options to import note metadata on markdown import. [Docs](https://github.com/dendronhq/dendron-site/pull/366)
#2198
=> enhance(pods): import note metadata on markdown import

packages/dendron-11ty/raw-assets/sass/base.scss, packages/dendron-next-server/styles/scss/base.scss, packages/nextjs-template/styles/scss/base.scss, test-workspace/vault/dendron.ref.markdown.md
This PR fixes numbered lists stacking on top of each other in publishing/preview when they have no content.
CSS: 
-  dimensions 
- browsers
#2178
=> fix: numbered lists without content stack on top of each other

packages/plugin-core/src/commands/pods/ConfigureExportPodV2.ts, packages/plugin-core/src/commands/pods/ConfigureServiceConnection.ts, packages/plugin-core/src/commands/pods/MarkdownExportPodCommand.ts, packages/plugin-core/src/commands/pods/NotionExportPodCommand.ts, packages/plugin-core/src/components/pods/PodControls.ts, packages/plugin-core/src/test/suite-integ/ConfigureExportPodV2.spec.ts, packages/plugin-core/src/test/suite-integ/ConfigureServiceConnection.spec.ts, packages/pods-core/src/v2/podConfig/NotionPodConfig.ts
This PR adds an option to create a new service connection and export pod v2 config. Apart from this, it adds a few fixes that were found relevant while testing export pod v2 in general.
---
madge report:
- master: 65 circular dependencies
- this branch: 65 circular dependencies
---
=> enhance(pods): configure export pod v2  to create new service and pod configs.

packages/common-all/src/error.ts, packages/dendron-cli/src/commands/devCLICommand.ts, packages/dendron-cli/src/commands/notes.ts, packages/dendron-cli/src/commands/publishCLICommand.ts, packages/dendron-cli/src/commands/seedCLICommand.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-server/src/markdown/utilsv5.ts, packages/engine-server/src/seed/service.ts, packages/plugin-core/src/commands/ConvertLink.ts, packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/components/pods/PodCommandFactory.ts, packages/plugin-core/src/components/pods/PodControls.ts, packages/plugin-core/src/components/views/NoteGraphViewFactory.ts, packages/plugin-core/src/features/RenameProvider.ts, packages/plugin-core/src/utils/site.ts, packages/plugin-core/src/views/LookupView.ts, packages/pods-core/src/v2/ConfigFileUtils.ts, packages/pods-core/src/v2/external-services/ExternalConnectionManager.ts
At several points in the codebase, `assertUnreachable` was used incorrectly with no parameter. When used this way, the function does no type checking and the code path may be actually reachable.
This PR fixes this by:
- Requiring a parameter for `assertUnreachable`
- Adding an additional example for the function, and a warning to not use it without parameters
- Where possible, updating the usage to pass a parameter
- Where not possible, adding an actual exception that will give information about the failure, rather than the "this code path should be unreachable!" error message you'd get when `assertUnreachable` is used incorrectly.
=> chore: clean up incorrect `assertUnreachable` usages

packages/plugin-core/src/components/pods/PodControls.ts
This PR:
- Adds a parameter to `assertUnreachable` in `PodControls.ts`, which causes a type error.
related: https://github.com/dendronhq/dendron/pull/2267
=> fix(dev): add omitted changes that causes type error

packages/common-server/src/parser.ts, packages/engine-test-utils/src/__tests__/engine-server/drivers/file/schemaParser.spec.ts, packages/engine-test-utils/src/presets/engine-server/utils.ts
Created testSchema:
```
version: 1
schemas:
- id: testSchema
children:
- child1
- child2
title: testSchema
parent: root
- id: child1
children:
- sharedGrandchild
- id: child2
children:
- sharedGrandchild
- id: sharedGrandchild
template: template.test
```
Created new notes 
* testSchema.child1.sharedGrandchild
* testSchema.child2.sharedGrandchild
Prior to this change only child2 used to have the template applied after this change both of the newly created files got the template …
=> fix: fix schema template match when there is same grandchild from two different schema parents

.github/workflows/issue-labler.yml
issue labeler should only update labels on first open instead of
everytime someone edits
=> chore: update github label policy

packages/nextjs-template/components/DendronSearch.tsx
fix(publishing): Search Bar Results to not stay anchored to the search bar when scrolling up
Uses information from the antd's FAQ: https://ant.design/docs/react/faq
=> fix(publishing): Search Bar Results to not stay anchored to the search bar when scrolling up

packages/engine-server/src/markdown/decorations/decorations.ts, packages/engine-server/src/markdown/remark/noteRefsV2.ts, packages/engine-server/src/markdown/remark/publishSite.ts, packages/engine-server/src/markdown/utils.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/remarkUtils.spec.ts, packages/plugin-core/src/utils/editor.ts
This PR marks `MDUtilsV4` as deprecated, moves several unrelated methods out of `MDUtilsV4`, and refactors a few low-hanging fruit to switch to MDUtilsV5.
Switching more of the code will take substantial work because changes quickly break tests, and some code relies on `MDUtilsV4` features that were not brought over to `MDUtilsV5`, like being able to pass overrides for certain options. I think it makes sense to take the time to think how those should be implemented going forward, which I'll continue working on.
This PR does not affect the number of cyclic dependencies.
Docs PR: https://github.com/dendronhq/dendron-docs/pull/13
=> chore: deprecate MDUtilsV4

packages/common-all/src/analytics.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/survey.ts
This PR:
- adds metadata to inactive user survey prompt event payload that are related to determining the prompt condition.
- [~] [Write Tests](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#writing-tests) 
- [~] If your tests changes an existing snapshot, make sure that snapshots are [updated](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#updating-test-snapshots)
- [~] If you are adding a new language feature (graphically visible in VS …
=> chore: add metadata to survey prompt event payload

packages/nextjs-template/components/DendronSearch.tsx, packages/nextjs-template/utils/fetchers.ts, packages/nextjs-template/utils/fuse.ts
enhance(publish): show lookup without waiting for notes to fetch
1. This PR allows the user to type in the lookup/search bar without waiting for the notes to load. 
2. I discovered that it takes a long time for the search results to render, so I'm capping the count to 30 as discussed with @kevinslin . People are unlikely to need 500 results there, so capping is a reasonable 20/80 approach.
=> enhance(publish): show lookup without waiting for notes to fetch

packages/nextjs-template/components/DendronLayout.tsx
fix(publish): CSS sidebar is off on smaller screens like iPad
Fixes #2290 by making sure we never actually subtract from the minimum `200px` width
=> fix(publish): CSS sidebar is off on smaller screens like iPad

packages/common-all/src/dnode.ts, packages/common-test-utils/src/presets/notes.ts, packages/engine-test-utils/src/__tests__/common-all/dnode.spec.ts
As followup from https://github.com/dendronhq/dendron/discussions/2207, we will use string replacement instead of lodash to support date variable substitution. Since we don't need javascript evalaution, we find this will be simpler. We will still use lodash default interpolate delimiter
**Testing**
Create template as follows:
```
Year is <%= CURRENT_YEAR %>
Month is <%=CURRENT_MONTH %>
Hour is <%=CURRENT_HOUR%>
This links goes to [[daily.journal.<%=CURRENT_YEAR%>.<%= CURRENT_MONTH%>.<%= CURRENT_DAY%>]]
```
Creating note with template leads to:
```
Year is 2022
Month is 01
Hour is 13
This links goes to [[daily.journal.2022.01.26]]
```
Updated docs for [[Template Variables|dendron://dendron.dendron-site/dendron.topic.templates#template-variables]]
**Madge**
Before: 130
After: 130
=> enhance(schemas): Support date subsitution via string replacement

packages/common-server/src/errorReporting.ts, packages/plugin-core/src/test/suite-integ/errorReporting.test.ts
enhance(dev): strip prefix from sentry stacktraces and traces formatting
For writing a test I looked through several dozen stack traces on actual traces.
=> enhance(dev): strip prefix from sentry stack traces and traces formatting

packages/common-server/src/errorReporting.ts
chore(dev): explicitly set sentry sampling rates and add comments
The current `traceSampleRate` setting does nothing whereas `sampleRate` is what we want.
=> chore(dev): explicitly set sentry sampling rates and add comments

.github/workflows/publish-extension-nightly.yml
fix(dev): correctly detect DENDRON_RELEASE_VERSION using both marketplace and package.json
Currently it gets it from `package.json`. The updated version gets the latest version from `package.json` and the marketplace by running (`npx vsce show dendron.nightly --json`). It concates both things and uses `sort -rn | head -n 1` to select the latest version.
I manually tested the command by running it separately in my shell with various versions in `package.json`.
=> fix(dev): correctly detect DENDRON_RELEASE_VERSION using both marketplace and package.json

packages/plugin-core/src/commands/ShowPreview.ts, packages/plugin-core/src/commands/ShowPreviewInterface.ts, packages/plugin-core/src/test/suite-integ/ShowPreview.test.ts, packages/plugin-core/src/vsCodeUtils.ts
Fixes a couple issues:
- Preview would open the wrong path on Windows (`Uri.path` instead of `Uri.fsPath`)
- When opened from the command bar, preview would open existing notes as non-note files
Also added automated tests for the preview to hopefully catch these issues in the future.
=> fix: preview opens wrong path on Windows

packages/plugin-core/src/commands/ShowPreview.ts
This was meant to be a part of #2326 but was missed.
=> fix: show preview doesn't display targeted files when using file explorer

packages/engine-server/src/markdown/remark/dendronPreview.ts, packages/plugin-core/src/windowWatcher.ts
Switches some logs created in `handleImage` and `onDidChangeTextEditorVisibleRanges` to debug. These were excessively filling up logs.
Also refactors the deprecated logger usage in `handleImage`.
=> chore: reduce unnecessary logs

packages/plugin-core/src/services/CommandRegistrar.ts, packages/plugin-core/src/test/suite-integ/ConfigureCommand.test.ts, packages/plugin-core/src/test/suite-integ/CreateSchemaFromHierarchyCommand.test.ts, packages/plugin-core/src/test/suite-integ/PreviewLinkHandler.test.ts, packages/plugin-core/src/test/suite-integ/ReferenceProvider.test.ts, packages/plugin-core/src/test/suite-integ/VaultAddCommand.test.ts, packages/plugin-core/src/test/suite-integ/components/traits/CommandRegistrar.test.ts, packages/plugin-core/src/test/suite-integ/components/traits/NoteTraitService.test.ts, packages/plugin-core/src/test/suite-integ/components/traits/RegisterNoteTraitCommand.test.ts, packages/plugin-core/src/test/testUtilsV3.ts, packages/plugin-core/src/test/testUtilsv2.ts
This PR deprecates `runLegacySingleTest` and `runLegacyMultiTest` because they are prone to errors, as evidenced by the tests here that were broken (tests that didn't run at all, or ran and failed but the failure wasn't picked up because the promise was dropped).
It also fixes some tests that were broken or failing. A few tests are skipped and marked with TODO, these tests were already effectively being skipped due to the incorrect testing code and fixing them is non-trivial.
=> chore: deprecate runLegacy*Test and fix failing or broken tests

.github/workflows/publish-extension-nightly.yml
chore(dev): append -nightly to the nightly build version for sentry
Tested:
1. Manually by running the command in my shell.
2. Manually by making a build with a random string and seeing a version with it in sentry.
=> chore(dev): append -nightly to the nightly build version for sentry

packages/dendron-cli/src/commands/base.ts, packages/dendron-cli/src/commands/workspaceCLICommand.ts, packages/engine-server/src/topics/git.ts, packages/engine-server/src/workspace/service.ts, packages/engine-server/src/workspace/workspaceServiceInterface.ts, packages/engine-test-utils/src/__tests__/engine-server/workspace.spec.ts, packages/engine-test-utils/src/utils/git.ts, packages/plugin-core/src/commands/AddAndCommit.ts, packages/plugin-core/src/commands/Sync.ts, packages/plugin-core/src/test/suite-integ/SyncCommand.test.ts, packages/plugin-core/src/vsCodeUtils.ts
This PR brings in many improvements to the Workspace Sync:
- it can now stash and unstash local changes to pull even when there are uncommitted changes
- it can detect merge conflicts and ongoing rebases to avoid committing bad notes (may help #2280)
- it can detect bad or misconfigured remotes and warn about them
- it can detect that a push would fail, and avoid pushing to remote
- it can detect that a push is not needed, and skip pushing
- The message displayed to the user will switch between an information, warning, and error message type depending on what happened during the sync.
- Commit messages now include the version of Dendron, the names of vaults in that repository, and the hostname of the committing machine #2281
Docs: https://github.com/dendronhq/dendron-site/pull/378
The …
=> enhance: Workspace Sync warns about bad states, can pull with uncommitted changes, and has better commit messages

packages/plugin-core/src/WSUtilsV2.ts, packages/plugin-core/src/WSUtilsV2Interface.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
**Bug**
1. `foo` exists in vault 1
2. `foo.two` exists in vault 2
3. Schema references template called `foo`
4. When creating a new note that matches the schema, body from `foo` in vault 1 should be applied. However, `foo` from vault 2 gets suggested b/c it is an stub note type
**Fix**
Filter out stub notes when suggesting template notes
=> fix(schemas): Do not include stubs as part of template suggestions when applying a template

packages/common-server/src/errorReporting.ts, packages/plugin-core/src/logger.ts
chore(dev): fix 'Non-Error exception captured' in Sentry
1. The `Non-Error exception captured` is happening because we are converting error in the payload with `error2PlainObject()`
2. I also discovered that we are overwriting context in `eventModifier` in `errorReporting.ts`: so I added `...event.extra`
=> chore(dev): fix 'Non-Error exception captured' in Sentry

packages/plugin-core/src/_extension.ts
There's currently a bug where users that use Dendron every day are still
getting prompted. Disabling until we root cause and fix
=> chore: disable inactive user survey prompt

package.json
`lint-staged` causes the unstaged hunks inside partially-staged files to be staged as well. This may cause people (especially myself) to accidentally commit changes they did not intend to commit. This PR removes `lint-staged`.
=> chore: remove lint-staged

packages/engine-server/src/workspace/service.ts, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/workspace.spec.ts.snap
- Adds `.next` and `pods/service-connections` as default ignored directories within newly initialized workspaces
- `.next` should always be ignored, unless explicitly added to a repo
- `pods/service-connections` should be ignored as these generally include API keys, and they are stored separate from other pod configuration files due to this
- Related: https://github.com/dendronhq/dendron/issues/2355
=> chore(workspace): Expand default .gitignore to include .next and pods/service-connections

pull_request_template.md
Team contributions have a few more steps compared to community
contributions - make this explicit by splitting out PR checklist into
two separate templates
=> chore(dev): update pr templates for community and team contributions

packages/plugin-core/src/test/suite-integ/WindowDecorations.test.ts, packages/plugin-core/src/test/suite-integ/migration.test.ts, packages/plugin-core/src/test/testUtilsV3.ts
- Adds function headers to describeSingleWS and describeMultiWS
- removes two existing instances of fn's marked async 
--- 
- General
- Operations
- Architecture
- CSS …
=> chore(dev): emphasize no async fns on the describeWS Test functions

packages/nextjs-template/components/DendronTOC.tsx
This addresses the reason why I didn't notice the warning about `useLayoutEffect` in #2379 
- General
- Operations
- Architecture
- CSS
- eg: [breaking dev change due to new dependency](https://github.com/dendronhq/dendron/pull/2188#pullrequestreview-855696330)
=> chore(publish): Fix missing unique key warning

packages/plugin-core/src/ExtensionProvider.ts, packages/plugin-core/src/WorkspaceWatcher.ts, packages/plugin-core/src/clientUtils.ts, packages/plugin-core/src/commands/MoveHeader.ts, packages/plugin-core/src/components/lookup/NotePickerUtils.ts, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/dendronExtensionInterface.ts, packages/plugin-core/src/features/windowDecorations.ts, packages/plugin-core/src/test/MockDendronExtension.ts, packages/plugin-core/src/test/suite-integ/WindowWatcher.test.ts, packages/plugin-core/src/test/suite-integ/WorkspaceWatcher.test.ts, packages/plugin-core/src/views/LookupView.ts, packages/plugin-core/src/views/utils.ts, packages/plugin-core/src/windowWatcher.ts, packages/plugin-core/src/workspace.ts
Madge Before: 53
Madge After: 48
Some notables changes in this commit:
- Update extension interface and extensionprovider to expose `isActive`, `getWorkspaceConfig`, and `getTreeView`
- Remove dependency on `workspace.ts` from `WorkspaceWatcher.ts`
- Update constructor of `WorkspaceWatcher.ts` to pass in windowwatcher instance
- Move `refreshLookupView` from `PickerUtilsV2` to class method of `LookupView`
- Update constructor of `LookupView` to take in extension instance
TODO: Resolve cyclic dependencies around `fileWatcher.ts` which should resolve rest of watcher specific issues
=> chore(workspace) First pass at resolving cyclic dependencies wrt windowwatcher/workspacewatcher

packages/common-all/src/utils.ts, packages/engine-test-utils/src/__tests__/common-all/journalTitle.spec.ts, packages/plugin-core/src/commands/CreateDailyJournal.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/test/MockDendronExtension.ts, packages/plugin-core/src/test/suite-integ/LookupJournal.test.ts, packages/plugin-core/src/traits/journal.ts
Fixes consistency issues where sometimes the titles on Journal notes weren't properly formatted as `yyyy-MM-dd` and the journalNote traitID wasn't being applied.
This also fixes other pre-existing issues where the journal title would not get properly generated if you deviate from the default `y-MM-dd` format for the journal note config.
Related: 
- https://github.com/dendronhq/dendron/issues/2341
- https://github.com/dendronhq/dendron/issues/2211
- https://github.com/dendronhq/dendron/issues/1911
After this change, when creating a Journal note from the following scenarios below should result in consistent frontmatter
- `Dendron: Create Daily Journal Note`
- `Dendron: Create Journal Note`
- Creating a note via Lookup with the Journal button selected
- Clicking on a new date in the Calendar …
=> fix(workspace): Journal Note Consistency with Title and Traits

packages/common-server/src/filesv2.ts, packages/engine-server/src/workspace/utils.ts, packages/engine-test-utils/src/__tests__/common-server/filev2.spec.ts, packages/plugin-core/src/WSUtilsV2.ts, packages/plugin-core/src/WorkspaceWatcher.ts, packages/plugin-core/src/dendronExtensionInterface.ts, packages/plugin-core/src/test/MockDendronExtension.ts, packages/plugin-core/src/test/suite-integ/WorkspaceWatcher.test.ts
This commit makes the following changes:
- `onFirstOpen` should only track files in the workspace
- note specific operations (eg. moving cursor past frontmatter) should only happen for dendron notes
- adds two new methods to `IDendronExtension` (`activateWatchers` and `deactivate`)
Before, opening a big json file (eg. Dendron Logs) would cause vscode to crash because Dendron would try to parse the entire log file. 
This commit also introduces two new conventions:
1. The `WorkspaceWatcher` is hard to test since methods are `private` and require a working VSCode workspace to actually trigger (which we do not have access to in tests). 
Some solutions that were explored:
- ad-hoc dependency injection: resulted in too many code changes, we're better off actually implementing DI properly using …
=> fix(workspace): Dendron will try to parse non-dendron files in `onFirstOpen`

packages/common-all/data/dendron-yml.validator.json, packages/common-all/src/types/intermediateConfigs.ts, packages/dendron-cli/src/commands/devCLICommand.ts, packages/dendron-next-server/data/dendron-yml.validator.json
This PR:
- adds json schema validation for the newly migrated v5 dendron configuration. 
- General
- [~] check whether code be simplified
- [~] check if similar function already exist in the codebase. if so, can it be re-used?
- Operations
- Architecture
- eg: [making changes to DNode](https://github.com/dendronhq/dendron/pull/2158#pullrequestreview-854 …
=> chore: add json schema validation for v5 config

packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/components/lookup/HierarchySelector.ts, packages/plugin-core/src/test/suite-integ/components/pods/BaseExportPodCommand.test.ts, packages/plugin-core/src/test/suite-integ/components/pods/TestExportCommand.ts
This PR attempts to respect the vault boundaries while performing hierarchy export in pods-v2. 
***
madge report
no new circular dependencies(48)
***
- General
- Operations
- Architecture
- CSS …
=> enhance(pods): add vault filter for pods-v2 hierarchy export

packages/common-all/package.json, packages/common-all/src/dnode.ts, yarn.lock
Vercel merged our contribution that fixes the international characters bug, and released a new version. This PR switches us back to that version so we can continue to get updates from upstream.
I added a warning to our fork of the repository and archived it.
=> chore: switch back to vercel's title package

packages/plugin-core/src/logger.ts
This PR adds a fix for
-  error message toast contains a very unreadably formatted error message for string payload.
related https://github.com/dendronhq/dendron/issues/2410
=> fix(workspace): error message to be readable in error toast

packages/common-all/package.json, packages/common-all/src/uuid.ts
This brings more compatibility to the widest possible use cases when synchronizing dendron notes with other sources.
For example, when ids are used in urls, certain hosting providers like netlify will lowercase all urls which will break users that publish using case sensitive ids.
This update makes the following changes:
- update dendron ids to be alphanumeric lowercase
- removes nanoidDictionary dependency
- extend the default length of a dendron id to 32 characters (this is the same length as what other providers like notion and loom use )
Documentation available at https://github.com/dendronhq/dendron-site/pull/402
***
- [~] circular dependency check: make sure your code is not introducing new circular dependencies in plugin-core.  See [Avoiding Circular …
=> enhance(notes): change dendron id format to be alphanumeric lowercase

packages/api-server/src/routes/note.ts, packages/common-all/src/api.ts, packages/common-all/src/types/typesv2.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/engineClient.ts, packages/engine-server/src/enginev2.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-server/src/utils.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/remarkUtils.spec.ts, packages/engine-test-utils/src/presets/engine-server/getAnchors.ts, packages/engine-test-utils/src/presets/engine-server/getLinks.ts, packages/engine-test-utils/src/presets/engine-server/index.ts, packages/plugin-core/src/services/EngineAPIService.ts, packages/plugin-core/src/services/EngineAPIServiceInterface.ts, packages/plugin-core/src/services/NoteSyncService.ts, packages/plugin-core/src/test/suite-integ/BacklinksTreeDataProvider.test.ts, test-workspace/vault/dendron.ref.links.md
This PR moves the calculation of backlinks (including backlink candidates) and anchors to the engine during editing. This should improve editor responsiveness as these calculations can block the extension thread for significant time for long files.
- General
- Operations
- Architecture …
=> enhance: calculate backlinks and anchors in engine for improved editor responsiveness

packages/dendron-next-server/styles/scss/base.scss, packages/nextjs-template/styles/scss/base.scss, packages/nextjs-template/styles/scss/main.scss, test-workspace/vault/dendron.ref.markdown.md
The height of the horizontal rule (line) in the preview depended on a browser default style that sets the border size for the rule. This PR makes that explicit so it's clearer in future refactors, and fixes this in publishing where that wasn't the default.
#2438
- CSS
=> fix(publish): horizontal rule height in publishing

packages/engine-server/src/config.ts, packages/engine-server/src/topics/site.ts, packages/engine-test-utils/src/__tests__/site.spec.ts
This PR:
- fixes a regression introduced in https://github.com/dendronhq/dendron/pull/2212 where `siteIndex` was not properly set when it was implicit
- When the config doesn't exist, it should be set to the first element of `siteHierarchies`
- General
- Operations
- Architecture
- [~] can we track the performance of this change to know if …
=> fix: properly set siteIndex when it's not explicitly set by config

packages/common-all/src/dnode.ts, packages/plugin-core/src/test/suite-integ/GotoNote.test.ts
**Background**
Previously, when we run Goto note command, we would only apply a template if it was in same vault as the note. Now we will apply the first template match. If there are multiple template matches across multiple vaults, pick first one to apply. This is temporary until we support xvault support for this command.
**Testing**
Verified manually and added new test case
- General
- Operations
- Architecture
- eg: [see usage for export pod](https://github.com/dendronhq/dendron/pull/2190#pullrequestr …
=> fix(schema): Apply schema template for goto-note-command if template is in different vault

packages/common-all/src/constants/configs/compat.ts, packages/common-all/src/utils.ts, packages/dendron-cli/src/commands/base.ts, packages/engine-test-utils/src/__tests__/common-all/config.spec.ts
This PR:
- readds config-client version mapping for v5 (config v5 to client version 0.83.0)
- In https://github.com/dendronhq/dendron/pull/2424 I removed the compat mapping for v5, which introduced a bug where users who are on v5 will hit an unexpected error because the validation logic was looking for a mapping that didn't exist. This PR fixes this regression.
- allow "soft mapping" of config-client version
- this is used to relax the config-client compatibility validation in dendron-cli when the newly introduced config version is backwards compatible.
- If a config is outdated (e.g. config v4 on version 0.83.0), the same mismatch notice will be printed, but will not exit the process since we still accept the outdated config.
madge reports no diffs
- eg: [if configuration for utilities …
=> chore: allow config client soft mapping

packages/engine-server/src/markdown/remark/utils.ts, packages/engine-server/src/markdown/types.ts, packages/engine-test-utils/src/presets/engine-server/getAnchors.ts, packages/nextjs-template/components/DendronTOC.tsx, test-workspace/vault/dendron.links.heading-anchors.md
#2456
The cache files need to be deleted for this fix to apply, otherwise the cached bad version will be published.
See ToC on the image above
- circular dependency count is unchanged
- General
- Operations
- Architecture
- [~] if you are adding analytics related changes, make sure the [Telemetry](https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html) docs are …
=> fix(publish): Table of Contents is missing user tags, inline code, dashes and underlines

packages/common-all/src/types/typesv2.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/plugin-core/src/ExtensionProvider.ts, packages/plugin-core/src/commands/ConvertLink.ts, packages/plugin-core/src/commands/GotoNote.ts, packages/plugin-core/src/dendronExtensionInterface.ts, packages/plugin-core/src/features/DefinitionProvider.ts, packages/plugin-core/src/features/ReferenceHoverProvider.ts, packages/plugin-core/src/features/ReferenceProvider.ts, packages/plugin-core/src/features/RenameProvider.ts, packages/plugin-core/src/test/MockDendronExtension.ts, packages/plugin-core/src/test/suite-integ/ConvertLink.test.ts, packages/plugin-core/src/test/suite-integ/ReferenceHoverProvider.test.ts, packages/plugin-core/src/test/suite-integ/ReferenceProvider.test.ts, packages/plugin-core/src/test/suite-integ/md.test.ts, packages/plugin-core/src/utils/md.ts, packages/plugin-core/src/workspace.ts
fix(workspace): dendron can hang when trying to provide hover for large non-dendron file
This currently happens because `ReferenceHoverProvider` can be triggered for all files. This function calls `getReferenceAtPosition` which will attempt to parse the file using `unified` to find hover positions. This will blow up spectacularly when parsing large files (eg. Dendron logs) and cause the vscode process to hang.
This fix adds a check in `getReferenceAtPosition` to not parse the file if it is not a dendron note or in a dendron workspace. It also provides this check across most of the symbol provider methods in Dendron. List of changes below:
Changes:
- convert `getReferenceAtPosition` to async, do not run for non-dendron note
- ReferenceHoverProvider restrict to dendron note (cause of …
=> fix(workspace): dendron can hang when trying to provide hover for large non-dendron file

packages/plugin-core/src/commands/GotoNote.ts
This PR
- Removes an unused import in `GoToNote.ts` that was introduced in https://github.com/dendronhq/dendron/commit/8d359d39c54672fdebbd647cd8bff1867b6000d2
- Looks like the use of `AnchorUtils` was removed from `GoToNote.ts` in #2455, then only the import statement was added back during a merge with the master branch.
=> chore: remove unused import

packages/common-frontend/src/features/engine/hooks.ts, packages/common-frontend/src/features/engine/slice.ts, packages/dendron-plugin-views/src/components/DendronApp.tsx, packages/dendron-plugin-views/src/components/DendronNotePage.tsx, packages/dendron-plugin-views/src/components/DendronTreeExplorerPanel.tsx
This change makes loading of our webviews faster. 
1. There was what I assume is a copy-paste error in `slice.ts` where `initNotes` and `syncNote` both had the same typePrefix of "engine/init" being passed into `createAsyncThunk`.  This inadvertently caused a big problem - we have `extraReducers` hooked up to trigger off of pending+fulfilled of `initNotes`.  But under the hood in redux, it seems like these are actually keyed off of the registered typePrefix - so the resulting effect is that every time we just wanted to do `syncNote`, we ended up triggering `initNotes` _twice_ (why twice instead of once I'm not too sure, but the logs showed that this was happening).  We set the `syncNote` flag extensively - it's set during tree view state changes and every time preview is changed - …
=> fix(views): faster webviews by reducing engine sync operations

packages/common-all/src/types/typesv2.ts, packages/common-frontend/src/features/engine/slice.ts, packages/dendron-plugin-views/src/components/DendronApp.tsx, packages/engine-server/src/enginev2.ts, packages/engine-test-utils/src/__tests__/engine-server/enginev2.spec.ts, packages/engine-test-utils/src/index.ts, packages/engine-test-utils/src/presets/engine-server/query.ts, packages/plugin-core/src/commands/GotoNote.ts, packages/plugin-core/src/features/BacklinksTreeDataProvider.ts, packages/plugin-core/src/views/DendronTreeViewV2.ts, packages/plugin-core/src/views/EngineNoteProvider.ts, packages/plugin-core/src/workspace.ts
**Background**
As part of initiative to deprecate notesyncservice#onnotechanged, we will first migrate the dendron treeviewv2 to the engine events. See part 1 of [[Deprecate Notesyncservice Onnotechanged|dendron://private/task.2022.02.14.deprecate-notesyncservice-onnotechanged]]
**Changes**
1. Update `DendronTreeViewV2` to use engine events instead of notesyncservice
2. Added optional param `activeNote` to `OnDidChangeActiveTextEditorData`. This param lets the frontend know which note to focus on. Sometimes users can make changes to notes outside the active note but we do not want the focus to change.
3. Avoid TypeError due to indexoutofboundsexception in frontend and engine
4. If engine cannot find a note for a given query, return empty array instead of an error
*Madge*
plugin-core …
=> chore(treev2): Migrate from notesyncservice to engine events

packages/common-all/src/constants/configs/global.ts, packages/common-all/src/constants/configs/preview.ts, packages/common-all/src/constants/configs/publishing.ts, packages/common-all/src/types/configs/preview/preview.ts, packages/common-all/src/utils.ts, packages/engine-server/src/markdown/remark/hierarchies.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/dendronPub.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/dendronPub.spec.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/test/suite-integ/migration.test.ts
This PR:
- Splits up `enableFrontmatterTags` and `enableHashesForFMTags` to be in `preview` and `publishing` namespace
- originally (before publishing namespace migration), both preview and publishing behavior was set by one config under `site.{enableFrontmatterTag|enableHashesForFMTags}`
No diff in madge output
- General
- Operations
- Architecture
- [~] if you are adding analytics …
=> chore: separate tag configs

packages/plugin-core/src/commands/Doctor.ts, packages/plugin-core/src/test/suite-integ/DoctorCommand.test.ts
This PR:
- fixes Doctor command so that `Reload Index` is not called before and after if the selected doctor action is `findIncompatibleExtensions`. (not needed, and significantly slows down operation in large workspaces.)
madge reports no diffs.
- General
- Operations
- Architecture …
=> fix: don't call reload index if action is findIncompatibleExtension

packages/plugin-core/src/views/DendronTreeViewV2.ts
- This fixes a regression with tree view where the tree view was getting refreshed regardless of its visibility, resulting in a forced side panel open and focus to the tree view panel.
- `refreshDendronTreeViewV2EngineNoteStateChanged` will not take effect if 
- `this._view` is `undefined` (tree view panel was never opened in this session), or
- `this._view.visible` is `false` (side panel is hidden / tree view panel is not expanded)
(in master)
1. open tree view once, 
2. hide side panel, 
3. try updating anything in any note, 
4. side panel is opened again and tree view is focused on every subsequent note change event 
- eg: [if configuration for utilities are already in one module or package, add future utilities there as well](https://github.com/dendronhq/dendron/pull/1960#discussion_r7 …
=> fix: don't refresh tree view if note visible

packages/dendron-cli/src/commands/devCLICommand.ts
Attempts to fix the issue causing the failure in the previous Publish Dendron pipeline: https://github.com/dendronhq/dendron/actions/runs/1883143675
Adds a 2 min sleep after we publish packages to NPM remote registry to give it adequate time to reflect on remote servers.  Otherwise, sometimes we get a 'package not found' when we try to download those packages on the next step of the build.
---
N/A for all below: 
- General
- Operations
- Architecture
- eg: [making …
=> chore(internal): sleep after npm publish in publish dendron workflow

packages/common-all/src/analytics.ts, packages/common-server/src/analytics.ts, packages/dendron-cli/src/utils/analytics.ts, packages/engine-test-utils/src/__tests__/engine-server/segmentClient.spec.ts, packages/plugin-core/src/scripts/uninstallHook.ts, packages/plugin-core/src/utils/analytics.ts
chore(analytics): fix session id logic
To track session id, segment expects the field to be passed in as `track({integrations: ...})`. We currently pass in all metadata as `properties`.
This change exposes all of segment's track properties to our analytic wrappers and also changes the input parameters to be object based (vs positional)
***
no change to circular dep
***
- General
- Operations
- Architecture
NA …
=> chore(analytics): fix session id logic

packages/common-frontend/src/components/DendronNote.tsx, packages/dendron-cli/src/utils/build.ts, packages/engine-server/src/markdown/utilsv5.ts, packages/nextjs-template/components/DendronLayout.tsx
This PR:
- Properly handles v5 configs for mermaid and katex (`publishing.enableMermaid` and `publishing.enableKatex`) when publishing, and fixes an issue that cause mermaid diagrams and katex expressions not rendering when the note is published.
- Properly sync katex fonts to plugin during build in `dendron dev sync_assets`
- General
- Operations
- Architecture
- [~] if you are adding analytics related changes, make sure the [Telemetry](https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.h …
=> fix: properly render mermaid and katex when published

packages/engine-server/src/markdown/remark/dendronPub.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-test-utils/src/__tests__/pods-core/v2/MarkdownExportPodV2.spec.ts, packages/pods-core/src/v2/pods/export/MarkdownExportPodV2.ts
```md
fix(pods): markdown export pod v2 to acknowledge `wikiLinkToURL` for links inside note references 
```
- related to [issue 2444](https://github.com/dendronhq/dendron/issues/2444)
- updates MarkdownExportV2 to use `MDUtilsV5`
- fixes a regression where wikiLinkToURL: true breaks noteRefs
***
madge report
No new circular dependencies added(18)
***
- General
- Operations
- Architecture …
=> fix(pods): md export v2 to acknowledge wikiLinkToURL for links inside noteRefs

packages/common-all/src/dnode.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-test-utils/src/__tests__/engine-server/EngineEvents.spec.ts, packages/engine-test-utils/src/__tests__/pods-core/GithubIssuePod.spec.ts, packages/engine-test-utils/src/presets/engine-server/write.ts, packages/plugin-core/src/test/suite-integ/MoveNoteCommand.test.ts
This PR:
- fixes a bug where overwriting an existing note's id will result in:
- stale children props of the parent of the note
- orphaned children of the written note
- generally refactors code that this edge case covers in `_writeNewNote` and add omitted relevant note change entries.
- adds the test that was skipped in `EngineEvents.spec.ts` that this bug was blocking.
No added circ dependencies.
- General
- Operations
- Architecture …
=> fix(internal): write note orphans child notes

packages/common-all/src/analytics.ts, packages/dendron-cli/src/commands/doctor.ts, packages/engine-server/src/doctor/service.ts, packages/engine-server/src/topics/git.ts, packages/engine-server/src/workspace/service.ts, packages/engine-server/src/workspace/workspaceServiceInterface.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/doctor.spec.ts, packages/engine-test-utils/src/utils/git.ts, packages/plugin-core/src/commands/Doctor.ts, packages/plugin-core/src/commands/ReloadIndex.ts, packages/plugin-core/src/test/suite-integ/ReloadIndex.test.ts
If a vault has a remote configured, but the vault configuration did not have a remote set, then this PR automatically updates the configuration to mark the vault as a remote vault.
The PR also adds telemetry for both this feature, and also the existing features that fix missing root note and schemas.
Finally, the PR improves our git wrapper when detecting the current remote. Before we would just use the first remote available, but that might not be the remote for the current branch. The new code tries to parse the remote from the upstream of the current branch, then falls back to the first available remote if that fails.
Docs: https://github.com/dendronhq/dendron-site/pull/418
- No change
- eg: [if configuration for utilities are already in one module or package, add future utilities …
=> enhance(workspace): automatically update configuration for vaults that have remotes, but aren't configured as such

packages/common-all/src/vault.ts, packages/engine-test-utils/src/__tests__/common-all/vault.spec.ts
**Change**
Update `getVaultByDirPath` to return exact match.
** Bug**
If vault to search has name "vault1", the method can return vaults that equal "vault", "va", etc..
- General
- Operations
- Architecture
- CSS
=> fix(vaults): Use exact match when getting vault by dir path

packages/plugin-core/src/test/suite-integ/VaultConvert.test.ts, packages/plugin-core/src/test/suite-integ/components/pods/GoogleDocsExportCommand.test.ts, packages/plugin-core/src/test/testUtilsV3.ts
**Background**
We have a wide variety of ways to write test cases, some deprecated, some modern. Moving forward, we would like all tests in `plugin-core` to use `describeSingleWS` or `describeMultiWS`. In order to make that possible, we need to make sure that the new test functions support existing use cases.
**Changes**
- Move functionality from `setupBeforeAfter` into both `describeSingleWS` or `describeMultiWS`
- Deprecate setupBeforeAfter
- See [[Issues with plugin test harness|dendron://private/meet.async.2022.02.25.describe-ws-updates]]
**Next changes**
- Update all tests using `describeSingleWS` or `describeMultiWS` to no longer use `setupBeforeAfter` 
- Migrate tests in plugin-core to use `describeSingleWS` or `describeMultiWS`
- eg: [if configuration for utilities are already in …
=> chore(tests): Deprecate setupBeforeAfter

packages/plugin-core/src/commands/base.ts
Re-throws the errors from the base command class during development. This avoids the issue where a command will fail when running tests, but the base command class blackholes these errors so from the viewpoint of the test it looks like the command worked. This can be hard to debug as it looks like the command worked, but the results of the command are partial.
=> chore: base commands rethrows error during development for easier debugging

packages/common-all/src/dnode.ts, packages/dendron-cli/src/commands/podsV2.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/exportPodV2CLI.spec.ts, packages/plugin-core/src/commands/pods/AirtableExportPodCommand.ts, packages/plugin-core/src/commands/pods/ConfigureExportPodV2.ts, packages/plugin-core/src/commands/pods/GoogleDocsExportPodCommand.ts, packages/plugin-core/src/commands/pods/JSONExportPodCommand.ts, packages/plugin-core/src/commands/pods/MarkdownExportPodCommand.ts, packages/plugin-core/src/commands/pods/NotionExportPodCommand.ts, packages/plugin-core/src/components/pods/PodCommandFactory.ts, packages/plugin-core/src/components/pods/PodControls.ts, packages/plugin-core/src/test/suite-integ/ConfigureExportPodV2.spec.ts, packages/plugin-core/src/test/suite-integ/ConfigureServiceConnection.spec.ts, packages/plugin-core/src/test/suite-integ/components/pods/GoogleDocsExportCommand.test.ts, packages/plugin-core/src/test/suite-integ/components/pods/JSONExportCommand.test.ts, packages/pods-core/src/utils.ts
```
chore(internal): remove deprecated getExtension and runLegacyWorkspaceTest from some files
```
This PR attempts to
- remove some getExtension() and runLegacyWorkspaceTest from files
- create two new utilities to get file path of pod custom config and service connection config.
***
madge report
no new dependency added(18 circular dependencies)
***
- General
- Operations
- Architecture
- [~] check if code is introducing changes on a foundational class or interface. if …
=> chore(internal): remove deprecated getExtension and runLegacyWorkspaceTest from some files

packages/common-all/src/dnode.ts, packages/engine-server/src/changelog/changelog.ts, packages/engine-server/src/enginev2.ts, packages/engine-server/src/markdown/decorations/taskNotes.ts, packages/engine-server/src/markdown/remark/backlinks.ts, packages/engine-server/src/markdown/remark/dendronPub.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-server/src/markdown/remark/wikiLinks.ts, packages/engine-server/src/markdown/utilsv5.ts, packages/engine-server/src/topics/site.ts, packages/plugin-core/src/commands/GoToSiblingCommand.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/features/completionProvider.ts, packages/plugin-core/src/test/suite-integ/CompletionProvider.test.ts, packages/plugin-core/src/utils/md.ts, packages/pods-core/src/builtin/AirtablePod.ts, packages/pods-core/src/builtin/NextjsExportPod.ts
I was doing some perf testing on preview, and I found that for notes with a lot of links and tags, the render time was O(n), where n is the number of notes in the workspace.  This was true even if all of the notes or tags were the exact same link, just repeated hundreds of times. 
I tracked this down to some code in `dendronPub.ts` which was using the legacy `getNoteByFnameV5` instead of the new `getNoteByFnameFromEngine`.  The legacy `getNoteByFnameV5` and `getNotesByFnameV5` are O(n) for note lookup, whereas the new versions are ~O(1) due to using a dictionary/hash-map implementation. 
Given the pervasive use of the legacy calls, I started to scrub through to upgrade many existing instances to the new ones, which should result in performance improvements across many different kinds of …
=> fix(views): md parsing and preview perf improvements

packages/dendron-cli/src/commands/base.ts, packages/dendron-cli/src/commands/devCLICommand.ts, packages/engine-server/src/migrations/migrations.ts, packages/engine-server/src/migrations/service.ts, packages/plugin-core/src/commands/RunMigrationCommand.ts, packages/plugin-core/src/test/suite-integ/migration.test.ts
This PR
- adds omitted migration.
- this resolves a regression with dendron-cli where `show_migration` would not display the latest (`0.83.0`) migration as an option.
- General
- Operations
- Architecture …
=> fix: add omitted migration entries

packages/common-all/data/dendron-yml.validator.json, packages/dendron-next-server/data/dendron-yml.validator.json
This PR:
- adds json schema validation for `preview.enableFrontmatterTags` and `preview.enableHashesForFMTags`
=> chore: add validation for enableFrontmatterTags and enableHashesForFMTags

packages/dendron-plugin-views/src/components/DendronTreeExplorerPanel.tsx
There's a race condition in the Tree View V2 which may cause the Tree View to not initialize properly.  This change makes the data fetching operations on Tree View wait for the engine to be initialized first.
--- 
- [N/A] circular dependency check: make sure your code is not introducing new circular dependencies in plugin-core.  See [Avoiding Circular Dependencies](dev.process.code.best-practices).
- General
- Operations
- Architecture …
=> fix(views): fix race condition in tree view v2 initialization logic

packages/pods-core/src/v2/pods/export/GoogleDocsExportPodV2.ts
```
fix(pods): Google Docs Export pod displays Bad Request error on export
```
This PR aims to resolve a `Bad Request 400` error thrown by Goggle Docs Export Pod. The GDoc export pod uses HTML Publish pod to perform the Md --> HTML conversion of note and send the data to google drive API. For some notes, the google API regards the content as invalid HTML and rejects it as bad request. 
- General
- Operations
- …
=> fix(pods): Google Docs Export pod displays Bad Request error on export.

packages/engine-server/src/util/noteMetadataUtils.ts, packages/engine-test-utils/src/__tests__/pods-core/v2/AirtableExportPodV2.spec.ts, packages/pods-core/src/builtin/AirtablePod.ts
```
enhance(pods): support null entries for dates in Airtable export v2
```
- General
- Operations
- Architecture …
=> enhance(pods): support null entries for dates in Airtable export v2

packages/dendron-cli/src/commands/pod.ts, packages/engine-server/src/topics/site.ts
fix(publish): better error messages when publishing
- don't throw podv2 warning when building a site
- don't dump engine state on bad vault warning
=> fix(publish): better error messages when publishing

packages/engine-server/src/markdown/remark/blockAnchors.ts, packages/engine-server/src/markdown/remark/dendronPub.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/blockAnchors.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/blockAnchors.spec.ts, packages/plugin-core/src/test/suite-integ/PreviewPanel.test.ts
Fixes an issue where the block anchors would show up in the preview.
#2531
Co-authored-by: tma66 <tma66@users.noreply.github.com>
- Same number
- General
- Operations
- Architecture
- [~] can we track the performance of …
=> fix: block anchors showing up in the preview

packages/dendron-cli/src/commands/devCLICommand.ts, packages/engine-server/src/migrations/utils.ts, packages/plugin-core/src/_extension.ts
chore(analytics): don't publish config data when reporting migration status
currently, we publish config data on migration status which is resulting in thousands of columns
=> chore(analytics): don't publish config data when reporting migration status

packages/engine-server/src/markdown/remark/noteRefsV2.ts
This change improves perf / reduces mem usage whenever a reference is being rendered. This includes hover preview, which uses the note reference rendering implementation.
The issue is with `proc()`, which is a copy constructor - this is actually an expensive call when you have a lot of notes in your workspace, because it does a deep copy of `proc.data` - in our case, this includes the entirety of `DEngineClient`, that is, all notes, schemas, vaults, etc.  We should make it a principle to not use `proc()` when we're in full mode and have `DEngineClient` in the data payload.
For org-private, this reduces hover preview time and reference preview rendering down from 500-1200ms range to < 50 ms.  From some profiling, the memory impact is not as significant as I expected (probably due to string …
=> fix(basics): improve perf around reference rendering including hover

packages/plugin-core/src/commands/Sync.ts
This PR adds telemetry to detect if there are any repositories in the workspace that have multiple vaults in them during the workspace sync command. This will let us know how many users would be affected if we required repositories to contain only a single vault.
Docs: https://github.com/dendronhq/dendron-site/pull/436
- General
- Operations
- Architecture
- Linked above
- eg: [see …
=> chore: telemetry to find if there are repositories with multiple vaults

packages/plugin-core/src/WorkspaceWatcher.ts
One of the top Sentry hitters right now is in `onWillSaveNote`, "Cannot read property 'updated' of undefined".
This happens when we can't find a particular note in the engine when it's being saved.  I think this is caused by a race condition between the vscode `onWillSaveNote` callback and our filewatcher logic of adding the note to the engine for the cases of a user adding a new note outside of the Lookup command.
We should just avoid modifying the `updated` property if we can't find it - according to VSCode's API docs, if your  `onWillSaveNote` logic crashes 3 times, it will no longer get invoked.
---
- eg: [if configuration for utilities are …
=> fix(workspace): fix crash in updated fm field logic on doc save

packages/nextjs-template/utils/build.ts
Related issue: https://github.com/dendronhq/dendron/issues/2549
The `dendron publish dev` command exports the header file from path specified in `customHeaderPath`(relative to workspace) to `.next/public` as `header.html`. This PR updates nextjs-template to retrieve header file from the same path.
- General
- Operations
- Architecture …
=> fix(publish): customHeaderPath breaks publishing if value is set to anything except header.html

packages/common-all/src/constants/index.ts, packages/common-server/src/git.ts, packages/engine-server/src/backup/backupServiceInterface.ts, packages/engine-server/src/backup/index.ts, packages/engine-server/src/backup/service.ts, packages/engine-server/src/config.ts, packages/engine-server/src/index.ts, packages/engine-server/src/migrations/migrations.ts, packages/engine-test-utils/src/__tests__/engine-server/backup.spec.ts, packages/plugin-core/package.json, packages/plugin-core/src/commands/OpenBackupCommand.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/OpenBackupCommand.test.ts, packages/plugin-core/src/test/suite-integ/migration.test.ts, test-workspace/.gitignore, test-workspace/dendron.yml
This PR:
- implements `BackupService` which can be generally used for various parts of Dendron where we need to back up a file.
- backup root is created when if it doesn't exist, and added to gitignore
- one directory for each key defined in `BackupKeyEnum` is created in the backup root, and holds all backups that were done under that key.
- provides a generic way of creating backup file names, with an option to add timestamp and / or a custom infix right before the file extension.
- implements `OpenBackupCommand` which can be used to open individual backup files grouped by keys stored in the backup root directory.
- fixes an issue wigh `GitUtils.addToGitignore`, where dotfile/dotdirs were not checked for existence properly because the regular expression was not escaped and was using the …
=> enhance: provide a standard way to create and read backup files

packages/engine-server/src/workspace/utils.ts, packages/engine-test-utils/src/utils/git.ts, packages/plugin-core/src/commands/AddAndCommit.ts, packages/plugin-core/src/commands/Sync.ts, packages/plugin-core/src/test/suite-integ/AddAndCommitCommand.test.ts, packages/plugin-core/src/test/suite-integ/SyncCommand.test.ts, packages/plugin-core/src/test/testUtilsV3.ts
```
fix(sync): Better error message on Workspace Add and Commit
```
This PR aims to solve the issue linked below. It also improves error messages when there is an in-progress rebase, merge conflicts or no new changes.
Related issue: https://github.com/dendronhq/dendron/issues/1297
- General
- Operations
- Architecture
- [~] if you …
=> fix(sync): Better error message on Workspace Add and Commit

packages/common-all/src/util/orderedMatchter.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
Related Issue: https://github.com/dendronhq/dendron/issues/1654
This PR aims to solve the above-mentioned issue. It allows lookup to be case insensitive.  For a vault with below files, when user lookup for foo.CH1, the result should contain `foo.ch1.md` 
- foo.ch1.md
- bar.ch1.md
- root.md
- General
- Operations
- Architecture
- [~] check if code is introducing changes on a foundational class or interface. if …
=> fix(lookup): lookup should be case-insensitive

packages/plugin-core/src/services/TextDocumentService.ts, packages/plugin-core/src/test/suite-integ/TextDocumentService.test.ts, packages/plugin-core/src/test/testUtilsV3.ts
*Bug*
The `this` in `onDidSave` was undefined while the callback was called via the vscode save events. Was accidentally removed from latest previewpanel refactor.
Tested manually and with `ExportPodV2`
- General
- Operations
- Architecture
- CSS
=> fix(workspace): issue with notes not being saved on export

packages/plugin-core/src/test/suite-integ/WindowDecorations.test.ts
Uses new `describeWS` format for window decorator tests. This also fixes windows issues with all of the decorator tests except one involving schemas which still skips on windows
=> chore: refactor window decorator tests

packages/engine-server/src/metadata/service.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/services/stateService.ts, packages/plugin-core/src/survey.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts
This PR:
- Removes the use of state service when storing prompt status of inactive user survey.
- Use metadata service instead
- Re-enables inactive user survey prompt during activation.
- Change re-prompt cadence to 4 weeks from 2 weeks.
- Ignores a rare case where first install time is later than first lookup time
- this has caused issues in around 4% of the observed prompted users
- Handle case for recently-prompted users that have `inactiveUserMsgSendTime` set, but does not yet have the new metadata `inactiveUserMsgStatus` set.
- In a similar case, where we introduced the global state and didn't backfill the in-between cases, 12% of the total observed prompted users were prompted prematurely.
- eg: [if configuration for utilities are already in one module or package, add future …
=> fix: Re-enable inactive user survey and store prompt status in filesystem for prompt reliability.

.github/workflows/publish-extension-dendron-minor.yml, .github/workflows/publish-extension-dendron-patch.yml
Creates a pipeline for publishing Dendron as a patch release, meant for 'emergency' or bug-fixing type releases. This also renames the existing publish Dendron pipeline to `publish-extension-dendron-minor` to avoid pipeline confusion.
=> chore: add pipeline for pub dendron patch

packages/plugin-core/src/dendronExtensionInterface.ts, packages/plugin-core/src/test/suite-integ/WindowWatcher.test.ts, packages/plugin-core/src/test/suite-integ/WorkspaceWatcher.test.ts, packages/plugin-core/src/workspace.ts
Simple change to remove window watcher <-> IDendronExtension circular dependencies.  There's no real usage of the window watcher property on the interface, so it was safe to remove.  
-3 circular dependencies:
```log
1) src/dendronExtensionInterface.ts > src/WorkspaceWatcher.ts
2) src/dendronExtensionInterface.ts > src/WorkspaceWatcher.ts > src/windowWatcher.ts
3) src/ExtensionProvider.ts > src/dendronExtensionInterface.ts > src/WorkspaceWatcher.ts > src/windowWatcher.ts > src/features/windowDecorations.ts
```
--- …
=> chore: fix window watcher circular dependencies

packages/common-all/src/analytics.ts, packages/plugin-core/package.json, packages/plugin-core/src/KeybindingUtils.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/CopyToClipboardCommand.ts, packages/plugin-core/src/commands/Doctor.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/test/suite-integ/Keybinding.test.ts, packages/plugin-core/src/test/testUtilsV3.ts, packages/plugin-core/src/vsCodeUtils.ts
This PR:
- Removes automatic keybinding conflict resolution in favor of manual resolution.
- The main goal of this PR is to give back user agency while also providing a streamlined way of manually resolving conflicts.
- adds doctor command `fixKeybindingConflicts`
- detects known extensions that have keybinding conflicts
- provide detailed instructions on how to resolve them
- removes automatic keybinding conflict resolution that happens during extension activation
- `dendron.copyToClipboard`
- This is a command that is added to provide a way to copy arbitrary text to system clipboard within a webview.
- This command is not accessible from any user-facing VSCode UI. (`when` clause is `false`)
- `KNOWN_KEYBINDING_CONFLICTS`
- This holds all the mappings between a known pair of conflicting …
=> feat: add doctor command for a more reliable keybinding resolution

packages/api-server/src/Server.ts, packages/api-server/src/modules/notes/index.ts, packages/common-all/src/analytics.ts, packages/common-server/src/analytics.ts, packages/common-server/src/errorReporting.ts, packages/dendron-cli/src/utils/analytics.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/logger.ts, packages/plugin-core/src/utils/analytics.ts
chore(analytics): add release and session to sentry
- this adds `sessionId` as a tag in sentry 
- this also adds `release` to sentry so we can start tracking [release health](https://docs.sentry.io/product/releases/health/)
- cleanup
- converts app targets like "vscode" and "cli" into an enum
- since we bumped the min version, updated the following
- remove check for old version of vscode when checking for workspace trust
- remove `VSCodeEvents.UserOnOldVSCodeVerUnblocked` event 
- remove commented code
Next Items
***
- General
- Operations
- Architecture …
=> chore(analytics): add release and session to sentry

packages/engine-server/src/markdown/remark/backlinks.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/backlinks.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/backlinks.spec.ts
If a backlink is invalid (with respect to the engine state), then preview gets stuck on a "Loading..." screen because the engine returns 500 for the render call. 
In the repro in org-workspace on `tags.scope.basic`, this was caused by a note with a duplicate ID containing a link to the `tags.scope.basic` note. 
Change co-authored by @SeriousBug
--- 
- [N/A] circular dependency check: make sure your code is not introducing new circular dependencies in plugin-core.  See [Avoiding Circular Dependencies](dev.process.code.best-practices). …
=> fix(views): unblock preview rendering when backlink is invalid

packages/common-all/src/analytics.ts, packages/common-server/src/filesv2.ts, packages/engine-test-utils/src/__tests__/common-server/filev2.spec.ts, packages/plugin-core/src/WelcomeUtils.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/utils/analytics.ts, packages/plugin-core/src/workspace/workspaceActivater.ts
enhance(basics): getting started tutorial updates
- if default folder for Dendron already exist, generate new folder with an incrementing suffix to avoid overriding original folder
- add telemetry event `ClickStart` to track if getting started gets clicked
This also refactors some of the workspace activation logic into a separate file
***
- General
- Operations
- Architecture …
=> enhance(basics): getting started tutorial updates

packages/common-server/src/filesv2.ts, packages/plugin-core/src/_extension.ts
fix(workspace): race condition when loading native workspace
To load up a workspace, we call the `reloadWorkspace` function which calls Dendron's `reloadIndex` function.
`reloadIndex` is registered after `reloadWorkspace`. If initialization of workspace finishes too quickly, Dendron will try to call `reloadIndex` before it is registered.
Fixed by registering `reloadIndex` ahead of calling `reloadWorkspace`
Also fix an issue where `getCodeWorkspaceSettingsSync` would be called in native workspaces
=> fix(workspace): race condition when loading native workspace

packages/dendron-cli/src/commands/doctor.ts, packages/dendron-cli/src/commands/exportPodV2.ts, packages/engine-server/src/doctor/service.ts, packages/engine-test-utils/src/__tests__/pods-core/v2/AirtableExportPodV2.spec.ts, packages/plugin-core/src/commands/Doctor.ts, packages/plugin-core/src/commands/pods/AirtableExportPodCommand.ts, packages/plugin-core/src/components/pods/PodControls.ts, packages/plugin-core/src/test/suite-integ/DoctorCommand.test.ts, packages/plugin-core/src/test/suite-integ/components/pods/AirtableExportPodCommand.test.ts, packages/pods-core/src/builtin/AirtablePod.ts, packages/pods-core/src/v2/podConfig/AirtablePodConfig.ts, packages/pods-core/src/v2/pods/export/AirtableExportPodV2.ts
```
enhance(pods): support exporting a note to multiple Airtable destination
enhance(workspace):  Doctor command 'fixAirtableMetadata' to convert airtableId from single scalar value to a hashmap
```
This PR aims to support multiple Airtable Ids in note frontmatter on Airtable export v2 by storing airtable ids in a hashmap
[Airtable Docs](https://github.com/dendronhq/dendron-site/pull/447)
- General
- [~] check if similar function already exist in the codebase. if so, can …
=> enhance(pods): support exporting a note to multiple Airtable destination

packages/plugin-core/src/commands/OpenBackupCommand.ts, packages/plugin-core/src/commands/RunMigrationCommand.ts, packages/plugin-core/src/test/suite-integ/RunMigrationCommand.test.ts
This PR:
- Fixes an error that happens during `_setupCommands` with `OpenBackupCommand` by defering backup service initialization to execute-time
- Fixes an error which causes `Run Migration` command to crash if user is in a native workspace.
- Correctly handles the case when workspace settings do not exist.
- Adds test to verify `Run Migration` works in native workspaces
- Removes the use of legacy testing harness in `RunMigrationCommand.test.ts`
=> fix: Prevent fatal errors in Open Backup Command and Run Migration Command in native workspaces

packages/plugin-core/src/components/lookup/LookupControllerV3.ts, packages/plugin-core/src/components/lookup/LookupProviderV3.ts
Sometimes key strokes get dropped on both the start of your query string as well as the end if you type quickly. 
This change largely fixes that with some 80/20 changes - there are still some cases where it seems like some keystrokes may still get dropped, but from my testing it's quite rare now. There are still underlying optimizations that can be made with the engine interactions via the lookup provider, but those are a little more involved and can be deferred for later.
---
- eg: [if configuration for utilities are already in one module or package, add future utilities there as well](https://github.com/dendronhq/dendron/pull/1960#discussion_r78622 …
=> fix(workspace): fix dropped keystrokes issue in lookup

packages/engine-server/src/doctor/service.ts, packages/plugin-core/src/commands/Doctor.ts
enhance(common): don't reload workspace when running doctor airtable command
Doctor doesn't need to reload the workspace when fixing airtable ids. This makes sure that it doesn't. 
Also fixes a race condition from not awaiting the output of `engine.write`
***
This introduces a new recipe: [[Adding a new doctor command|dendron://dendron.docs/pkg.plugin-core.dev.cook#adding-a-new-doctor-command]]
***
- General
- Opexations
- Arcxitecture
NA
- [~] [Write …
=> enhance(common): don't reload workspace when running doctor airtable command

packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/components/lookup/LookupProviderV3.ts, packages/plugin-core/src/components/lookup/LookupProviderV3Interface.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
fix(lookup): autocomplete causes notes to be created in wrong vault 
NoteLookupAutocomplete pre-emptively cancelling updatePicker results
***
- General
- Operations
- Architecture
- eg: [see usage for export pod](https://github.com/dendronhq/dendron/pull/2190#pullrequestrev …
=> fix(lookup): autocomplete causes notes to be created in wrong vault 

.github/workflows/ci.yml, packages/common-all/src/api.ts, packages/common-frontend/src/features/engine/hooks.ts, packages/common-frontend/src/features/engine/slice.ts, packages/common-frontend/src/types.ts, packages/common-server/src/etc.ts, packages/dendron-next-server/lib/env.ts, packages/dendron-next-server/lib/types.ts, packages/dendron-next-server/pages/_app.tsx, packages/dendron-next-server/pages/vscode/mini-preview.tsx, packages/dendron-next-server/pages/vscode/note-preview.tsx, packages/dendron-plugin-views/src/hooks/index.tsx, packages/dendron-plugin-views/src/types/index.ts, packages/engine-test-utils/src/__tests__/common-frontend/features/engine/slice.spec.tsx, packages/plugin-core/src/components/views/PreviewPanel.ts, packages/plugin-core/src/views/DendronTreeViewV2.ts, packages/plugin-core/src/views/LookupView.ts, packages/plugin-core/src/views/utils.ts
Instead of passing a port into the preview and having it generate a localhost URL, we instead generate a URL with the VSCode API and pass the generated URL in. This way VSCode can set up port forwarding in remote workspaces. For local workspaces, the API is a no-op and we just get a local connection.
#2606
Co-authored-by: jonathanyeung <jonathanyeung@users.noreply.github.com>
- Not affected
- General
- No, the API is a no-op for local workspaces, and port forwarding is required for remote workspaces.
- Operations
- Architecture
- [~] check if code is introducing changes on a foundational class or interface. if …
=> fix(views): Pass in a port-forwarded URL to preview for remote workspaces

packages/plugin-core/src/test/suite-integ/RunMigrationCommand.test.ts, packages/plugin-core/src/test/testUtilsV3.ts
This PR:
- Correctly name test for native workspace case
- disable native workspace test case for `RunMigrationCommand` in windows
- General
- Operations
- Architecture
- eg: [see usage for export pod](https://github.com/dendronhq/dendron/pull/2190#pullrequestreview-8557156 …
=> chore: fix RunMigrationCommand test

packages/common-server/src/analytics.ts, packages/plugin-core/src/survey.ts, packages/plugin-core/src/utils/analytics.ts
This PR:
- Adds an identify call when the background survey is answered. This allows us to have the user role as an identified user trait.
- Modifies `AnalyticUtils.identify` to optionally accept a partial `VSCodeIdentifyProps`
- General
- Operations
- Architecture
- eg: [see usage for export pod](https://github.com/dendronhq/dendron/pull/2190#pullreques …
=> chore: identify users with role when background survey is answered

packages/dendron-next-server/hooks/useGraphElements.tsx, packages/dendron-next-server/pages/_app.tsx, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/components/views/NoteGraphViewFactory.ts
This PR aims to hook Graph View with Engine Events. It also fixes rendering issues on ShowNoteGraph.
- General
- Operations
- Architecture
- CSS
- eg: [breaking dev change due to new dependency](https://github.com/dendronhq/dendron/pull/2188#pullrequestreview-855696330)
=> chore(internal): ShowNoteGraph to use engine events

packages/common-test-utils/src/presets/notes.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/CopyNoteLink.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/test/suite-integ/CopyNoteLink.test.ts, packages/plugin-core/src/test/testUtilsV3.ts
**Bug**
If user updates note title without saving and runs CopyNoteLink command, it grabs the previous note title. This is because the engine note has not been updated
**Changes**
1. Save document if dirty before executing rest of command
2. Subscribe to engine on`onEngineNoteStateChanged` to make sure execution happens after engine is updated
3. Dispose after command is executed
4. Refactored `CopyNoteLink.test.ts` to use latest test suites
5. Expanded test util to allow creation of preset notes after engine is running in test harness
- General
- Operations
- Architecture …
=> fix(copynotelink): Allow user to run copyNoteLink without needing to save first

packages/common-server/src/analytics.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/utils/analytics.ts
- Adds the number of notes in a workspace to `identify`
- Adds Dendron Version on each event to make SQL querying easier.
---
- General
- Operations
- Architecture
I'll update airtable after merge.
- CSS …
=> chore: adding numNotes to identify + add dendron version per event

packages/plugin-core/src/commands/MoveNoteCommand.ts
Adds analytics on how many notes have been moved with a "Move Note" command. If the user cancels the prompt, that is also tracked as 0 notes being moved.
=> chore: add analytics for how many notes have been moved

packages/plugin-core/src/features/BacklinksTreeDataProvider.ts, packages/plugin-core/src/views/EngineNoteProvider.ts
There's code execution done by vs code in the native tree view that wasn't covered by Sentry - this change fixes that and also adds reporting for the backlinks view as well.
This should point us at the issue behind the following:
- https://github.com/dendronhq/dendron/issues/2534
- https://github.com/dendronhq/dendron/issues/2451
---
- General
- [N/A] check if this change adversely impact performance
- Operations
- [N/A] when shipping this change, will it just work or …
=> chore(views): report exceptions for treeview

packages/common-all/src/analytics.ts, packages/common-server/src/analytics.ts, packages/engine-server/src/metadata/service.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/DevTriggerCommand.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/survey.ts, packages/plugin-core/src/test/suite-integ/Survey.test.ts, packages/plugin-core/src/workspace/tutorialInitializer.ts
This PR:
- Adds `siteUrl` as part of `InitializeWorkspace` event if present.
- Adds Initial survey question asking the context of Dendron use.
- Adds all initial survey answers as part of user trait
- Refactors initial survey prompt logic to use metadata service instead of state service
- Prior state written to state service will be backfilled.
- General
- Operations
- Architecture
- [pending] if you are adding analytics related changes, make sure you …
=> chore: update survey and various user properties for better analytics

hooks/pre-push.js
Adds a pre push hook to check that the circular dependency count in plugin-core is <= 2; push will fail otherwise.  This will absolve our need to run the madge checks manually.
Update made to dendron-docs: https://github.com/dendronhq/dendron-docs/commit/51d5f6679bee2edc0a442d64191380edf8cbda2a
---
=> Chore: pre push hook for circular dependencies

packages/engine-server/src/workspace/utils.ts, packages/plugin-core/src/commands/VaultAddCommand.ts, packages/plugin-core/src/test/suite-integ/VaultAddCommand.test.ts, packages/plugin-core/src/test/testUtilsv2.ts
Fixes an error that happens when adding a self contained vault to a native workspace.
- General
- Operations
- Architecture …
=> fix: error when adding a self contained vault inside a native workspace

bootstrap/scripts/fastRebuild.sh
chore: fast rebuild script when building dendron plugin locally
This adds the steps in [[Build|dendron://dendron.docs/pkg.plugin-core.dev.build]] into a script
=> chore: fast rebuild script when building dendron plugin locally

packages/nextjs-template/components/DendronTreeMenu.tsx, packages/nextjs-template/styles/scss/main.scss, packages/nextjs-template/utils/hooks.ts
Uses a link instead of a clickable item on the side bar, making it possible to right click on them, and open them in a new tab.
For the links, I matched the style of the old clickable text areas, except for the underline when hovered. I left that in but I'm not sure either way, so let me know if you, the reviewer, would prefer it removed.
On Firefox, right clicking an item:
On Firefox, hovering over an item:
On Chrome, hovering over an item:
#2615 
- General
- Operations
- Architecture
- eg: [see usage …
=> enhance: use a link instead of a clickable item for the tree view menu

packages/common-frontend/src/features/engine/slice.ts, packages/dendron-plugin-views/src/components/DendronNotePage.tsx, packages/dendron-plugin-views/src/hooks/index.tsx, packages/engine-server/src/enginev2.ts
Discovered this error path in the Sentry logs: if rendering a note fails, Dendron throws an error which would end up in Sentry. With this PR:
- Any errors thrown during rendering a note is caught
- If there is an error, the note preview will display the error (see below for how this looks)
- The error state in the preview is cleared once a preview action succeeds. Otherwise the preview would be stuck displaying the error.
- General
- Operations
- Architecture
- [~] if you are adding analytics related …
=> chore(view): note preview catches and displays error messages

package.json
chore: add jest as workspace dep
Jest is required to build dendron
=> chore: add jest as workspace dep

packages/dendron-next-server/package.json, packages/nextjs-template/package.json, packages/plugin-core/package.json, yarn.lock
- DEPENDENCY_UPDATE: @dendronhq/plugin-core updated textextensions from 5.14.0 to 5.15.0
This change includes my contribution adding `XAML` as a text extension to the list, which will allow the Dendron preview to open XAML files when a linked to one is clicked in the preview.
The upgrade command also pulled in minor version upgrades to `nextjs`, but I left them in since they should be harmless.
#1695
=> fix: upgrade `textextensions` version so links to `XAML` files in preview open in editor

packages/common-all/src/analytics.ts, packages/common-all/src/vault.ts, packages/engine-server/src/topics/git.ts, packages/engine-server/src/workspace/service.ts, packages/plugin-core/src/_extension.ts
This telemetry is needed to measure the success of the self contained vaults project.
- General
- The telemetry runs async while Dendron initialization is happening, and is only done during initialization.
- Operations
- Architecture
- CSS
=> chore: telemetry for number of remote vaults & repo contributor count

packages/plugin-core/src/commands/CreateJournalNoteCommand.ts, packages/plugin-core/src/commands/CreateScratchNoteCommand.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/components/lookup/LookupControllerV3.ts, packages/plugin-core/src/components/lookup/LookupControllerV3Factory.ts, packages/plugin-core/src/components/lookup/LookupControllerV3Interface.ts, packages/plugin-core/src/test/suite-integ/components/lookup/LookupControllerV3.test.ts
Fixing the issue introduced with the lookup refactoring where a handful of views that required lookup wouldn't work because of a "webview with this name has already been registered" error from vscode.
There are two parts to this problem- this review only addresses one of them, but it should be sufficient to resolve this issue.  They are:
1. We weren't properly disabling lookup Panel view via the LookupV3Controller factory options for all views that didn't want the panel (which right now is all lookup instances besides the "main" lookup . Thus, a `LookupPanelView` would still get constructed, which would in turn do the vscode webview registration. I've flipped the opt from being a 'disablePanelView' to 'enablePanelView', and made the default `false` instead of true. This code change …
=> fix(workspace): webview already registered problem with lookup panel

CHANGELOG.md, README.md, packages/common-all/data/dendron-yml.validator.json, packages/common-all/src/types/workspace.ts, packages/common-server/src/git.ts, packages/dendron-next-server/data/dendron-yml.validator.json, packages/engine-server/CHANGELOG.md, packages/engine-server/src/config.ts, packages/engine-server/src/topics/site.ts, packages/engine-test-utils/CHANGELOG.md, packages/engine-test-utils/src/__tests__/common-server/git.spec.ts, packages/engine-test-utils/src/__tests__/site.spec.ts, packages/nextjs-template/components/DendronNoteFooter.tsx, packages/plugin-core/CHANGELOG.md, packages/plugin-core/README.md, packages/plugin-core/src/test/suite-integ/RefactorHierarchy.test.ts, templates/dendron.md.j2
This only changes the typo of `Hiearchy` to `Hierarchy` and `hiearchy` to `hierarchy`
More typos: "shoud" -> "should"
=> fix: typo "hierarchy", "should"

packages/dendron-cli/src/commands/devCLICommand.ts
chore: add sleep for building plugin locally
sometimes npm assets aren't ready locally immediately after publishing
=> chore: add sleep for building plugin locally

packages/plugin-core/webpack.common.js
Fixing a regression from https://github.com/dendronhq/dendron/pull/2563 where we changed release names in Sentry to have to flavors, @vscode prefixed and @express prefixed. 
Symbols are not properly being associated with the releases anymore.  This change does a dual upload to add artifacts to the changed release names.
Testing: difficult to test locally - we can test via nightly builds.
=> chore: fixing release names for sentry source map uploads

packages/common-all/src/analytics.ts, packages/common-server/package.json, packages/common-server/src/abTesting.ts, packages/common-server/src/analytics.ts, packages/common-server/src/index.ts, packages/engine-test-utils/src/__tests__/common-server/abTesting.spec.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/abTests.ts, packages/plugin-core/src/views/UpgradeView.ts, packages/plugin-core/src/views/utils.ts, yarn.lock
Adds an A/B testing framework to Dendron. To demonstrate this framework, also adds an A/B test for displaying a toast with a link to the changelog, versus displaying the changelog page in a webview.
Docs: https://github.com/dendronhq/dendron-docs/pull/25
The webview looks like this: 
Co-authored-by: jonathanyeung <jonathanyeung@users.noreply.github.com>
- General
- Operations
- Architecture
- CSS …
=> chore: ab testing framework

packages/plugin-core/src/WorkspaceWatcher.ts, packages/plugin-core/src/commands/pods/AirtableExportPodCommand.ts, packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/commands/pods/GoogleDocsExportPodCommand.ts, packages/plugin-core/src/commands/pods/JSONExportPodCommand.ts, packages/plugin-core/src/commands/pods/MarkdownExportPodCommand.ts, packages/plugin-core/src/commands/pods/NotionExportPodCommand.ts, packages/plugin-core/src/services/EngineAPIService.ts, packages/plugin-core/src/services/EngineAPIServiceInterface.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts, packages/plugin-core/src/test/suite-integ/TextDocumentService.test.ts, packages/plugin-core/src/test/suite-integ/components/pods/BaseExportPodCommand.test.ts, packages/plugin-core/src/test/suite-integ/components/pods/TestExportCommand.ts, packages/plugin-core/src/test/testUtilsV3.ts
**Background**
Similar to https://github.com/dendronhq/dendron/pull/2631, this PR fixes the issue where user needs to save first before exporting to airtable.
**Changes**
1. Before exporting, we will first save the current document if it is dirty. After the save, listen to the engine for an `onEngineNoteStateChanged` event before continuing the command.
2. Expose EngineEmitter as part of EngineAPIService. This makes it easier to listen to events since the extension is readily available
3. Remove updating the engine as part of `onWillSaveNote`. 
- The TextDocument entering onDidSave for the TextDocumentService contains the proper updated timestamp
- `note.updated = now` actually updates the engine note for us so we can leave this in in case there's a bug that causes  onDidSave to never be …
=> fix(airtable): Exporting to airtable automatically saves current document

packages/nextjs-template/package.json, yarn.lock
fix(publish): add luxon as dev dependency
Required for clean build of nextjs-template
=> fix(publish): add luxon as dev dependency

packages/plugin-core/src/commands/ShowNoteGraph.ts, packages/plugin-core/src/components/views/NoteGraphViewFactory.ts
This PR aims to add telemetry for graph view. It adds the following properties for the existing event `dendron.showNoteGraph`. 
1. A new property `message`  to measure the % of users that uses Graph View to navigate their workspace.
2. A new property `timeOpen` is added to measure the duration for which Graph View was used.
- General
- Operations
- Architecture
- …
=> chore(internal): add telemetry for note graph view usage

packages/plugin-core/src/_extension.ts, packages/plugin-core/src/abTests.ts, packages/plugin-core/src/views/UpgradeView.ts
I removed the test, but kept the view in with the issues documented in case we decide to go back to it at some point.
For the upgrade toast, I introduced a test that tests out 3 different wordings:
- See what changed (existing)
- See what's new
- Open the changelog
=> chore: remove upgrade view A/B test, add upgrade toast button wording test

packages/common-all/src/analytics.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts
This PR:
- fixes an issue where an install event on a fresh vscode instance is recorded as an "initial install" globally.
- this may have caused problems with prompt logic that rely on the integrity of the metadata service.
- General
- Operations
- Architecture
- [~] If your tests changes an existing snapshot, …
=> fix: metadata service respects initial installs from new vscode instances for improved metadata accuracy

packages/common-all/src/types/compat.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/CopyNoteLink.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/test/suite-integ/BacklinksTreeDataProvider.test.ts, packages/plugin-core/src/test/suite-integ/CopyNoteLink.test.ts, packages/plugin-core/src/test/testUtilsV3.ts
**Changes**
1. One reason `CopyNoteLink` test keeps failing is that its trying to access the engine before its setup. Add requirement in class to need active workspace
2. Fixed bug in BackLinksDataProvider (with help from hikchoi) where linkCandidates wasn't respecting the same vault only requirement
3. Refactored BackLinksDataProvider test to newest test harness
4. Add `await` to setupCommands. Noticed some tests ran into "this command is already registered command". I believe its caused by running `setupCommands` twice w/o waiting for the first to finish.
- General
- Operations
- Architecture
- eg: [making …
=> chore(internal): Fix flaky CopyNoteLink and BacklinksTreeDataProvider test

packages/common-all/data/dendron-yml.validator.json, packages/common-all/src/constants/configs/workspace.ts, packages/common-all/src/dnode.ts, packages/common-all/src/types/configs/workspace/workspace.ts, packages/dendron-next-server/data/dendron-yml.validator.json, packages/engine-test-utils/src/__tests__/common-all/dnode.spec.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts, packages/plugin-core/src/test/suite-integ/migration.test.ts
Gives a new workspace config setting to allow users to utilize the full hierarchy to generate the note title upon note creation. For example,  a new note named `one.two.three` will generate a note title of `One Two Three` as opposed to just `Three`. 
Docs PR: https://github.com/dendronhq/dendron-site/pull/453
---
- General
- Operations
- Architecture
- eg: [see …
=> feat(workspace): option to gen title using full hierarchy

packages/engine-server/src/workspace/service.ts, packages/plugin-core/src/test/suite-integ/SyncCommand.test.ts
Self contained vaults previously would be considered workspace vaults during sync, and would follow the workspace vault settings. This PR fixes this so self contained vaults will follow the setting for regular vaults.
- General
- Operations
- Architecture
- CSS
=> fix: self contained vaults sync

packages/common-all/src/types/typesv2.ts, packages/dendron-plugin-views/src/components/DendronApp.tsx, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/ShowNoteGraph.ts, packages/plugin-core/src/components/views/NoteGraphViewFactory.ts
This Pr aims to 
- fix the regression of Graph migration to `dendron-plugin-views` which broke the application of graph's custom CSS.
- It also adds back Show Note Graph in `_extension.ts`.
- General
- Operations
- Architecture
- [~] check if code is introducing changes …
=> fix(view): support custom styles for Note Graph

packages/common-server/src/etc.ts, packages/dendron-plugin-views/src/components/DendronApp.tsx, packages/plugin-core/src/views/utils.ts
This is an attempt to quickly fix the issue: https://github.com/dendronhq/dendron/issues/2738.
More info about the class `vscode-reduce-motion` [here](https://code.visualstudio.com/api/extension-guides/webview#accessibility). 
- General
- Operations
- Architecture
- eg: [see usage for export pod](https://github.com/dendronhq/dendron/pull/2190#pullrequestreview-85571 …
=> fix(view): apply current theme when vscode reduce motion setting is on

packages/common-all/src/analytics.ts, packages/common-all/src/utils.ts, packages/common-server/src/analytics.ts, packages/dendron-cli/src/commands/launchEngineServer.ts, packages/engine-test-utils/src/__tests__/engine-server/EngineEvents.spec.ts, packages/engine-test-utils/src/engine.ts, packages/engine-test-utils/src/presets/engine-server/write.ts, packages/plugin-core/src/services/EngineAPIService.ts, packages/plugin-core/src/test/suite-integ/TextDocumentService.test.ts, packages/plugin-core/src/windowWatcher.ts, packages/plugin-core/src/workspace/tutorialInitializer.ts
Adds new metrics for new KPI's around user engagement:
- Note Update / Delete / Create based off of EngineEvents
- Note View - if a user opens up a new Dendron Note and keeps it as the active text editor for at least 5 seconds.  I did some testing to see how 5 seconds 'feels', and to me it feels like a reasonable grace period, but I'm open to tweaking this as well.  The goal is to reasonably capture the effect of someone looking at a note and getting some info out of it while also filtering out any instances of a user opening a note inadvertently or opening the note they weren't looking for.
I also did some cleanup on the watcher class to remove the legacy `registerActiveTextEditorChangedHandler` pattern.
---
- NOTE: the links don't work. you'll need to go into the wiki and use lookup to …
=> chore: new engagement metrics

packages/plugin-core/src/_extension.ts, packages/plugin-core/src/abTests.ts, packages/plugin-core/src/vsCodeUtils.ts
This PR adds an A/B test for self contained vaults, split 10% to 90%. For new users in the self contained vaults group, we'll set the default for new workspaces as self contained. Any new workspaces created by these users will be self contained vaults.
I did some manual testing, the "Get started" button will create a self contained vault.
=> enhance: starting general release of self contained vaults for some new users

packages/common-all/src/utils.ts, packages/common-server/src/git.ts, packages/engine-server/src/workspace/service.ts, packages/plugin-core/src/commands/VaultConvert.ts, packages/plugin-core/src/test/suite-integ/VaultConvert.test.ts
If self contained vaults are enabled in the workspace, "Vault Convert" will now move them to the right folder under `dependencies` based on their remote. This doesn't convert the vault into a self contained vault, just puts it in the correct folder.
The prompt when the folder is going to be moved:
- General
- Operations
- Architecture
- CSS
- eg. [breaking dev change due to new …
=> enhance(workspace): vault convert moves self contained vaults to the right location

packages/engine-server/src/markdown/remark/utils.ts, packages/engine-test-utils/src/__tests__/pods-core/MarkdownPod.spec.ts, packages/engine-test-utils/src/__tests__/pods-core/__snapshots__/MarkdownPod.spec.ts.snap, packages/engine-test-utils/src/__tests__/pods-core/v2/MarkdownExportPodV2.spec.ts, packages/pods-core/src/builtin/MarkdownPod.ts
fix(pods): export markdown links with `.md` extension
Prior to this fix we were not exporting markdown notes with the `.md` extension
***
- General
- Operations
- Architecture
NA
- [~] [Write Tests](https://wiki.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html) 
NA
NA
NA
NA
=> fix(pods): export markdown links with `.md` extension

packages/plugin-core/src/features/DefinitionProvider.ts, packages/plugin-core/src/test/suite-integ/DefinitionProvider.test.ts, test-workspace/vault/dendron.ref.links.md
This PR fixes Dendron opening asset files when hovering over them while holding `ctrl`.
This would cause asset links to text files (`[[/example.txt]]`) to open inside VSCode when hovered (rather than offering the file location), and binary files to launch the default app for them when hovered.
With this PR, `ctrl+hover` over a link to a text file will show the definition as expected, and for binary files it will do nothing (this is VSCode behavior, if VSCode adds support later it may display it as a definition).
=> fix(workspace): hovering an asset link while holding `ctrl` opens it

packages/common-frontend/src/features/engine/slice.ts, packages/dendron-plugin-views/src/components/DendronCalendarPanel.tsx, packages/engine-server/src/enginev2.ts
The issue was caused by the API stringifying properties passed to it. This meant selfContained: true would become selfContained: "true", and the engine would think that these are different vaults.
This issue was first discovered for the calendar view, but likely affected other views.
This fix solves the problem by parsing the stringified property. Also included are a few small refactors to use VaultUtils.isEqualV2.
This is the same as #2783, but there were a lot of conflicts when rebasing that PR so I opted to cherry pick it into a new PR.
=> fix(view): views don't update for new notes with self contained vaults

packages/plugin-core/src/commands/MoveHeader.ts, packages/plugin-core/src/test/suite-integ/LookupUtils.test.ts, packages/pods-core/src/builtin/GithubIssuePod.ts, packages/pods-core/src/builtin/NotionPod.ts
From an earlier debugging session, there was an issue caused by a `iterable.foreach(async () => {})` construct.  Because these issues are hard to detect, I went ahead and scrubbed through the code base for other instances and fixed them.
--- 
- General
- Operations
- Architecture …
=> chore: fixing all instances of foreach => asyncs

packages/common-frontend/src/features/engine/slice.ts, packages/common-frontend/src/types.ts, packages/dendron-plugin-views/src/hooks/useGraphElements.tsx
This change makes an optimization in the calculation of nodes/edges from engine state in the graph view.  The cause of slowdown is that we were still using `getNoteByFnameV5`.  Switching to use the dictionary based `getNoteByFnameFromEngine` isn't straightforward though, as the engine isn't available in the webviews (at least, it's not a `DEngineClient`) - furthermore, the `NoteFNameDict` class can't be serialized and consequently cannot be sent over the API, so I opted to reconstruct the FName Dict in the engine slice, which seems fast enough.
Results - for org-workspace, which is currently at ~ 
- 24000 nodes
- 24322 hierarchical edges
- 53250 link edges
The computation time is down from ~5 minutes to less than 1 second.  Cytoscape will still take about 10 additional seconds to do its …
=> fix(views): optimize graph view graph calculation speed

packages/engine-server/src/markdown/utils.ts, packages/plugin-core/src/WSUtils.ts, packages/plugin-core/src/WSUtilsV2.ts, packages/plugin-core/src/clientUtils.ts, packages/plugin-core/src/commands/ConvertLink.ts, packages/plugin-core/src/commands/DeleteNodeCommand.ts, packages/plugin-core/src/commands/Doctor.ts, packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/features/RenameProvider.ts, packages/plugin-core/src/features/completionProvider.ts, packages/pods-core/src/basev3.ts, packages/pods-core/src/builtin/GDocPod.ts, packages/pods-core/src/builtin/GithubIssuePod.ts, packages/pods-core/src/builtin/OrbitPod.ts
Encountered another perf issue with Note Graph view around usage of `getNoteByFnameV5`, so I decided to do another scrub and remove more instances.  This change may result in some perf benefits across Dendron.
Remaining references:
- tests
- a few tricky ones within `storev2`, where we don't have an engine ref and hence can't use the new function.
---
- General
- Operations
- Architecture
- CSS
- …
=> chore: removing more instances of getNoteByFnameV5

packages/common-all/src/analytics.ts, packages/common-all/src/utils.ts, packages/common-server/src/filesv2.ts, packages/engine-server/src/doctor/service.ts, packages/plugin-core/src/commands/ReloadIndex.ts, packages/plugin-core/src/test/suite-integ/ReloadIndex.test.ts, packages/plugin-core/src/utils/StartupUtils.ts
If the user has a self contained vault that was incorrectly configured as a self contained vault, then this PR will detect that issue and offer to fix it with a prompt. This PR also adds the doctor action that will fix the misconfigured vault.
I also disabled the "create missing root note/schema" automatic fix for when it's a misconfigured self contained vault, as otherwise it would create a root note in the wrong folder. That means the initialization fails, but Dendron will unbreak itself once the user fixes the config or accepts out prompt.
=> enhance: detect misconfigured self contained vaults and offer to fix them

packages/plugin-core/src/test/suite-integ/VaultRemoveCommand.test.ts
- This PR refactors the tests in the `VaultRemoveCommand.test.ts` to use the new harness.
- This PR also adds tests for self contained vaults being removed with VaultRemoveCommand.
=> chore: add tests for vault remove with self contained vaults

packages/plugin-core/src/abTests.ts
This PR re-adds the self contained vaults AB test, split 90/10.
=> chore: self contained vaults rollout AB test

packages/dendron-plugin-views/src/components/DendronApp.tsx, packages/dendron-plugin-views/src/index.tsx
fix(views): add margin back into note preview
bundling changes made the 33px margin dissapear on preview. this adds it back in and consolidates setting the margin in `index.ts` 
manual test across all webviews to make sure that margin looks good
=> fix(views): add margin back into note preview

packages/common-server/src/filesv2.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/enginev2.ts, packages/engine-test-utils/src/presets/engine-server/rename.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/test/suite-integ/MoveNoteCommand.test.ts, packages/plugin-core/src/test/suite-integ/NativeTreeView.test.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts, packages/plugin-core/src/test/suite-integ/RefactorHierarchy.test.ts, packages/plugin-core/src/test/suite-integ/RenameProvider.test.ts
- This PR does a second pass of fixing engine / treeview state mismatch issues.
- Case: renaming a note into an already existing stub note
- Doing this used to leave the + mark in the tree view because the parent / children were not properly updated
- This used to leave `stub: true` in the renamed note's frontmatter, which caused a lot of problems
- The resulted renamed note would appear in lookup twice. one would be a stub and one wouldn't.
- depending on the accepted item, there was a possibility of losing the entire body of the note.
- Now all notes will lose their `stub: true` property once they are persisted in the store.
- this, however, doesn't _disallow_ the user from adding the property themselves.
- a separate PR will be submitted for a doctor command that scrubs existing …
=> fix: second pass of treeview v1 sync issue

.github/workflows/ci-windows-test.yml, .github/workflows/ci.yml
=> chore: bumping Node to v14+16 in ci

packages/plugin-core/src/_extension.ts
This PR:
- fixes a regression introduced in the initialization logic where previous global and workspace version was not properly handled
- With the recent clean-up of the initialization logic the following changes were omitted
- previousGlobalVersion from state service was not getting backfilled to the corresponding metadata, and was not read from metadata for subsequent use
- previousWorkspaceVersion from state service was not getting backfilled to the corresponding workspace metadata, and was not read from workspace metadata for subsequent use
- This resulted in an `InstallStatus.UPGRADED` for every initialization
NOTE: to manually test that this fixes the issue, you may need to reload once after dendron is initialized since that we need the first pass of initialization for the …
=> fix: correctly handle previous global and workspace version

packages/plugin-core/src/components/lookup/LookupControllerV3.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
#2854
- General
- Operations
- Architecture
- CSS
=> fix: Lookup creates a bad wikilink if `selection2link` is enabled and the selection is multiline

packages/common-all/src/dnode.ts, packages/plugin-core/src/test/suite-integ/InsertNoteIndexCommand.test.ts
- When insert note index command runs it collects the active note's child notes. 
- These notes will be checked with the condition which was modified. 
- The condition checked if the note's name startsWith "tags". 
- If it was true, the next line splits the note's name at "tags." and returns the 1st element (without checking the result of the split).
Related to: https://github.com/dendronhq/dendron/issues/2314
=> fix: insert note index `#undefined` in case missing tags

packages/plugin-core/src/test/suite-integ/NativeTreeView.test.ts
This PR:
- Adds a suite of tests in an attempt to find issues with the tree view given some delete operations.
- This PR is test only (does not fix any issues)
- Fortunately, after the two passes of engine fixes, typical cases of delete operations are not breaking the tree view.
- General
- Operations
- Architecture
- [~] can we track the performance of …
=> chore: add blackbox testing for tree view (delete interaction)

packages/common-all/src/types/configs/workspace/task.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/plugin-core/src/commands/CreateTask.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts, packages/plugin-core/src/test/suite-integ/components/lookup/LookupControllerV3.test.ts
This PR sets the `Create Task Note` command's default configuration so that tasks will look like `task.2022.04.29.task-name`.
This format is what we've been using and it has worked well for us. We also had some feedback from a community member that this setup makes more sense.
This change will only affect new workspaces, as existing users might be already creating tasks with their existing config and we wouldn't want to break their setup.
I also added some telemetry for the `addBehavior` used when creating the task. The default changed from `childOfCurrent` to `asOwnDomain`, so we can use that to measure if people with the new default are stickier with tasks. …
=> enhance: use better defaults for `Create Task Note`

packages/engine-server/src/markdown/decorations/wikilinks.ts, packages/plugin-core/src/test/suite-integ/WindowDecorations.test.ts, test-workspace/vault/dendron.ref.links.md
#2862
- General
- Operations
- Architecture
- CSS
=> fix: highlighting misidentified capitalized header anchors on wikilinks as missing

packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/DoctorCommand.test.ts
The extension `dendron.dendron-markdown-links` is unnecessary since the note graph is built into Dendron now, but it also breaks the built-in note graph. This change will warn users if they have the extension installed.
=> chore: mark `dendron.dendron-markdown-links` as incompatible

packages/common-server/src/filesv2.ts, packages/common-test-utils/src/presets/plugin-core/lookup-single.ts, packages/common-test-utils/src/utils.ts, packages/engine-test-utils/src/engine.ts, packages/plugin-core/package.json, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/GoToNoteInterface.ts, packages/plugin-core/src/commands/Goto.ts, packages/plugin-core/src/commands/GotoNote.ts, packages/plugin-core/src/commands/OpenLink.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/features/codeActionProvider.ts, packages/plugin-core/src/test/presets/GotoNotePreset.ts, packages/plugin-core/src/test/suite-integ/CodeActionProvider.test.ts, packages/plugin-core/src/test/suite-integ/Goto.test.ts, packages/plugin-core/src/test/suite-integ/GotoNote.test.ts, packages/plugin-core/src/utils/editor.ts, packages/plugin-core/src/utils/index.ts
feat: add goto command
This adds a new command `Go to` which supports navigating the `uri` parameter of [[Proxy Notes|dendron://dendron.docs/rfc.38-links-to-non-note-files#proxy-notes]].
See docs in https://github.com/dendronhq/dendron-site/pull/489
In addition to implementing this feature, the following sections were cleaned up: 
- refactor codeActionProvider (to avoid introducing a new circular dependency)
- fix some tests in GotoNote
- add presents for GotoNote
- extract some utilities as common utilities
- General
- Operations
- Architecture …
=> feat: add goto command

docs/dendron.yml, packages/common-all/src/analytics.ts, packages/common-all/src/utils.ts, packages/engine-server/src/doctor/service.ts, packages/engine-server/src/migrations/utils.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/doctor.spec.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/Doctor.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/utils/StartupUtils.ts
This PR:
- Adds doctor action `removeDeprecatedConfigs` that detects and removes deprecated config keys marked in `DEPRECATED_PATHS`
- This also creates a backup.
- User is given a follow-up prompt to optionally open and inspect `dendron.yml` and the backup file side by side.
- Adds `dev.enableWebUI` to `DEPRECATED_PATHS`
- Adds prompt on upgrade letting users know that there is a deprecated key in `dendron.yml`, and a button that triggers the doctor command.
- This addition removes the need to explicitly write migration code that scrubs config keys that are no longer used.
- General
- Operations
- …
=> feat: Add doctor command to remove deprecated config and prompt on upgrade

packages/common-all/src/analytics.ts, packages/common-all/src/api.ts, packages/common-all/src/error.ts, packages/common-all/src/types/errorTypes.ts, packages/common-all/src/types/index.ts, packages/common-all/src/types/typesv2.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/markdown/remark/noteRefsV2.ts, packages/plugin-core/src/commands/ReloadIndex.ts, packages/plugin-core/src/logger.ts, packages/plugin-core/src/test/suite-integ/ReloadIndex.test.ts
Adds a warning when there are notes with duplicate IDs detected during initialization or reload.
Also refactors error handling to match what was discussed in the previous PR.
=> enhance(workspace): detect and warn for duplicate note IDs

packages/common-server/src/filesv2.ts, packages/engine-server/src/workspace/service.ts, packages/engine-test-utils/src/__tests__/engine-server/workspace.spec.ts
Fixes a bug where self contained vaults would get cloned into the wrong directory at startup if they were missing.
=> fix: self contained vaults get cloned into the wrong directory

packages/plugin-core/src/abTests.ts, packages/plugin-core/src/showcase/MeetingNotesTip.ts
We've collected enough data for this prompt test for Meeting Notes.  The effect of ending this test is that users in the B group will see the toast one time.  Users in the A group will not see the toast a second time.
=> chore: end the MEETING_NOTE_FEATURE_SHOWCASE_TEST a/b test

packages/common-all/src/analytics.ts, packages/plugin-core/src/commands/CreateTask.ts, packages/plugin-core/src/commands/GotoNote.ts, packages/plugin-core/src/utils/MeetingTelemHelper.ts
Adding telemetry to let us know when a user is creating a note from a Meeting Note. This is meant to test the hypothesis that Meeting Notes will lead to users creating more notes.
=> chore: enhancing meeting note telemetry

packages/plugin-core/src/features/TipOfTheDayWebview.ts
Fixing the `messageType` property of the `FeatureShowcaseDisplayed` event for the 'Tip of the Day' view. It's currently reporting blank.
Verified the behavior under the debugger.  Updated Airtable record.
=> chore: fixing messageType prop in tip of day telem

packages/engine-server/src/markdown/remark/dendronPub.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/dendronPub.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/dendronPub.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/utilsv5.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/v5/__snapshots__/image.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/v5/image.spec.ts
Fixes a bug where images without leading slashes in the URL would be broken in publishing if there is no `assetsPrefix` set.
For example, `![](assets/image.jpg)` would be exported as `<img src="assets/image.jpg">` which is the wrong path.
Fixed existing tests which were checking for the wrong value, and added a new test to cover this case.
#2860
- General
- Operations
- Architecture
- CSS
- eg. …
=> fix(publishing): images without leading forward slashes are broken when published in some setups

packages/plugin-core/src/_extension.ts
- Adding Links telemetry to user properties
- Removing the 'round to the nearest 10' for numNotes.
I tested the calculations in org-workspace for the link information; it takes ~10 ms so no perf concerns around slowing down initialization.
Telemetry notes added to Airtable
---
- General
- Operations
- Architecture
Pending v94 release.
- [n] if you are adding analytics related changes, make sure the [Telemetry](https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html) docs are updated
=> chore: adding links telemetry to InitializeWorkspace event props

packages/dendron-next-server/styles/scss/main.scss, packages/dendron-plugin-views/src/hooks/useGraphElements.tsx
This PR aims to highlight workspace information when `Full Graph View` is open for the first time. The message is autoclosable in 5s.
- General
- [~] check whether code be simplified
- [~] check if similar function already exist in the codebase. if so, can it be re-used?
- Operations
- [~] when shipping this change, will it just work or will it introduce additional operational overhead due to complicated interface …
=> enhance: display workspace information in full graph view

packages/common-all/src/dnode.ts, packages/common-all/src/utils.ts, packages/common-frontend/src/features/engine/slice.ts, packages/engine-server/src/cache/dendronFileSystemCache.ts, packages/engine-server/src/drivers/file/noteParser.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-test-utils/src/__tests__/engine-server/enginev2.spec.ts, packages/engine-test-utils/src/presets/engine-server/delete.ts, packages/engine-test-utils/src/presets/engine-server/rename.ts, packages/engine-test-utils/src/presets/engine-server/update.ts, packages/engine-test-utils/src/presets/engine-server/write.ts, packages/plugin-core/src/commands/GoUpCommand.ts
**Background**
While timestamping the initialisation process, I found out that the bulk of the time was spent in `addOrUpdateParents`. This was due to the linear search component of using `_.find` with a noteprops array. By changing the signature to use a combination of `NotePropsDict` and `NoteFNamesDict`, I was able to make drastic improvements to init speed.
Before (org-workspace on local Macbook): ~50 sec
After: ~4 sec
**Changes**
1. Use `NotePropsDict` and `NoteFNamesDict` in place of `NoteProps[]` within noteParser.ts
**Future work**
Continue to scrub code for more usages of `_.find` with a noteprops array or `getNoteByFnameV5` …
=> enhance(workspace): Speed up workspace initialization

packages/plugin-core/assets/dendron-ws/tutorial/treatments/main/tutorial.taking-notes.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/no-refactor/tutorial.taking-notes.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/original/tutorial.taking-notes.md
This PR:
- Adds omitted h3 header for meeting note mentions in all three treated tutorial assets.
related to #2889
=> chore: sync tutorial to add omitted headers for meeting note mention

packages/common-all/src/abTests.ts, packages/plugin-core/src/_extension.ts
This PR ends the AB test for the upgrade toast wording. After several weeks of data, it appears that "see what's new" is a clear winner.
The chart below is the cumulative number of unique users who clicked the button after an upgrade. Over several weeks "see what's new" maintained a clear lead over the other options, so this PR sets that as the default and ends the experiment.
=> chore: end the upgrade toast wording AB test

packages/plugin-core/src/_extension.ts
Some users have a corrupt value for 'version' in their `.dendron.ws` file if they ran the CLI.  This would cause their activation to fail.
Related: https://github.com/dendronhq/dendron/pull/2871
=> fix: fix corrupt .dendron.ws version to unblock activation

packages/engine-server/src/markdown/remark/utils.ts
Fixing a relatively large Sentry hitter in `POST api/notes/links`.  isNotUndefined doesn't address the case where the value of `note.tags` is `null`. 
Example Hit: https://sentry.io/organizations/dendron/issues/3263381836/?project=5898219
=> chore: fixing crash in POST api/notes/links

packages/plugin-core/src/showcase/GraphThemeTip.ts
This PR:
- defers AB testing user group calculation in `GraphThemeTip` to each call that needs the user group.
- determining the user group in the constructor caused `SegmentClient` to be instantiated during module load, which comes before the activation lifecycle.
- Our activate logic assumes that the segment client is not instantiated when it starts.
- General
- Operations
- Architecture
- [~] if you are adding analytics related changes, make sure you …
=> chore: defer user group calc in GraphThemeTip to after activation

packages/common-all/src/abTests.ts, packages/plugin-core/package.json, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/constants.ts
This PR makes self contained vaults the default for all new workspaces, both for new and existing users. This ends the self contained vaults AB-test, although the self contained vaults experiment itself is still ongoing.
=> chore: make self contained vaults default for all new workspaces

packages/engine-server/src/markdown/remark/dendronPub.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/blockAnchors.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/blockAnchors.spec.ts, test-workspace/vault/dendron.ref.links.block-anchors.md
A block anchor located after a table would cause the preview to crash (and likely publishing too, although I did not test if it does). This fix solves the issue.
We also decided to standardize on supporting block anchors after tables and not next to them. This works around a bug with the table parser, but also is a best practice since formatters and markdown table extensions otherwise misinterpret block anchors.
Co-authored-by: Kevin Lin <kevin@dendron.so>
=> fix: block anchor after table crashes preview

packages/plugin-core/src/views/EngineNoteProvider.ts, packages/plugin-core/src/views/NativeTreeView.ts
This PR:
- Attempts to fix an issue with the tree view where the `onOpenTextDocument` calls `treeView.reveal` too early.
- This causes an exception because `reveal` expects the tree item to be already there, but we haven't given the tree data provider to fully parse the tree yet.
To reproduce this issue:
1. pull in master branch
1. build
1. create note `a.b`, (`a` is a stub here)
1. create note `a.c`
You will see an exception raised by the extension host when creating a tree item handle. 
```
rejected promise not handled within 1 second: TypeError: Cannot destructure property 'id' of 'undefined' as it is undefined.
internal/timers:557
stack trace: TypeError: Cannot destructure property 'id' of 'undefined' as it is undefined.
at _.createHandle (/Applications/Visual Studio …
```
=> chore: temporary fix for tree view race condition

.github/workflows/ci.yml, babel.config.js, jest.config.js, package.json, packages/engine-test-utils/package.json, packages/plugin-core/src/test/suite-integ/BacklinksTreeDataProvider.test.ts, yarn.lock
chore: faster cli based tests
Remove `ts-jest` and use `babel` transformer to cli based test
`ts-jest` will run typescript compiler on all test files which is meant to catch type errors but this is unecessary since we already run `tsc build` during `ci` and `tsc --watch` during local development. this resulted in tests + all dependencies being compiled twice during `ci` (and many more times during local development)
the `babel` based typescript support does transpilation without typechecking (aka find & replace), resulting in drastic speedups and significant less CPU/memory overhead during local development. 
it also speeds up the `ci` test:
cli based tests using ts-node: 11min
cli basd tests using babel:  8min
=> chore: faster cli based tests

packages/common-all/src/constants/configs/publishing.ts, packages/common-all/src/constants/configs/workspace.ts, packages/common-all/src/types/configs/publishing/publishing.ts, packages/common-all/src/types/configs/workspace/task.ts, packages/dendron-next-server/styles/scss/main.scss, packages/engine-server/src/markdown/remark/dendronPub.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/dendronPub.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/dendronPub.spec.ts, packages/nextjs-template/styles/scss/main.scss, packages/plugin-core/src/test/suite-integ/migration.test.ts, packages/plugin-core/src/test/utils/workspace.ts, test-workspace/dendron.yml, test-workspace/vault/task.2021.10.26.020813.prepare-report.mail-report.md, test-workspace/vault/task.2021.10.26.020813.prepare-report.md
Displays the task note status when linking to task notes, both in the preview and in publishing.
Docs: https://github.com/dendronhq/dendron-site/pull/505
=> feat: display task note status when linking to task notes in publishing and in preview

packages/common-all/src/utils.ts, packages/plugin-core/src/commands/MoveHeader.ts, packages/plugin-core/src/commands/MoveNoteCommand.ts, packages/plugin-core/src/commands/RefactorHierarchyV2.ts, packages/plugin-core/src/commands/RenameHeader.ts
This PR:
- adds `createdCount`, `deletedCount`, and `updatedCount` to analytics payload of the following commands:
- `MoveNote`
- `RefactorHierarchy`
- `MoveHeader` (only adds `updatedCount`)
- `RenameHeader`
- General
- Operations
- Architecture
- …
=> chore(internal): track note changed entry counts in refactoring commands

packages/engine-server/src/markdown/remark/dendronPub.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/v5/__snapshots__/image.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/v5/image.spec.ts
Fixes an issue that was reported on the Discord about a recent update breaking images in publishing. The issue turns out to be `assetsPrefix` introducing an extra leading slash for images, which breaks publishing for some servers that are strict about URLs.
Modified an existing test so it would fail without this fix.
- General
- Operations
- Architecture
- CSS
- eg. [breaking dev change due to new …
=> fix(publish): assetsPrefix breaks images

packages/common-all/package.json, packages/common-all/src/dnode.ts, packages/common-all/src/index.ts, packages/common-server/package.json, packages/common-server/src/index.ts, packages/common-server/src/template.ts, packages/engine-server/src/enginev2.ts, packages/engine-test-utils/src/__tests__/common-all/template.spec.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts
chore(markdown): this moves templating functionality to `common-server`
Handlebars has a node dependency which would cause frontend build to fail when bundled with `common-all`
https://github.com/dendronhq/dendron/pull/2969
=> chore(markdown): this moves templating functionality to common-server

packages/common-all/src/types/unified.ts, packages/engine-server/src/markdown/remark/dendronPreview.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/utilsv5.spec.ts, packages/plugin-core/src/features/ReferenceHoverProvider.ts, packages/plugin-core/src/test/suite-integ/ReferenceHoverProvider.test.ts
Makes any wikilinks in hover clickable, which will navigate to the note via `GoToNote`
Coauthored by @SeriousBug.
---
- General
- Operations
- Architecture
- eg: [breaking dev change due to new dependency](https://github.com/dendronhq/dendron/pull/2188#pullre …
=> enhance(navigate): make wikilinks clickable in hover

packages/nextjs-template/components/DendronNoteFooter.tsx
Fixes an issue reported on Discord where the `edit this page on...` links on published pages would point to the wrong location for self contained vaults.
=> fix(publish): "edit this page on ..." link uses the wrong path for self contained vaults

packages/plugin-core/src/_extension.ts, packages/plugin-core/src/workspace.ts
Previously, the help and feedback panel would be empty if you weren't in a Dendron workspace.  This change fixes that issue.
=> fix(workspace): Help and Feedback Panel shows info when not in Dendron WS

packages/common-all/src/index.ts, packages/common-all/src/publish.ts, packages/common-all/src/types/index.ts, packages/common-all/src/util/treeUtil.ts, packages/common-all/src/utils.ts, packages/engine-test-utils/src/__tests__/common-all/util/__snapshots__/treeUtil.spec.ts.snap, packages/engine-test-utils/src/__tests__/common-all/util/treeUtil.spec.ts, packages/nextjs-template/components/DendronTreeMenu.tsx
feat(publish): ability to exclude children in dendron side nav
For notes with a lot of children, the side nav can become overcrowded. Introduce an option to disable children on the nav. Also make this the default when `has_collection` is `true`
- before: https://loom.com/i/710825588ced436487dc7687d5cf30f8
- after: https://www.loom.com/i/5b0330bb90b347838158b99ac3f3a5ef
- diff size:
- small: https://www.loom.com/i/0fe71bb4be94402a90d77f999ea2fd06
- large: https://www.loom.com/i/caf5d9e47fa446e1bb4d864de5f437a9
- reg: https://www.loom.com/i/5b0330bb90b347838158b99ac3f3a5ef
Docs: https://github.com/dendronhq/dendron-site/pull/509
*** …
=> feat(publish): ability to exclude children in dendron side nav

packages/api-server/src/Server.ts, packages/common-server/src/analytics.ts, packages/engine-test-utils/src/__tests__/engine-server/segmentClient.spec.ts, packages/plugin-core/src/_extension.ts
This PR:
- Adds a static _lock_ to `SegmentClient` that will prevent access of `SegmentClient.instance()` before it has been explicitly _unlocked_.
- Unlocking is done right at the beginning of `_activate` in `plugin-core`, and when the server is run as a separate process
- This prevents `SegmentClient` from being accessed (thus potentially creating a uuid file) during module load time.
- General
- Operations
- Architecture …
=> chore(internal): add safeguard for unexpected segment client instantiation

packages/plugin-core/src/_extension.ts
- A quick fix for identifying notes that are tutorial notes, and adjusting our numNotes, numWikilinks, numBacklinks, and numNoteRefs values accordingly. 
@kevinslin and @hikchoi - please add to the hardcoded list of tutorial ID's as we have more experimental tutorial versions.
Tested for startup time - org-workspace still only spending ~15 ms on this part, so we're ok.
---
Airtable Updated
=> chore(internal): add tutorial note count information

packages/engine-test-utils/src/__tests__/pods-core/NextjsExportPod.spec.ts, packages/pods-core/src/builtin/NextjsExportPod.ts
Fixes an issue that was reported on Discord, where the logo file was moved without updating the configuration, which caused the export to get stuck and hang forever.
This fix solves the issue by recognizing it when the logo file is missing, warning the user, and continuing with the export.
- General
- Operations
- Architecture
- CSS
- eg. [breaking dev change due to new …
=> fix(publish): Export gets stuck if `logoPath` is set but the logo doesn't exist

packages/common-all/src/vault.ts, packages/engine-server/src/doctor/service.ts, packages/engine-server/src/workspace/service.ts, packages/plugin-core/src/settings.ts, packages/pods-core/src/builtin/GDocPod.ts, packages/pods-core/src/builtin/MarkdownPod.ts, packages/pods-core/src/v2/pods/export/MarkdownExportPodV2.ts
Fixed some usages of `vault2Path` and `VaultUtils.getRelPath` to be self contained vault aware.
Also performed some minor cleanup of the codebase as I hit warnings/deprecations.
- General
- Operations
- Architecture
- CSS
=> chore: check vault path usages for self contained vaults

packages/plugin-core/package.json, packages/plugin-core/scripts/genConfig.ts
chore(workspace): fix a few command settings
- disable goto keybinding if plugin isn't active
- correct name of "Apply Template" command
- add a safety to generate plugin active when clause for keybinding if command has a similar when clause
=> chore(workspace): fix a few command settings

packages/common-server/src/filesv2.ts, packages/engine-server/src/workspace/service.ts, packages/plugin-core/src/test/suite-integ/MigrateSelfContainedVault.test.ts
This PR improves the "Migrate to Self Contained Vault" command to:
- Update the logoPath, if one was set, and it was a logo inside of the vault that's being migrated
- If there's a gitignore file, moves it along with the migrated vault (before the gitignore file would be left in the notes subfolder)
- General
- Operations
- Architecture
- CSS
- eg. [breaking dev change due to new …
=> enhance(workspace): "Migrate to Self Contained Vault" updates logoPath and moves gitignore file

packages/common-server/src/types/index.ts, packages/engine-server/src/topics/hooks.ts, packages/engine-test-utils/src/__tests__/engine-server/topics/hooks.spec.ts, packages/plugin-core/src/commands/CreateHookCommand.ts
- `Maarrk#9537`
- **I didn't see a section named "commit style"** after visiting that note
- I just looked at other commits
- NOTE: make sure to read [Addressing open issues](https://docs.dendron.so/notes/adc39825-77a6-46cf-9c49-2642fcb4248e.html#addressing-open-issues)
- Related to https://github.com/dendronhq/dendron/issues/2964
- only importing axios package which was already a dependency, won't be circular because it's external
- added axios in the same way as execa
- not needed, this is self-documenting with the hook template
- see above
=> enhance: Add axios to hook function

packages/common-server/src/template.ts, packages/engine-test-utils/src/__tests__/common-all/template.spec.ts, packages/plugin-core/src/commands/ApplyTemplateCommand.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, test-workspace/vault/daily.journal.2022.05.30.md, test-workspace/vault/daily.journal.2022.05.31.md, test-workspace/vault/template.daily.md
feat(edit): template helpers
built-in helpers to make handlebar templates more powerful in Dendron.
This PR introduces 3 new helpers: `eq`, `fname2Date`, and `getDayOfWeek`
Docs: https://github.com/dendronhq/dendron-site/pull/523
Adds follwoing analytics to `TemplateApplied` event that show how many times each helper was invoked per template
```
helperStats: {
fname2Date: number
eq: number
getDayOfWeek: number
}
```
- General
- Operations
- Architecture …
=> feat(edit): template helpers

packages/engine-server/src/markdown/remark/dendronPreview.ts, packages/plugin-core/src/test/suite-integ/PreviewPanel.test.ts
For example: `![](images/Pasted%20image%2020220529172111.png)` is not rendered in the Preview, while this is perhaps not caused by pasting images directly into the Dendron Paste Image extension, some users might use other editors to edit the same note, those editors may store the image from clipboard with a space-separated name and return an unexpectedly encoded URI.
=> fix: Images with encoded URI are not rendered in the Preview

packages/common-all/src/analytics.ts, packages/plugin-core/assets/dendron-ws/tutorial/treatments/main/tutorial.conclusion.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/main/tutorial.linking-notes.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/main/tutorial.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/main/tutorial.rich-formatting.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/main/tutorial.taking-notes.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/main/tutorial.user-interface.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/no-refactor/tutorial.conclusion.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/no-refactor/tutorial.linking-notes.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/no-refactor/tutorial.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/no-refactor/tutorial.rich-formatting.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/no-refactor/tutorial.taking-notes.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/no-refactor/tutorial.user-interface.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/original/tutorial.conclusion.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/original/tutorial.linking-notes.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/original/tutorial.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/original/tutorial.rich-formatting.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/original/tutorial.taking-notes.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/original/tutorial.user-interface.md, packages/plugin-core/src/workspace/tutorialInitializer.ts
This PR:
- Proposes a new convention for tutorials for consolidating tutorial view events into one
- Add additional information about tutorial view event for easier analysis
- `fname`, `currentStep`, `totalSteps`
- syncs tutorial that has additional frontmatter as per new convention
- fixes an issue where some tutorial view events were omitted
- Tutorials now should have frontmatter `currentStep` and `totalSteps`, indexed by zero. (entry point is always `currentStep: 0`)
- We have a sizable number of users who have never reported some tutorial events.
- This seems to be rooted from a race between registering the callback to `onDidChangeVisibleTextEditors`, and actually opening the note
- This is mitigated by making sure we register the callback before we proceed with opening tutorial …
=> chore(workspace): support initializing variable length tutorials

packages/plugin-core/package.json, packages/plugin-core/src/commands/ConfigureCommand.ts, packages/plugin-core/src/commands/TaskComplete, packages/plugin-core/src/commands/TaskComplete.ts, packages/plugin-core/src/commands/TaskStatus.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/ConfigureCommand.test.ts, packages/plugin-core/src/test/suite-integ/TaskStatus.test.ts
Adds the commands "Set Task Status" and "Complete Task".
Set Task Status will prompt the user for the status to use based on the task symbol mappings, while "Complete Task" uses the first `taskCompleteStatus` without prompting.
For both commands, if the user has a link to a note selected, they will set the status for that note. If they don't have any links selected but are currently in a task note, then it will set the status for that note (only if the current note is a task note, to avoid setting the status accidentally in non-task notes).
If the user has a link selected but the link is ambiguous (multiple notes across vaults with the same name, and the link isn't x-vault), then it will also prompt for which note the user wanted.
Docs: https://github.com/dendronhq/dendron-site/pull/525
- …
=> feat(structure): Set Task Status and Complete Task commands

packages/common-all/src/fuse.ts, packages/dendron-cli/src/commands/devCLICommand.ts, packages/engine-server/src/seed/service.ts, packages/engine-server/src/workspace/service.ts, packages/engine-test-utils/src/__tests__/engine-server/workspace.spec.ts, packages/engine-test-utils/src/engine.ts, packages/engine-test-utils/src/utils/workspace.ts, packages/plugin-core/src/commands/SetupWorkspace.ts, packages/plugin-core/src/features/completionProvider.ts, packages/plugin-core/src/test/suite-integ/CopyNoteRef.test.ts, packages/plugin-core/src/test/suite-integ/VaultAddCommand.test.ts, packages/plugin-core/src/test/suite-integ/WindowWatcher.test.ts, packages/plugin-core/src/test/testUtilsV3.ts, packages/plugin-core/src/test/testUtilsv2.ts, packages/plugin-core/src/workspace/blankInitializer.ts, packages/plugin-core/src/workspace/seedBrowserInitializer.ts, packages/plugin-core/src/workspace/templateInitializer.ts, packages/plugin-core/src/workspace/tutorialInitializer.ts, packages/plugin-core/src/workspace/workspaceInitializer.ts
chore: add `create_test_vault` dev method, fix issue with `createWorkspace`, other backend changes
- introduce `dendron dev create_test_vault` which can create vaults with pre-configured distribution of notes/vaults (useful for diagnosing performance issues)
- fix issue with `createWorkspace` cmd - when passing in multiple vaults to a self contained workspace, only the first vault is actually added to the `dendron.yml`
- this led to a larger refactoring of the `createWorkspace` to make a distinction between the `wsVault` (for sc vault, this is the vault in `notes` folder) and `additionalVaults`
- also modified `WorkspaceInitializer` interface to account for `wsVault` and `additionalVaults`
- cleaned up some tests
=> chore: add `create_test_vault` dev method, fix issue with `createWorkspace`, other backend changes

packages/plugin-core/package.json, packages/plugin-core/src/constants.ts
Fixing an issue where some of our panels have Duplicated Titles:
=> fix(workspace): fix duplicated panel titles

packages/common-all/data/dendron-yml.validator.json, packages/common-all/src/constants/configs/workspace.ts, packages/common-all/src/types/configs/workspace/graph.ts, packages/dendron-next-server/data/dendron-yml.validator.json, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/plugin-core/src/components/views/NoteGraphViewFactory.ts, packages/plugin-core/src/test/utils/workspace.ts, packages/plugin-core/src/views/GraphPanel.ts, test-workspace/dendron.yml
This PR aims to add a graph config `createStub` with default value as `false`. This is to have graph nodes not create default stubs when clicked. The graph view will still update the view around node clicked.
Docs PR: https://github.com/dendronhq/dendron-site/pull/524
- General
- Operations
- Architecture
- [~] check if code …
=> enhance(views): configure note creation with graph view

packages/engine-server/src/metadata/service.ts, packages/plugin-core/package.json, packages/plugin-core/src/commands/ImportPod.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/commands/pods/ImportObsidianCommand.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/showcase/AllFeatureShowcases.ts, packages/plugin-core/src/showcase/FeatureShowcaseToaster.ts, packages/plugin-core/src/showcase/ObsidianImportTip.ts, packages/plugin-core/src/survey.ts, packages/plugin-core/src/workspace.ts, packages/plugin-core/src/workspace/tutorialInitializer.ts
MVP flow for Obsidian Import, specifically targeting onboarding users who are coming from Obsidian. This utilizes markdown import pod under the hood, but gets rid of the need to fill out a `config.yml` file.  All a user needs to do is use a file picker control to pick the folder. 
This will show up in a feature toaster to users under the following conditions:
1. user marked 'Obsidian' in prior tools in the survey
2. user opened a tutorial workspace
3. Either the user reached the last page of the tutorial, or 10 minutes has elapsed, whichever comes first.
This change doesn't improve or fix existing issues in the Markdown Import Pod.  That will be deferred to a subsequent PR. 
TODO: 
1. Need to resolve the tutorialInitializer logic against Mark's change here: …
=> feat(sync): Obsidian Import Flow

packages/common-all/src/analytics.ts, packages/common-all/src/util/treeUtil.ts, packages/common-frontend/src/utils/tree-view.tsx, packages/engine-test-utils/src/__tests__/common-all/util/treeUtil.spec.ts, packages/plugin-core/src/test/suite-integ/EngineNoteProvider.test.ts, packages/plugin-core/src/test/suite-integ/NativeTreeView.test.ts, packages/plugin-core/src/views/EngineNoteProvider.ts
This PR:
- Preemptively filters out note ids that will cause the sort logic to fatally crash the tree view rendering (note ids not in sync with noteDict)
- tree view will omit the out-of-sync note ids from rendering.
- Properly log when this happens so we can troubleshoot the root cause with the surrounding context available.
- General
- Operations
- Architecture
- …
=> chore: gracefully handle tree view sort error to avoid crashing the tree view

packages/plugin-core/src/components/lookup/LookupControllerV3.ts
There's a lag between hitting Ctrl+L and the lookup quick pick showing up when you have a lot of notes.  This causes a lot of stray keystrokes to get added in notes.  This change attempts to fix the initial lag.
---
=> chore: make lookup control appear faster

packages/common-server/src/filesv2.ts, packages/engine-server/src/workspace/service.ts
The issue was caused because:
1. VSCode locks the open workspace folders
2. Windows does not allow renaming locked folders
The issue did not present in UNIXes because they do allow folders that are in use to be renamed. 
This PR fixes the issue by instead moving the individual note files when migrating vaults. This will be slower for large vaults, but the performance tradeoff should be acceptable since this is a one-off action.
Tested manually on Windows and migration now works.
#3021
- General
- Operations
- Architecture
- eg: [making changes to DNode](https://github.com/dendronhq/dendron/pull/2158#pullrequest …
=> fix(workspace): Migrate to Self Contained Vault causes EBUSY errors on Windows

packages/common-all/src/types/configs/workspace/workspace.ts, packages/engine-test-utils/src/__tests__/common-all/template.spec.ts, packages/engine-test-utils/src/__tests__/common-server/abTesting.spec.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/plugin-core/src/test/utils/workspace.ts
enhance(edit): this sets handlebars as the default template format
BREAKING: this sets handlebars as the default template format. users that were using `<% %>` syntax for template variables will no longer work. please see the [[Migration|dendron://dendron.dendron-site/dendron.topic.templates.handlebars.migration]] guide to switch to handlebar based templates
=> enhance(edit): this sets handlebars as the default template format

packages/plugin-core/package.json
VSCode now supports displaying a "Sponsor" button on the extension store. This PR adds the required `package.json` config for Dendron.
See docs: https://code.visualstudio.com/updates/v1_68#_extension-sponsorship
What the button looks like: https://code.visualstudio.com/updates/v1_68#_sponsoring-extensions
=> chore: add sponsorship link

packages/plugin-core/src/features/HelpFeedbackTreeview.ts
There's an issue with the Help and Feedback panel where if you click an item multiple times, it'll only launch the link once.  This may make it feel like the button is broken. This change addresses that issue.
I also added an additional link to our FAQ page.
=> fix(views): double click issue on help and feedback panel

packages/common-all/src/analytics.ts, packages/common-all/src/vault.ts, packages/engine-server/src/seed/service.ts, packages/plugin-core/src/commands/Sync.ts, packages/plugin-core/src/test/suite-integ/OutOfDateSeedCheck.test.ts, packages/plugin-core/src/test/suite-integ/SeedCommand.test.ts, packages/plugin-core/src/test/suite-integ/SyncCommand.test.ts, packages/plugin-core/src/test/utils/TestSeedUtils.ts
The `root` path of a seed configuration is added to the users config file as the `fsPath` of the corresponding seed vault. However, if the `root` configuration of the seed vault changes, the `fsPath` is not updated.
This PR adds a check during workspace sync where we'll check if the path has changed, and prompt the user to update their configuration file. I added this to the sync since that's when the user will hit an issue with the change: the vault will continue to work until the user pulls in an update with the sync.
This is required to migrate seed vaults to self contained without causing significant impact to users. Without this feature, we'd have to rely on users to manually update the configuration or remove and re-add the vault.
- eg: [if configuration for utilities are already in …
=> enhance(workspace): Prompt to update seed vault configuration during sync if the seed configuration changed

packages/api-server/src/modules/notes/index.ts, packages/common-all/src/api.ts, packages/common-all/src/types/typesv2.ts, packages/common-server/src/etc.ts, packages/engine-server/src/engineClient.ts, packages/engine-server/src/enginev2.ts, packages/engine-server/src/topics/connector.ts, packages/plugin-core/src/services/EngineAPIService.ts, packages/plugin-core/src/services/EngineAPIServiceInterface.ts, packages/plugin-core/src/views/utils.ts, packages/plugin-core/src/vsCodeUtils.ts
This PR tries to patch the `EPERM` issues some users reported on Windows. I can't reproduce the bug, but I patched all places that are likely to cause issues.
Looking at Sentry, it looks like the issue happens inside `_activate`, but that's as much as Sentry gives me because the real stack trace seems to get lost.
Also removed the deprecated `RespRequired` type, and updated the `info()` engine interface which was the only place where it was used.
=> fix(workspace): try to patch `EPERM` issues for windows

packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/engineClient.ts, packages/plugin-core/src/commands/DeleteNodeCommand.ts, packages/plugin-core/src/test/suite-integ/DeleteNodeCommand.test.ts
The tests fail on Windows only, and only when running the entire test suite. It seems like a race condition (the tests sometimes pass and sometimes fail when running locally, although they seem to consistently fail on CI), but I wasn't able to find any issues with the code or any common mistakes like not awaiting a promise.
I can't figure out why the tests are failing when running the entire suite, but I did some cleanup which would be useful to merge.
=> chore: clean up some DeleteNodeCommand tests

packages/common-all/src/analytics.ts, packages/plugin-core/src/commands/VaultAddCommand.ts, packages/plugin-core/src/test/suite-integ/VaultAddCommand.test.ts
This PR adds a check when a self contained vault is being added to the workspace. If the self contained vault has transitive dependencies, the user will be warned with a prompt which they'll need to acknowledge before we continue. I opted to have this blocking prompt because the user otherwise won't have enough time to see the prompt before the window reloads.
Docs: https://github.com/dendronhq/dendron-site/pull/545
=> enhance(workspace): make vault add command warn for transitive deps

packages/common-all/src/utils/index.ts, packages/common-all/src/vault.ts, packages/dendron-cli/src/commands/vaultCLICommand.ts, packages/engine-server/src/workspace/service.ts, packages/engine-test-utils/src/__tests__/engine-server/workspace.spec.ts, packages/engine-test-utils/src/utils/index.ts, packages/plugin-core/src/commands/VaultAddCommand.ts, packages/plugin-core/src/test/suite-integ/VaultAddCommand.test.ts
This PR does 2 things:
1. Newly added vaults will always use UNIX style paths, as opposed to platform specific paths. This is required for cross compatibility for vaults created in Windows. Dendron will continue to correctly read these paths on Windows. #3040 
2. When adding an existing vault as a remote vault to a workspace, Dendron will no longer try to create `.gitignore` and `dendron.yml` files inside the added vault.
=> enhance(workspace): Vaults always use UNIX style separators in config files & Adding an existing remote vault avoids creating workspace files

.github/workflows/ci.yml, packages/common-all/src/types/typesv2.ts, packages/engine-server/src/config.ts, packages/engine-server/src/enginev2.ts, packages/engine-server/src/workspace/service.ts, packages/engine-test-utils/src/__tests__/engine-server/dconfig.spec.ts, packages/plugin-core/src/test/suite-integ/CreateDailyJournalNote.test.ts, packages/plugin-core/src/test/suite-integ/VaultAddCommand.test.ts, packages/plugin-core/src/workspace/baseWorkspace.ts
enhance(workspace): validate dendronrc.yml and emit error if invalid
dendronrc.yml will prevent the workspace from loading if `workspace` is specified with an empty object or `vaults` is not an array
also fix some issues with tests timing out in plugin
=> enhance(workspace): validate dendronrc.yml and emit error if invalid

packages/engine-server/src/engineClient.ts, packages/engine-server/src/enginev2.ts, packages/engine-server/src/markdown/remark/noteRefsV2.ts, packages/engine-server/src/markdown/utilsv5.ts, packages/engine-server/src/workspace/vscode.ts
Dendron will try to format `created`/`updated` according to `dendron.defaultTimestampDecorationFormat` option from `dendron.code-workspace` when processing note references. This will fail on any workspace that does not have `dendron.code-workspace`. This leads to an error on publish (see https://github.com/dendronhq/dendron/issues/2988) and probably errors in other places
For frontmatter variable substitution, we never meant for `created`/`updated` to actually be formatted. To simplify the method call, remove the requirement to parse `dendron.code-workspace`
=> fix(publish): issue publishing note with ref without a `code-worksapce` file

packages/plugin-core/src/commands/Sync.ts
only thing changed is the wording of the message, no logic altered.
see issue here: https://github.com/dendronhq/dendron/issues/2816
discord username: avhb#0567
=> fix(workspace): improve phrasing of sync message

packages/common-all/src/analytics.ts, packages/common-all/src/types/typesv2.ts, packages/common-frontend/src/features/ide/slice.ts, packages/dendron-plugin-views/src/components/DendronApp.tsx, packages/dendron-plugin-views/src/components/DendronGraphPanel.tsx, packages/dendron-plugin-views/src/components/DendronSideGraphPanel.tsx, packages/dendron-plugin-views/src/components/GraphFilterView.tsx, packages/dendron-plugin-views/src/components/graph.tsx, packages/dendron-plugin-views/src/hooks/useGraphElements.tsx, packages/dendron-plugin-views/src/utils/graph.ts, packages/engine-server/src/metadata/service.ts, packages/plugin-core/package.json, packages/plugin-core/src/components/views/NoteGraphViewFactory.ts, packages/plugin-core/src/components/views/SchemaGraphViewFactory.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/views/GraphPanel.ts, packages/plugin-core/src/workspace.ts
In the Graph Filter menu, an additional filter for "depth" has been added. The depth value varies from 1(default) through 3. This is to improve the usability of the local graph view. This value is also saved so that the graph opens with the same depth the next time.
Use the graph panel buttons to update the graph depth. The depth is saved back to meta.json file when panel is Collapsed
As the graph becomes dense with incoming and outgoing links, it begins to look messy. This may be resolved by adding more filters to show/hide incoming/outgoing links.
Level 1 (default) displays: active note, its parent, children and links
Level 2 displays active note, parent, grandparent, children, grandchildren, active note's links, active note's links' links
Docs link: …
=> feat(views): depth filter for local graph

packages/plugin-core/src/_extension.ts
Takes a count of task notes in the workspace as a telemetry.
=> chore: task note count telemetry

packages/engine-server/src/workspace/service.ts, packages/plugin-core/src/commands/MigrateSelfContainedVault.ts, packages/plugin-core/src/test/suite-integ/MigrateSelfContainedVault.test.ts
Self contained vault migration will now allow users to migrate workspace vaults that only contain one vault.
=> enhance(workspace): support single-vault workspace vaults for self contained vault migration

packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/DiagnosticsReport.ts, packages/plugin-core/src/workspace.ts
Fixes an issue that causes an error during initialization if a native workspace is used, or if a code workspace is opened without opening the workspace file.
#3122
=> fix(workspace): error when native workspaces are initializing

packages/common-all/src/abTests.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/workspace/tutorialInitializer.ts
This PR:
- Ends the quickstart tutorial AB test in preparation of other tutorial related ab tests.
- Fixes `TutorialInitializer` to properly recognize that there are no active running tutorial ab tests.
- General
- Operations
- Architecture
- [~] [Write …
=> chore(analytics): end quickstart tutorial ab test

packages/plugin-core/src/features/completionProvider.ts
This PR:
- register a debounced version of `provideCompletionItem` to avoid triggering lookup (potentially expensive depending on workspace size) on every keystroke.
- We have another completion item provider for block completions, but this does not get triggered on every keystroke, and doesn't use lookup so it is generally lighter than `provideCompletionItem`. For this reason this is not debounced.
This is not straightforward to write a test so confirming manually that it is successfully debounced:
as-is:
to-be:
- General
- Operations
- Architecture …
=> chore(workspace): debounce completion provider trigger to reduce lag when autocompleting wikilinks

packages/common-all/src/analytics.ts, packages/common-all/src/types/noteTrait.ts, packages/plugin-core/package.json, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/ConfigureNoteTraitsCommand.ts, packages/plugin-core/src/commands/CreateNoteWithTraitCommand.ts, packages/plugin-core/src/commands/CreateNoteWithUserDefinedTrait.ts, packages/plugin-core/src/commands/RegisterNoteTraitCommand.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/dendronExtensionInterface.ts, packages/plugin-core/src/services/NoteTraitManager.ts, packages/plugin-core/src/services/NoteTraitService.ts, packages/plugin-core/src/test/MockDendronExtension.ts, packages/plugin-core/src/test/suite-integ/components/traits/CreateNoteWithTraitCommand.test.ts, packages/plugin-core/src/test/suite-integ/components/traits/NoteTraitService.test.ts, packages/plugin-core/src/test/suite-integ/components/traits/TestTrait.ts, packages/plugin-core/src/test/suite-integ/components/traits/testJSTraits/InvalidTestTrait.js, packages/plugin-core/src/test/suite-integ/components/traits/testJSTraits/TestTraitUsingModules.js, packages/plugin-core/src/test/suite-integ/components/traits/testJSTraits/UserTestTrait.js, packages/plugin-core/src/traits/TraitUtils.ts, packages/plugin-core/src/traits/UserDefinedTraitV1.ts, packages/plugin-core/src/traits/webpack-require-hack.ts, packages/plugin-core/src/workspace.ts, packages/plugin-core/src/workspace/workspaceActivater.ts
Various improvements to Note Traits:
- Note Traits now supports application of a template
- 'Adding' support for lodash, luxon access in the trait definition JS.  It turns out that it was already accessible via Node JS' `module.require`, but just completely undiscoverable.  I've added require statements to the traits template.
- Revamping the traits template to include more thorough documentation, including rudimentary Intellisense support via JSDoc strings
- Allows traits to 'hot' reload, so you no longer need to reload window to test if your code is working
- Add a watch-like compile capability - when a user saves their JS file, the code does a test run of each function during the traits registration process.  If any of the functions have errors, we'll provide a helpful error toast …
=> enhance(structure): improved note traits

packages/plugin-core/assets/dendron-ws/tutorial/treatments/main/tutorial.conclusion.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/quickstart-v1/tutorial.md, packages/plugin-core/src/workspace/tutorialInitializer.ts
- Adding a small tip about Obsidian Import to the tutorial
- Shortening the duration for the feature toaster to show up after 3 minutes instead of 10
Corresponding PR for dendron-site: https://github.com/dendronhq/dendron-site/pull/561
=> enhance(sync): adding import hint to tutorial

packages/common-all/src/abTests.ts
- This re-enables quickstart tutorial ab test that was ended in #3130 since we don't have any newly proposed ab tests for the tutorial ready.
=> chore(analytics): re-enable quickstart tutorial ab test

packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/SetupWorkspace.ts, packages/plugin-core/src/dendronExtensionInterface.ts, packages/plugin-core/src/test/MockDendronExtension.ts, packages/plugin-core/src/test/suite-integ/WindowDecorations.test.ts, packages/plugin-core/src/utils/ExtensionUtils.ts, packages/plugin-core/src/workspace/workspaceActivater.ts
chore(pr): refactoring of extension startup logic
Some prep work to enable enabling workspace initialization without reloading
- move ExtensionUtils into own file
- workspace activator shouldn't require user input
=> chore(pr): refactoring of extension startup logic

packages/nextjs-template/components/DendronBreadCrumb.tsx, packages/nextjs-template/components/DendronLayout.tsx, packages/nextjs-template/components/DendronLogoOrTitle.tsx, packages/nextjs-template/components/DendronNoteFooter.tsx, packages/nextjs-template/components/DendronSearch.tsx, packages/nextjs-template/components/DendronTreeMenu.tsx, packages/nextjs-template/utils/hooks.ts
This PR aims to reduce the load time of Dendron sidebar in a published site.
- Removed unnecessary dependencies on load, unused imports and duplicate fetch request.
Tested by commenting out the custom BannerAlert code
- General
- Operations
- Architecture
- eg: [making changes to DNode](https://github.com/dendronhq/dendron/pull/2158#pullrequestreview-85 …
=> fix(publish): slow rendering of sidebar in published site

packages/plugin-core/src/commands/RefactorHierarchyV2.ts
Fixing an old issue with the refactor hierarchy command, where the quickpick would get "stuck" and require a mouse to click either "proceed" or "cancel".  The QuickPick was losing focus because of the webview we show that contains the list of note renames.
=> fix(structure): quickpick stuck issue for refactor hierarchy cmd

packages/engine-server/src/topics/webpack-require-hack.ts, packages/plugin-core/src/commands/RegisterNoteTraitCommand.ts, packages/plugin-core/src/traits/webpack-require-hack.ts, packages/plugin-core/webpack-require-hack.js
Fixing two issues with the note traits updates:
- Hot reloading wasn't working in the webpacked build because the wrong `webpack-require-hack` file was being modified.
- Commenting out the `applyTemplate` function of the default trait template.
=> fix(structure): hot reload in note traits + no template by default

.github/workflows/ci-windows-test.yml, .github/workflows/ci.yml, packages/engine-server/src/workspace/service.ts, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/plugin-core/src/test/suite-integ/VaultRemoveCommand.test.ts
It also re-enables the tests related to duplicate note behavior settings when a vault is removed, which were skipped when switching the default vault type for tests to self contained.
The issue affects all vaults that have a `name`, where their name is different from the `fsPath`. The issue was "dormant" until self contained vaults since old style vaults would typically use the same name as their fsPath or wouldn't use a name at all, while self contained vaults have longer `fsPath`s and they set their `name` different than `fsPath` by default.
=> fix(workspace): removing vault with a name different than their `fsPath` doesn't remove them from `duplicateNoteBehavior`

packages/common-all/src/error.ts, packages/common-all/src/types/typesv2.ts, packages/common-server/src/filesv2.ts, packages/common-test-utils/src/noteUtils.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/markdown/remark/noteRefsV2.ts, packages/engine-test-utils/src/__tests__/common-server/filev2.spec.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/doctor.spec.ts, packages/plugin-core/src/WorkspaceWatcher.ts, packages/plugin-core/src/commands/MoveHeader.ts, packages/plugin-core/src/components/doctor/utils.ts, packages/plugin-core/src/fileWatcher.ts, packages/plugin-core/src/test/testUtilsv2.ts, packages/plugin-core/src/workspace/tutorialInitializer.ts
This PR:
- Handles the case where duplicate note id detection is triggered for a file that is opened in the editor, but is already removed (VSCode keeps the editor open even after a file system delete).
- This also covers some cases where the note is temporarily removed from the file system during workspace sync (caused by git stashing)
- ~~Adds a custom type guard `isRespV3SuccessResp` for `RespV3` that can be used to help typescript properly narrow the type of the response.~~ Changes `ErrorUtils.isErrorResp` to be a user defined type guard that can be used to help typescript properly narrow the type of the response.
- change `file2Note` to return a `RespV3` in cases where the file path does not exist.
- refactors all usage of `file2Note`.
- eg: [if configuration for utilities are …
=>  fix(workspace): duplicate note id detected even after a file is removed

packages/plugin-core/src/features/BacklinksTreeDataProvider.ts
This PR:
- fixes an issue with the backlinks tree view where notes that have the characters `.`, `m` and `d` at the end were getting trimmed excessively.
1. Create note named `somenotemdm.dmd.mmm.ddd`
2. Create note named `foo`
3. Add `[[foo]]` in the body of `somenotemdm.dmd.mmm.ddd`
4. Go to the note `foo` and focus on the backlinks tree view
5. Backlink tree item for `somenotemdm.dmd.mmm.ddd` is labeled as `somenote` 
- General
- Operations
- Architecture
- eg: …
=> fix(views): backlink tree item labels are trimmed excessively

packages/plugin-core/package.json, packages/plugin-core/src/commands/ConfigureLocalOverride.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/ConfigureLocalOverride.test.ts
task: `[[task.2022.06.29.configure-local-config]]`
doc pr: [570](https://github.com/dendronhq/dendron-site/pull/570)
When run, the command opens up quick pickup to ask if user wants to configure overrides for the current workspace or all local workspaces of that user.
When `dendronrc.yml` doesn't exist for the specified scope, the command creates one.
=> feat(plugin-core): command for local override config

packages/common-all/src/api.ts, packages/common-all/src/types/typesv2.ts, packages/common-all/src/utils/lookup.ts, packages/engine-server/src/doctor/service.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/engineClient.ts, packages/engine-test-utils/src/presets/engine-server/query.ts, packages/engine-test-utils/src/presets/engine-server/rename.ts, packages/engine-test-utils/src/presets/engine-server/write.ts, packages/plugin-core/src/commands/MoveHeader.ts, packages/plugin-core/src/components/lookup/NotePickerUtils.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/services/EngineAPIService.ts, packages/plugin-core/src/services/EngineAPIServiceInterface.ts
We have some improperly typed responses in API.ts that make the data prop of `Resp` be `Required`.  The server was not passing back Data in some cases due to exceptions, which led to cascading issues on the plugin side because the type definitions on the responses were not accurate.
The main way I found this manifesting itself is with Doctor Fix:Frontmatter, which was always showing a modal dialog error because we try to re-write root as part of that operation, which store doesn't permit right now (another separate issue).
Example errors that we were getting below: 
```log
"TypeError: Cannot read properties of undefined (reading 'forEach')
at DendronEngineClient.refreshNotesV2 (/Users/jyeung/code/dendron/dendron/packages/engine-server/src/engineClient.ts:356:11)
at …
```
=> fix(workspace): proper handling of invalid data for write note ops

packages/common-all/src/dnode.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-server/src/markdown/remark/wikiLinks.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/wikiLink.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/wikiLink.spec.ts
`[[foo | dendron://vault/foo]]` is parsed incorrectly, with `dendron://vault/foo` taken as the name of the note (vs being identified as a vault prefix).
First brought up in https://github.com/dendronhq/dendron/issues/3179
=> fix(retrieve): bad parsing of xvault wikilink with space

packages/common-all/data/dendron-yml.validator.json, packages/common-all/src/constants/configs/workspace.ts, packages/common-all/src/types/configs/workspace/workspace.ts, packages/common-all/src/utils/index.ts, packages/engine-server/src/config.ts, packages/engine-server/src/markdown/remark/noteRefsV2.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-server/src/workspace/service.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/dconfig.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/noteRefv2.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/noteRefv2.spec.ts, packages/engine-test-utils/src/utils/seed.ts, packages/plugin-core/package.json, packages/plugin-core/src/commands/CopyNoteRef.ts, packages/plugin-core/src/test/suite-integ/CopyNoteRef.test.ts, packages/plugin-core/src/test/utils/workspace.ts
- introduce smart note references as described in [[smart header references|dendron://dendron.docs/rfc.47-better-note-references#smart-header-references]]
- introduce `enableSmartRef` config option with default set to true
- NOTE: decided to go with this instead of `enableLegacyRef` - the plan is to manually migrate everyone to the new syntax and remove legacy ref syntax
- fix bug in `extractHeader` (was mutating the block when extracting)
- copy note ref behavior update, if using `enableSmartRef` and a header is selected, don't generate `#{header},1:#*` but `#{header}` instead
Docs: https://github.com/dendronhq/dendron-site/pull/573
=> feat(workspace): smart note refs

packages/common-all/src/noteDictsUtils.ts, packages/common-all/src/types/typesv2.ts, packages/dendron-cli/src/commands/notes.ts, packages/dendron-cli/src/commands/utils.ts, packages/engine-server/src/DendronEngineV3.ts, packages/engine-server/src/cache/dendronFileSystemCache.ts, packages/engine-server/src/drivers/file/NoteParserV2.ts, packages/engine-server/src/engineClient.ts, packages/engine-server/src/enginev2.ts, packages/engine-server/src/index.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/noteCli.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/DendronEngineV3.spec.ts, packages/engine-test-utils/src/engine.ts, packages/engine-test-utils/src/presets/engine-server/index.ts, packages/engine-test-utils/src/presets/engine-server/init.ts, packages/plugin-core/src/services/EngineAPIService.ts, packages/plugin-core/src/services/EngineAPIServiceInterface.ts
**Background**
Continuing from https://github.com/dendronhq/dendron/pull/3125, this PR will begin to slowly integrate the new store system with the dendron CLI by introducing a new command "GET" that will get a note by id. This will also involve creating a new engine to initialise and populate the new stores.
Through this change, we will be able to sanity check the init and get logic of the new store.
**Changes**
1. New GET cli command to get note by id
2. New engine, DendronEngineV3 (name to possibly change after removing old), that will implement initNotes logic and get logic
3. Introduce `findNotesMeta`. With the new stores storing notemetadata and noteprops separately, the new engine will support retrieval of either components.
4. New `NoteParserV2` (will replace current noteparser). …
=> enhance(workspace): Create new GET CLI command to use new engine/store

packages/api-server/src/modules/notes/index.ts, packages/common-all/src/api.ts, packages/common-all/src/types/typesv2.ts, packages/engine-server/src/DendronEngineV3.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/engineClient.ts, packages/plugin-core/src/services/EngineAPIService.ts, packages/plugin-core/src/services/EngineAPIServiceInterface.ts, packages/plugin-core/src/services/TextDocumentService.ts
This change fixes an issue where notes added by workspace sync were causing engine state drift.  The root cause is that the `updateNote` API doesn't return `NoteChangedEvents[]`, and we were using `updateNote` instead of `writeNote` in the file watcher `onCreate` callback.
This change adds a full `NoteChangedEvents[]` in the updateNote response.  I've intentionally not added tests for this, since we will likely modify this API surface as part of @tma66's refactoring work.
---
- General
- Operations
- Architecture
- eg: [making changes to DNode](https://github.com/dendronhq/dendron/pull/2158#pullrequestreview-85 …
=> fix(workspace): workspace sync will maintain proper engine state

packages/common-all/src/store/INoteStore.ts, packages/common-all/src/types/typesv2.ts, packages/dendron-cli/src/commands/notes.ts, packages/engine-server/src/DendronEngineV3.ts, packages/engine-server/src/enginev2.ts, packages/engine-server/src/store/NoteStore.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/noteCli.spec.ts, packages/pods-core/src/basev3.ts
**Background**
Continuing to test the new dendron store via the notes cli command, we will also introduce a new command `FIND` that will find notes based on note properties (currently only fname and vault).
**Changes**
1. New `FIND` cli command that uses new engine
2. Migrate `LOOKUP` command to use new engine
TODO: update docs after approval
=> enhance(workspace): Add new FIND notes CLI command

packages/nextjs-template/components/DendronTreeMenu.tsx
The SubMenus were closing the sidebar when clicked, but the MenuItems were not.  AntD Menu Items don't have an `onClick` handler built in to them, but their parent `Menu` component does.  So I used that to handle closing the sidebar.
I've decided to create two separate events, even though they do the same thing, but I think that verbosity is good in the long term.
I was very confused by the `changeActiveNote(noteId, { noteIndex: props.noteIndex });` call on line 82.  It made me think that there was some handler somewhere doing something like that for the `MenuItem` click, but it turns out that AFAIK line 82 was extraneous.  Both sub menus and menu items handle their navigation via the `MenuItemTitle` component's `Link` at the bottom of the file.  So I deleted that confusing line.
- NOTE: …
=> fix(views): hide sidebar when clicking a non-submenu note on mobile

packages/common-all/src/types/typesv2.ts, packages/common-frontend/src/features/ide/slice.ts, packages/dendron-plugin-views/src/components/DendronApp.tsx, packages/dendron-plugin-views/src/components/DendronGraphPanel.tsx, packages/dendron-plugin-views/src/hooks/useGraphElements.tsx, packages/engine-server/src/metadata/service.ts, packages/plugin-core/package.json, packages/plugin-core/src/constants.ts, packages/plugin-core/src/views/GraphPanel.ts, packages/plugin-core/src/workspace.ts
This PR aims to add an option to toggle hierarchical edges in the Graph Panel.
loom: https://www.loom.com/share/88c169c981244c289dde63eac2419bd1
- General
- Operations
- Architecture
- [~] can we track the performance of …
=> enhance(views): option to filter hierarchical edges from graph panel

packages/plugin-core/src/views/NativeTreeView.ts, packages/plugin-core/src/workspace/workspaceActivator.ts, yarn.lock
This PR:
- Forces a focus to the tree view panel once when the workspace is activated
- Fixes an issue where if the a note was already open, the tree view was not being focused to the active note that was open when the tree view was first turned visible
- General
- Operations
- Architecture
- [~] can we track the performance of this change …
=> fix(views): properly focus tree view to active note when it is first shown

packages/plugin-core/src/WorkspaceWatcher.ts
This PR:
- Properly ignores non-note renames that happen in the workspace when running note related workspace watcher operations.
- This is transparent to the user / not user-facing. fyi @bpathakota 
- This should clean up some not-so-useful reports from Sentry.
- General
- Operations
- Architecture …
=> chore(workspace): ignore non-note renames from workspace watcher

packages/common-all/src/types/foundation.ts, packages/common-all/src/utils/publishUtils.ts, packages/nextjs-template/components/DendronSEO.tsx
docs: 
- [[seo description should be generated from `desc` field of note if available|task.2022.07.17.seo-description-should-be-generated-from-desc-field-of-note-if-available]]
- https://github.com/dendronhq/dendron/issues/1596
=> enhance(publish): use note's `desc`field for SEO description

packages/plugin-core/src/_extension.ts, packages/plugin-core/src/test/suite-integ/CopyNoteRef.test.ts, packages/plugin-core/src/test/suite-integ/DoctorCommand.test.ts
This PR:
- Fix timeout issue on some long running tests that commonly fail during the pipeline.
- This should resolve the recent issue with the plugin test that fails for mac in CI.
=> chore(internal): fix timeout on some tests

packages/common-all/src/dnode.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-test-utils/src/presets/engine-server/write.ts, packages/plugin-core/src/test/suite-integ/RenameHeader.test.ts
**Bug**
When `engine.writeNote` is called and the id is different, the intended behavior is to delete the old note with the old id and create a new note with the new id. Currently there is a out-of-sync issue where the engine retains the old note b/c we forgot to filter out the `delete` entries from changeEntries.
=> chore(internal): Fix bug where note is not properly deleted via writeNote

packages/plugin-core/assets/dendron-ws/tutorial/treatments/quickstart-skip-welcome/tutorial.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/quickstart-v1/tutorial.md
fix(workspace): fix typos in getting started tutorial
- correct shortcut for triggering `command prompt`
- better emphasis on note names
- clarify directions
- correct shortcut for switching back to previous note
=> fix typos and enhance tutorial

packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/components/lookup/TabUtils.ts, packages/plugin-core/src/components/lookup/utils.ts
enhance(preview): open note in different editor group then preview
When opening a note by clicking a link from preview, open it in an different editor group API.
This makes use of the `Tab Groups` API that is only available in vscode `1.67`. 
Dendron currently supports vscode `1.62` which means users using versions prior to `1.67` will not have this feature enabled.
=> enhance(preview): open note in different editor group then preview

packages/engine-server/src/markdown/decorations/diagnostics.ts, packages/plugin-core/src/commands/Doctor.ts, packages/plugin-core/src/components/doctor/utils.ts, packages/plugin-core/src/components/pods/PodControls.ts, packages/plugin-core/src/dendronExtensionInterface.ts, packages/plugin-core/src/test/MockDendronExtension.ts, packages/plugin-core/src/test/suite-integ/DoctorCommand.test.ts, packages/plugin-core/src/test/suite-integ/DuplicateNote.test.ts, packages/plugin-core/src/utils/pods.ts
This PR aims to add a Fix It button in duplicate note id warning toaster. Fix It button runs the doctor regenerate note id command underneath the hood. 
This PR also increases the range of no frontmatter error from 0 to line 8.
*** 
Telemetry:
Adds a property `state: "resolved"` for an existing workspace event: `DuplicateNoteFound`
- General
- Operations
- Architecture
- eg: [making changes to DNode](https://github.com/dendronhq/dendron/pull/2158#pullrequestreview-8546895 …
=> enhance(workspace): 'Fix It' button in warning toaster for duplicate note id

packages/common-all/src/abTests.ts, packages/plugin-core/assets/dendron-ws/tutorial/treatments/quickstart-v1/tutorial.md, packages/plugin-core/src/commands/LaunchTutorialWorkspaceCommand.ts
chore: update init tutorial
- disable instant load of tutorial (we rely on workspace settings that are not being activated)
- explicitly call out how to open command prompt
=> chore: update init tutorial

packages/plugin-core/src/commands/TogglePreview.ts
Related issue: https://github.com/dendronhq/dendron/issues/3309
- General
- Operations
- Architecture
- CSS
- eg: [breaking dev change due to new dependency](https://github.com/dendronhq/dendron/pull/2188#pullrequestreview-855696330)
=> fix(views): toggle preview doesnt toggle preview off when focus is on the preview Itself

packages/plugin-core/package.json, packages/plugin-core/src/constants.ts
This PR aims to replace references of `showPreview` with `togglePreview`, this is to fix the error toaster on init and the missing preview icon in editor
=> fix(retrieve): remove references of show preview

.github/workflows/publish-extension-dendron-patch.yml, packages/plugin-core/package.json, packages/plugin-core/src/constants.ts, packages/plugin-core/src/showcase/GraphThemeTip.ts
This PR aims to
-  update graph commands key to resolve `dendron.showSchemaGraph already exists` error
- updates patch release pipeline to always raise a PR even if the above step fails
=> chore: update graph commands key

packages/common-all/src/dnode.ts, packages/common-all/src/fuse.ts, packages/common-all/src/store/INoteStore.ts, packages/common-all/src/types/store.ts, packages/common-all/src/types/typesv2.ts, packages/common-test-utils/src/noteUtils.ts, packages/dendron-cli/src/commands/notes.ts, packages/engine-server/src/DendronEngineV3.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/engineClient.ts, packages/engine-server/src/enginev2.ts, packages/engine-server/src/store/NodeJSFileStore.ts, packages/engine-server/src/store/NoteMetadataStore.ts, packages/engine-server/src/store/NoteStore.ts, packages/engine-test-utils/src/__tests__/common-all/fuse.spec.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/noteCli.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/DendronEngineV3.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/EngineEvents.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/store/noteStore.spec.ts, packages/engine-test-utils/src/presets/engine-server/delete.ts, packages/engine-test-utils/src/presets/engine-server/index.ts, packages/engine-test-utils/src/presets/engine-server/rename.ts, packages/engine-test-utils/src/presets/engine-server/write.ts, packages/nextjs-template/utils/hooks.ts, packages/plugin-core/src/services/EngineAPIService.ts, packages/plugin-core/src/services/EngineAPIServiceInterface.ts, packages/plugin-core/src/test/suite-integ/MoveNoteCommand.test.ts
**Background**
Continuing on from https://github.com/dendronhq/dendron/pull/3200, this PR updates the notes cli `DELETE` command to use the new engine.
**Changes**
1. Migrate delete/write logic from old engine to new engine
2. Add support in `NoteStore` to find notes by child (ie return parent or closest ancestor)
3. Add support in fuse engine to update notes index based on `NoteChangeEntry` entries
4. Update `NoteStore` methods to take into account stub notes. Ie if we are getting/writing a stub, skip filesystem logic
5. Migrate `DELETE` notes cli  command to new engine
6. Update delete logic for both engines. If deleting a note and replacing with a stub, create stub with new id. Previously we were keeping the same id for the stub, but in order to be consistent, all new notes should have …
=> enhance(workspace): Add delete/write logic to new engine

packages/common-all/src/dnode.ts, packages/common-all/src/types/typesv2.ts, packages/engine-server/src/DendronEngineV3.ts, packages/engine-server/src/drivers/file/NoteParserV2.ts, packages/engine-server/src/drivers/file/noteParser.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/enginev2.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-server/src/store/NoteStore.ts, packages/engine-server/src/utils/engineUtils.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/remarkUtils.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/remarkUtils.spec.ts, packages/plugin-core/src/WorkspaceWatcher.ts, packages/plugin-core/src/commands/MoveHeader.ts, packages/plugin-core/src/fileWatcher.ts, packages/plugin-core/src/services/TextDocumentService.ts, packages/plugin-core/src/test/suite-integ/WorkspaceWatcher.test.ts
**Background**
While working on the engine `rename` refactoring, I've realized that manually renaming a file outside of dendron can easily cause the engine state to drift. This is due to not properly cleaning up the note metadata of the old file
**Changes**
1. Update `renameNote` param to use `metaOnly` instead of `isEventSourceEngine`. Therefore if the change is from vscode, we will delete/write to only the note metadata store
2. Consolidate link/anchor refresh logic into one method under `EngineUtils`
3. Deprecate `getLinks` and `getAnchors` on engine. In the future, we will not need the engine to perform these actions
4. Remove `onDidRenameFiles` from watcher. Since `renameNote` handles writing the note metadata, there is no need to write the same thing again.
=> chore(workspace): Fix engine sync issue from manual rename

packages/plugin-core/package.json, packages/plugin-core/src/constants.ts
fix: windows keybindings for toggle preview
turns out the `key` settings needs to be set for the keybinding to take into effect
=> fix: windows keybindings for toggle preview

packages/common-all/src/dnode.ts, packages/plugin-core/src/components/lookup/NoteLookupProvider.ts, packages/plugin-core/src/test/suite-integ/LookupProviderV3.test.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
This PR:
- Validates the value of the quickpick of note lookup
- disallows 
- leading / trailing whitespaces in individual hierarchy string
- leading / trailing dots
- empty hierarchy string
- General
- Operations
- Architecture …
=> fix: validate file name on note lookup

packages/plugin-core/src/commands/CreateNoteWithTraitCommand.ts, packages/plugin-core/src/test/suite-integ/components/traits/CreateNoteWithTraitCommand.test.ts, packages/plugin-core/src/test/suite-integ/components/traits/TestTrait.ts
This PR aims to support cross vault template in note traits.
- General
- Operations
- Architecture
NA
NA
NA
NA
=> enhance(structure): support xvault template in note traits

packages/common-all/src/vault.ts
This PR aims to fix issues with remote vaults in windows. In windows, remote vault is not recognized and throws no vault found error while running commands like (Create Schema From Hierarchy) and does not display webviews.
related issue: https://github.com/dendronhq/dendron/issues/3301
- General
- Operations
- Architecture …
=> fix(workspace): remote vault not recognized by dendron for windows

packages/nextjs-template/components/DendronLayout.tsx, packages/nextjs-template/components/DendronNotePage.tsx, packages/nextjs-template/components/MermaidScript.tsx, packages/nextjs-template/components/layout/DendronContent.tsx, packages/nextjs-template/components/layout/DendronHeader.tsx, packages/nextjs-template/components/layout/DendronSidebar.tsx, packages/nextjs-template/context/DendronProvider.tsx, packages/nextjs-template/context/useDendronContext.tsx, packages/nextjs-template/pages/_app.tsx, packages/nextjs-template/types/window.d.ts
In addition to cleaning up DendronLayout, this also optimizes Mermaid so that it only loads the mermaid library once and only once, when a note page that has a mermaid chart is encountered.
- Track if isMobile and whether or not the sidebar is open using a useDendronContext hook.  Can add more to that state in the future.
- Split the DendronLayout component to make it easier to grok in the future.
- General
- Operations
- Architecture …
=> refactor(nextjs-template): componetize the parts of DendronLayout.tsx

packages/common-all/src/types/typesv2.ts, packages/dendron-plugin-views/src/components/DendronApp.tsx, packages/plugin-core/src/commands/TogglePreviewLock.ts, packages/plugin-core/src/components/views/PreviewPanel.ts, packages/plugin-core/src/components/views/PreviewProxy.ts, packages/plugin-core/src/test/MockPreviewProxy.ts
This PR aims to allow the user to toggle preview's lock-state from inside the preview instead from the command "Toggle Preview Lock" only.
- [[Allow Preview Lock Toggle from inside Preview|dendron://private/task.2022.07.29.allow-preview-lock-toggle-from-inside-preview]]
- https://github.com/dendronhq/dendron-site/pull/604
- General
- Operations
- Architecture
- eg: …
=> enhance(views): toggle preview lock from inside preview

packages/engine-server/src/markdown/decorations/wikilinks.ts, packages/engine-server/src/markdown/remark/noteRefsV2.ts, packages/plugin-core/src/test/suite-integ/WindowDecorations.test.ts, test-workspace/vault/dendron.ref.links.begin-end.md
This PR:
- fixes window decoration for wikilink / note references that contain the anchors `^begin` and `^end`
- General
- Operations
- Architecture
- CSS
- [~] display is correct for following dimensions
- [~] sm: screen ≥ 576px, eg. iphonex, (375x812)
- [~] lg: screen ≥ 992px
- [~] xxl: screen ≥ 1600px eg. mac (1600x900)
- [~] display is correct for following browsers (across the various …
=> fix(workspace): correctly decorate begin and end anchors

packages/common-all/src/dnode.ts, packages/common-all/src/store/ISchemaStore.ts, packages/common-all/src/store/index.ts, packages/common-all/src/types/store.ts, packages/common-server/src/filesv2.ts, packages/common-server/src/parser.ts, packages/engine-server/src/drivers/file/schemaParser.ts, packages/engine-server/src/store/NoteStore.ts, packages/engine-server/src/store/SchemaMetadataStore.ts, packages/engine-server/src/store/SchemaStore.ts, packages/engine-server/src/store/index.ts, packages/engine-test-utils/src/__tests__/engine-server/store/schemaStore.spec.ts
**Changes**
1. Create `SchemaStore` in charge of working with `SchemaModuleProps` storage layer
**Design Decisions**
1. Since we don't have anything metadata specific, I've chosen to use the same typing for both the metadata store and the non-metadata store
2. Get calls will retrieve from the metadata store. This is to align with current behavior of storing schemas in an in-memory dictionary
3. Delete/write will work with both metadata store and file system (like current behavior)
=> enhance(workspace): Add new SchemaStore

packages/plugin-core/src/web/extension.ts
Don't throw during activation of web ext - seeing if this will bypass Marketplace validation checks.
=> fix(workspace): don't throw during activation

packages/plugin-core/src/commands/GoToSiblingCommand.ts, packages/plugin-core/src/test/suite-integ/GoToSibling.test.ts
This PR fixes the bug caused when `Dendron: Go Next/Previous Sibling` command is run without an active dendron note on the editor.
issue: #3355
=> fix (navigate): check if dendron note is active

packages/plugin-core/src/commands/PublishDevCommand.ts
This PR aims to deprecate `Dendron: Publish Dev` command. The user gets a warning toaster to use Dendron CLI instead with a button to publish cook docs.
added it as a `fix` to include this in changelog
=> fix(publish): deprecate Dendron: Publish Dev command

packages/plugin-core/src/commands/SetupWorkspace.ts, packages/plugin-core/src/workspace/tutorialInitializer.ts, packages/plugin-core/src/workspace/workspaceActivator.ts
This PR:
- Fixes an issue with the workspace activation logic where the workspace initializer's `onWorkspaceActive` hook was not being properly invoked
- This fixes the issue with tutorial workspace where the tree view was not being focused after workspace activation.
- General
- Operations
- Architecture
- [~] can we track the performance …
=> fix(workspace): correctly focus tree view on tutorial activation

packages/common-server/src/StateValidator.ts, packages/engine-server/src/DendronEngineV3.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/workspace/service.ts, packages/engine-test-utils/src/__tests__/engine-server/drivers/file/schemaParser.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/store/noteStore.spec.ts, packages/plugin-core/src/commands/Refactor.ts, packages/plugin-core/src/web/test/helpers/WorkspaceHelpers.ts, packages/plugin-core/src/web/test/suite/commands/NoteLookupCmd.test.ts
This PR aims to fix an error on master and nightly `107.4` which throws error on windows.
```DendronError: Schema 'undefined' is malformed. Reason: undefined\\n    at g.createMalformedSchemaError``` : https://github.com/dendronhq/dendron/runs/7788087046?check_suite_focus=true#step:15:9
=> chore: fix init error on windows

packages/plugin-core/src/workspace/tutorialInitializer.ts
- This PR:
- Fixes a type error introduced in https://github.com/dendronhq/dendron/pull/3380
=> chore: fix type error in tutorial initializer

packages/common-assets/styles/scss/main.scss, packages/common-server/src/etc.ts, packages/dendron-plugin-views/src/components/DendronApp.tsx
This PR aims to improve the calendar view by integrating with vscode theme.
Here we make use of vscode theme editor background token and set calendar-view's background to it.
task: [[Better Compatibility with Vscode Theme|dendron://private/task.2022.07.28.better-compatibility-with-vscode-theme]]
=> enhance(views): improve vscode theme integration

packages/dendron-plugin-views/src/components/DendronNotePreview.tsx
This PR aims to remove an accidentially added semicolon into the render function of the preview view.
=> fix(views): removes semicolon in preview

.github/workflows/ci.yml, packages/engine-server/src/markdown/remark/utils.ts, packages/plugin-core/package.json, packages/plugin-core/src/commands/MergeNoteCommand.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/components/lookup/LookupProviderV3Interface.ts, packages/plugin-core/src/components/lookup/NoteLookupProvider.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/MergeNoteCommand.test.ts, test-workspace/vault/dendron.ref.merge-note.destination.md, test-workspace/vault/dendron.ref.merge-note.should-update-1.md, test-workspace/vault/dendron.ref.merge-note.source.md, yarn.lock
This PR:
- adds a new command `Dendron: Merge Note`
- enhances Lookup provider so that it can take a list of `preAcceptValidators` when it is created by the lookup provider factory.
- this will allow lookup-derivative commands (such as this one) to pass in list of a predicate functions that would be executed when the user hits enter in the quickpick.
- if any of the `preAcceptValidator` fails, lookup will not be accepted until the user selects a valid item from the quickpick
- In merge note command, this is used to prevent users from merging the active note to itself.
- General
- Operations
- Architecture
- …
=> feat(refactor): merge note command

packages/common-all/src/dnode.ts, packages/engine-test-utils/src/__tests__/common-all/dnode.spec.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
This PR:
- Correctly matches notes with namespace schema nodes
- namespace node match pattern was trimmed excessively and was not matching the node on the same depth as well as its immediate children
- Correctly apply schema when a note that existed as a stub is accepted as a new item through note lookup
- When a note is created as a stub (because of a leaf note), it bypasses any schema application.
- When this note is later accepted as a new note through lookup, this note that can potentially have a schema match does not get created with a schema applied.
1. create the following schema:
```
version: 1
imports: []
schemas:
- id: test
children: 
- testing
title: test
parent: root
- id: testing
pattern: "*"
title: "testing"
namespace: true
template:
id: template.test
type: note
```
2. …
=> fix(schema): correctly match namespace schema nodes, and correctly apply schema to new note when note existed as stub

packages/common-assets/styles/scss/content.scss
fixes: https://github.com/dendronhq/dendron/issues/3396
[[Preview Headers Link No Whitespace|dendron://private/task.2022.08.16.preview-headers-link-no-whitespace]]
=> fix(views): show whitespace for links in headers

packages/plugin-core/package.json, packages/plugin-core/src/constants.ts
This PR aims to fix a regression with duplicate `Dendron Delete` in contextual Menu. 
Source: https://discordapp.com/channels/717965437182410783/739186036495876126/1009055467982557275
NA
NA
NA
=> fix(workspace): duplicate Dendron Delete command in contextual menu

packages/plugin-core/package.json, packages/plugin-core/src/commands/CreateNoteCommand.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts
This PR aims to add a create note command. This a wrapper around `Ctrl/Cmd + L` for visibility
NA
NA
NA
=> feat(workspace): Create Note Command

packages/plugin-core/package.json, packages/plugin-core/src/constants.ts
Fixing tree view visibility in web ext + hiding some recently added commands.  I'll do an async on properly marking the 'when' clause when adding new cmds.
=> fix(workspace): proper visibility on views and commands for web ext

packages/common-all/src/abTests.ts, packages/plugin-core/assets/dendron-ws/templates/templates.daily.md, packages/plugin-core/assets/dendron-ws/templates/templates.meet.md, packages/plugin-core/src/commands/CreateDailyJournal.ts, packages/plugin-core/src/commands/CreateMeetingNoteCommand.ts, packages/plugin-core/src/test/suite-integ/CreateDailyJournalNote.test.ts
This PR:
- ends `_2022_05_DAILY_JOURNAL_TEMPLATE_TEST`
- change occurence of `dendron.templates.*` to `templates.*` to match the default configuration
- clean up template contents for meeting note and daily journal note
- General
- Operations
- Architecture
- …
=> chore: update templates for special notes

packages/dendron-cli/src/commands/notes.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/noteCli.spec.ts
**Background**
Moving forward, we would like the notes CLI to closely mirror engine notes methods. For this pr, we will introduce a `WRITE` cli command that will create a note if fname/vault doesn't exist or update body of existing note.
Options:
`fname`: Required
`vault`: Required if more than one vault exists
`body`: Not required. Defaults to ""
**How to use**
```
dendron note write --useLocalEngine --fname "mytest" --vault vault --body "this is a body"
```
**Other Changes**
1. Renamed options for `DELETE` and `MOVE` to use `fname` instead of `query`
=> enhance(cli): New write notes CLI command

packages/plugin-core/src/WorkspaceWatcher.ts, packages/plugin-core/src/commands/MoveNoteCommand.ts, packages/plugin-core/src/commands/RenameNoteCommand.ts, packages/plugin-core/src/components/doctor/utils.ts, packages/plugin-core/src/components/lookup/LookupProviderV3Interface.ts, packages/plugin-core/src/components/lookup/NoteLookupProvider.ts, packages/plugin-core/src/test/suite-integ/LookupProviderV3.test.ts, packages/plugin-core/src/test/suite-integ/MoveNoteCommand.test.ts, packages/plugin-core/src/test/suite-integ/RenameNoteCommand.test.ts
This PR:
- fixes an issue with lookup validation that blocked lookup of already existing notes with invalid names
- allows lookup of invalid name if it already exists
- prompts for a rename of that note when it opens
- General
- Operations
- Architecture
- eg: …
=> fix(lookup): allow lookup accept for existing invalid hierarchy

packages/common-all/src/util/treeUtil.ts, packages/plugin-core/src/test/suite-integ/EngineNoteProvider.test.ts, packages/plugin-core/src/web/views/treeView/EngineNoteProvider.ts
Make the sort order in tree view case insensitive. This addresses the issue both in current tree view and the upcoming web ext tree view.
related to: https://github.com/dendronhq/dendron/issues/3418
=> fix(workspace): case insensitive tree view sorting

packages/engine-server/src/drivers/SQLiteMetadataStore.ts
Currently will throw a `UNIQUE constraint error`
=> fix(workspace): sqlite store properly update from cache when encountering existing notes

packages/plugin-core/src/commands/MoveHeader.ts, packages/plugin-core/src/test/suite-integ/MoveHeader.test.ts
Related to #2238
I wasn't sure about the tests - I couldn't get the integration tests for the `MoveHeader.test.ts` to progress - it seems like it fails at an assertion that seems to take time and is repeated on the CI until it passes? Is this related to using the old testing utils?
EDIT: I noticed that the tests are failing for the plugin on the CI, I'll have to take a look at that too.
If there are any pointers on how to get this to work, I can have a go at writing a test for this. 
https://user-images.githubusercontent.com/9913851/186452753-232d5a03-a904-4f4e-b438-da1c5ed40526.mp4
- ~~[ ] if your change reflects documentation changes, also submit a PR to …
=> enhance(plugin-core): fill in current hierarchy for Move Header

packages/common-all/src/util/treeUtil.ts, packages/plugin-core/package.json, packages/plugin-core/src/commands/CreateNoteCommand.ts, packages/plugin-core/src/commands/DeleteCommand.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/DeleteCommand.test.ts, packages/plugin-core/src/test/suite-integ/NativeTreeView.test.ts, packages/plugin-core/src/views/TreeNote.ts
- This PR aims to add a context menu for tree view. Added Delete Command in tree view context menu.
- It also fixes an issue with Delete Command: If the note is not open in the text editor. it is not deleted when the command is run from the explorer menu.
- It adds a Create Note command in context menu of Tree view, the lookup bar has the initial value of tree item responsible for action.
- adds source: Tree view property for Create Note and Delete Command
- General
- …
=> enhance(view): context menu for tree view

packages/plugin-core/package.json, packages/plugin-core/src/constants.ts, packages/plugin-core/src/web/views/treeView/NativeTreeView.ts
There's an issue where the tree view on the web ext won't show any contents when you open up a repository for the first time. It'll show up if you focus on a note, and it seems that it'll remain in a good state on all subsequent times you open that repository.
I'm not sure what's the exact cause of the issue, but this change adds a mitigation: it leaves a message whenever the tree view is empty that tells the user to open a Dendron note.  
This also fixes a tangentially related issue where the tree view will focus on the active note when you toggle its visibility.
Credit to @hkievet for identifying the issue.
=> fix: tree view init problem on web

packages/pods-core/src/builtin/NextjsExportPod.ts
Related issue: https://github.com/dendronhq/dendron/issues/3426 and https://github.com/dendronhq/dendron/issues/3425
In nextjsexportpod `engine.config` has stale value and is only updated when workspace is reloaded. Updated references of engine.config with engine.getConfig which returns the latest config values
=> fix(sync): nextjs export pod to fetch latest dendron config

packages/common-all/src/drivers/string2Note.ts, packages/common-all/src/types/foundation.ts, packages/engine-server/src/drivers/file/noteParser.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/utils/engineUtils.ts
- `links` frontmatter will override implict note `links` prop, causing notes with `links` property to throw errors during startup
- no warning about notes being too long when initiliazing engine
=> fix(workspace): noisy warnings in engine startup

packages/engine-server/src/metadata/service.ts, packages/plugin-core/src/showcase/AllFeatureShowcases.ts, packages/plugin-core/src/showcase/SettingsUITip.ts
Added Settings UI tip to tip of the day
- General
- Operations
- Architecture
- [~] …
=> enhance(view): added settings UI tip

packages/engine-server/src/workspace/service.ts, packages/plugin-core/src/test/suite-integ/MigrateSelfContainedVault.test.ts
Related issue: https://github.com/dendronhq/dendron/issues/3466
When a regular vault is migrated to a self-contained vault using the `Migrate to Self Contained Vault` command, the folder structure of a self-contained vault is incorrect. The testcases were all passing because of missing await in expect(so expect condition always returns true for `verifyVaultHasMigrated`). Below is the buggy folder structure.
```
workspace
|_______vaultx
|______ notes
| _____notes
|            |____assets folder
|            |____root.md
|            |_____root.schema.yml
|
|_____dendron.yml
|_____dendron.code.workspace
```
The below solution updates the wsRoot for vault migration from `wsRoot/vaultx/notes` to `wsRoot/vault`. This would prevent adding `dendron.yml` and `dendron.code-workspace` inside notes …
=> fix(workspace): migrate self contained vaults command does not migrate the vault correctly 

packages/common-all/src/util/treeUtil.ts, packages/plugin-core/src/web/views/treeView/EngineNoteProvider.ts
In case a title is missing from NoteProps metadata, the sort order logic won't crash.
=> fix(workspace): tree view still displays if a note has no title

packages/common-all/data/dendron-yml.validator.json, packages/common-all/src/constants/configs/workspace.ts, packages/common-all/src/types/configs/workspace/workspace.ts, packages/common-all/src/utils/index.ts, packages/dendron-plugin-views/src/utils/dendronConfig.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/noteRefv2.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/noteRefv2.spec.ts, packages/plugin-core/src/commands/CopyNoteRef.ts, packages/plugin-core/src/test/suite-integ/CopyNoteRef.test.ts, packages/plugin-core/src/test/utils/workspace.ts, packages/unified/src/remark/noteRefsV2.ts, test-workspace/dendron.yml
This PR aims to remove `enableSmartRefs` config from `workspace` scope.
- General
- Operations
- Architecture
NA
- [~] if your change reflects documentation changes, also submit …
=> chore: remove enableSmartRefs config

packages/common-all/src/constants/lookup.ts, packages/common-all/src/dnode.ts, packages/dendron-cli/src/commands/base.ts, packages/dendron-cli/src/commands/doctor.ts, packages/engine-server/src/doctor/service.ts, packages/engine-test-utils/src/__tests__/common-all/util/noteUtils.spec.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/doctor.spec.ts, packages/plugin-core/src/commands/Doctor.ts, packages/plugin-core/src/components/doctor/utils.ts, packages/plugin-core/src/components/lookup/LookupProviderV3Interface.ts, packages/plugin-core/src/components/lookup/NoteLookupProvider.ts, packages/plugin-core/src/test/suite-integ/DoctorCommand.test.ts, packages/plugin-core/src/test/suite-integ/LookupProviderV3.test.ts
This PR:
- Extends the file name validation logic to capture illegal SQLite characters.
- Enhance warning / error messages to be more specific about what is invalid.
- Add doctor action `fixInvalidFileNames` on cli and extension
- 
- General
- Operations
- Architecture
- [~] If you are adding a new language feature (graphically visible in VS Code/preview/publishing), an example is included in the …
=> chore(workspace): validate filename that are illegal in SQLite

packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/hierarchies.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/dendronPub.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/v5/__snapshots__/hierarchies.spec.ts.snap, packages/unified/src/remark/dendronPub.ts
This PR:
- fixes issue with markdown links (e.g. `[some pdf](assets/dummy-pdf.pdf)`) to be corrected properly if asset prefix is given during publishing. (+ add forward slash if missing)
- General
- Operations
- Architecture
- [~] if you are adding analytics related changes, make sure the [Telemetry](https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html) docs are …
=> fix(publish): correctly handle asset prefix in markdown link

packages/engine-server/src/migrations/utils.ts
This PR:
- adds `workspace.enableSmartRefs` to `DEPRECATED_PATHS` so they could be properly cleaned up at upgrade.
=> chore(internal): add `workspace.enableSmartRefs` to `DEPRECATED_PATHS`

packages/common-frontend/src/components/DendronNote.tsx, packages/dendron-plugin-views/src/components/DendronNotePreview.tsx, packages/dendron-plugin-views/src/hooks/index.tsx
Fixes mermaid diagrams in preview.  Note: this change causes mermaid to always be enabled, and no longer observes the `enableMermaid` setting. I don't think this should be a problem though, given the recent change to lazy load mermaid only when it's necessary.  Let me know if you think otherwise. 
TODO: Remove the `enableMermaid` setting.
=> fix(views): fix mermaid diagrams

dendron-main.code-workspace, docs/dendron.yml, packages/api-server/src/modules/schemas/index.ts, packages/common-all/src/api.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/engineClient.ts, packages/engine-server/src/enginev2.ts, packages/plugin-core/.vscode/launch.json, packages/plugin-core/src/WSUtilsV2.ts, packages/plugin-core/src/WSUtilsV2Interface.ts, packages/plugin-core/src/services/EngineAPIService.ts, packages/plugin-core/src/services/SchemaSyncService.ts, packages/plugin-core/src/services/SchemaSyncServiceInterface.ts, packages/plugin-core/src/test/suite-integ/SchemaSyncService.test.ts
fix(schema): schemas being overwritten on save 
Inline schemas ([[dendron://dendron.dendron-site/dendron.topic.schema#inline-schema-anatomy]]) are stored as a flat dictionary when saved in dendron - this representation is in memory and should not be persisted back to disk. The recent engine refactoring changed this behavior by writing these changes to disk
This change also cleans up olds tests in our workspace by removing un-used launch tests and excluding un-used assets from search.
=> fix(schema): schemas being overwritten on save 

dendron-main.code-workspace, packages/nextjs-template/.dockerignore, packages/nextjs-template/.gitignore, packages/nextjs-template/next.config.js, packages/nextjs-template/utils/build.ts
chore: make Nextjs build more customizable
Some changes to make it possible to use a single instance of the `nextjs-template` to build any number of sites. Before this change, nextjs will build everything in the directory as `nextjs-template`. 
- BUILD_DIR: where nextjs compiles the output
- DATA_DIR: where notes data can be found
- PUBLIC_DIR: where the public dir can be found
Details of how these will be used for managed publishing in [[dendron://private/pkg.worker-buildv2.lifecycle.build]]
=> chore: make Nextjs build more customizable

packages/common-all/src/utils/index.ts, packages/plugin-core/src/utils/ExtensionUtils.ts
This PR:
- adds `configVersion` as prop of `InitializeWorkspace`
- General
- Operations
- Architecture
- [~] If your tests changes an existing snapshot, snapshots have been [updated](dev.process.qa.test)
- [~] If you are adding a new language feature (graphically visible in VS Code/preview/publishing), …
=> chore(internal): add configVersion on InitializeWorkspace event

packages/engine-server/src/metadata/service.ts, packages/plugin-core/package.json, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/CreateScratchNoteCommand.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/showcase/AllFeatureShowcases.ts, packages/plugin-core/src/showcase/CreateScratchNoteKeybindingTip.ts, packages/plugin-core/src/utils/ExtensionUtils.ts
This PR:
- Changes default keybinding for `Create Scratch Note` from `shift+cmd/ctrl+s` to `cmd/ctrl+k s`
- Add a temporary feature toast during startup to notify the change, and a fail-safe backup toast in the command itself
- This is only shown once ever, and will be tracked with `FeatureShowcaseDisplayed`
- General
- Operations
- Architecture
- [~] if you are adding analytics …
=> chore(workspace): Change default keybinding for Create Scratch Note

packages/plugin-core/src/web/commands/lookup/LookupQuickpickFactory.ts
This PR aims to fix the lookbar bar initial value for codespaces(windows)
Bug:
=> fix(workspace): initial value incorrect in lookup for webext(win)

dendron-main.code-workspace
This PR:
- Adds an omitted comma in `dendron-main.code-workspace`
=> chore(internal): fix typo in dendron-main.code-workspace

packages/plugin-core/package.json, packages/plugin-core/src/constants.ts, packages/plugin-core/src/web/extension.ts, packages/plugin-core/src/workspace/workspaceActivator.ts
This PR aims to add a Create Note button in tree view. 
- Docs PR: https://github.com/dendronhq/dendron-site/pull/649
- Loom video: https://www.loom.com/share/5975b56f2dfb4e0d9615e9a507f2f56e
- General
- Operations
- Architecture
- [~] if you are adding analytics related changes, make sure the [Telemetry](https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35 …
=> feat(views): create note button in tree view

packages/common-all/src/analytics.ts, packages/common-all/src/utils/index.ts, packages/engine-test-utils/src/__tests__/engine-server/configUtils.spec.ts, packages/plugin-core/src/utils/ExtensionUtils.ts, yarn.lock
This PR:
- Adds new properties `dendronConfigChanged` and and `changedDendronConfigs`, which tracks configs that deviated from the default configuration defined
- General
- Operations
- Architecture
- [~] If you are adding a new language feature (graphically visible in VS Code/preview/publishing), an example is included in the [test workspace](dev.ref.test-workspace)
- CSS
- [~] display is correct …
=> chore(internal): track config diff during startup

packages/plugin-core/src/commands/MoveHeader.ts, packages/pods-core/src/builtin/HTMLPod.ts, packages/pods-core/src/builtin/MarkdownPod.ts, packages/pods-core/src/v2/pods/export/MarkdownExportPodV2.ts, packages/unified/src/decorations/hashTags.ts, packages/unified/src/decorations/references.ts, packages/unified/src/decorations/userTags.ts, packages/unified/src/decorations/wikilinks.ts, packages/unified/src/utilities/getParsingDependencyDicts.ts
Fixing a few regressions from the unified refactoring:
- wikilinks (and hashtags / user tags) were showing up as broken links (yellow in color). 
- a few fixes in export pod logic.
- some small additional cleanup
=> fix(workspace): wikilinks appear broken + pod fixes

packages/nextjs-template/components/DendronTreeMenu.tsx, packages/nextjs-template/utils/hooks.ts
This PR aim is to make clicks into the "empty area" of sidebar submenuitems not do nothing and rather to something.
The something could be expanding the submenuitem or opening the page. I decided for expanding since that is the default behavior of the antd Menu component. I think it makes sense to expect/intiut that the user wants to expand the submenu when he has not clicked directly on the link text.
Context: [[dendron://private/task.2022.08.21.nav-bar-should-navigate-when-menu-is-clicked]]
Demostration of the issue: https://www.loom.com/share/4998f4d983e94ee8b2ecb55a3550a6ec
Demostration of the fix: https://www.loom.com/share/266547466558423ba20b9b775cbcf405
If you are a community contributor, copy and paste the PR template from [Dendron Community PR …
=> fix: click into "empty area" on sidebar submenuitem

packages/engine-server/src/topics/site.ts, packages/nextjs-template/components/DendronNotePage.tsx, packages/pods-core/src/builtin/NextjsExportPod.ts, packages/unified/src/SiteUtils.ts, packages/unified/src/remark/noteRefsV2.ts
Fixing a few issues in Next JS Export and the playwright test pass:
- adding back 'handleDup' logic in publishing
- adding a missing `wsRoot` parameter in NextJS Export Pod
- Fixing a compile warning/error in `DendronNotePage.tsx`
=> fix(sync): next js export pod error

packages/engine-test-utils/src/__tests__/engine-server/markdown/dendronPub.spec.ts, packages/unified/src/remark/dendronPub.ts
Fixing a subtle regression introduced with https://github.com/dendronhq/dendron/pull/3497. Markdown links that point to a header on the same page now work again in Dendron Preview.
=> fix(markdown): same page header links

packages/common-server/src/etc.ts, packages/dendron-plugin-views/src/components/DendronApp.tsx
The aim of this PR is to fix [inconsistent background colors](https://github.com/dendronhq/dendron/issues/3453) when using the `preview.theme` setting.
The issue was introduced in 6fad4f05fc (my change) and basically reverts it.
The commit message expands on the reasons.
=> fix(views): make preview theme background color render correctly

packages/common-all/src/BacklinkUtils.ts, packages/common-all/src/DLinkUtils.ts, packages/common-all/src/dnode.ts, packages/common-all/src/engine/EngineV3Base.ts, packages/common-all/src/index.ts, packages/common-all/src/noteDictsUtils.ts, packages/engine-server/src/DendronEngineV3.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/enginev2.ts, packages/engine-test-utils/src/presets/engine-server/delete.ts, packages/engine-test-utils/src/presets/engine-server/rename.ts, packages/engine-test-utils/src/presets/engine-server/write.ts, packages/plugin-core/src/commands/RenameHeader.ts, packages/plugin-core/src/test/suite-integ/CopyNoteLink.test.ts, packages/plugin-core/src/test/suite-integ/MergeNoteCommand.test.ts, packages/plugin-core/src/test/suite-integ/RenameNoteCommand.test.ts, packages/plugin-core/src/test/suite-integ/RenameProvider.test.ts, packages/plugin-core/src/web/engine/DendronEngineV3Web.ts, packages/unified/src/remark/utils.ts
**Background**
Currently we do not update backlinks when a note is created/updated/deleted. This pr fills in that gap by computing the diff of links between the old and new note. This will be implemented for both the engine v3 and v2.
**Changes**
1. For a newly created note, scan through its links and create backlink if applicable
2. For a deleted note,  scan through its links and delete backlink if applicable
3. For updated note, calculate diff and add/remove backlinks
4. Created new `BacklinkUtils` to handle basic backlink methods. `LinkUtils` is intertwined with many other services so I wanted to keep it separate
=> fix(workspace): Update backlinks after engine updates

packages/plugin-core/src/commands/GotoNote.ts, packages/plugin-core/src/features/ReferenceHoverProvider.ts, packages/plugin-core/src/test/suite-integ/GotoNote.test.ts, packages/plugin-core/src/test/suite-integ/ReferenceHoverProvider.test.ts
This PR:
- disallows note creation through go to note if the filename at reference position is invalid
- an error toast will be displayed
- show warning on hover when filename at reference position is invalid
hover:
toast:
- General
- Operations
- Architecture …
=> fix(workspace): Disallow note creation through go to note if filename is invalid

packages/nextjs-template/package-lock.json, packages/nextjs-template/package.json, yarn.lock
This PR aims to revert a change from https://github.com/dendronhq/dendron/pull/3533 which is downgrading `@types/react`.
The cause of if it basically a missmatch between `antd` still depending on an older version.
This commit adds also missing `yarn.lock` changes that came in through upgrading `next` version in the above mentioned PR.
To copy the template, click on the `Raw` button on the gist to copy the plaintext …
=> chore: fix typescript error in nextjs-template

packages/common-all/src/dnode.ts, packages/common-all/src/utils/lookup.ts, packages/dendron-plugin-views/src/hooks/useGraphElements.tsx, packages/nextjs-template/.gitignore, packages/nextjs-template/components/DendronNotePage.tsx, packages/nextjs-template/components/DendronSearch.tsx
Fixing a few build errors related to refactoring changes:
- useGraphElements.tsx build error 
- type error in `DendronNotePage.tsx`
- Adding back `fetchRootResults` and its dependencies (@tma66 it's still needed in published site)
If you also include @namjul 's change here https://github.com/dendronhq/dendron/pull/3561, then the playwright tests will pass now.
=> chore: fixing useGraphElements.tsx build error

packages/common-all/data/dendron-yml.validator.json, packages/common-all/src/constants/configs/publishing.ts, packages/common-all/src/dnode.ts, packages/common-all/src/types/configs/publishing/publishing.ts, packages/common-all/src/utils/index.ts, packages/common-all/src/utils/lookup.ts, packages/dendron-plugin-views/src/utils/dendronConfig.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/nextjs-template/components/DendronSearch.tsx, packages/plugin-core/src/test/utils/workspace.ts
This PR aims to make search as default mode in a published site. It also adds a config option `searchDefaultBehavior` which can take two values: either `search` or `lookup`.  Added back the `fetchRootResults` in `NoteLookupUtils`. This is still needed in nextjs-template
```yml
publishing:
searchDefaultBehavior: "search|lookup"
```
- if set to `lookup`, default lookup, add a `?` to toggle search
- if set to `search`, default search, add a `/` to toggle lookup
- General
- …
=> enhance(publish): make search mode as default for search bar in published site

packages/plugin-core/package.json, packages/plugin-core/src/ExtensionProvider.ts, packages/plugin-core/src/KeybindingUtils.ts, packages/plugin-core/src/commands/CopyAsCommand.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/commands/pods/ExportPodV2Command.ts, packages/plugin-core/src/commands/pods/JSONExportPodCommand.ts, packages/plugin-core/src/commands/pods/MarkdownExportPodCommand.ts, packages/plugin-core/src/components/pods/PodCommandFactory.ts, packages/plugin-core/src/components/pods/PodControls.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/CopyAsCommand.test.ts, packages/pods-core/src/index.ts
This PR aims to add a Copy As command. It is similar to Export pod command, with a predefined config. 
Presently it supports two formats: JSON and markdown. The formatted note is copied to the clipboard.
- Task: [[Copy as Command|dendron://private/task.2022.07.31.copy-as-command]]
- Docs: https://github.com/dendronhq/dendron-site/pull/655
TODO: copy as for a selection in note body
- General
- Operations
- Architecture
- [~] check if code is introducing changes on a …
=> feat(workspace): copy as command

packages/nextjs-template/pages/_app.tsx
This Pr aims to fix the issue with rendering favicon when assetsPrefix is set
- General
- Operations
- Architecture
- …
=> fix: render favicon when assetsPrefix is set

packages/engine-server/src/drivers/file/storev2.ts, packages/unified/src/remark/utils.ts
Fixing a regression caused by https://github.com/dendronhq/dendron/pull/3482. 
Note candidates were doing an API call for each word in each note. This change reverts the logic to use a local note dictionary set, but with the restriction that this is only used within engine initialization.
=> fix(workspace): engine init with note candidates enabled

packages/common-all/src/dnode.ts, packages/plugin-core/src/commands/CreateDailyJournal.ts, packages/plugin-core/src/commands/CreateMeetingNoteCommand.ts, packages/plugin-core/src/commands/Goto.ts, packages/plugin-core/src/commands/GotoNote.ts, packages/plugin-core/src/commands/MoveHeader.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/components/views/PreviewLinkHandler.ts, packages/plugin-core/src/features/DefinitionProvider.ts, packages/plugin-core/src/features/ReferenceHoverProvider.ts, packages/plugin-core/src/features/completionProvider.ts, packages/plugin-core/src/test/suite-integ/CompletionProvider.test.ts, packages/plugin-core/src/test/suite-integ/ReloadIndex.test.ts, packages/plugin-core/src/utils/md.ts, packages/plugin-core/src/views/CalendarView.ts, packages/plugin-core/src/views/GraphPanel.ts, packages/plugin-core/src/web/views/preview/PreviewLinkHandler.ts, packages/pods-core/src/builtin/AirtablePod.ts, packages/pods-core/src/v2/pods/export/AirtableExportPodV2.ts, packages/unified/src/SiteUtils.ts
Similar to https://github.com/dendronhq/dendron/pull/3581, except this PR migrates the `getNotesByFnameFromEngine`
=> chore(workspace): Migrate getNotesByFname to engine methods

packages/common-all/src/analytics.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/utils/StartupUtils.ts
This PR aims to add a check to see if localhost is available at the time of Dendron init. Incase of blocked localhost, we send a warning toaster reporting the same with a link to see [troubleshooting docs](https://wiki.dendron.so/notes/a6c03f9b-8959-4d67-8394-4d204ab69bfe/#whitelisting-localhost).
- Task: [[show error message when localhost is blocked|task.2022.09.13.show-error-message-when-localhost-is-blocked]]
- General
- Operations
- Architecture
- [~] check if code …
=> chore: add telemetry and inform if localhost is blocked

packages/engine-server/src/seed/service.ts, packages/engine-server/src/workspace/service.ts, packages/plugin-core/src/test/suite-integ/VaultAddCommand.test.ts, packages/plugin-core/src/test/suite-integ/VaultRemoveCommand.test.ts
This PR:
- fixes an issue with vault add / remove where overridden vaults in `dendronrc.yml` are merged back into `dendron.yml` when a new vault is create, or an existing vault is deleted.
- NOTE: Ideally this should be done without WorkspaceService having the knowledge pertaining to local config override, but that is left as a future task as it seems our strategy towards handling config with the recent engine v3 migration seems to be unclear at the moment. This PR strictly tackles the issue reported in #3290 
- General
- Operations
- Architecture …
=> fix: correctly update dendron.yml when adding / deleting vaults

packages/engine-test-utils/src/__tests__/engine-server/markdown/hashtag.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/userTags.spec.ts, packages/plugin-core/src/_extension.ts, packages/unified/src/remark/hashtag.ts, packages/unified/src/remark/userTags.ts
This PR aims to fix the ongoing issue with usertags and hashtags autocomplete after first `.` (eg: #kind. , @johndoe. won't show autocomplete suggestions)
- removed `#` from `MARKDOWN_WORD_PATTERN` to display autocomplete for tags
- General
- Operations
- Architecture …
=> fix(workspace): autocomplete for usertags and hashtags

packages/nextjs-template/components/DendronNotePage.tsx
We accidentally removed `offsetTop` at some point which is responsible for keeping `DendronTOC` below the header.
This PR adds this prop back.
Preview of the issue: https://www.loom.com/share/caf8f308ed20469a808c2ebc77e29597
=> fix(publish): prevent "Table of content" overflowing container

packages/dendron-cli/src/commands/exportPodV2.ts, packages/plugin-core/src/commands/CopyAsCommand.ts, packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/components/pods/PodControls.ts, packages/plugin-core/src/test/suite-integ/components/pods/BaseExportPodCommand.test.ts, packages/pods-core/src/v2/podConfig/PodV2Types.ts
This PR aims to support selection scope while exporting a note with export pod v2. This also benefits the `Copy As` command. 
- General
- Operations
- Architecture
- [~] can we track the performance …
=> enhance(sync): selection export scope for pods v2

packages/plugin-core/src/features/DefinitionProvider.ts
This PR aims to fix the issue with `Go to Definition` not working correctly when used on wikilinks with header.
- [bug](https://www.loom.com/share/00570ddc70244549a6c1748e4d91dce5)
- task: [[dendron://private/task.2022.10.02.go-to-definition-doesnt-work-inside-the-same-header-on-newly-created-notes]]
The Reference Hover provider creates a new note with same name but id with prefix `fake-` to render hover. This PR aims to filter those references in definition provider
=> fix(workspace): go to definition for wikilink with header

packages/common-all/src/types/configs/publishing/publishing.ts, packages/common-all/src/utils/index.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/nextjs-template/components/DendronSearch.tsx
This PR aims to set searchMode config to `search` for new users and  the value `lookup` for  existing dendron users that have published site.
- General
- Operations
- Architecture
- eg: [see usage for …
=> chore: update default for searchMode config for new and existing users

packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/enginev2.spec.ts.snap, packages/engine-test-utils/src/presets/engine-server/render.ts, packages/unified/src/utilities/getParsingDependencyDicts.ts
fix(preview): task notes inside of note references should render correctly #3640 
This is related to https://github.com/dendronhq/dendron/issues/3578
=> fix(preview): task notes inside of note references should render correctly

packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
This PR:
- fixes an issue where `Create Note with Template` will create an empty note even when no template is selected.
- also fixes an issue where the an empty note was assumed as a template when the user hits enter while the template selector quickpick showed no select-able items.
- this was caused because note lookup provider will assume "Create New" as a selection when `selectedItems` is an empty list.
- General
- Operations
- Architecture …
=> fix(lookup): cancel note creation during "Create Note with Template" if template was not selected

package.json, packages/dendron-viz/package.json, yarn.lock
When running `npm install dendron-cli`, there are 8 high security vulnerabilities, which is highly visible to end users as they are trying to install the CLI.  This change attempts to remove those vulnerabilities by using [yarn resolutions](https://yarnpkg.com/configuration/manifest#resolutions)
=> chore: removing vulnerabilities from cli

packages/common-all/src/dnode.ts, packages/engine-test-utils/src/__tests__/common-all/util/noteUtils.spec.ts, packages/unified/src/decorations/frontmatter.ts, packages/unified/src/decorations/hashTags.ts, packages/unified/src/remark/dendronPub.ts
Related issue: https://github.com/dendronhq/dendron/issues/3605
This PR aims to fix the issue with Dendron not recognizing color code set at the frontmatter.
Previously, the NoteUtils's color method looked up the ancestors of fname provided and returned configured/generated color.
With this fix, we provide note to render(one with the frontmatter) to color method and it returns the generated/configured color accordingly.
=> fix(workspace): custom color decoration for hashtags

package.json, packages/nextjs-template/.gitignore, packages/nextjs-template/components/DendronSearch.tsx, packages/nextjs-template/components/DendronTreeMenu.tsx, packages/nextjs-template/components/MermaidScript.tsx, packages/nextjs-template/env/client.js, packages/nextjs-template/hooks/useIFrameHeightAdjuster.tsx, packages/nextjs-template/hooks/useToggle.tsx, packages/nextjs-template/next-env.d.ts, packages/nextjs-template/pages/notes/[id].tsx, packages/nextjs-template/pages/refs/[id].tsx, packages/nextjs-template/tsconfig.build.json, packages/nextjs-template/tsconfig.json, packages/nextjs-template/utils/getStaticPropsUtil.tsx
This PR's aim is to fix an error that occurs while [building nextjs-template](https://github.com/dendronhq/dendron/actions/runs/3201841712/jobs/5230211157#step:10:27).
These changes where missed when doing https://github.com/dendronhq/dendron/pull/3630
In addition this PR does a cleanup in `nextjs-template` so that it is possible to let it run through `run lerna:typecheck`.
=> fix(internal): correct reading of error tack

packages/plugin-core/src/WorkspaceWatcher.ts, packages/plugin-core/src/test/suite-integ/WorkspaceWatcher.test.ts
Reverted onWillSaveNote method to be sync. This adds back the deprecated `getNoteByFnameFromEngine` reference in `onWillSaveNote` method
=> chore: revert onWillSave method to be sync

package.json
Quick fix to add an overrides field for packages with vulnerabilities. This is in addition to the 'resolutions' field which was previously added, but 'resolutions' is only recognized by yarn and not npm. 
This is an attempted fix at the vulnerabilities warning in dendron-cli.
=> fix: npm overrides for packages with vulnerabilities

packages/common-all/src/analytics.ts, packages/engine-server/src/workspace/service.ts, packages/engine-test-utils/src/__tests__/engine-server/topics/git.spec.ts, packages/plugin-core/src/test/suite-integ/workspaceActivator.test.ts, packages/plugin-core/src/workspace/workspaceActivator.ts
This PR:
- adds a new event `GitEvents.TopLevelRepoFound`, which tracks the hash of the remote url if the workspace has a top level remote repo.
- For remotely tracked self contained vault and workspace vault, this would be the repo at wsRoot.
- If a repo is not found in wsRoot, either it is not tracked remotely, or in the case of a workspace, individual vaults may be tracked by not the workspace itself. We don't count this as a "top repo" as it is ambiguous. 
- General
- Operations
- Architecture
- eg: …
=> chore(internal): track remote information on init

.github/workflows/publish-extension-nightly.yml
Noticed after forking dendron that I was getting a github actions error message once per evening about a failing publish job.
- Fixes https://github.com/dendronhq/dendron/issues/3674
N/A, doesn't modify application code . 
- Credit for the fix comes from https://github.com/prisma/prisma/issues/3539#issuecomment-690260573
=> chore(build): disable nightly workflow in forks

.github/workflows/ci-windows-test.yml, .github/workflows/ci.yml, .github/workflows/create-early-seed-branch.yml, .github/workflows/create-release-branch.yml, .github/workflows/create-release-image-patch.yml, .github/workflows/create-release-image.yml, .github/workflows/hackathon-create-test-image.yml, .github/workflows/proto.yml, .github/workflows/publish-extension-dendron-minor.yml, .github/workflows/publish-extension-dendron-patch.yml, .github/workflows/publish-extension-nightly.yml
A few updates to our github workflows:
- Create Release Branch now runs on Wednesdays 7pm UTC every other week
- Removing AWS upload steps which were failing from an auth issue
- Updating actions to use v3 to get rid of node 12 warnings, which are getting deprecated in Github Actions.
=> chore: workflow update for 2 week release cycle and cleanup

packages/nextjs-template/hooks/useDendronConfig.ts, packages/nextjs-template/utils/useFuse.ts
The aim of this PR is to fix a regression that came in from https://github.com/dendronhq/dendron/pull/3684.
In that PR I had a false assumption, which was that the dendron config will have been loaded initially to the redux store and therefore thought its safe to add the `assertUnreachable` throw. I made the mistake and did not check for runtime errors locally.
This was not caught inside our CI because we currently do not check for runtime errors.
This PR fixes that by removing it.
NOTE: In the newer 8.x version of `react-redux` there exists a new prop for the `Provider`. [`serverState`](https://react-redux.js.org/api/provider#props) is its name and we could use that to provide the initial dendron config in `packages/nextjs-template/pages/_app.tsx:61:1`. This way we can work based on the …
=> fix(publish): runtime error on undefined dendron config

packages/engine-server/src/drivers/file/NoteParserV2.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/blockAnchors.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/extendedImage.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/footnotes.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/hashtag.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/userTags.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/wikiLink.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/utils.ts, packages/engine-test-utils/src/engine.ts, packages/plugin-core/src/WorkspaceWatcher.ts, packages/plugin-core/src/test/suite-integ/DoctorCommand.test.ts, packages/plugin-core/src/test/suite-integ/WindowDecorations.test.ts, packages/plugin-core/src/test/suite-integ/WorkspaceWatcher.test.ts
This PR focuses on updating tests to use engine v3. This will be the last pr before switching to v3 in client code
**Other changes**
1. Update snapshot files after fixing tests. Previous snapshots did not include the children of root in the html
2. During the `onWillSave` event, when we update the `updated` timestamp, we technically do not need to write to the engine. This is because we already write to the engine from the `onDidSave` event. This saves us an extra write call everytime a workspace edit is made
=> chore(tests): Switch engine tests to use engine v3

packages/api-server/src/modules/workspace/index.ts, packages/common-all/data/dendron-yml.validator.json, packages/common-all/src/constants/configs/dev.ts, packages/common-all/src/types/configs/dev/DendronDevConfig.ts, packages/dendron-plugin-views/src/utils/dendronConfig.ts, test-workspace/dendron.yml
This change adds a new config`enableEngineV3` to use engine v3 if enabled. If false or not set, use the default engine v2.
Enabled for test-workspace
=> enhance(workspace): Create enableEngineV3 dev config

packages/common-all/src/abTests.ts, packages/plugin-core/src/components/lookup/NotePickerUtils.ts
This PR:
- removes ab test defined to test effectiveness of quickpick label highlight
- this also correctly adds the quickpick label highlight
- General
- Operations
- Architecture …
=> fix: correctly add quickpick label highlight functionality

packages/nextjs-template/hooks/useIFrameHeightAdjuster.tsx
This PR aims to fix a same-origin error.
It was reported here: https://discord.com/channels/717965437182410783/735365126227493004/1033370857789210634
Sometimes browser extensions embed iframes. In this case `updateIFrameHeight`
is trying to access iframes which could possibly throw a same-origin policy (`SecurityError: Permission denied to access property "document" on cross-origin object`).
The solution is to add a check that makes sure the iframe accessible.
If you are a team member, copy and paste the template from [Dendron Extended PR …
=> fix(publish): make safe access to iframe

packages/nextjs-template/e2e/general.spec.ts, packages/unified/src/utilities/getParsingDependencyDicts.ts
The aim of this PR is to fix https://github.com/dendronhq/dendron/issues/3701
Additionally a temporarily disabled e2e test-case is enabled again.
=> fix(scope?): correct hashtag parsing by using relevant property

Makefile, packages/common-all/src/constants/configs/dev.ts, packages/common-all/src/types/configs/dev/DendronDevConfig.ts, packages/common-all/src/types/editor.ts, packages/common-all/src/util/index.ts, packages/common-all/src/utils/index.ts, packages/dendron-cli/src/commands/devCLICommand.ts, packages/plugin-core/src/ExtensionProvider.ts, packages/plugin-core/src/dendronExtensionInterface.ts, packages/plugin-core/src/features/NoteRefComment.ts, packages/plugin-core/src/features/ReferenceHoverProvider.ts, packages/plugin-core/src/features/windowDecorations.ts, packages/plugin-core/src/test/MockDendronExtension.ts, packages/plugin-core/src/test/suite-integ/WindowDecorations.test.ts, packages/plugin-core/src/windowWatcher.ts, packages/plugin-core/src/workspace.ts, packages/unified/src/decorations/decorations.ts, packages/unified/src/decorations/references.ts, packages/unified/src/decorations/wikilinks.ts, packages/unified/src/remark/dendronPreview.ts, packages/unified/src/remark/dendronPub.ts, packages/unified/src/remark/index.ts, packages/unified/src/remark/noteRefsV2.ts, test-workspace/dendron.yml
enhance: experimental inline note references
Renders note references inline as comments that display HTML. This makes it possible to use Dendron note references without using the preview
See loom for example: https://www.loom.com/share/458300e3a66f4753aa5cb1875bf4cd60?from_recorder=1&focus_title=1
---
This PR also addresses some other issues (aka scope creep):
- enhance(preview): slight update on hover preview behavior: don't render note title (it takes up a lot of vertical space and is not necessary since your hovering over the note)
- enhance(workspace): perf improvement when shifting focus to non-file panels. window watcher will currently call `updateDecorator` and `refreshBacklinks` on **all** editors (eg. terminal, output pane, etc) 
- fix(commands): urls were broken in hover
- …
=> enhance: experimental inline note references

packages/plugin-core/src/commands/GotoNote.ts, packages/plugin-core/src/test/suite-integ/GotoNote.test.ts
This PR aims to fix the duplicate entries in vault prompt while running `Go To Note` command. The Reference Hover provider creates a new note with same name but id with prefix fake- to render hover. This PR aims to filter those references in gotonote command
- General
- Operations
- Architecture …
=> fix(workspace): remove duplicate entries in prompt to select vault with go to note command

.github/workflows/ci.yml, .github/workflows/create-early-seed-branch.yml, .github/workflows/create-release-branch.yml
- Makes the create branch workflows run every Wednesday. For Github Actions, the attempted syntax of '0 19 8-14,22-28 * 3' will actually run as a OR union instead of an AND, resulting in the job running every day 8-14, 22-28 of the month.  If we just run the job every week, we'll get our intended effect, as the alternating weeks will result in the job failing b/c the branch already exists.
- Makes ci.yml be able to be triggered manually; a few times here and there ci.yml doesn't trigger automatically for some reason.
=> chore: workflow tweaks

packages/common-all/src/vault.ts, packages/plugin-core/package.json, packages/plugin-core/src/commands/AddExistingVaultCommand.ts, packages/plugin-core/src/commands/ConvertVaultCommand.ts, packages/plugin-core/src/commands/CreateNewVaultCommand.ts, packages/plugin-core/src/commands/RemoveVaultCommand.ts, packages/plugin-core/src/commands/VaultAddCommand.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/AddExistingVaultCommand.test.ts, packages/plugin-core/src/test/suite-integ/ConvertVaultCommand.test.ts, packages/plugin-core/src/test/suite-integ/CreateNewVaultCommand.test.ts, packages/plugin-core/src/test/suite-integ/RemoveVaultCommand.test.ts, packages/plugin-core/src/test/suite-integ/WorkspaceWatcher.test.ts
This PR aims to 
- fix an windows path issue: https://github.com/dendronhq/dendron/issues/3648
- Adds a new `Create New Vault command`
- Adds a new `Add Existing Vault command`
- Adds a deprecation toaster for `Vault Add` command
- Updates `Vault Remove, Vault Convert` command to have {Verb} {noun} format: `Convert Vault, Remove Vault`
- Docs: https://github.com/dendronhq/dendron-site/pull/675
- Create New Vault
when config option `enableSelfConatinedVaults` is set to false: prompt user to select destination folder, create new vault there.
when enableSelfConatinedVaults is set to true, always create a new vault at dependencies/localhost.
- Add Existing vault 
when config option `enableSelfConatinedVaults` is set to false and is a local vault, add the existing vault to the workspace, when …
=> enhance(workspace): support adding existing vault to the workspace

packages/api-server/src/routes/note.ts, packages/common-all/src/api.ts, packages/engine-server/src/engineClient.ts, packages/engine-test-utils/src/__tests__/api-server/notes.spec.ts
This change moves engineClient to v3 for the following methods
- getNote
- getNoteMeta
- bulkGetNotes
- bulkGetNotesMeta
Similar to the backend, this will be under a dev flag `enableEngineV3`
=> enhance(workspace): Move engineClient to v3

packages/plugin-core/package.json, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/views/common/treeview/EngineNoteProvider.ts, packages/plugin-core/src/views/common/treeview/NativeTreeView.ts, packages/plugin-core/src/views/common/treeview/TreeNote.ts, packages/plugin-core/src/web/extension.ts, packages/plugin-core/src/workspace/workspaceActivator.ts
This PR aims to 
- resolve the issue of accidentally creating a stub note when clicking a tree-item. It expands the tree item in case of click on a stub.
- remove the + icon from the tree view.
- add back the book icon for schema in tree view
- adds a view action item for stubs to automatically create note when clicked on the action icon(+)
- General
- Operations
- Architecture
- eg: [making changes to DNode](https://github.com/dendronhq/dendron/pull/2158#pullrequestrevie …
=> enhance(views): remove stub icon from tree view

packages/common-all/src/git.ts, packages/common-all/src/index.ts, packages/common-server/src/git.ts, packages/engine-test-utils/src/__tests__/common-all/git.spec.ts, packages/nextjs-template/components/DendronNoteFooter.tsx
The aim of this PR is to consolidate spread out common git utils `common-all`.
git utils inside `common-all` are re-exported in git utils `common-server` thereby nothing changes for the rest of the code. Its also practicall to have `common-all` git utils included in `common-server`.
=> chore(internal): consolidate git utils

packages/engine-server/src/DendronEngineV3.ts, packages/engine-server/src/engineClient.ts, packages/engine-server/src/enginev2.ts
This PR aims to fix the issue with duplicate note entries in lookup bar by filtering out the note ids that starts with prefix fake.
- Bug: https://discordapp.com/channels/717965437182410783/802578902429597726/1031927164645421116
- Debug: all the three entries are of same note
=> fix(workspace): duplicate note entries in lookup bar

packages/engine-server/src/DendronEngineV3.ts
with enginev3 flag enabled, schemas are not loaded on init and Dendron throws the below-specified error. This is because, in windows URI.parse does not have the correct file scheme and appends `C:/` drive to the wsRoot.
`
Multiple errors: - Unable to get schemas for vault archive - Unable to get schemas for vault dendron.community - Unable to get schemas for vault incubator - Unable to get schemas for vault dendron.docs - Unable to get schemas for vault users - Unable to get schemas for vault dendron.blog - Unable to get schemas for vault dendron.dendron-site - Unable to get schemas for vault dendron.handbook - Unable to get schemas for vault private - Unable to get schemas for vault dev
`
=> chore(workspace): load schemas in windows when engineV3 is enabled

packages/api-server/src/Server.ts, packages/api-server/src/routes/note.ts, packages/engine-test-utils/src/__tests__/api-server/notes.spec.ts
There's an issue with bulk operations (or any operations passing in an array as a query parameter) where an array param exceeding 20 items will get converted to an object. This may cause engine side logic to fail. See https://github.com/expressjs/express/issues/2661
This was causing an issue with the wikilink completion provider not providing results for bigger workspaces while on v3, and potentially other issues as well that call `bulkGet`, `bulkGetMeta`, `bulkAdd`
=> fix(workspace): completionProvider and other bulk operations for engine v3

packages/api-server/src/routes/note.ts, packages/common-all/src/engine/EngineV3Base.ts, packages/engine-server/src/topics/site.ts
For Engine V3, there's an issue during Next JS Export when exporting a domain that has no children.  This change fixes it at several layers (even though only one is necessary to unblock the scenario):
- in NextJS, don't call bulkGet with an empty ID list as an argument (unnecessary network call)
- On Engine side, do some _slightly_ better input validation.
In general, we need more robust input validation in api-server or we'll keep hitting issues like this. We do a lot of 'as unknown as foo' casting which is problematic.
=> fix(sync): next js export pod fix on engine v3

packages/nextjs-template/package-lock.json, packages/nextjs-template/package.json, packages/nextjs-template/yarn.lock, yarn.lock
The aim of this PR is to fix [a publishing issue where `npx dendron publish dev´ ](https://github.com/dendronhq/dendron/issues/3746)
The issue is that the lock files point to `12.3.0` which seems to have a bug when running next in dev mode.
=> fix(publish): make sure `nextjs-template` uses bugfree next version

packages/unified/src/decorations/frontmatter.ts, packages/unified/src/decorations/hashTags.ts, packages/unified/src/remark/dendronPub.ts
This PR aims to address the following issue: https://github.com/dendronhq/dendron/issues/3605#issuecomment-1297023998
Note this PR does not fix the one 'intended regression' which is that colors don't observe the hierarchy anymore (i.e. if #foo is red, then #foo.bar used to be red too, but now it'll be something else).
=> fix(workspace): decoration does not display correct custom color for hashtags

packages/plugin-core/src/fileWatcher.ts
This PR aims to fix the issue with notes appearing modified on Workspace sync.
Issue: https://www.loom.com/share/bd47d4e6c0d84c85a47adf0dc32b369f
***
- General
- Operations
- Architecture
=> fix(sync): needless modified notes after workspace sync

packages/plugin-core/src/commands/GoToNoteInterface.ts, packages/plugin-core/src/commands/GotoNote.ts, packages/plugin-core/src/test/suite-integ/GotoNote.test.ts
This PR:
- fixes an issue with go to note, where newly created notes using go to note (originating from a wikilink) was not getting backlinks populated.
- this happens in both engine v2 and v3 (not an engine v3 regression)
- Ideally, the client probably shouldn't be concerned with this detail. I was considering adding this logic to the engine (like the rest is done in https://github.com/dendronhq/dendron/pull/3535), but the case where we need to populate backlinks of a newly created note is very limited (pretty much only this case I can think of so far), and for a generic real-time backlink updating in the engine we would have to a O(nk) pass of all existing notes and all their links, just to find one backlink to update. So I left the logic here in the command for the time being. Maybe we …
=> fix(workspace): correctly populate backlink when creating new note using go to note

packages/common-all/package.json, packages/common-all/src/parse.ts, yarn.lock
The aim of this PR is to make zod validation more readable.
This uses `zod-validation-error` library to return a more readably validation message.
from 
```sh
DendronError: Invalid Dendron Config
[
{
"code": "invalid_type",
"expected": "boolean",
"received": "string",
"path": [
"publishing",
"copyAssets"
],
"message": "Expected boolean, received string"
}
]
```
to 
```sh
DendronError: Invalid Dendron Config: Expected boolean, received string at "publishing.copyAssets"
```
If you are a team member, copy and paste the template from [Dendron Extended PR …
=> chore(internal): make zod validation message more readably

packages/common-all/src/util/compat.ts, packages/plugin-core/src/components/lookup/LookupControllerV3.ts, packages/plugin-core/src/test/suite-integ/MoveSelectionToCommand.test.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts, packages/plugin-core/src/utils/md.ts, packages/unified/src/remark/utils.ts
This PR:
- fixes an issue where block references were not being updated after block anchor was moved with `Move Selection to`
- fixes an issue where same file links were not being updated after block anchor was moved with `Move Selection to`
- since `Move selection to` is a wrapper around note lookup with some special inputs, this was also happening with regular selection extracts in note lookup, and is fixed as well.
- fixes a race condition where the engine and VSCode both attempts a file system change asynchornously, which results in dirty file state during the reference update process
related to: https://github.com/dendronhq/dendron/issues/3644, https://github.com/dendronhq/dendron/issues/3728
- eg: [if configuration for utilities are already in one module or package, add future …
=> fix(refactor): correctly handle reference updates after move selection to

packages/common-all/package.json, packages/dendron-plugin-views/config/webpack.config.js, yarn.lock
This aim of this PR is to fix the build task within `dendron-plugin-views` package which currently results into the following error:
```
/home/nam/code/dendronhq/dendron/node_modules/zod-validation-error/node_modules/@swc/helpers/src/index.mjs
Can't reexport the named export '__decorate' from non EcmaScript module (only default export is available)
```
The commit 419dec79d880228e5677b005f89b52db724b4dc1 (PR: https://github.com/dendronhq/dendron/pull/3762) is responsible for this by adding a dependency
which conflicts with the webpack build in `dendron-plugin-views`. That
dependency uses withing its cjs build files `@swc/helpers` which
conflicts with the import type from webpack.
`@swc/helpers` provides a `module` entry https://github.com/swc-project/swc/blob/main/packages/swc-helpers/packa …
=> chore: fix `dendron-plugin-views` build

packages/common-all/src/store/NoteStore.ts, packages/engine-server/src/DendronEngineV3.ts, packages/engine-test-utils/src/__tests__/common-all/store/noteStore.spec.ts
This PR:
- correctly reads and applies local override in engine v3
- I've commented in https://github.com/dendronhq/dendron/pull/3687 that using `DConfig.readConfigAndApplyLocalOverrideSync` would not be safe yet but that turns out to be an unfounded worry. Not doing so caused a regression with engine v3 where local vaults are not properly loaded. Apologies @tma66 
- adding them back fixes the issue.
- I've also found an issue with note path resolution where if the override specifies a vault with absolute path (which works in engine v2 and there are users doing this)
- I've added a crude resolution in `NoteStore` for this issue.
- Ultimately these should all be resolved with the migration from `DConfig` to `ConfigService`, but with our timeline for rolling out engine v3, it seems very …
=> fix(workspace): Correctly read and apply local override config in engine v3

packages/common-all/src/index.ts, packages/common-all/src/service/ConfigService.ts, packages/common-all/src/service/index.ts, packages/common-all/src/store/ConfigStore.ts, packages/common-all/src/store/IConfigStore.ts, packages/engine-test-utils/src/__tests__/engine-server/ConfigService.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/ConfigStore.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/ConfigService.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/ConfigStore.spec.ts.snap
This PR:
- adds a `ConfigService` that can be consumed by the engine and the client separately.
- `ConfigStore` now only holds primitive store-level operations regarding the configs, and the rest of the higher level logic is moved to `ConfigService`.
- As a result, the interface for `ConfigStore` has slight changes.
- Swap out `DConfig` with `ConfigService`
- This will resolve various local override vault issues (before engine v3 rollout)
- Deprecate `DConfig`
- Refactor `ConfigUtils` to be part of the service
- Make `ConfigService` an `@injectable` (after wider tsyringe adoption)
- Implement `ConfigEventEmitter` to enable real time config updates and remove the need for reload …
=> chore(internal): Implement ConfigService

packages/engine-server/src/DendronEngineV3.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/plugin-core/src/test/suite-integ/RenameNoteCommand.test.ts
Related issue: https://github.com/dendronhq/dendron/issues/3780
- General
- [~] If your tests changes an existing snapshot, snapshots have been [updated](dev.process.qa.test)
=> fix(workspace): rename note breaks noteref for user hierarchy

packages/plugin-core/src/utils/autoCompleter.ts
Related to https://github.com/dendronhq/dendron/issues/3784.
If a user manually selects an item from the quickpick drop down list and hits tab for autocomplete, the desired behavior is to have the quickpick value be populated with the selected item - but we had an issue where that wasn't happening (I think a regression was maybe introduced after some ordering of the 'Create New' items was changed around.
=> fix: autocomplete properly fills out value if user manually selected an item

.github/workflows/ci.yml
If you make multiple pushes in close succession, we'll kick off a CI job for every push, which can take up our github actions resources.  Turns out there's a github actions syntax that can auto-cancel all jobs except for the last one. 
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
=> chore: cancel redundant ci jobs

packages/common-all/src/dnode.ts, packages/common-all/src/drivers/string2Note.ts, packages/common-all/src/store/NoteStore.ts, packages/common-server/src/filesv2.ts, packages/plugin-core/src/web/utils/note2File.ts
When extracting NoteProps from a string/physical file via `string2note`, omit the stub property from NoteProps even if it's set to true - a real file should never be marked as a stub.  Only non-existing nodes that are used to form a complete hierarchy should have stub=true. This is necessary for the sqlite db logic to work properly.
=> chore: mark all real notes with stub=undefined

packages/plugin-core/src/_extension.ts
This PR:
- disables inactive user prompts and lapsed user prompts that asks users if they want to schedule onboarding and feedback sessions.
=> chore(internal): disable startup prompts

packages/plugin-core/.eslintrc.json, packages/plugin-core/src/vsCodeUtils.ts, packages/plugin-core/src/web/views/preview/WebViewUtils.ts
This PR aims to 
- fix a regression with preview background CSS introduced with preview code consolidation(#3777). 
Updated WebviewUtils files to be in-sync with `src/views/utils.ts`
Fix for: https://discordapp.com/channels/717965437182410783/1046957933340143626/1047067244301127730
- fix plugin test cases regression after enterprise build #3804 
- removes trailing comma from packages/plugin-core/.eslintrc.json to fix commit hook
=> chore(internal): fix regression in preview background

packages/common-all/src/constants/index.ts
This change adds a '.' prefix to the sqlite db file, to make it covered by the existing .gitignore pattern of `.dendron.*` - this is to prevent users from accidentally checking in their sqlite db file into git.
=> chore: rename sqlite db file for .gitignore 

.github/workflows/publish-extension-nightly.yml
Context: there's still one issue with the nightly flow, which is that the publishing of the general version of the ext fails cuz the platform-specific ones are published already.  There's an issue just opened on vsce about this: https://github.com/microsoft/vscode-vsce/issues/785
=> chore: separate general build job for nightly

packages/common-all/src/index.ts, packages/engine-server/src/DendronEngineV3Factory.ts, packages/engine-server/src/drivers/file/parseAllNoteFilesForSqlite.ts, packages/engine-server/src/drivers/sqlite/SqliteDbFactory.ts, packages/engine-server/src/drivers/sqlite/SqliteMetadataStore.ts, packages/engine-server/src/drivers/sqlite/tables/HierarchyTableUtils.ts, packages/engine-server/src/drivers/sqlite/tables/SchemaNotesTableUtils.ts, packages/engine-test-utils/src/__tests__/common-all/store/sqliteMetadataStore.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/sqlite/parseAllNoteFilesForSqlite.fts.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/sqlite/parseAllNoteFilesForSqlite.spec.ts, packages/engine-test-utils/src/noteStore.common.ts
This PR:
- properly parse and apply note schemas during engine init when `useSqlite` is enabled.
- supersedes #3822
Notes: 
- now `SchemaNotes` table is properly populated after initialization.
- currently schema initialization happens after all delta initialization steps are done. this may change once we move on to a more proper `Schemas` table in the future.
- there are a few points we can optimize (e.g. remove expensive `.get` calls used to create `NoteDicts`), but currently the init step is implemented to use the existing `SchemaUtils.matchDomain` as much as possible with minimal change to the existing way we do it. this could be done by adding sqlite specific utilities to create `NoteDicts` in one query for example. this is also left for future iteration.
- eg: [if configuration for …
=> chore(internal): note schema parity when sqlite backend is enabled

packages/api-server/src/modules/workspace/index.ts, packages/plugin-core/src/_extension.ts
This PR:
- changes init process so that config service is instantiated as early as possible.
=> fix(workspace): instantiate config service as early as possible to avoid timing issue

packages/common-all/src/types/typesv2.ts, packages/plugin-core/src/components/lookup/types.ts, packages/plugin-core/src/web/commands/CreateJournalNoteCmd.ts, packages/plugin-core/src/web/commands/MoveNoteCmd.ts, packages/plugin-core/src/web/commands/NoteLookupCmd.ts, packages/plugin-core/src/web/commands/lookup/LookupController.ts, packages/plugin-core/src/web/commands/lookup/LookupQuickPickView.ts, packages/plugin-core/src/web/commands/lookup/QuickPickUtils.ts, packages/plugin-core/src/web/commands/lookup/VaultQuickPick.ts, packages/plugin-core/src/web/engine/DendronEngineV3Web.ts, packages/plugin-core/src/web/extension.ts, packages/plugin-core/src/web/test/helpers/setupTestEngineContainer.ts, packages/plugin-core/src/web/test/suite/commands/MoveNoteCmd.test.ts, packages/plugin-core/src/web/test/suite/commands/NoteLookupCmd.test.ts, packages/plugin-core/src/web/utils/NoteLookupUtilsWeb.ts, packages/plugin-core/src/web/utils/WSUtils.ts
This Pr aims to add Move Note command in web along with the following buttons to lookup
- vault confirm on create button
- direct child only
- journal note
- General
- Operations
- Architecture
- eg: [breaking dev change due to new dependency](https://github.com/dendronhq/dendron/pull/2188#pullrequestreview-855696330)
=> feat: add lookup buttons in web

.github/workflows/ci.yml, package.json, packages/common-server/src/errorReporting.ts, packages/common-server/src/files.ts, packages/engine-test-utils/package.json, packages/engine-test-utils/src/audit.ts, packages/engine-test-utils/src/index.ts, packages/nextjs-template/.gitignore, packages/nextjs-template/audit/audit.spec.ts, packages/nextjs-template/playwright.config.ts, yarn.lock
The aim of this PR is to add a web performance harness that measures the metrics [web vital](https://web.dev/vitals/) (a group of metrics defined by the web-vital project), [bundle size](https://github.com/ai/size-limit) and [time](https://github.com/mbalabash/estimo). 
Reports in airtable: https://airtable.com/appCWyZZPrLlVUblF/tblLRZhYUKGmScOai/viwPWgniLl5LM6gRC?blocks=bipFIuRw2Al2FLkw8 (open "Extensions" panel on the right to view through the [json editor](https://support.airtable.com/docs/json-editor-extension))
In the current state this runs as part of the test-playwright ci job therefore on every PR.
As a next step we could add a comparison,  which prints a warning (PR comment) when a threshold or budget gets exceeded.
=> feat(internal): web performance harness

packages/engine-server/src/DendronEngineV3.ts
This PR aims to filter out rendering broken note ref links(pointing to non-existent files)
Presently with engineV3, the preview fails with an error: `Problem Rendering Note: Cannot read properties of undefined (reading 'updated')`
=> fix(views): broken preview for note having links to non-existent note refs

.github/workflows/ci.yml, .github/workflows/create-release-image-patch.yml, .github/workflows/create-release-image.yml, .github/workflows/hackathon-create-test-image.yml, .github/workflows/proto.yml, .github/workflows/publish-extension-dendron-minor.yml, .github/workflows/publish-extension-dendron-patch.yml
This PR:
- bumps node version used in github actions to be at least 16.
- for matrices, we can later add 18 and beyond. for now leaving it to only run on 16.
=> chore(internal): bump node version to 16 in ci

.github/workflows/create-release-image.yml, .github/workflows/publish-extension-dendron-minor.yml, .github/workflows/publish-extension-dendron-patch.yml, .github/workflows/publish-extension-nightly.yml, bootstrap/scripts/buildPatch.sh, package.json
This PR aims to update both `publishing-minor` and `publishing-patch` workflow to include platform-specific matrix for downloading sqlite binaries
=> chore(internal): add platform specific matrix to publish extension workflow

packages/plugin-core/assets/dendron-ws/tutorial/treatments/quickstart-v1/tutorial.md
While going through the Dendron tutorial I found this typo in the Markdown file. Wanted to contribute to correct the information for future users.
=> Correct small typo in tutorial

packages/plugin-core/src/components/lookup/QuickPickTemplateSelector.ts, packages/plugin-core/src/test/suite-integ/ApplyTemplateCommand.test.ts
- tlylt
- related to #998
I decided to change the condition in `QuickPickTemplateSelector.ts` to capture the case where the template is not found and return undefined from there. It is also possible to make that change downstream in `ApplyTemplateCommand.ts` (line 61) with something like:
```ts
if (_.isUndefined(templateNote) || templateNote?.children.length === 0) {
throw new DendronError({ message: `Template not found` });
}
```
Similar to the existing logic when template is undefined, template not found will now trigger an error message. 
Let me know if there's any issue with the current approach.
I adjusted some code in the integration tests for apply template to add …
=> enhance(create): show error when applying template but no template found

README.md, setup.sh, shell/_setup_nvm_source_me.sh, shell/_util.sh, shell/_verify_env_variables.sh, shell/_verify_node_version.sh, shell/_verify_npm.sh, shell/_verify_nvm_source_me.sh, shell/_verify_yarn.sh, shell/setup.sh, watch.sh
Adding `./setup.sh` which automates the setup described in https://docs.dendron.so/notes/64f0e2d5-2c83-43df-9144-40f2c68935aa/
Tested in `bash` and `zsh`.
To use it, run `./setup.sh` in the root of Dendron mono repo.
=> Adding ./setup.sh to automate development setup.
