dendronhq/dendron

packages/plugin-core/src/commands/Doctor.ts, packages/plugin-core/src/test/suite-integ/DoctorCommand.test.ts
Add an emoji (and indicate that the Doctor command has initiated)
=> Avoid doc-ception and doc-ception encouraging test

packages/engine-server/src/__tests__/__snapshots__/enginev2.spec.ts.snap, packages/engine-server/src/__tests__/enginev2.spec.ts
Fixing two minor transpositions.
=> Fixing minor typos

dendron-cli.code-workspace, dendron-lsp.code-workspace, dendron-next-server.code-workspace, dendron.code-workspace
Removed the settings that affect the appearance of vscode.
=> chore(code-workspace): remove appearance settings

packages/common-test-utils/src/presets/engine-server/utils.ts, packages/common-test-utils/src/presets/notes.ts, packages/pods-core/src/builtin/__tests__/MarkdownPod.spec.ts
- Added additional tests for `MarkPublishPod`
Closes https://github.com/dendronhq/dendron/issues/417
=> chore: add more tests for MarkdownPod

packages/engine-server/src/config.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts
Fixes #464 
Not sure if the description default is good though.
=> Add description option to dendron config

packages/plugin-core/src/features/FrontmatterFoldingRangeProvider.ts, packages/plugin-core/src/test/suite-integ/FrontmatterFoldingRangeProvider.test.ts, packages/plugin-core/src/windowWatcher.ts, packages/plugin-core/src/workspace.ts
Related to #446 
- Implement and register `FrontmatterFoldingRangeProvider`
- Add basic test for said range provider
=> Provide folding range for note frontmatter

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/pod-request-template.md, .github/ISSUE_TEMPLATE/seed-request.md, .github/config/issue-labler/labler-v0.yml, .github/workflows/issue-labler.yml
- Added the issue-labler workflow added a v0 config.
- modified bug_report.md to be able to work with the issue-labler
- modified feature_request.md to be able to work with the issue-labler
Closes #451 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dendronhq/dendron/453)
=> 451 [Proposal] Issue labeling automation

.github/config/issue-labler/labler-v1.yml
All RegExes got an optional space infront or after the x of the checkbox.
The types and enhancements now got the correct text to match against.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dendronhq/dendron/532)
=> ci(issue-labler): fix regexes

packages/plugin-core/src/commands/VaultAddCommand.ts
This PR:
- Adds a progress bar when adding a remote vault.
closes: #485
=> Add progress to remote vault add

.all-contributorsrc, .github/ISSUE_TEMPLATE/bug_report.md, README.md, docs/CONTRIBUTING.md
We want our readme to be cleaner + link to all the contributors. First step is to enable the contributor bot so there's a clean, easy way of adding people to the readme and it doesn't have to be so manual. 
Pay attention to the roles + emojis used and please provide feedback if you have any tips/tricks on seeding the contributor bot.
=> Updated README + added contributors

packages/engine-server/src/topics/git.ts, packages/engine-server/src/workspace.ts, packages/engine-test-utils/src/index.ts, packages/engine-test-utils/src/utils.ts, packages/plugin-core/package.json, packages/plugin-core/src/commands/Sync.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/SyncCommand.test.ts
This pull request completes the existing Sync command stub, and adds tests for it. It also makes a few small changes to `pullVaults` and `pushVaults` functions to make testing easier.
=> feat: Workspace Sync command

packages/engine-server/src/topics/git.ts, packages/engine-server/src/workspace.ts, packages/engine-test-utils/src/utils.ts, packages/plugin-core/src/commands/DiagnosticsReport.ts, packages/plugin-core/src/test/suite-integ/DiagnosticsReport.test.ts, packages/plugin-core/src/test/suite-integ/MoveNoteCommand.test.ts, packages/plugin-core/src/test/suite-integ/SyncCommand.test.ts
This pull request fixes several tests that were silently failing due to issues with promises. The fix includes both fixing the tests so that the failures are caught, and fixing the code where necessary to fix issues.
=> Fix rejected promises in testing

packages/engine-test-utils/src/__tests__/engine-server/markdown/blockAnchors.spec.ts
Looks like the merged fixes already solved this issue. Added a test anyway.
=> Add test for block anchors at the end of headers

hooks/common.js, hooks/pre-commit.js, hooks/pre-push.js, package.json, packages/engine-test-utils/src/__tests__/engine-server/topics/hooks.spec.ts
This is just a suggestion. Personally, I keep forgetting to take `debugger;` statements out when committing, so I would find this useful. I tested it with a commit and can confirm that it works.
=> Check in pre-commit against `debugger;` statements

packages/engine-server/src/markdown/remark/utils.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/wikiLink.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/wikiLink.spec.ts
=> fix: incorrect parsing of aliases starting with `#`

packages/plugin-core/assets/dendron-ws/vault/dendron.welcome.md, packages/plugin-core/assets/dendron-ws/vault/welcome.html
I think something like this could work but might take other product changes. 
Detailed in [[scratch.2021.06.08.205026.onboarding-test]]
=> welcome now asks for initialization

packages/dendron-next-server/components/graph.tsx, packages/dendron-next-server/hooks/useApplyGraphConfig.tsx, packages/dendron-next-server/hooks/useGraphElements.tsx, packages/dendron-next-server/lib/graph.ts, packages/dendron-next-server/pages/vscode/graph-note.tsx, packages/dendron-next-server/pages/vscode/graph-schema.tsx, test-workspace/vault/bar.md, test-workspace/vault2/bar.md
Adds:
- show/hide different vaults in graph
- move graph config application into separate hook to separate concerns
=> feat: filter note and schema graphs by vault

packages/common-test-utils/src/presets/notes.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-test-utils/src/__tests__/pods-core/MarkdownPod.spec.ts, packages/engine-test-utils/src/__tests__/pods-core/__snapshots__/MarkdownPod.spec.ts.snap, packages/pods-core/src/basev3.ts, packages/pods-core/src/builtin/MarkdownPod.ts
Improving functionality around markdown pod export. 
Related Links
- https://github.com/dendronhq/dendron/issues/541#issue-831219413
- https://wiki.dendron.so/notes/ccab31c4-e9ca-4ee8-b754-f786a3f3be6e.html
=> feat:export markdown pod functionality

packages/common-all/src/types/typesv2.ts, packages/pods-core/package.json, packages/pods-core/src/basev3.ts, packages/pods-core/src/builtin/AirtablePod.ts, packages/pods-core/src/builtin/GitPod.ts, packages/pods-core/src/builtin/GraphvizPod.ts, packages/pods-core/src/builtin/JSONPod.ts, packages/pods-core/src/builtin/MarkdownPod.ts, packages/pods-core/src/builtin/SnapshotPod.ts, packages/pods-core/src/utils.ts, yarn.lock
Added changes for validating export config.
=> feat : ajv to validate export conf

packages/dendron-next-server/styles/theme-antd.ts
Changes:
- reworked graph theme composition, removing the possibility of light mode styles being applied unintentionally to dark mode graphs
- increased contrast of nodes and edges in the graph to increase visibility
=> fix: graph theming stability, higher contrast edges and nodes

packages/dendron-next-server/components/graph.tsx, packages/dendron-next-server/hooks/useApplyGraphConfig.tsx, packages/dendron-next-server/lib/graph.ts
Changes:
- Rename "Whitelist" and "Blacklist" to "Allowlist" and "Blocklist"
=> refactor: move from whitelist/blacklist to allowlist/blocklist

packages/dendron-next-server/pages/vscode/calendar-view.tsx, yarn.lock
[[scratch.2021.06.23.094100.fix-calendar-view-creating-new-note-when-navigating-months.md]]
This adds two enhancements:
- Switching mode (month<->year) does not implicitly create a daily journal entry anymore
- Adds a "Today" button to the calendar which creates or opens today's daily journal entry.
=> enhance(calendar-view): simple betterments

packages/dendron-next-server/components/graph.tsx, packages/dendron-next-server/hooks/useApplyGraphConfig.tsx, packages/dendron-next-server/lib/graph.ts
Changes:
- Added option in filter ui to show/hide labels on graph for a less cluttered view
=> feat: add ability to show/hide labels on graph

packages/plugin-core/src/components/lookup/LookupProviderV2.ts, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
=> feat: Direct child filter ignores stubs

packages/common-all/src/analytics.ts, packages/plugin-core/assets/dendron-ws/vault/welcome.html, packages/plugin-core/src/windowWatcher.ts, packages/plugin-core/src/workspace.ts
Improving our telemetry around the tutorial experience
=> fix/Improving Tutorial Telemetry

packages/dendron-cli/src/commands/backfillV2.ts, packages/plugin-core/src/commands/Doctor.ts, packages/plugin-core/src/test/suite-integ/DoctorCommand.test.ts
Only does so if the note id is bad.
=> feat: Doctor "fix frontmatter" fixes broken note ids

packages/plugin-core/assets/dendron-ws/tutorial/tutorial.md
Tutorial website was broken after the onboarding v2 doc changes...
=> fix:tutorial website link

.editorconfig
Just a basic config based on the style of .ts files. I can expand rules if needed, but even these two lines already help set up editor settings instantly.
=> Basic .editorconfig

packages/common-all/src/dnode.ts, packages/common-all/src/types/foundation.ts, packages/common-all/src/types/typesv2.ts, packages/common-all/src/types/workspace.ts, packages/common-test-utils/src/presets/notes.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/enginev2.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-server/src/markdown/types.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/remarkUtils.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/remarkUtils.spec.ts, packages/plugin-core/src/commands/ConvertLink.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/features/BacklinksTreeDataProvider.ts, packages/plugin-core/src/services/NoteSyncService.ts, packages/plugin-core/src/test/suite-integ/BacklinksTreeDataProvider.test.ts, packages/plugin-core/src/utils/md.ts, packages/plugin-core/src/workspace.ts, yarn.lock
This PR:
- Adds functionality to show unreferenced links in the backlink panel.
Tasks:
=> feat: show unreferenced links in backlink panel

packages/common-all/src/analytics.ts, packages/plugin-core/package.json, packages/plugin-core/src/scripts/uninstallHook.ts
Add some analytics around extension uninstall
=> fix: add uninstall analytics

packages/plugin-core/src/commands/Doctor.ts, packages/plugin-core/src/features/codeActionProvider.ts, packages/plugin-core/src/features/windowDecorations.ts, packages/plugin-core/src/test/suite-integ/WindowDecorations.test.ts, packages/plugin-core/src/utils.ts, packages/plugin-core/src/workspace.ts
Warns against:
* Frontmatter missing
* Frontmatter has no id
* Frontmatter id is bad (starts or ends with underscore or hypen)
It also provides automatic code action to fix the issue, which runs the doctor command to fix the frontmatter.
https://www.loom.com/share/ab0c253442814bc2b78f03f08bd7d342
=> feat: warn against missing or bad frontmatter

packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/components/lookup/LookupControllerV3.ts, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/components/lookup/types.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
This PR:
- Adds journal modifier to lookup V3
- Adds tests for journal modifier behavior
=> feat: journal modifier for lookup V3

packages/plugin-core/src/features/codeActionProvider.ts
Delays while the user is typing. User is considered typing if they have been typing for the last 500 ms.
=> feat: delay warnings while user is typing

packages/plugin-core/src/commands/LookupCommand.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/test/suite-integ/LookupCommand.test.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
This PR:
- adds copyNoteLink modifier to `NoteLookup`
- adds a test for said modifier
=> feat: add effects modifier to lookup v3

packages/plugin-core/src/commands/CopyNoteLink.ts, packages/plugin-core/src/commands/CopyNoteRef.ts, packages/plugin-core/src/test/suite-integ/CopyNoteRef.test.ts, packages/plugin-core/src/utils.ts
=> fix: CopyNoteRef respects noXVaultWikiLink option

packages/dendron-cli/src/commands/vaultCLICommand.ts, packages/engine-server/src/workspace/service.ts, packages/engine-server/src/workspace/vscode.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/dendron-cli/commands/vaultCli.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/engine-test-utils/src/engine.ts
=> fix: add new vaults from CLI to code workspace

packages/engine-test-utils/src/__tests__/pods-core/GithubPod.spec.ts, packages/pods-core/src/builtin/GithubPod.ts
Fix for tags in github issue. Retreived tags from `note.tags`
=> fix: frontmatter tags

packages/common-all/src/types/typesv2.ts, packages/plugin-core/package.json, packages/plugin-core/src/commands/InsertNoteLink.ts, packages/plugin-core/src/commands/MoveNoteCommand.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/commands/RenameNoteV2a.ts, packages/plugin-core/src/commands/SchemaLookupCommand.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/components/lookup/LookupControllerV3.ts, packages/plugin-core/src/components/lookup/LookupProviderV3.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/MoveNoteCommand.test.ts, packages/plugin-core/src/test/suite-integ/SchemaLookupCommand.test.ts, packages/plugin-core/src/workspace.ts
This PR:
- Adds `SchemaLookupCommand` with basic schema lookup functionality.
- Adds tests for basic schema lookup.
=> feat: Add SchemaLookupCommand

packages/plugin-core/src/components/lookup/LookupProviderV3.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts, test-workspace/vault/recipe.md, test-workspace/vault/recipe.schema.yml
This PR:
- adds schema suggestion to `NoteLookupCommand`
- adds basic test for schema suggestion
=> feat: add schema suggestion to NoteLookupCommand

packages/engine-server/src/workspace/vscode.ts, packages/plugin-core/package.json, packages/plugin-core/src/test/testUtilsv2.ts, packages/plugin-core/webpack.config.js
This is #1108 fixed, had to restart the branch because of some build issues.
=> feat: provide YAML validator & suggest YAML extension

packages/plugin-core/src/components/lookup/LookupControllerV3.ts
This PR:
- Adds rich picker title to lookup v3 (a la v2)
=> chore: add rich picker title to lookup v3

packages/dendron-next-server/styles/scss/base.scss
This PR:
- Fixes issue with Preview V2 not rendering horizontal rules
=> fix: horizontal rule not rendering

packages/engine-test-utils/src/__tests__/engine-server/markdown/utilsv5.spec.ts
This PR:
- Adds non-snapshot based test for noteref rendering in preview
=> chore: add non snapshot test for noteref title render

packages/nextjs-template/components/DendronBreadCrumb.tsx, packages/nextjs-template/utils/links.ts
This PR:
- Makes breadcrumbs in nextjs publishing clickable.
=> feat: make breadcrumbs clickable

packages/plugin-core/src/features/ReferenceHoverProvider.ts, packages/plugin-core/src/test/suite-integ/ReferenceProvider.test.ts, packages/plugin-core/src/utils/md.ts
=> enhance: improve hover message for missing notes

packages/dendron-next-server/components/graph.tsx, packages/dendron-next-server/hooks/useGraphElements.tsx, packages/dendron-next-server/lib/graph.ts
Tag colors are now displayed on the graph.
=> feat: tag colors in graph

packages/nextjs-template/components/DendronLayout.tsx, packages/nextjs-template/styles/constants.ts, packages/nextjs-template/styles/scss/content.scss
includes
- layout change to be centered
- increase main content font-size to 16px
=> nextjs template style improvements 2

packages/engine-server/src/markdown/remark/noteRefsV2.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/noteRefv2.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/noteRefv2.spec.ts, test-workspace/vault/scratch.2021.08.31.004036.md
=> fix: block anchor in list with single top level element

packages/dendron-cli/package.json, packages/plugin-core/package.json, packages/plugin-core/webpack.config.js, yarn.lock
Some initial work on reducing our bundle size. removes 10mb off final package
=> chore: reduce vscode bundle size

packages/plugin-core/src/features/windowDecorations.ts, packages/plugin-core/src/test/suite-integ/WindowDecorations.test.ts
Frontmatter tags are now highlighted in the same way hashtags are.
Hashtags and frontmatter tags with missing tag notes are now
highlighted in the same way wikilinks for missing notes are.
The idea is that since a lot of features (autocomplete, backlinks in publishing etc.)
depend on the tag notes actually existing, the highlighting would encourage users to create the tag notes.
```markdown
```
=> enhance: FM tags highlighting & missing tag notes highlighted as missing

packages/plugin-core/src/commands/PublishPod.ts, packages/plugin-core/src/commands/ReloadIndex.ts, packages/plugin-core/src/workspace.ts, packages/pods-core/src/builtin/GithubPod.ts
```markdown
```
- [n] add a [test](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#writing-tests) for the new feature
- [n] do a spot check by running your feature with our [test workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace)
- [n] if your tests changes an existing snaphot, make sure that snapshots are [updated](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#updating-test-snapshots)
- [n] if you are adding a new language …
=> fix: reload index to be silent by default

packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/markdown/remark/userTags.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-server/src/topics/git.ts, packages/engine-test-utils/src/__tests__/common-server/git.spec.ts, packages/engine-test-utils/src/engine.ts, packages/engine-test-utils/src/presets/engine-server/rename.ts, packages/engine-test-utils/src/utils/git.ts, packages/plugin-core/src/features/completionProvider.ts, packages/plugin-core/src/test/suite-integ/CompletionProvider.test.ts, packages/plugin-core/src/utils/md.ts
Adds autocomplete support for user tags, and user tags will now be updated when a user note is renamed. Also fixes user tags not creating backlinks.
Also fixed an error with some tests that fail if the default git branch is set to something other than `master`. Sorry for stuffing that in this PR, I can split it if preferred.
- [x ] add a [test](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#writing-tests) for the new feature
```markdown
This changes capitalizes all occurences of …
```
=> feat: user tag autocomplete & user tags updated on rename

packages/dendron-11ty/raw-assets/sass/_portal.scss, packages/dendron-next-server/styles/scss/_portal.scss, packages/nextjs-template/styles/scss/_portal.scss
Links at the top or bottom of a reference were not clickable due to the "top fader" and "bottom fader" elements in the reference. It looks like these faders were disabled by removing their color, but were otherwise left in. As a result they blocked access to elements below. This PR:
- Sets their height to 0 so that they won't obstruct the contents of the reference
- Allows clicks to propagate through the faders if a custom theme re-enables them
#1274 
```markdown
This changes capitalizes all occurences …
```
=> fix: links at top/bottom of reference aren't clickable

packages/plugin-core/src/features/windowDecorations.ts, packages/plugin-core/src/test/suite-integ/WindowDecorations.test.ts
Revised the code so that this issue won't pop up again.
```markdown
```
=> fix: decorations for erased tags persist

packages/engine-test-utils/src/__tests__/pods-core/NextjsExportPod.spec.ts, packages/nextjs-template/components/DendronTreeMenu.tsx, packages/nextjs-template/next.config.js, packages/nextjs-template/package.json, packages/nextjs-template/pages/_app.tsx, packages/nextjs-template/pages/notes/[id].tsx, packages/nextjs-template/tsconfig.build.json, packages/nextjs-template/utils/fetchers.ts, packages/nextjs-template/utils/links.ts, packages/pods-core/src/builtin/NextjsExportPod.ts, test-workspace/dendron.yml
Add support for [assetPrefix](https://wiki.dendron.so/notes/f2ed8639-a604-4a9d-b76c-41e205fb8713.html#assetsprefix) option
Docs: https://github.com/dendronhq/dendron-site/pull/188/files
```markdown
```
=> enhance: support `assetPrefix` option with next publishing

packages/engine-server/src/markdown/remark/dendronPreview.ts, packages/engine-server/src/markdown/remark/dendronPub.ts, packages/engine-server/src/markdown/remark/extendedImage.ts, packages/engine-server/src/markdown/remark/index.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-server/src/markdown/types.ts, packages/engine-server/src/markdown/utils.ts, packages/engine-server/src/markdown/utilsv5.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/extendedImage.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/extendedImage.spec.ts, test-workspace/vault/dendron.ref.extended-images.md
This is a new feature that allows users to extend
images by setting custom CSS properties.
The properties are written with an inline YAML map
(like `{width: 50%, height: 400px}`) placed after the image.
Only certain properties are allowed to avoid any potential abuse.
The extended images work in both preview and publishing.
#1273
```markdown
```
=> feat: extended images for custom CSS properties

packages/nextjs-template/components/DendronGATracking.tsx, packages/nextjs-template/package.json, packages/nextjs-template/pages/_app.tsx, packages/nextjs-template/utils/analytics.ts, packages/nextjs-template/utils/build.ts
```markdown
```
Tested against a google analytics account locally by adding 
```js
{gaOptions: {cookieDomain: "none"}}
``` 
in ga initialize. The analytics were recorded for each route.
- [n] add a [test](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#writing-tests) for the new feature
- [n] if your tests changes an existing snaphot, make sure that snapshots are [updated](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#updating-test-snapshots)
- [n] if you are adding a new …
=> enhance(publishing): support ga tracking in nextjs publishing

hooks/pre-push.js, packages/common-all/src/types/typesv2.ts, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/enginev2.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-test-utils/src/presets/engine-server/index.ts, packages/engine-test-utils/src/presets/engine-server/rename.ts, packages/plugin-core/src/test/suite-integ/MoveNoteCommand.test.ts, packages/plugin-core/src/test/suite-integ/RefactorHierarchy.test.ts, packages/plugin-core/src/views/DendronTreeView.ts, packages/plugin-core/src/windowWatcher.ts
Rename note will delete the parent note if it is a stub. If the rename results in a new note whose parents is also a stub, rename note will not create those stubs. This leads to issues with the tree view and other parts of Dendron that rely on the proper metadata to exist
***
- [~] if you are adding a new language feature (graphically visible in …
=> fix(commands): rename note leaves incorrect metadata if parent is a stub

packages/nextjs-template/components/DendronGATracking.tsx, packages/nextjs-template/pages/_app.tsx, packages/nextjs-template/utils/analytics.ts
=> chore(publish): convert Google Analytics comp to hook.

packages/nextjs-template/components/DendronLayout.tsx, packages/nextjs-template/components/DendronNotice.tsx, packages/nextjs-template/hooks/useToggle.tsx
=> feat(publish): notice for dev mode

packages/plugin-core/webpack.config.js
=> chore(build): option to skip sentry file upload

packages/engine-server/src/markdown/remark/hashtag.ts, packages/plugin-core/src/test/suite-integ/CompletionProvider.test.ts
=> fix: hashtags not at the start of line don't autocomplete

packages/dendron-next-server/components/graph.tsx
=> feat(preview): button for toggle local/global graph

packages/plugin-core/src/_extension.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/utils.ts
This PR:
- fixes a bug where vim keybinding resolution resulted in a corrupted (not recognized by vscode) `keybinding.json`, which also made lookup keybinding resolution fail.
- adds backup of original keybinding before applying vim keybinding resolution
- adds notification similar to lookup keybinding migration through a toast message that vim keybinding conflict has been resolved.
- [~] if your tests changes an existing snaphot, make sure that snapshots are [updated](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b …
=> fix: prevent malformed keybinding.json

packages/common-all/src/types/workspace.ts, packages/engine-server/src/markdown/remark/dendronPub.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/hashtag.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/hashtag.spec.ts, packages/plugin-core/src/features/windowDecorations.ts
Publishing already had a "no randomly colored tags" option, which disables the tag color display for tag notes that don't have a color set explicitly. This PR adds a similar option for the editor.
https://wiki.dendron.so/notes/8bc9b3f1-8508-4d3a-a2de-be9f12ef1821.html#disabling-automatic-colors
#1351
```markdown
```
=> enhance: option to disable randomly colored tags in editor

packages/nextjs-template/components/DendronTreeMenu.tsx
=> feat(publish): add popover for long title in menu

packages/plugin-core/src/features/DefinitionProvider.ts, packages/plugin-core/src/features/ReferenceProvider.ts, packages/plugin-core/src/features/codeActionProvider.ts, packages/plugin-core/src/test/suite-integ/ReferenceProvider.test.ts
```markdown
This fixes additional exceptions hit in various providers that should not run when not in a Dendron workspace.
```
---
```markdown
```
=> fix: fixes in providers when not in dendron workspace

packages/pods-core/src/builtin/NextjsExportPod.ts
=> enhance(publish): filter body out of generated notes.json for next

packages/nextjs-template/components/DendronLayout.tsx, packages/nextjs-template/components/DendronTreeMenu.tsx, packages/nextjs-template/styles/constants.ts
a working, albeit not as ideal implementation of mobile nav simulating existing 11ty template without changing much of the laylout.
=> feat(publish): mobile navigation

packages/plugin-core/package.json, packages/plugin-core/src/commands/DeleteNodeCommand.ts, packages/plugin-core/src/commands/VaultRemoveCommand.ts, packages/plugin-core/src/test/suite-integ/DeleteNodeCommand.test.ts, packages/plugin-core/src/test/suite-integ/VaultRemoveCommand.test.ts
```markdown
#feat: Contextual UI - added Context Menus for Note and Vault Specific operations like vault remove and note delete.
```
- [~] if you are adding a new language feature (graphically visible in vscode/preview/publishing), make sure that it is included in [test-workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb …
=> Feat/contextual UI

packages/common-all/src/dnode.ts
- [] after you submit your pull request, check the output of our [integration test](https://github.com/dendronhq/dendron/actions) and make sure all tests pass
Small optimization, however, this method is used in many places. 
Some benchmarking shows almost ~50%+ speed up of this function.
```
Sample id being compared: '0d342ce5-3648-472a-85eb-5a447de1be091fb8b41c-d7f6-4a46-870c-dc6b1a92023f7904d17c-66dc-413e-9f53-bed41cb1cedc'
Took '7ms' to loop through and equal compare '100000' when stacked '3' in single id, (toLowerInEachIteration: 'false)'
Took '12ms' to loop through and equal compare '100000' when stacked '3' in single id, (toLowerInEachIteration: 'true)'
```
Running benchmark …
=> enhance: mini optimization in looking up notes by filename

packages/common-all/src/types/workspace.ts, packages/engine-server/src/markdown/remark/hierarchies.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/dendronPub.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/dendronPub.spec.ts
This PR adds an option that when enabled, will display `#` symbols before Frontmatter Tags.
Docs: https://github.com/dendronhq/dendron-site/pull/210
#1316
```markdown
```
=> enhance: option to add # symbols for FM tags

packages/common-all/src/analytics.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/survey.ts, packages/plugin-core/src/test/suite-integ/Survey.test.ts, packages/plugin-core/src/workspace/tutorialInitializer.ts
This PR:
- Adds an initial survey that will be used to further customize the onboarding experience
DOCS: https://github.com/dendronhq/dendron-site/pull/212
- [~] if you are adding a new language feature (graphically visible in vscode/preview/publishing), make sure that it is included in …
=> feat: initial survey

packages/common-all/src/types/typesv2.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/nextjs-template/components/DendronTOC.tsx, packages/nextjs-template/pages/notes/[id].tsx
=> feat(publish): add table of contents

packages/engine-server/src/markdown/remark/utils.ts, packages/plugin-core/package.json, packages/plugin-core/src/commands/MoveHeader.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/MoveHeader.test.ts, packages/plugin-core/src/test/testUtilsV3.ts, test-workspace/vault3/move.dest.md, test-workspace/vault3/move.md, test-workspace/vault3/not-secret.md
This PR adds a new command `Dendron: Move Header`, that lets you select a header similar to `Dendron: Rename Header`, and choose a note to move the header.
The selected header will be removed from the original note and added to the end of the selected note's body.
All wikilinks that reference this header will be updated to point to the newly moved header.
Docs PR: https://github.com/dendronhq/dendron-site/pull/204
---
- [~] if your tests changes an existing snaphot, make sure that snapshots are …
=> feat(command): move header command

packages/plugin-core/src/commands/DeleteNodeCommand.ts, packages/plugin-core/src/test/suite-integ/DeleteNodeCommand.test.ts
#enhance/improve-user-messaging-on-node-delete-by-specifying-the-vault-of-the-deleted-node
=> #enhance/improve-user-messaging-on-node-delete-by-specifying-the-vault-of-the-deleted-node

packages/common-all/src/types/workspace.ts, packages/engine-server/package.json, packages/engine-server/src/workspace/fileWatcher.ts, packages/engine-server/src/workspace/index.ts, packages/plugin-core/src/fileWatcher.ts, packages/plugin-core/src/test/suite-integ/FileWatcher.test.ts, packages/plugin-core/src/workspace/codeWorkspace.ts, yarn.lock
Created an adapter to allow both watchers to be used interchangably.
The native watcher is only used for native workspaces, or if forced using a `dev` config.
```markdown
```
=> chore: add native filespace watcher for native WS

packages/engine-server/src/migrations/service.ts, packages/engine-server/src/workspace/service.ts, packages/plugin-core/src/test/suite-integ/migration.test.ts, packages/plugin-core/src/workspace.ts
There's some issues with note creation not working correctly. I'll be working on fixing these bugs to get feature parity.
```markdown
```
=> fix: initialization for native workspaces

packages/plugin-core/assets/dendron-ws/tutorial/tutorial.3-linking-your-notes.md
`dendron-site` PR: https://github.com/dendronhq/dendron-site/pull/217
Noticed that the "unique to your system" ctrl/cmd key wasn't applicable for tab switching. Made an extra note in the `dendron-site` PR too, as I (and perhaps many others too) have specific key bindings to match the defaults across other apps:
```
{
"key": "ctrl+shift+tab",
"command": "workbench.action.previousEditor"
},
{
"key": "ctrl+tab",
"command": "workbench.action.nextEditor"
},
```
NOTE: Leaving the checklist in below in case I missed something 🤷  …
=> Update docs for tab switch keybinding

packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/test/suite-integ/LookupUtils.test.ts
- [x ] add a [test](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#writing-tests) for the new feature
- [x ] make sure all the existing [tests](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#running-all-tests) pass
=> fix(lookup): vault selection use wrong label

packages/plugin-core/src/features/windowDecorations.ts, packages/plugin-core/src/test/suite-integ/WindowDecorations.test.ts, test-workspace/vault/dendron.ref.links.md
Wildcard note refs with header offsets (like `![[foo.bar.*#header]]`) would be highlighted as missing, this PR highlights them as existing instead. Since an actual check would be expensive, wildcard refs are always highlighted as existing for now.
```markdown
```
=> fix: highlighting for wildcard note refs with header offsets

packages/engine-server/src/markdown/remark/blockAnchors.ts, packages/engine-test-utils/src/__tests__/pods-core/MarkdownPod.spec.ts, packages/pods-core/src/builtin/MarkdownPod.ts
=> fix: markdown publish to hide block reference anchors

packages/common-all/src/analytics.ts, packages/plugin-core/src/survey.ts
This PR
- Adds `Personal Knowledge Base` to use case survey
- Adds `Researcher` to background survey
- Limits background survey to one _primary_ background
- Adds `PublishingUseCaseSurvey`
- [~] …
=> enhance: better survey

packages/plugin-core/src/features/codeActionProvider.ts
```markdown
```
- [~] if you are adding a new language feature (graphically visible in VS Code/preview/publishing), make sure that it is included in …
=> Copy Header Reference code action

packages/api-server/src/Server.ts, packages/api-server/src/modules/oauth.ts
The properties in the base Error class weren't getting propagated in the api-server error handler. This also unwraps exceptions getting thrown in the OAuth route handler.
---
```markdown
```
=> fix: improving error response on api server

packages/common-server/src/analytics.ts, packages/engine-test-utils/src/__tests__/engine-server/segmentClient.spec.ts
Fixing a regression introduced in https://github.com/dendronhq/dendron/pull/1515 where the ordering of payload and context were flipped. Also fixes a typo introduced with the `nodeVersion` property.
---
```markdown
```
=> fix: incorrect payload and context ordering on track

packages/plugin-core/src/commands/MoveHeader.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/test/suite-integ/MoveHeader.test.ts
This PR
- Allows new note creation in `MoveHeaderCommand` if destination note doesn't exist yet.
- [~] if you are adding a new language feature (graphically visible in VS Code/preview/publishing), make sure that it is included in [test-workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test …
=> fix: allow creation of new notes when move header destination doesn't exist yet

packages/plugin-core/src/features/codeActionProvider.ts
=> chore:  warning to remove stub property if the note has content

packages/common-all/src/analytics.ts, packages/plugin-core/src/components/lookup/LookupControllerV3.ts
This PR:
- Adds telemetry around lookup modifier state when:
- A lookup quickpick is created, to track the initial state of modifiers
- A lookup modifier button is triggered, to track the frequency of manual button triggers.
- This change will track Lookup and all derivative commands that utilize the lookup controller.
Tracking events have been verified to correctly reach Segment.
This could be seen [here](https://app.segment.com/dendron/sources/ide_dev/debugger) by searching `Lookup_Modifier_`
- NOTE: if …
=> chore: add telemetry around lookup modifier state

packages/plugin-core/package.json, packages/plugin-core/src/commands/ShowNoteGraph.ts, packages/plugin-core/src/commands/ShowSchemaGraph.ts, packages/plugin-core/src/constants.ts
=> chore: renamed graph commands

packages/plugin-core/src/commands/InsertNoteCommand.ts, packages/plugin-core/src/commands/InsertNoteLink.ts, packages/plugin-core/src/commands/MoveHeader.ts, packages/plugin-core/src/commands/MoveNoteCommand.ts, packages/plugin-core/src/commands/RenameNoteV2a.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/test/suite-integ/LookupUtils.test.ts
This PR
- Abstracts the subscribe logic for the lookup provider history service.
- Refactors lookup derivative commands to use the abstracted logic.
- [~] if you are adding a new language feature (graphically visible in VS Code/preview/publishing), make sure that it is included in …
=> chore: lookup provider history service abstraction

pull_request_template.md
This PR:
- Updates the pull request template
- [~] make sure all the existing [tests](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#running-all-tests) pass
- [~] do a spot check by running your feature with our [test workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace)
- [~] after you submit your pull request, check the output of our [integration test](https://github.com/dendronhq/dendron/actions) and make sure all tests pass
- NOTE: if …
=> chore: update PR template

packages/engine-server/src/markdown/remark/hierarchies.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/footnotes.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/footnotes.spec.ts
=> fix: footnote definitions including links are rendered incorrectly

packages/engine-server/src/markdown/utilsv5.ts, packages/plugin-core/src/test/suite-integ/CodeActionProvider.test.ts, packages/plugin-core/src/test/testUtilsV3.ts, packages/plugin-core/src/utils/editor.ts
=> fix: apply enableUser/HashTags to broken wikilinks code action

packages/plugin-core/src/components/lookup/LookupControllerV3.ts
This PR
- Fixes payload of `LookupModifierToggledByUser` simpler so that it could be consumed without additional processing.
- NOTE: If you running MacOS or Linux, pay special attention to the Windows output and vice …
=> chore: make LookupModifierToggledByUser payload simpler

packages/common-all/src/dnode.ts, packages/plugin-core/src/test/suite-integ/CopyNoteLink.test.ts
- [~] if you are adding a new language feature (graphically visible in VS Code/preview/publishing), make sure that it is included in [test-workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace). We use this to manually inspect new changes and for auto regression testing
- [~] …
=> chore: copy a tag note link results in hashtags

packages/plugin-core/src/commands/MoveNoteCommand.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/test/suite-integ/LookupUtils.test.ts
This PR:
- Fixes a bug where vaults disappear intermittently
- Clean up a minor error in `MoveNoteCommand`
bug:
- There was a bug where one vault would be in the suggested vault in the vault selection quickpick but when we ran the command again, it disappeared.
- What actually happened is that:
1. The first quickpick also had a missing vault. (Had to watch the loom recording a million times to catch this :sweat_smile: )
2. This vault and the vault that disappeared on the second execution had the same `fsPath`, which the vault suggestion logic was using to sort the vaults before suggesting. 
3. After the sort, the vault suggestion util would go through the already suggested vaults and remaining vaults to add the outstanding vault suggestions. 
4. Here, one of the two vaults with the same …
=> fix: disappearing vaults in vault selection quickpick

packages/common-all/src/analytics.ts, packages/plugin-core/src/survey.ts
This PR:
- adds a prompt to the initial survey asking if they want to join the newsletter, which they can add in their email address.
- [~] If your tests changes an existing snapshot, make sure that snapshots are [updated](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#updating-test-snapshots)
- [~] If you are adding a new language feature (graphically visible in VS Code/preview/publishing), make sure that it is included in …
=> enhance: add newsletter subscription prompt for initial survey

packages/engine-server/src/markdown/utilsv5.ts, test-workspace/vault/dendron.ref.variables.md
This PR:
- exposes frontmatter property `desc` to the `fm` object for variable substition.
- this was a simple omission from the latest changes to variable substition.
- [~] If your tests changes an existing snapshot, make sure that snapshots are [updated](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#updating-test-snapshots)
- [~] If you are adding analytics related …
=> enhance: expose `desc` frontmatter property for variable substitution

packages/dendron-11ty/raw-assets/sass/minimal-mistakes/_sidebar.scss
=> fix: remove duplicate CSS

packages/engine-server/src/workspace/service.ts
This change removes a trailing whitespace in the default root note body.
```markdown
```
=> fix(workspace): remove trailing whitespace in note

packages/common-all/src/dnode.ts, packages/common-frontend/src/utils/tree-view.tsx, packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/markdown/remark/transformLinks.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/plugin-core/src/commands/MoveHeader.ts, packages/plugin-core/src/commands/MoveNoteCommand.ts, packages/plugin-core/src/utils/md.ts
=> chore: checks against fnames with all lowercase

packages/common-all/src/utils.ts, packages/engine-server/src/markdown/utilsv5.ts, packages/engine-server/src/migrations/migrations.ts, packages/engine-server/src/migrations/utils.ts, packages/engine-server/src/workspace/service.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/test/suite-integ/migration.test.ts, test-workspace/dendron.yml
This PR:
- fixes migration to not preserve `usePrettyRefs` at top level
- `usePrettyRefs` for publishing resides in site config so it should be unset with the migration.
- fixes issue with migration not unsetting keys that are listed in `DEPRECATED_PATHS`
- updates `dendron.yml` in `test-workspace`
- [~] If you are adding a new language feature (graphically visible in VS …
=> chore: preview config migration clean-up

packages/plugin-core/package.json, packages/plugin-core/src/constants.ts
Adds a Dendron preview button.
Also fixed a few places where changes were made to `plugin-core/package.json` but changes weren't made to the constants file where `package.json` is generated from.
=> feat: add Dendron preview button

packages/engine-server/src/markdown/remark/index.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/components/lookup/LookupControllerV3.ts, packages/plugin-core/src/components/lookup/LookupProviderV3.ts, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/components/lookup/types.ts, packages/plugin-core/src/test/suite-integ/LookupProviderV3.test.ts, test-workspace/vault/dendron.selection-to-items.md
This PR:
- Adds a new selection modifier `selection2Items`, which takes the selection from active note, extracts wikilinks from selection, and use the extracted wikilinks as possible lookup quickpick items.
This is a pre-cursor to [[Refactor from Selection|task.lookup.refactor-can-take-clipboard-as-multi-select-input]] that adds the needed base lookup functionality.
- [~] If your tests changes an existing snapshot, make sure that snapshots are [updated](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a3 …
=> enhance: lookup selection to items

packages/engine-test-utils/src/__tests__/pods-core/__snapshots__/podsv2.spec.ts.snap, packages/engine-test-utils/src/__tests__/pods-core/podsv2.spec.ts, packages/plugin-core/package.json, packages/plugin-core/src/commands/base.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/commands/pods/AirtableExportPodCommand.ts, packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/commands/pods/ExportPodV2Command.ts, packages/plugin-core/src/commands/pods/MarkdownExportPodCommand.ts, packages/plugin-core/src/components/pods/PodCommandFactory.ts, packages/plugin-core/src/components/pods/PodControls.ts, packages/plugin-core/src/constants.ts, packages/pods-core/src/builtin/index.ts, packages/pods-core/src/index.ts, packages/pods-core/src/v2/ConfigFileUtils.ts, packages/pods-core/src/v2/ExportPodBase.ts, packages/pods-core/src/v2/PodConfigManager.ts, packages/pods-core/src/v2/external-services/AirtableConnection.ts, packages/pods-core/src/v2/external-services/ExternalConnectionManager.ts, packages/pods-core/src/v2/podConfig/AirtablePodConfig.ts, packages/pods-core/src/v2/podConfig/MarkdownPodConfig.ts, packages/pods-core/src/v2/podConfig/PodV2Types.ts, packages/pods-core/src/v2/pods/export/AirtableExportPodV2.ts, packages/pods-core/src/v2/pods/export/MarkdownExportPodV2.ts
V2 prototype of pods, loosely following spec defined here https://github.com/dendronhq/dendron/discussions/1656. 
This is a refactor on how Pods work, particularly the existing export/publish workflow.
Changes:
- Removing the 1-1 mapping between pod type and pod config (via a YAML file).
- Pods now run against a dynamic config, which can be either persisted(currently via a YAML config file, but other implementations can be added), obtained from user input, or a combination of both.
- Multiple configs can be saved for the same pod type, i.e., one can have multiple airtable pod configs, one for each table or note/data type.
- Separating out pod config from external connection config(such as authenticated credentials to Google, Airtable, etc.). Multiple pod configs can re-use the same …
=> feat(pods): Export Pod V2

packages/common-all/package.json, packages/common-all/src/dnode.ts, yarn.lock
=> fix: Note titles containing international characters are correctly capitalized

packages/common-all/src/analytics.ts, packages/dendron-cli/src/commands/base.ts, packages/dendron-cli/src/utils/analytics.ts, packages/engine-server/src/metadata/service.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/base.spec.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/components/lookup/LookupControllerV3.ts, packages/plugin-core/src/components/lookup/LookupProviderV3.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/survey.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
This PR contains various tasks related to metrics.
- [~] If your tests changes an existing snapshot, make sure that snapshots are [updated](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#up …
=> chore: various metrics tasks

packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/test/suite-integ/autoCompleter.test.ts, packages/plugin-core/src/utils/autoCompleter.ts, test-workspace/vault/dendron.note-lookup.md
=> enhance: have auto complete respect value that has been scrolled down  to by arrows

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/config/issue-labler/labler-v4.yml
Update the bug and feature request issue templates + the issue labeler to accomodate the new scope.* based area tags.
---
```markdown
```
=> chore: update github issue labeler for scope tags

packages/dendron-plugin-views/package.json
Fixes an error when building on Windows by adding `cross-env` to the npm build command parameters.
```markdown
```
=> fix: add cross-env for win build script

packages/dendron-cli/src/commands/devCLICommand.ts
This PR
- fixes `run_migration` in cli to respect JSONC when reading workspace config
- …
=> fix: cli migration now handles JSONC for wsConfig

package.json, packages/plugin-core/package.json, yarn.lock
Dropping `--packagePath` argument from ovsx command.
---
```markdown
```
=> chore: fix ovsx command to publish .vsix file

packages/plugin-core/package.json, packages/plugin-core/webpack.common.js, yarn.lock
There's a webpack plugin that can help us identify circular dependencies. I'm adding it to the dev webpack step, currently set to warn (not error out).
The results of the analysis are listed at [[dendron://private/scratch.2021.11.12.143118.circular-dependency-issues-with-0682#dec-1st-analysis-via-circular-depedency-webpack-analyzer]].  Most of the circular deps revolve around `workspace.ts`, `utils.ts`, and `/components/lookup/utils.ts`.  Fixing the circular deps is deferred to part 2.
Example PR …
=> chore: add circular dep plugin tool to webpack

packages/plugin-core/src/commands/InsertNoteLink.ts, packages/plugin-core/src/commands/MoveNoteCommand.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/commands/RefactorHierarchyV2.ts, packages/plugin-core/src/components/lookup/LookupControllerV3.ts, packages/plugin-core/src/components/lookup/LookupProviderV3.ts, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/components/lookup/types.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/test/suite-integ/LookupProviderV3.test.ts, packages/plugin-core/src/test/suite-integ/RefactorHierarchy.test.ts, test-workspace/vault/dendron.selection-to-items.md
This PR
- Adds scoping capability to refactor hierarchy command
- Can choose to use all notes or use `selection2Items` and `multiSelect` to cherry pick notes to refactor through lookup
- Add full regular expression support for capturing stage
- Add full regular expression support for replacing stage
- NOTE: If you running MacOS or Linux, pay …
=> enhance: enable scoping and full regex support for refactor hierarchy command

packages/plugin-core/src/commands/pods/AirtableExportPodCommand.ts, packages/pods-core/src/builtin/AirtablePod.ts, packages/pods-core/src/v2/podConfig/AirtablePodConfig.ts
A few small fixes in the airtable v2 export pod
---
```markdown
```
=> fix: minor error in airtable v2 export pod

packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/test/suite-integ/WorkspaceInit.test.ts, packages/plugin-core/src/test/testUtilsV3.ts, packages/plugin-core/src/test/testUtilsv2.ts
Fixes a regression introduced with https://github.com/dendronhq/dendron/pull/1827
Because the registerProvider functionality was moved out of the singleton Workspace/DendronExtension class, we must properly dispose of them on each test. Otherwise, we will register a new provider on each test run, causing many duplicate providers to get registered. This causes massive slowdown on tests and other issues as well.
--- 
```markdown
This changes capitalizes all occurrences of `foo` to …
```
=> chore: properly dispose resources in tests

packages/dendron-cli/src/commands/doctor.ts, packages/engine-server/src/doctor/service.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/doctor.spec.ts, packages/plugin-core/src/commands/Doctor.ts, packages/plugin-core/src/test/suite-integ/DoctorCommand.test.ts, test-workspace/vault/dendron.ref.links.md
This PR:
- adds a doctor command to cli and plugin
- plugin: finds all broken links and opens a webview with the list of broken links (if there are any)
- cli: finds all broken links and prints them as json
- [~] If your tests changes an existing snapshot, make sure that snapshots are [updated](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#updating-test-snapshots)
- [~] If you are adding a new language feature (graphically visible in VS Code/preview/publishing), make sure that …
=> feat: find broken links

packages/plugin-core/src/commands/pods/MarkdownExportPodCommand.ts, packages/plugin-core/src/components/pods/PodControls.ts
Makes a few adjustments to Pod V2 UI, mainly addressing point outlined in [
](https://github.com/dendronhq/dendron/pull/1772#pullrequestreview-813163713)
- Add a Go to Config File button in Markdown Export
- Added descriptions and titles for Export Scope Quick Pick and Pod V2 Types
- Added missing `ignoreFocusOut` props for a few picker controls.
---
```markdown
```
- All PRs should start with …
=> enhance: small tweaks to pod v2 UI

packages/common-all/src/constants/views.ts, packages/common-all/src/index.ts, packages/common-all/src/types/typesv2.ts, packages/common-frontend/src/features/ide/slice.ts, packages/plugin-core/src/commands/ConfigureWithUI.ts, packages/plugin-core/src/commands/SeedBrowseCommand.ts, packages/plugin-core/src/commands/SeedCommandBase.ts, packages/plugin-core/src/commands/ShowNoteGraph.ts, packages/plugin-core/src/commands/ShowPreview.ts, packages/plugin-core/src/commands/ShowSchemaGraph.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/views/DendronTreeViewV2.ts, packages/plugin-core/src/views/utils.ts, packages/plugin-core/src/windowWatcher.ts, packages/plugin-core/src/workspace.ts
- consolidate views
- simplify tree view setup
```markdown
```
=> chore(views): simplify tree view setup

packages/plugin-core/src/WelcomeUtils.ts
If a user has exiting workspaces in our default paths for the tutorial on first launch, they'll get the standard prompts for `InitializeWorkspace` command when running `Launch Tutorial` command instead of getting taken directly to the tutorial workspace.
---
```markdown
```
=> fix: tutorial initializer with existing ws in default paths

packages/plugin-core/src/commands/RefactorHierarchyV2.ts
This PR:
- Reverts the match text prompt behavior to show active note's name if available.
- NOTE: If you running MacOS or Linux, pay special attention to the Windows output and vice versa if you are developing on …
=> fix: revert match text default value to active note name

packages/plugin-core/src/commands/CreateNoteWithTraitCommand.ts, packages/plugin-core/src/traits/UserDefinedTraitV1.ts, packages/plugin-core/src/traits/webpack-require-hack.ts
Note traits dynamic .js wasn't working with a webpack built image. I've added the require webpack hack, which is the same mechanism used for hooks.  I also made some fixes to the lookup controller invoked with the create note with trait command.
---
```markdown
```
=> fix: note traits not working after webpack

.npmrc
The npmrc file that was introduced is blocking npm scripts from running when the NPM_TOKEN env variable is not set.
I'm removing the file, as we only need this during publishing - which should be largely handled in the automated pipeline going forward anyway.
---
```markdown
```
=> fix: delete npmrc

packages/dendron-cli/src/commands/publishCLICommand.ts, packages/dendron-cli/src/commands/utils.ts
=> feat: replaced instances of 'spwan' with 'spawn'.

packages/plugin-core/src/commands/pods/AirtableExportPodCommand.ts, packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/commands/pods/GoogleDocsExportPodCommand.ts, packages/plugin-core/src/commands/pods/MarkdownExportPodCommand.ts, packages/pods-core/src/v2/podConfig/AirtablePodConfig.ts, packages/pods-core/src/v2/podConfig/GoogleDocsConfig.ts, packages/pods-core/src/v2/podConfig/MarkdownPodConfig.ts
PR to add validation for pod's runnable config schema.
=> chore: added ajv validation for runnable config

packages/common-all/src/md.ts, packages/plugin-core/src/features/completionProvider.ts, packages/plugin-core/src/test/suite-integ/CompletionProvider.test.ts
=> fix: autocomplete deletes text following wikilink with no closing brackets

.github/workflows/publish-extension-dendron.yml
Adding back the logical change from https://github.com/dendronhq/dendron/pull/1898/files into the build pipeline for `Publish-Extension-Dendron`
---
```markdown
```
=> chore: add npmrc file gen in pub ext dendron workflow

packages/plugin-core/src/KeybindingUtils.ts, packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/commands/pods/ExportPodV2Command.ts, packages/plugin-core/src/components/pods/PodControls.ts
- make it such that you can add a keyboard shortcut to run a pod v2 export for a certain config
- have the keyboard shortcut show up in the quick pick
- Add a progress bar on export
`keybinding.json` example:
```json
{
"key": "cmd+k t",
"command": "dendron.exportPodv2",
"args": "dendron-tasks"
},
```
---
```markdown
```
- All PRs should start with …
=> enhance(pod): add keybinding shortcuts to pod v2

packages/engine-server/src/seed/registry.ts
=> fix: xkcd seed vault description

packages/plugin-core/src/commands/pods/AirtableExportPodCommand.ts, packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/commands/pods/GoogleDocsExportPodCommand.ts, packages/plugin-core/src/commands/pods/MarkdownExportPodCommand.ts, packages/plugin-core/src/components/lookup/HierarchySelector.ts, packages/plugin-core/src/test/suite-integ/components/pods/BaseExportPodCommand.test.ts, packages/plugin-core/src/test/suite-integ/components/pods/TestExportCommand.ts, packages/plugin-core/src/test/testUtilsV3.ts, packages/pods-core/src/v2/ExportPodBase.ts, packages/pods-core/src/v2/pods/export/AirtableExportPodV2.ts
Building out more functionality in pods v2: implement export scopes for hierarchy and workspace.
---
```markdown
```
=> enhance(pods): support export hierarchy and workspace

packages/common-all/src/dnode.ts, packages/engine-server/src/markdown/remark/utils.ts, packages/engine-test-utils/src/presets/engine-server/init.ts, packages/plugin-core/src/commands/DeleteNodeCommand.ts, packages/plugin-core/src/features/FrontmatterFoldingRangeProvider.ts, packages/plugin-core/src/test/suite-integ/DeleteNodeCommand.test.ts, packages/plugin-core/src/windowWatcher.ts
This PR:
- adds a preview of delete node when the command is run on a note that will create broken links if deleted
As a follow-up enhancement, various convenience commands to convert broken links will be added.
- …
=> enhance: better delete node

packages/engine-server/src/markdown/remark/utils.ts, packages/engine-server/src/markdown/remark/wikiLinks.ts, packages/plugin-core/package.json, packages/plugin-core/src/commands/ConvertCandidateLink.ts, packages/plugin-core/src/commands/ConvertLink.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/features/BacklinksTreeDataProvider.ts, packages/plugin-core/src/features/completionProvider.ts, packages/plugin-core/src/test/suite-integ/ConvertLink.test.ts, test-workspace/vault/dendron.ref.links.md
This PR:
- renames internal command `dendron.convertLink` to `dendron.convertCandidateLink`, that was used in the backlinks panel to convert candidate links to wikilinks
- hides `dendron.convertCandidateLink` from userland as this is not functional outside of the backlinks panel context.
- implements `Dendron: Convert Link`, which can
- convert broken links to plaintext. user is prompted to choose what part of the link text to use.
- choices
- alias: use link's alias if exists (otherwise option isn't suggested)
- note name: use link destination's note name (basename excluding all parent hierarchies)
- hierarchy: use link destination's entire hierarchy
- prompt: user is prompted to manually input text to use
- change destination: user is prompted a lookup to choose a different existing …
=> feat: convert link command

packages/engine-server/src/workspace/service.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/services/stateService.ts, packages/plugin-core/src/workspace.ts
Add documentation on how `dendorn.yml` configuration is changed during upgrades
=> chore(docs): document migratioon process

packages/plugin-core/src/components/lookup/LookupProviderV3.ts, packages/plugin-core/src/test/suite-integ/SchemaLookupCommand.test.ts
- Instead of a warning message, show a modal message
Testing
- Added test case to check for warning message
- Verified manually by performing multilevel schema lookup
=> chore(lookup): Better schema lookup error message

packages/nextjs-template/components/DendronLayout.tsx, packages/nextjs-template/components/DendronTreeMenu.tsx
Left pic with fix and right pic without
=> fix(fix(publish): hamburger display in wrong position

packages/plugin-core/src/commands/OpenLink.ts, packages/plugin-core/src/test/suite-integ/PasteLink.test.ts, packages/plugin-core/src/utils.ts, packages/plugin-core/src/workspace.ts
also remove deprecated and un-used methods
```markdown
```
=> chore(test): update paste link to new style tests

.github/workflows/publish-extension-nightly.yml
=> chore: run Nightly build on Mondays

packages/common-server/src/analytics.ts, packages/dendron-cli/src/commands/base.ts
This PR
- Adds `userAgent: "vscode" | "cli"` to track call properties.
- Adds `.identify()` calls to cli commands.
- NOTE: If you running MacOS or Linux, pay special attention to the Windows output and vice versa if …
=> enhance: track user agent

packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/SeedCommandBase.ts, packages/plugin-core/src/commands/base.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/types.ts
Seed command expects a panel as first argument. Take it out of command
registration. Also did some refactoring of registering commands
=> fix(commands): seed commands broken by refactor

packages/plugin-core/package.json, packages/plugin-core/src/commands/DevTriggerCommand.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts
Will add a mention in dev tips section when merged. 
=> chore: add DevTrigger command for more convinient development environment

packages/plugin-core/src/commands/VaultConvert.ts
This PR closes #1991 and displays the correct convert message when converting to a remote vault. No tests were added as it is a fix to existing string.
```markdown
```
=> fix(workspace): convertVault Typo

pull_request_template.md
Update links and make template more concise
=> chore(internal): update pr template

README.md, packages/plugin-core/README.md
This change adds extra badges to the readme files, syncs the readmes with their latest content and updated links
=> chore(docs): badges and tweaks to readme files

packages/engine-server/src/markdown/remark/backlinks.ts, packages/engine-server/src/markdown/remark/hierarchies.ts, packages/engine-server/src/markdown/utilsv5.ts, packages/engine-test-utils/src/__tests__/api-server/notes.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/backlinks.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/blockAnchors.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/container.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/dendronPub.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/extendedImage.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/footnotes.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/hashtag.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/hierarchies.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/noteRefv2.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/userTags.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/wikiLink.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/v5/__snapshots__/hierarchies.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/v5/__snapshots__/image.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/v5/__snapshots__/mermaid.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/v5/__snapshots__/noteRef.spec.ts.snap, packages/nextjs-template/components/DendronTOC.tsx
BREAKING: change backlinks and child links from `<h2> to <strong>`
BREAKING: change order of sections (child links come before backlinks)
BREAKING: remove backlinks and child links from toc
=> enhance(markdown): various updates to backlinks and child links

.github/workflows/publish-extension-dendron.yml
The .npmrc file was getting written to before the token env var was set.
---
=> chore: change order of setting npm token env var

packages/engine-server/src/migrations/service.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/constants.ts
Also add slight refactoring on startup logic
=> fix(workspace): don't show calendar view unless dendron tree view is active

packages/engine-server/src/markdown/remark/backlinks.ts, packages/engine-server/src/markdown/remark/hierarchies.ts, packages/engine-server/src/markdown/utilsv5.ts, packages/engine-server/src/topics/site.ts, packages/engine-server/src/utils.ts, packages/engine-test-utils/src/__tests__/api-server/notes.spec.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/backlinks.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/blockAnchors.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/container.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/dendronPub.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/extendedImage.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/footnotes.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/hashtag.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/hierarchies.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/noteRefv2.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/userTags.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/wikiLink.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/v5/__snapshots__/hierarchies.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/v5/__snapshots__/image.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/v5/__snapshots__/mermaid.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/v5/__snapshots__/noteRef.spec.ts.snap, packages/nextjs-template/components/DendronTOC.tsx
Make publishing more clear. Also fix bug where `custonFrontmatter` field from `hConfig` was not being applied
=> chore: cleanup site publish logic

packages/plugin-core/src/ExtensionProvider.ts, packages/plugin-core/src/WSUtilsV2.ts, packages/plugin-core/src/WSUtilsV2Interface.ts, packages/plugin-core/src/WorkspaceWatcher.ts, packages/plugin-core/src/commands/CreateSchemaFromHierarchyCommand.ts, packages/plugin-core/src/commands/ShowPreview.ts, packages/plugin-core/src/dendronExtensionInterface.ts, packages/plugin-core/src/services/SchemaSyncService.ts, packages/plugin-core/src/services/SchemaSyncServiceInterface.ts, packages/plugin-core/src/test/suite-integ/WindowWatcher.test.ts, packages/plugin-core/src/test/suite-integ/WorkspaceWatcher.test.ts, packages/plugin-core/src/vsCodeUtils.ts, packages/plugin-core/src/workspace.ts
From 167 to 126 circular dependencies.
Note: removed   getMatchingTextDocument from vsCodeUtils since it wasn't being used and was dragging a heavy dependnecy in. 
=> chore: Add interface for SchemaSyncService

packages/plugin-core/src/components/lookup/LookupControllerV3.ts
This PR:
- Fixes a regression introduced by #2004 where the `onTriggerButton` was not properly getting access of `this`.
- This is fixed by changing the `onTriggerButton` back to an arrow function instead of it being a function expression.
- We can instead keep `onTriggerButton` as a function expression but instead bind them to `this` in the class. Arguably the _better_ way to do it as it can have potential performance / inheritance issues, but since lookup controllers are always created and disposed in the lifecycle of a lookup (derivative) command, I don't think that's a necessary change that we should introduce right now. We should maybe consider it in the future if this no longer is the case.
If this is your first time submitting a pull request to Dendron, copy and paste the full …
=> fix: regression on onTriggerButton not scoping properly

packages/common-test-utils/src/presets/notes.ts, packages/engine-test-utils/src/__tests__/pods-core/podsv2.spec.ts, packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/commands/pods/MarkdownExportPodCommand.ts, packages/pods-core/src/v2/podConfig/MarkdownPodConfig.ts, packages/pods-core/src/v2/pods/export/MarkdownExportPodV2.ts
=> enhance(pods): config settings for user tags and hashtags in markdown export pod v2 

packages/engine-server/src/markdown/remark/utils.ts, packages/plugin-core/src/ExtensionProvider.ts, packages/plugin-core/src/commands/RefactorHierarchyV2.ts, packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/components/pods/PodControls.ts, packages/plugin-core/src/test/suite-integ/components/pods/BaseExportPodCommand.test.ts, packages/pods-core/src/v2/podConfig/PodV2Types.ts
This PR:
- Adds a new pod export source `LinkInSelection` that lets you export notes that are in selection (as wikilink).
- Adds a new pod export source `Lookup` that lets you lookup / select notes to export.
- …
=> enhance: add LinkInSelection and Lookup pod export source

packages/common-all/src/types/foundation.ts, packages/plugin-core/src/commands/pods/AirtableExportPodCommand.ts, packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/commands/pods/MarkdownExportPodCommand.ts, packages/plugin-core/src/test/suite-integ/components/pods/TestExportCommand.ts, packages/pods-core/src/builtin/AirtablePod.ts, packages/pods-core/src/v2/pods/export/AirtableExportPodV2.ts
- chore(internal): clean up unused bootstrap scripts
- error message when single tag field is wrong
- introduce new note props type
- - make onExportComplete be async - await on async exports inside BaseExportPod
- update export pod logic
=> enhance(pods): various airtable pod enhancements

packages/pods-core/src/builtin/AirtablePod.ts
=> fix(pod): issue with linkedRecord not getting correct airtable id

packages/engine-test-utils/src/__tests__/pods-core/podsv2.spec.ts, packages/plugin-core/src/commands/pods/AirtableExportPodCommand.ts, packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/commands/pods/ConfigureExportPodV2.ts, packages/plugin-core/src/commands/pods/ConfigureServiceConnection.ts, packages/plugin-core/src/commands/pods/MarkdownExportPodCommand.ts, packages/plugin-core/src/components/pods/PodControls.ts, packages/plugin-core/src/test/suite-integ/components/pods/BaseExportPodCommand.test.ts, packages/plugin-core/src/test/suite-integ/components/pods/TestExportCommand.ts, packages/pods-core/src/v2/ExportPodBase.ts, packages/pods-core/src/v2/podConfig/PodV2Types.ts, packages/pods-core/src/v2/pods/export/AirtableExportPodV2.ts, packages/pods-core/src/v2/pods/export/MarkdownExportPodV2.ts
- [~] [Write Tests](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#writing-tests) 
- [~] If your tests changes an existing snapshot, make sure that snapshots are [updated](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#updating-test-snapshots)
- [ ~] If you are adding a new language feature (graphically visible in VS Code/preview/publishing), make sure that it is included in the [test workspace](https://docs.dendron.so/notes/dtMsF12SF2SUhLN10sYe2.html)
- [ ~] …
=> chore: removed exportText from ExportpodV2 interface

packages/plugin-core/src/components/pods/PodControls.ts
Reimplementing a pod circular dependency fix that was accidentally removed during a previous merge conflict resolution.  This deletes an unused method and gets rid of 
```typescript
import { PodCommandFactory } from "./PodCommandFactory";
```
---
=> chore: re-implementing pod circ dep fix

packages/plugin-core/src/components/lookup/ButtonTypes.ts, packages/plugin-core/src/components/lookup/LookupControllerV3.ts, packages/plugin-core/src/components/lookup/LookupControllerV3Interface.ts, packages/plugin-core/src/components/lookup/LookupProviderV3.ts, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/components/lookup/types.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts, packages/plugin-core/src/test/suite-integ/buttons.test.ts, packages/plugin-core/src/test/testUtils.ts, packages/plugin-core/src/views/LookupView.ts
Simple change that gets rid of about ~10 circular dependencies: Separate out `button.ts` types into a separate file for some of the methods that don't take a static dep on `ExtensionProvider`.
Down to 66 circular dependencies in plugin-core after this change.
---
=> chore(dev): remove circular dependencies with button.ts

packages/plugin-core/src/views/DendronTreeViewV2.ts, packages/plugin-core/src/views/utils.ts, packages/plugin-core/src/workspace.ts
- https://github.com/dendronhq/dendron/commit/b66032fef1b8cb5f7a6fa522a5e0ad14ac4d8388 - this change introduced a fix to have tree view update when the frontmatter of a note got edited.  However, it also introduced a bug where tree view would re-appear when editing a note, even if it were hidden
- https://github.com/dendronhq/dendron/pull/2049 - this accidentally removed both the fix and the bug of the above change during merge resolution
This change re-adds the fix but also addresses the panel pop up bug.  Furthermore, I did a few small changes to remove circular dependency issues associated with `DendronTreeViewV2.ts`
NOTE: some refresh scenarios still don't work in TreeViewV2 (and weren't working, even after https://github.com/dendronhq/dendron/commit/b66032fef1b8cb5f7a6fa522a5e0ad14ac4 …
=> fix(views): tree view refresh and circ dependency removal

packages/engine-test-utils/src/__tests__/pods-core/v2/AirtableExportPodV2.spec.ts, packages/pods-core/src/v2/podConfig/AirtablePodConfig.ts, packages/pods-core/src/v2/podConfig/PodV2Types.ts, packages/pods-core/src/v2/pods/export/AirtableExportPodV2.ts
This helps debug which record caused an error
=> enhance(pod): show payload of records on error

packages/engine-server/src/util/noteMetadataUtils.ts, packages/engine-test-utils/src/__tests__/pods-core/v2/AirtableExportPodV2.spec.ts, packages/engine-test-utils/src/__tests__/pods-core/v2/__snapshots__/AirtableExportPodV2.spec.ts.snap, packages/pods-core/src/builtin/AirtablePod.ts, packages/pods-core/src/v2/podConfig/PodV2Types.ts
Also support required field for number field.  Next task is to support
required field on all tasks
=> enhance(pod): support number field for airtable

packages/engine-server/src/util/noteMetadataUtils.ts, packages/engine-test-utils/src/__tests__/engine-server/noteMetaDataUtils.spec.ts, packages/engine-test-utils/src/__tests__/pods-core/v2/__snapshots__/AirtableExportPodV2.spec.ts.snap, packages/pods-core/src/builtin/AirtablePod.ts, packages/pods-core/src/v2/podConfig/PodV2Types.ts
Docs:
https://github.com/dendronhq/dendron-site/commit/9f9e1ae26b5cc57d775accd16e0556125075b004
=> enhance(pod): Support Null and Required Properties for Scalar Values

packages/engine-test-utils/src/__tests__/pods-core/podsv2.spec.ts, packages/plugin-core/src/commands/pods/NotionExportPodCommand.ts, packages/plugin-core/src/components/pods/PodCommandFactory.ts, packages/plugin-core/src/components/pods/PodControls.ts, packages/pods-core/src/index.ts, packages/pods-core/src/v2/ConfigFileUtils.ts, packages/pods-core/src/v2/external-services/ExternalConnectionManager.ts, packages/pods-core/src/v2/external-services/NotionConnection.ts, packages/pods-core/src/v2/index.ts, packages/pods-core/src/v2/podConfig/NotionPodConfig.ts, packages/pods-core/src/v2/podConfig/PodV2Types.ts, packages/pods-core/src/v2/podConfig/index.ts, packages/pods-core/src/v2/pods/export/NotionExportPodV2.ts
migrates notion export to pods v2
=> chore(pods): migrate notion export pod to v2

packages/common-all/src/analytics.ts, packages/common-all/src/constants.ts, packages/common-all/src/constants/configs/compat.ts, packages/common-all/src/index.ts, packages/common-all/src/utils.ts, packages/dendron-cli/src/commands/base.ts, packages/dendron-cli/src/commands/devCLICommand.ts, packages/dendron-cli/src/utils/analytics.ts, packages/dendron-cli/src/utils/cli.ts, packages/engine-server/src/migrations/service.ts, packages/engine-server/src/migrations/types.ts, packages/engine-server/src/workspace/service.ts, packages/engine-test-utils/src/__tests__/common-all/config.spec.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/RunMigrationCommand.ts, packages/plugin-core/src/test/suite-integ/migration.test.ts
This PR:
- adds compatibility validation for config and client.
- adds validation logic to CLI commands
- all cli commands excluding `dendron dev` will have have this validation logic running prior to execution.
- when there is a client / config compatibility mismatch, the process will exit and display a message informing how to fix it.
- ![image](https://user-images.githubusercontent.com/1219789/148946941-84e975ea-44b1-4076-a4b9-c56e8d864724.png)
- ![image](https://user-images.githubusercontent.com/1219789/148947400-d5aea879-19e2-4c97-90cf-ad75ad958eb3.png)
- later this will be enhanced to have an option to pass `--yes` to automatically fix (if possible) the mismatch (useful in CI/CD)
- adds tracking of client / config mismatch events
- fixes client version fetching logic in CLI (will …
=> enhance: detect config / client compatibility mismatch in cli

packages/engine-test-utils/src/__tests__/pods-core/podsv2.spec.ts, packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/commands/pods/JSONExportPodCommand.ts, packages/plugin-core/src/commands/pods/MarkdownExportPodCommand.ts, packages/plugin-core/src/components/pods/PodCommandFactory.ts, packages/plugin-core/src/components/pods/PodControls.ts, packages/plugin-core/src/test/suite-integ/components/pods/JSONExportCommand.test.ts, packages/pods-core/src/v2/ConfigFileUtils.ts, packages/pods-core/src/v2/index.ts, packages/pods-core/src/v2/podConfig/JSONPodConfig.ts, packages/pods-core/src/v2/podConfig/PodV2Types.ts, packages/pods-core/src/v2/podConfig/index.ts, packages/pods-core/src/v2/pods/export/JSONExportPodV2.ts
=> chore(pods): migrated json export pod to v2

packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/utils.ts, packages/plugin-core/src/commands/RenameNoteV2a.ts, packages/plugin-core/src/test/suite-integ/RefactorHierarchy.test.ts
details of fix process in [[Refactor Issue|dendron://private/user.kevin.journal.2022.01.13.s.refactor-issue]]
=> fix(refactor): bad refactor logic

packages/plugin-core/src/_extension.ts, packages/plugin-core/src/services/EngineAPIService.ts, packages/plugin-core/src/views/CalendarView.ts, packages/plugin-core/src/workspace.ts
Removes circular dependencies on EngineAPIService and CalendarView
---
=> chore: circ dep EngineAPIService and CalendarView

packages/common-server/src/git.ts, packages/dendron-cli/src/commands/publishCLICommand.ts, packages/pods-core/src/builtin/NextjsExportPod.ts
Verify that the repository is using the expected remotes, the correct branch is checked out, the branch tracks the correct remote branch and that the working tree is clean.
If it is, issue a git fetch followed by git reset.
If any of the checks fail, we fall back to removing the .next directory and trying again.
- I didn't see existing tests for the `publish init` command -- happy to add some that cover these Git operations.
=> enhance(publish): attempt to update template in-place

packages/engine-server/src/markdown/remark/hashtag.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/hashtag.spec.ts
Fixes #2148
Adds `()` characters to the `PUNCTUATION_MARKS` character list. Added it closer to start of string because I suspect they are more common than the other ones that were already there.
Adds assertion in existing and related unit test case.
Kudos to @SeriousBug for pointers to relevant code so I didn't have to waste time on finding those. 🙇 
---
If this is your first time submitting a pull request to Dendron, copy and paste the full [Dendron Review Checklist](https://docs.dendron.so/notes/1EoNIXzgmhgagqcAo9nDn.html) into this request and check off each item as necessary.
- ~~[ ] if your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR~~
- I tried to test manually …
=> fix(tags): Exclude parenthesis from tags

packages/plugin-core/package.json, packages/plugin-core/src/constants.ts, packages/plugin-core/src/features/ReferenceHoverProvider.ts, packages/plugin-core/src/test/suite-integ/ReferenceProvider.test.ts
=> fix: renamed command from goto note to go to note

.github/workflows/create-release-image.yml, .github/workflows/proto.yml, .github/workflows/publish-extension-dendron.yml, .github/workflows/publish-extension-nightly.yml
This PR fixes a typo in the GitHub Actions username. It is a cosmetic thing, but I noticed [this](https://github.com/dendronhq/dendron/commit/8ceaf215ee34a23ca9a8e2d0fff5e8ce3a08f3a0) commit and realized that the username used in the workflows is incorrect. As per the [checkout action readme](https://github.com/actions/checkout#push-a-commit-using-the-built-in-token), the username should actually be `github-actions` and not `github.actions`.
=> chore: fix typo in github-actions username

hooks/pre-commit.js, hooks/pre-push.js, package.json, yarn.lock
BREAKING: adds madge as a dev-dependency; requires madge installation in your local dev environment
Simple hook for now to add warning text to the husky hook with a madge report on the count of circular dependencies. Adding a delta is a bit more involved (need to modify local git state), so I'll defer on that for now.
---
=> chore: hook for soft warning on circular dependency

packages/nextjs-template/components/DendronLayout.tsx, packages/nextjs-template/components/DendronLogoOrTitle.tsx
- Fix title wrap on mobile
- Fix hamburger button offset on mobile
https://github.com/dendronhq/dendron/issues/2159
Video:
https://drive.google.com/file/d/1vCqYasHUxp6ZvB4aAlmq7HIvvpEJWfmz/view?usp=sharing
https://drive.google.com/file/d/1PZt3kOkrbFJIM5lsz7UjaFd8cutvzrBy/view?usp=sharing
=> fix: title wrap and hamburger offset on mobile

packages/plugin-core/src/components/lookup/LookupProviderV3.ts, packages/plugin-core/src/components/lookup/NotePickerUtils.ts, packages/plugin-core/src/components/lookup/SchemaPickerUtils.ts, packages/plugin-core/src/components/lookup/constants.ts, packages/plugin-core/src/components/lookup/utils.ts, packages/plugin-core/src/utils/autoCompleter.ts
Fix #1246: "Note does not exist. Create?" should read "Schema does not exist. Create?" in Schema Lookup
=> fix(lookup): "Note does not exist. Create?" should read "Schema does not exist. Create?" in Schema Lookup

packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/commands/pods/ExportPodV2Command.ts, packages/plugin-core/src/components/pods/PodCommandFactory.ts
Docs PR: https://github.com/dendronhq/dendron-site/pull/374
---
madge report:
- master: 65 circular dependencies
- this branch: 65 circular dependencies
---
=> enhance(pods): add exportScope to podsv2  keybinding shortcuts

docs/README.md
This fixes https://github.com/dendronhq/dendron/issues/1912
=> chore(docs): fix broken developer links

packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/pods-core/src/builtin/AirtablePod.ts, packages/pods-core/src/v2/pods/export/AirtableExportPodV2.ts
This PR improves the error feedback to a user.
=> chore(pods): improve error feedback to user

packages/plugin-core/package.json, packages/plugin-core/scripts/genConfig.ts, packages/plugin-core/src/WSUtils.ts, packages/plugin-core/src/WSUtilsV2.ts, packages/plugin-core/src/WSUtilsV2Interface.ts, packages/plugin-core/src/commands/LookupJournalNoteCommand.ts, packages/plugin-core/src/commands/LookupScratchNoteCommand.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/LookupJournalNoteCommand.test.ts, packages/plugin-core/src/test/suite-integ/LookupScratchNoteCommand.test.ts
This PR:
- Registers separate commands `Dendron: Lookup Journal Note` and `Dendron: Lookup Scratch Note`
- [~] [Write Tests](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#writing-tests) 
- [~] If your tests changes an existing snapshot, make sure that snapshots are [updated](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#updating-test-snapshots)
- [~] If you are adding a new language feature (graphically visible in VS Code/preview/publishing), make sure that …
=> chore: separate journal scratch commands

packages/common-all/src/analytics.ts, packages/dendron-cli/src/commands/doctor.ts, packages/engine-server/src/doctor/service.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/doctor.spec.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/Doctor.ts, packages/plugin-core/src/components/doctor/buttons.ts, packages/plugin-core/src/components/doctor/types.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/dendronExtensionInterface.ts, packages/plugin-core/src/features/codeActionProvider.ts, packages/plugin-core/src/test/suite-integ/DoctorCommand.test.ts
This PR:
- Adds warning for conflicting extensions
- Will only warn when in Dendron Workspace
- Will show a warning message with a button that opens a webview
- Webview will show instructions for how to disable certain extensions per workspace
- Webview will list conflicting extensions along with a `commandUri` that will open the `Extensions` panel in vscode with the corresponding extension id pre-filled in the query.
Warning message displayed on activation if in Dendron workspace
Webview with instructions
Extensions panel with query pre-filled open when clicking `View Extension`
Since it isn't straightforward to write integ tests for this, I've manually tested with all extensions listed in `CONFLICTING_EXTENSIONS` and confirmed that they trigger the warning and correctly show up in the …
=> enhance(workspace): conflicting extension warning

packages/dendron-cli/src/commands/publishCLICommand.ts, packages/engine-server/src/markdown/remark/dendronPub.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/v5/__snapshots__/image.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/v5/image.spec.ts
Related issue https://github.com/dendronhq/dendron/issues/2356 and https://github.com/dendronhq/dendron/issues/2355
=> fix(publish): skip adding asset prefix to images with web url

packages/engine-test-utils/src/__tests__/pods-core/MarkdownPod.spec.ts, packages/pods-core/src/builtin/MarkdownPod.ts
Related to  https://github.com/dendronhq/dendron/issues/1237
=> fix(pod): markdown import to update asset references

bootstrap/scripts/package.json, package.json, packages/api-server/package.json, packages/common-all/package.json, packages/common-frontend/package.json, packages/common-server/package.json, packages/common-test-utils/package.json, packages/dendron-cli/package.json, packages/engine-server/package.json, packages/engine-test-utils/package.json, packages/lsp-client/package.json, packages/nextjs-template/package.json, packages/plugin-core/package.json, packages/pods-core/package.json
causing slowdown in regular dev process. will investigate later to see
if it makes sense to incorporate
=> chore(dev): remove incremental build

packages/common-all/src/dnode.ts, packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
- General
- Operations
- Architecture
=> fix(workspace): correct title generartion for notes with sub-hierarchy starting with .md

packages/dendron-cli/.vscode/tasks.json, packages/dendron-cli/src/commands/pod.ts, packages/dendron-cli/src/commands/publishPod.ts
Related to : https://github.com/dendronhq/dendron/issues/2345
=> fix(pod): acknowledge cli args for publish pod

.github/workflows/ci.yml
This also limits the playwright test to only run on a single test suite in the matrix (extra runners are redundant since we are testing across browsers, not operating systems)
- General
- Operations
- Architecture
N/A
N/A
N/A
N/A
N/A
=> chore(build): overwrite old files when unzipping assets for playwright test

packages/plugin-core/package.json, packages/plugin-core/src/commands/CreateJournalNoteCommand.ts, packages/plugin-core/src/commands/CreateScratchNoteCommand.ts, packages/plugin-core/src/commands/NoteLookupCommand.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/components/lookup/LookupControllerV3.ts, packages/plugin-core/src/components/lookup/LookupControllerV3Factory.ts, packages/plugin-core/src/components/lookup/LookupControllerV3Interface.ts, packages/plugin-core/src/components/lookup/buttons.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/CreateJournalNoteCommand.test.ts, packages/plugin-core/src/test/suite-integ/CreateScratchNoteCommand.test.ts
This PR:
- Renames `Dendron: Lookup Journal Note` and `Dendron: Lookup Scratch Note` commands to `Dendron: Create Journal Note` and `Dendron: Create Scratch Note`
- Modifies `NoteLookupCommand` so that it can accept custom controllers prior to `gatherInput`
- Supply custom controllers in `CreateJournal/SratchNoteCommand` with own set of buttons and quickpick title
- [~] [Write Tests](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#writing-tests) 
- [~] If your tests …
=> chore(workspace): LookupJournal/ScratchNoteCommand cleanup

packages/common-all/data/dendron-yml.validator.json, packages/dendron-next-server/data/dendron-yml.validator.json
This PR
- adds omitted json schema validation for `commands.copyNoteLink` namespace
- [~] code should follow [Code Conventions](dev.process.code)
- [~] circular dependency check: make sure your code is not introducing new circular dependencies in plugin-core.  See [Avoiding Circular Dependencies](dev.process.code.best-practices).
- [~] sticking to existing conventions instead of creating new ones 
- General
- [~] check whether code be simplified
- [~] check if similar function already exist in the codebase. if so, can it be re-used?
- Operations
- …
=> chore: add validation for copyNoteLink namespace

packages/common-server/src/etc.ts, test-workspace/vault/dendron.preview.md
- added HTML Decoding to the copy event handler in `genVSCodeHTMLIndex` in `./packages/common-server/src/etc.ts`
- improved comments jsdoc style
- added testdata to `dendron.preview` in the test-workspace
Related to: #2301
- NOTE: make sure to read [Addressing open issues](https://docs.dendron.so/notes/adc39825-77a6-46cf-9c49-2642fcb4248e.html#addressing-open-issues)
=> fix(views): Code blocks and spans in preview are html encoded

packages/plugin-core/src/commands/Doctor.ts
Adds command type and command scope to the analytics.
Docs: https://github.com/dendronhq/dendron-site/pull/432
=> chore: add analytics for doctor command in plugin

packages/common-all/src/helpers.ts, packages/common-all/src/types/typesv2.ts, packages/engine-server/src/backup/service.ts, packages/plugin-core/src/_extension.ts
fix(workspace): race condition when backing up configuration 
When ensuring that a backup folder exists, actually await the return result
***
- General
- Operations
- Architecture
NA
- [~] If your tests changes an existing snapshot, snapshots have been [updated](dev.process.qa.test)
NA
- [~] if your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your …
=> fix(workspace): race condition when backing up configuration 

packages/engine-server/src/workspace/service.ts, packages/engine-server/src/workspace/utils.ts
Also did some minor cleanup of code.
- [~] circular dependency check: make sure your code is not introducing new circular dependencies in plugin-core.  See [Avoiding Circular Dependencies](https://wiki.dendron.so/notes/pMS27sHxbWeKMoPRrWEzs.html).
- General
- Operations
- Architecture
- eg: …
=> chore(workspace): improve error message for bad or missing code-workspace file

packages/common-all/data/dendron-yml.validator.json, packages/common-all/src/types/workspace.ts, packages/dendron-next-server/data/dendron-yml.validator.json
=> fix: typo in dendron.yml

packages/dendron-plugin-views/package.json, packages/dendron-plugin-views/src/hooks/index.tsx, yarn.lock
- DEPENDENCY_UPDATE: @dendronhq/dendron-plugin-ciews updated mermaid from 8.13.3 to 8.14.0
The update is required to fix the issue with angle brackets syntax. Fixed version is shown below, and the relevant issue is below that.
#2630 
- [~] code should follow [Code Conventions](https://wiki.dendron.so/notes/773e0b5a-510f-4c21-acf4-2d1ab3ed741e.html)
- [~] circular dependency check: make sure your code is not introducing new circular dependencies in plugin-core.  See [Avoiding Circular Dependencies](https://wiki.dendron.so/notes/pMS27sHxbWeKMoPRrWEzs.html).
- [~] sticking to existing conventions instead of creating new ones 
- eg: [if configuration for utilities are already in one module or package, add future utilities there as well](https://github.com/dendronhq/dendron/pull/1960#discussion …
=> fix(views): update mermaid version for mermaid fixes

packages/dendron-next-server/pages/_app.tsx
This PR aims to fix an issue with the rendering of components from dendron-next-server. 
- General
- Operations
- Architecture
- [~] If your tests changes an existing snapshot, snapshots …
=> fix(views): dendron-next-server to pass port-forwarded url

.github/ISSUE_TEMPLATE/bug_report.md
Thanks to @LamentConfiguration for catching this!
=> chore: fix command in the template file

packages/plugin-core/src/test/suite-integ/VaultAddCommand.test.ts
This test runs fine locally on Windows, but fails in CI. Skipping for now, I'll look over this more as I work on self contained vaults.
=> skip native WS self contained vault test on windows

packages/plugin-core/src/commands/MoveNoteCommand.ts, packages/plugin-core/src/components/lookup/LookupControllerV3Factory.ts, packages/plugin-core/src/test/suite-integ/CopyNoteLink.test.ts, packages/plugin-core/src/test/suite-integ/CopyNoteUrl.test.ts, packages/plugin-core/src/test/suite-integ/MoveNoteCommand.test.ts
chore: fix a few flaky tests
Fix tests by extending timeout (CopyNoteLink) and converting MoveNote to new test harness
=> chore: fix a few flaky tests

packages/common-all/src/dnode.ts, packages/plugin-core/src/test/suite-integ/ShowPreview.test.ts, test-workspace/vault/lorem.ipsum.mdone.first.md
Related issue: https://github.com/dendronhq/dendron/issues/2644
- General
- Operations
- Architecture …
=> fix(view): broken preview for links with sub-hierarchy starting with .md

docs.code-search
chore: doc search
this makes it easy to do a full text search of md files in the workspace
https://www.loom.com/share/f53a26462f514cc29a89961a1584cc99?from_recorder=1&focus_title=1
=> chore: doc search

packages/plugin-core/src/test/suite-integ/VaultAddCommand.test.ts
chore: fix VaultAdd tests
convert vaultadd tests from old style to new style test harness
=> chore: fix VaultAdd tests

packages/plugin-core/src/windowWatcher.ts
- Adding DaysSinceCreated + DaysSinceUpdated properties in the NoteView telemetry point
- Making a fix to those that telemetry point where it would fire for any document inside a Dendron workspace. It now only fires when a note recognized by Dendron Engine is open.
Airtable Telem Updated
---
- General
- Operations
- Architecture …
=> chore: days since update + create in noteview telem + fixes

packages/dendron-cli/bin/dendron-cli.ts
Related to #2300 - this PR changes the CLI so that when given unrecognized commands, it will emit an error and usage message.
Before:
After:
- NOTE: make sure to read [Addressing open issues](https://docs.dendron.so/notes/adc39825-77a6-46cf-9c49-2642fcb4248e.html#addressing-open-issues)
This change seemed small enough not to require new automated tests.
=> fix: Make CLI report invalid commands

packages/dendron-cli/src/commands/launchEngineServer.ts
=> fix: CLI writes "cli" as the version into the meta file which breaks initialization

packages/plugin-core/src/abTests.ts, packages/plugin-core/src/showcase/GraphThemeTip.ts, packages/plugin-core/src/views/ShowMeHowView.ts
This PR aims to add a `Show me how` button in the Feature showcase toaster. Currently, we have this for showcasing Graph Themes. 
- General
- [~] check whether code be simplified
- [~] check if similar function already exist in the codebase. if so, can it be re-used?
- Operations
- Architecture
- [~] check if code is introducing changes on a foundational class or interface. if so, call for design review if …
=> chore: 'show me how' button in feature showcase toaster

packages/common-all/src/analytics.ts, packages/common-all/src/constants/views.ts, packages/plugin-core/package.json, packages/plugin-core/src/features/HelpFeedbackTreeview.ts, packages/plugin-core/src/workspace.ts
Adds a Help and Feedback panel to the new Dendron View Container.
---
- General
- Operations
- Architecture
Added to Airtable / Upcoming
- [N/A] [Write Tests](dev.process.qa.test)
=> enhance: help and feedback panel

packages/common-all/src/analytics.ts, packages/plugin-core/package.json, packages/plugin-core/src/constants.ts, packages/plugin-core/src/features/BacklinksTreeDataProvider.ts, packages/plugin-core/src/workspace.ts
Adding telemetry to Backlinks Panel.  
EDIT: Airtable Updated.
=> chore: adding telemetry to backlinks panel

packages/common-all/src/analytics.ts, packages/common-all/src/types/typesv2.ts, packages/dendron-plugin-views/src/components/graph.tsx, packages/plugin-core/src/components/views/NoteGraphViewFactory.ts
This PR aims to add some telemetry around the toggle of graph view and the default graph theme saved by user
- General
- Operations
- Architecture
TODO: update Airtable
- [~] …
=> chore: added telemetry for toggle graph view

packages/engine-server/src/doctor/service.ts
Related issue : https://github.com/dendronhq/dendron/issues/2880
- General
- Operations
- Architecture
NA
NA
NA
NA
=> fix: doctor removeStubs resulting in 'no data' prompt

packages/dendron-plugin-views/package.json, packages/engine-server/package.json, test-workspace/vault/dendron.ref.markdown.md, yarn.lock
- DEPENDENCY_UPDATE: `@dendronhq/engine-server` update `@dendronhq/remark-mermaid` from 0.2.0 to 0.3.0
- DEPENDENCY_UPDATE: `@dendronhq/dendron-plugin-views` update `mermaid` from 8.14.0 to 9.1.1
The first dependency update is needed for #2630, the second one is not but it brings us up to date with the latest mermaid features.
Also added an example of a graph that would have failed before into the test workspace.
- General
- Operations
- Architecture …
=> fix(views): mermaid class diagrams with `<<annotations>>` cause an error

.github/auto_assign.yml
Adds @bpathakota to code reviews to check for scope/commit style
=> add bindhu to code reviews

packages/common-all/src/constants/views.ts, packages/dendron-next-server/styles/scss/content.scss, packages/dendron-plugin-views/src/components/DendronApp.tsx, packages/dendron-plugin-views/src/components/SeedBrowser.tsx, packages/dendron-plugin-views/src/components/Seeds.tsx, packages/dendron-plugin-views/src/index.tsx, packages/plugin-core/src/commands/SeedBrowseCommand.ts
This PR aims to migrate Seed Browser to plugin views from `dendron-next-server`. Came across it while deprecating next server.
- General
- Operations
- Architecture
- [~] can we track the performance of this change to …
=> chore(view): migrate seed browser to plugin views

packages/common-server/src/etc.ts
Fixes the issue by always applying a default theme first, then overriding if needed.
=> fix: preview theme is missing code style blocks when following editor colors

.gitignore, packages/_pkg-template/LICENSE, packages/_pkg-template/package.json, packages/_pkg-template/tsconfig.build.json, packages/_pkg-template/tsconfig.json
chore: new package scaffold
Scaffolding to ease adding new packages in Dendron in the future. Documentation here > [[Adding a new package|dendron://dendron.docs/dev.process.code.monorepo.cook-advanced#adding-a-new-package]]
Will post async when merged
=> chore: new package scaffold

packages/plugin-core/src/commands/RefactorHierarchyV2.ts
The success message of Refactor Hierarchy was displayed as: Dendron updated [object Object],[object Object],[object Object],[object Object] files
- General
- Operations
- Architecture
- CSS …
=> fix(refactor): updated refactor hierarchy message to include no. of files changed

.github/workflows/hackathon-create-test-image.yml
creating a workflow for creating images on hackathon branches
=> chore: create hackathon image building workflow

packages/common-all/src/constants/configs/publishing.ts, packages/common-all/src/index.ts, packages/common-all/src/types/configs/publishing/publishing.ts, packages/common-all/src/util/treeUtil.ts, packages/common-all/src/utils/index.ts, packages/common-all/src/utils/publishUtils.ts, packages/engine-test-utils/src/__tests__/pods-core/NextjsExportPod.spec.ts, packages/engine-test-utils/src/__tests__/pods-core/__snapshots__/NextjsExportPod.spec.ts.snap, packages/nextjs-template/.gitignore, packages/nextjs-template/components/DendronNotePage.tsx, packages/nextjs-template/custom/README.md, packages/pods-core/src/builtin/NextjsExportPod.ts
https://www.loom.com/i/f573ef84983148d6ad8dafcd339f5b65
This is still an experimental feature - still noodling on how to best incorporate custom code points into Dendron.
Will not be included in release notes yet.  Docs here: task.2022.06.18.banner-on-site.docs
=> enhance(publish): Support a custom banner on published page

packages/engine-server/src/markdown/remark/hashtag.ts, packages/engine-server/src/markdown/remark/index.ts, packages/engine-server/src/markdown/remark/userTags.ts, packages/plugin-core/src/features/completionProvider.ts, packages/plugin-core/src/test/suite-integ/CompletionProvider.test.ts
fix(edit): autocomplete issues with tags and mentions
Enhancement to autocomplete broke tags and user mentions. 
Also adds some tests and light refactoring of utilities
=> fix(edit): autocomplete issues with tags and mentions

packages/common-server/src/template.ts, packages/engine-test-utils/src/__tests__/common-all/template.spec.ts, packages/plugin-core/src/test/suite-integ/ApplyTemplateCommand.test.ts
enhance(edit): add capture helper for hb templates
This helper lets users capture parts of a text. Docs: https://github.com/dendronhq/dendron-site/pull/544
=> enhance(edit): add capture helper for hb templates

packages/common-all/src/abTests.ts, packages/plugin-core/src/showcase/GraphThemeTip.ts
This PR aims to close the Show Me How AB Test for Graph Theme Tip.
Taking into account the results of the experiment, we are able to conclude that we need to make the most of both worlds. In order to leverage this insight, we open both views, show me how, and graph view. This would serve as an external trigger for the user to take action.
- General
- Operations
- Architecture
- [~] check if code is introducing changes on a foundational class or interface. if so, …
=> chore(internal): close show me how ab test for graph theme

packages/dendron-cli/.vscode/tasks.json, packages/dendron-cli/src/commands/publishCLICommand.ts
Related : https://github.com/dendronhq/dendron/issues/3093
***
- General
- Operations
- Architecture
NA
NA
NA
NA
NA
=> fix(cli): dendron publish --help to display full list of arguments

packages/nextjs-template/.gitignore, packages/nextjs-template/components/DendronNotePage.tsx, packages/nextjs-template/custom/NoOp.tsx, packages/nextjs-template/custom/README.md
fix(publish): compile error with no banner present
replace require with no-op to appease compiler
=> fix(publish): compile error with no banner present

.github/workflows/ci.yml, packages/engine-test-utils/src/__tests__/dendron-cli/utils/setupEngine.spec.ts, packages/nextjs-template/components/DendronNotePage.tsx, packages/plugin-core/src/WSUtils.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/test/suite-integ/Extension-PostUpgrade.test.ts, packages/plugin-core/src/test/suite-integ/TaskStatus.test.ts, packages/plugin-core/src/test/suite-integ/components/pods/BaseExportPodCommand.test.ts, packages/plugin-core/src/test/suite-integ/migration.test.ts, packages/plugin-core/src/test/testUtilsV3.ts
chore: fix various flaky tests
- extend timeouts on tests that are timing out
- dispose of disposables
- skip a bunch of unecessary initialization steps for tests
=> chore: fix various flaky tests

packages/common-all/src/StatisticsUtils.ts, packages/common-all/src/analytics.ts, packages/common-all/src/index.ts, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/ArchiveHierarchy.ts, packages/plugin-core/src/commands/MoveHeader.ts, packages/plugin-core/src/commands/MoveNoteCommand.ts, packages/plugin-core/src/commands/RefactorHierarchyV2.ts, packages/plugin-core/src/commands/RenameHeader.ts, packages/plugin-core/src/commands/RenameNoteCommand.ts, packages/plugin-core/src/commands/RenameNoteV2a.ts, packages/plugin-core/src/commands/index.ts, packages/plugin-core/src/constants.ts, packages/plugin-core/src/features/RenameProvider.ts, packages/plugin-core/src/test/suite-integ/MoveHeader.test.ts, packages/plugin-core/src/test/suite-integ/StatisticsUtils.test.ts, packages/plugin-core/src/utils/ProxyMetricUtils.ts
This PR:
- Adds proxy metrics for various refactoring commands for easier analytics.
- General
- Operations
- Architecture
- [~] If you are adding a new language feature (graphically visible in VS Code/preview/publishing), an example is included in the [test workspace](dev.ref.test-workspace)
- CSS
- [~] display is correct for following dimensions
- [~] sm: screen ≥ 576px, eg. iphonex, (375x812)
- …
=> chore(internal): add proxy metrics for refactoring commands

packages/dendron-viz/ensureDir.js, packages/dendron-viz/package.json
This PR aims to build dendron-viz package in windows as well, currently building/compiling workspace throws an error, since `cp` is not a command in windows.
- General
- Operations
- Architecture
NA
NA
=> chore(internal): build dendron-viz for windows

packages/plugin-core/src/workspace/workspaceActivator.ts
fix(workspace): bad workspace version when init native workspace
=> fix(workspace): bad workspace version when init native workspace

packages/plugin-core/assets/dendron-ws/tutorial/treatments/no-refactor/tutorial.rich-formatting.md
=> Correct a latex equation in the tutorial

packages/plugin-core/src/commands/Goto.ts, packages/plugin-core/src/commands/OpenLink.ts, packages/plugin-core/src/test/presets/GotoNotePreset.ts, packages/plugin-core/src/test/suite-integ/Goto.test.ts
task: `[[task.2021.11.28.merge-open-links-and-goto-note-command#^mcvpqds17ddr]]`
doc pr: [https://github.com/dendronhq/dendron-site/pull/579](https://github.com/dendronhq/dendron-site/pull/579)
=> enhance(plugin-core): make Goto command also open external links

packages/plugin-core/src/_extension.ts, packages/plugin-core/src/test/suite-integ/SetupWorkspace.test.ts, packages/plugin-core/src/utils/StartupPrompts.ts
chore(workspace): improve initial startup experience
- remove v100 launch screen
- fix lapsed user message being shown to new users
=> chore(workspace): improve initial startup experience

packages/pods-core/src/v2/pods/export/GoogleDocsExportPodV2.ts
task: [[Gdoc Export Pod Should Add Uri Parameter|task.2022.07.07.gdoc-export-pod-should-add-uri-parameter]]`
doc pr:
=> enhance(pod): Add url of gdoc created as uri in frontmatter

packages/plugin-core/src/utils/ExtensionUtils.ts
Introduced from the merging of the weekly release branch into master. https://github.com/dendronhq/dendron/pull/3232
=> chore: fixing build issue in extensionutils

packages/common-all/src/types/typesv2.ts, packages/common-frontend/src/features/ide/slice.ts, packages/dendron-plugin-views/src/components/DendronApp.tsx, packages/dendron-plugin-views/src/components/DendronGraphPanel.tsx, packages/dendron-plugin-views/src/components/graph.tsx, packages/dendron-plugin-views/src/hooks/useGraphElements.tsx, packages/dendron-plugin-views/src/styles/custom.ts, packages/dendron-plugin-views/src/styles/theme-block.ts, packages/dendron-plugin-views/src/utils/graph.ts, packages/engine-server/src/metadata/service.ts, packages/plugin-core/package.json, packages/plugin-core/src/constants.ts, packages/plugin-core/src/views/GraphPanel.ts, packages/plugin-core/src/workspace.ts
This PR aims to : 
1. Add options to toggle display of backlinks and outward links in the Graph Panel.
2. Adds arrows for linked edges in graph.
3. Updates linked edges of Block theme from `unbundled-bezier` to `bezier`. This is to keep the dense graph clean.
***
- [Docs link](https://github.com/dendronhq/dendron-site/pull/583)
loom: https://www.loom.com/share/099ae94230464a9b9885a85ffd48573b
***
- General
- Operations
- Architecture …
=> enhance(views): filter linked edges(backlinks and outward links) from graph panel.

packages/plugin-core/src/_extension.ts, packages/plugin-core/src/utils/StartupUtils.ts, test-workspace/dendron.code-workspace
This PR aims to display a modal on initialization for users that have `dendron-markdown-links` extension installed. On Clicking uninstall, the extension is uninstalled.
***
- General
- Operations
- Architecture
- [~] if you are adding analytics …
=> fix(workspace): information modal to uninstall 'dendron markdown links' extension

packages/nextjs-template/components/DendronTreeMenu.tsx
This PR aims the fix the issue with the current item on the sidebar not collapsing. 
- General
- Operations
- Architecture
- [~] can we track the performance of this change to know if it is …
=> fix(publish): current menu item on the sidebar wont collapse for a published site

packages/plugin-core/src/views/GraphPanel.ts
This PR:
- Fixes graph panel depth increase / decrease button not working.
- General
- Operations
- Architecture
- [~] [Write …
=> fix(views): graph panel depth increase / decrease button not working

packages/common-all/src/analytics.ts
=> chore: fix bad event name

packages/engine-server/src/markdown/remark/noteRefsV2.ts, packages/engine-test-utils/src/__tests__/engine-server/markdown/__snapshots__/noteRefv2.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/markdown/noteRefv2.spec.ts
enhance(pr): support end block anchor
This supports end block anchor of [[47 Better Note References|dendron://dendron.docs/rfc.47-better-note-references]]
https://github.com/dendronhq/dendron/pull/3248
docs: https://github.com/dendronhq/dendron-site/pull/593
=> enhance(pr): support end block anchor

packages/common-server/src/analytics.ts, packages/engine-server/src/metadata/service.ts, packages/plugin-core/assets/dendron-ws/tutorial/treatments/quickstart-skip-welcome/tutorial.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/quickstart-v1/tutorial.md, packages/plugin-core/src/components/views/PreviewLinkHandler.ts, packages/plugin-core/src/survey.ts
chore: update tutorial analytics & content
- track team knowledge base intent 
- add link to report bugs and issues with tutorial
New metrics:
- [teamIntent](https://airtable.com/appVUixSC6jZbSUI1/tblHzTJJL5aVhJMYq/viwB7nxuhGKf5vUPD/recA1whOyG1dCJlig?blocks=hide)
=> chore: update tutorial analytics & content

packages/engine-server/src/workspace/vscode.ts, packages/plugin-core/src/test/testUtilsv2.ts, test-workspace/dendron.code-workspace, test-workspace/dependencies/localhost/vault3/dendron.code-workspace
- List `dendron.dendron-markdown-preview-enhanced` as unwantedRecommendation for Dendron workspaces/vaults when initialized, since Dendron show preview is what is used today and built-in to Dendron
> **NOTE:** Should evaluate unpublishing the unwanted extensions? ([unpublishing VSCode extensions via SO](https://stackoverflow.com/a/60444475/5340149)) - not sure if "unpublish" means that it will be a reserved extension/namespace or not, from a security perspective?
If you are a team member, copy and paste the template from [Dendron Extended PR …
=> fix(workspace): List dendron.dendron-markdown-preview-enhanced as unwantedRecommendation

Makefile
Based on [this blog post](https://spin.atomicobject.com/2021/03/22/makefiles-vs-package-json-scripts/).
Makefile commands can be called much like `npm run <script>` commands PLUS you can have *comments* in the Makeful, unlike package.json.
This PR has some simple commands that simplify setting up the project for new developers.
```
Clone the repository
Make sure you node version is LTS (16 at the moment).
Call `make cleanBuild`
```
Want to watch for changes? 
`make watch`.
Easy to remember and lookup commands. …
=> build: add a Makefile for simplified build commands

packages/dendron-plugin-views/src/hooks/index.tsx, packages/dendron-plugin-views/src/types/window.d.ts, packages/nextjs-template/components/DendronCollection.tsx, packages/nextjs-template/pages/notes/[id].tsx, packages/nextjs-template/tsconfig.build.json, packages/nextjs-template/tsconfig.json, packages/nextjs-template/types/window.d.ts, packages/nextjs-template/utils/build.ts, packages/nextjs-template/utils/getStaticPropsUtil.tsx
I had a hard time groking the build process for the nextjs application.  So I made some changes that should make things easier to grok in the future.
Notably:
* lots of comments
* lots of typings
* removing unused dependencies
Perhaps easiest to review going commit by commit?
Making this PR before the changeset gets any larger.
- General
- Operations
- Architecture …
=> refactor(nextjs-template): general comments small changes

packages/common-server/src/etc.ts
=> fix: nested bullets in preview (#3139)

packages/plugin-core/src/workspace/tutorialInitializer.ts, packages/plugin-core/src/workspace/workspaceActivator.ts, packages/plugin-core/src/workspace/workspaceInitializer.ts
This PR:
- fixes circular dependencies introduced in https://github.com/dendronhq/dendron/commit/724c6f29b4a11f4ce0fa01fb7e50ee522a6798d3
```sh
>pwd                                                                                 (chore/fix-circ-dependencies|⚑1✔)
/Users/hikchoi/dev/dendronhq/dendron/packages/plugin-core
>madge --circular --extensions ts .                                                  (chore/fix-circ-dependencies|⚑1✔)
Processed 375 files (1.5s) (18 warnings)
✔ No circular dependency found!
>
```
=> chore(internal): fix circular dependencies

packages/plugin-core/src/test/suite-integ/NoteLookupCommand.test.ts
This PR
- removes the stray `.only` that sneaked in with my PR because my husky hook is broken locally
=> chore(internal): clean up test code

packages/common-all/data/dendron-yml.validator.json, packages/common-all/src/constants/configs/workspace.ts, packages/common-all/src/types/configs/workspace/workspace.ts, packages/common-server/src/template.ts, packages/common-test-utils/src/presets/notes.ts, packages/engine-server/src/migrations/utils.ts, packages/engine-test-utils/src/__tests__/common-all/template.spec.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/engine-test-utils/src/presets/engine-server/utils.ts, packages/plugin-core/src/test/suite-integ/ApplyTemplateCommand.test.ts, packages/plugin-core/src/test/suite-integ/CopyNoteRef.test.ts, packages/plugin-core/src/test/utils/workspace.ts, packages/plugin-core/src/utils/ExtensionUtils.ts, packages/plugin-core/src/utils/StartupUtils.ts, test-workspace/dendron.yml
This PR:
- Removes all references to `enableHandlebarTemplates`
- Removes deprecated `applyLodashTemplates`
- updates snapshots for tests
- remove old tests
- rewords current tests a bit
- `enableHandlebarTemplates` property from the even `InitializeWorkspace` has been removed.
- General
- Operations
- Architecture
- CSS …
=> chore: remove enable handlebar template config

packages/plugin-core/src/test/suite-integ/VaultAddCommand.test.ts
This PR aims to fix tests for `Vault Add` command on windows
=> chore(workspace): fix windows test for vault add command

packages/common-all/src/dnode.ts
- Related to #2467
- Discord handle is `queueknee#9509`
Before:
After:
=> enhance(lookup): add space between note title and vault name

packages/plugin-core/src/showcase/FeatureShowcaseToaster.ts
enhance(workspace): only show the feature showcase once
=> enhance(workspace): only show the feature showcase once

packages/dendron-plugin-views/src/components/DendronApp.tsx, packages/dendron-plugin-views/src/components/DendronNotePreview.tsx, packages/plugin-core/src/_extension.ts, packages/plugin-core/src/commands/TogglePreviewLock.ts, packages/plugin-core/src/test/suite-integ/TogglePreviewLock.test.ts
- Removes preview lock button from other panel views. https://www.loom.com/i/8deabd68e4ed4266b138535010bda576
- Adds scollfix to to preview lock button.
[[Solve Issues with Preview Lock Button|dendron://private/task.2022.08.05.fix.solve-issues-with-preview-lock-button]]
=> fix(views): resolve issues with preview lock button

packages/plugin-core/package.json, yarn.lock
fix(workspace): remove bad dependency which was causing error on parsing notes
=> lock title dependency

packages/engine-server/src/markdown/remark/noteRefsV2.ts, packages/engine-server/src/markdown/utils.ts, packages/engine-server/src/markdown/utilsv5.ts
chore: remove old version of mdutils
=> chore: remove old version of mdutils

packages/plugin-core/src/test/suite-integ/ConfigureLocalOverride.test.ts, packages/plugin-core/src/test/suite-integ/Extension-PostInstall.test.ts
This PR aims to fix test cases for windows.
=> chore: fix windows tests

bootstrap/scripts/buildPatch.sh, bootstrap/scripts/fastRebuild.sh, bootstrap/scripts/helpers.sh, bootstrap/scripts/install.sh, bootstrap/scripts/lerna-helpers.sh, bootstrap/scripts/stats.sh, bootstrap/scripts/test-ci-plugin.sh, bootstrap/scripts/watch.sh
I am using fish shell and encountered some had a missing sheband and I
updated the rest to use `#!/usr/bin/env`.
=> chore: update shell script shebangs

packages/plugin-core/package.json, packages/plugin-core/src/constants.ts
Updates the visibility of Copy Note URL command in codespaces
=> fix: updated visibility of copy note url command in codespaces

packages/common-all/src/types/noteTrait.ts, packages/plugin-core/src/commands/CreateNoteWithTraitCommand.ts, packages/plugin-core/src/test/suite-integ/components/traits/CreateNoteWithTraitCommand.test.ts, packages/plugin-core/src/test/suite-integ/components/traits/TestTrait.ts
task: `[[Specify Vault for Note Trait|task.2022.08.23.specify-vault-for-note-trait]]`
=> enhance(editing): new api for onCreate of note traits

packages/plugin-core/src/utils/ExtensionUtils.ts
This PR:
- adds new event properties `extensionsDetail`, `numExtensions`, and `codeFoldersCreated`
- General
- Operations
- Architecture
- [~] If your tests changes an existing snapshot, snapshots have been [updated](dev.process.qa.test)
- [~] If you are adding a new language feature (graphically …
=> chore(internal): add extended analytics

packages/plugin-core/src/test/suite-integ/ApplyTemplateCommand.test.ts, packages/plugin-core/src/test/suite-integ/CopyNoteRef.test.ts
updated timeout for a few tests that were failing in CI. They were already with the new test harness
=> chore(internal): fix flaky test

packages/plugin-core/package.json, packages/plugin-core/src/constants.ts
This PR aims to fix visibilty of Toggle Preview command in codespace
=> fix: visibilty of Toggle Preview in codespace

packages/common-all/src/abTests.ts, packages/plugin-core/assets/dendron-ws/vault/welcome_video.html, packages/plugin-core/src/WelcomeUtils.ts
This PR aims to add an AB test for 1 min feature highlights video in the Welcome screen displayed after running `Launch Tutorial` command. 
- used `webm` format for video, with `.mp4` there was no sound.
- General
- Operations
- Architecture
- [~]  is this a developer BREAKING change? if another person cloning from …
=> chore: ab test for video in launch tutorial welcome screen

packages/plugin-core/src/test/suite-integ/ApplyTemplateCommand.test.ts, packages/plugin-core/src/test/suite-integ/CreateMeetingNoteCommand.test.ts, packages/plugin-core/src/test/suite-integ/TaskStatus.test.ts
This PR aims to increase timeout of few flaky tests
=> chore: increase timeout for flaky tests

packages/common-all/data/dendron-yml.validator.json, packages/common-all/src/constants/configs/global.ts, packages/common-all/src/constants/configs/preview.ts, packages/common-all/src/constants/configs/publishing.ts, packages/common-all/src/types/configs/global/global.ts, packages/common-all/src/types/configs/preview/preview.ts, packages/common-all/src/types/configs/publishing/publishing.ts, packages/common-all/src/utils/index.ts, packages/dendron-plugin-views/src/hooks/index.tsx, packages/dendron-plugin-views/src/utils/dendronConfig.ts, packages/engine-server/src/migrations/utils.ts, packages/engine-test-utils/src/__tests__/dendron-cli/commands/__snapshots__/seedCLICommand.spec.ts.snap, packages/engine-test-utils/src/__tests__/engine-server/__snapshots__/seedSvc.spec.ts.snap, packages/nextjs-template/components/MermaidScript.tsx, packages/plugin-core/src/test/utils/workspace.ts, packages/unified/src/utilsWeb.ts, packages/unified/src/utilsv5.ts, test-workspace/dendron.yml
This PR aims to remove the enableMermaid config
Docs Update PR: https://github.com/dendronhq/dendron-site/pull/651
=> chore(internal): remove enableMermaid config

packages/engine-server/src/drivers/file/storev2.ts, packages/engine-server/src/enginev2.ts
chore: more logging around engine init
=> chore: more logging around engine init

packages/plugin-core/src/test/suite-integ/ReloadIndex.test.ts
fix for : https://github.com/dendronhq/dendron/actions/runs/3132820573/jobs/5085550582
=> chore(internal): fix reload index flaky test on windows

packages/engine-server/src/enginev2.ts
chore: info logs set to error
correct some bad log levels
=> chore: info logs set to error

packages/plugin-core/src/_extension.ts, packages/plugin-core/src/test/suite-integ/Extension.test.ts, packages/plugin-core/src/utils/StartupUtils.ts
fix for issue with Dendron init on nightly 114.2
=> chore: updated ping args to send single echo request

packages/engine-server/src/topics/git.ts
related issue: https://github.com/dendronhq/dendron/issues/3463
=> fix(workspace): convert local vault to remote

packages/common-all/src/abTests.ts, packages/plugin-core/assets/dendron-ws/vault/welcome_video.html, packages/plugin-core/src/WelcomeUtils.ts
This PR aims to close the video tutorial AB tests and makes the video default on the Welcome page.
=> chore(internal): close video tutorial ab test

bootstrap/scripts/buildPatch.sh
The extensionTarget variable was renamed to extensionType
=> chore: fixing CLI arguments in buildPatch.sh

.github/workflows/ci-perf.yml, .github/workflows/performace-tests.yml, package.json, packages/plugin-core/.vscode/launch.json, packages/plugin-core/package.json, packages/plugin-core/src/test/perf-test/PerfTesting.test.ts, packages/plugin-core/src/test/perf-test/index.ts, packages/plugin-core/src/test/runPerfTest.ts, packages/plugin-core/src/test/suite-integ/index.ts, packages/plugin-core/src/test/testUtilsV3.ts
This PR aims to add performance tests to engine methods and pushes result report to Airtable.
Airtable: https://airtable.com/appCWyZZPrLlVUblF/tbl0spyZvEsizgw2Y/viw4xGEjmfRHtaYJi?blocks=hide
=> chore(internal): performance testing for engine methods

.github/workflows/create-release-image.yml
This PR aims to allow manually trigger create release image pipeline
=> chore: add manual trigger to create release image action

packages/common-all/src/engine/EngineV3Base.ts, packages/engine-server/src/engineClient.ts
**Background**
Lookup on v3 was taking a long time (upwards of up to ~10sec). The reason is that the engine v3 queries in the following steps
1. Query results from fuse Engine
2. For each result, get note body from file system
For our org-workspace, step 1 can lead to 10k+ notes which is causing the latency issues. It's not an issue in v2 b/c the note body is all stored in memory.
**Changes**
- Cap number of results from step 1. In lookup, we cap the query results to 50 so by capping on the engine side first, it won't effect the lookup results.
- Cap on engine is arbitrarily set to 100 for now
**Todo**
- This might affect other use cases of `queryNotes` such as Doctor that might expect more than 100 results. However, I believe it makes sense to have a sensible cap when possible as we …
=> chore(workspace): Cap number of query results from engine

bootstrap/scripts/buildNightly.sh
=> chore: fixing param argument in buildNightly.sh

packages/plugin-core/package.json, packages/plugin-core/src/constants.ts, packages/plugin-core/src/test/suite-integ/ConvertVaultCommand.test.ts, packages/plugin-core/src/test/suite-integ/DoctorCommand.test.ts, packages/plugin-core/src/test/suite-integ/MoveSelectionToCommand.test.ts, packages/plugin-core/src/test/suite-integ/PreviewLinkHandler.test.ts, packages/plugin-core/src/test/suite-integ/ReferenceProvider.test.ts, packages/plugin-core/src/test/suite-integ/ReloadIndex.test.ts, packages/plugin-core/src/test/suite-integ/RenameHeader.test.ts, packages/plugin-core/src/test/suite-integ/RenameProvider.test.ts, packages/plugin-core/src/test/suite-integ/SetupWorkspace.test.ts, packages/plugin-core/src/test/suite-integ/TaskStatus.test.ts, packages/plugin-core/src/test/suite-integ/VaultAddCommand.test.ts
=> chore: update enablement of lookup web commands and update timeout for flaky tests

packages/common-all/package.json, packages/engine-server/package.json, packages/engine-server/src/drivers/file/parseAllNoteFilesForSqlite.ts, packages/engine-server/src/drivers/sqlite/SqliteMetadataStore.ts, packages/engine-server/src/drivers/sqlite/SqliteQueryUtils.ts, packages/engine-server/src/drivers/sqlite/tables/HierarchyTableUtils.ts, packages/engine-server/src/drivers/sqlite/tables/LinksTableUtils.ts, packages/engine-server/src/drivers/sqlite/tables/NotePropsFtsTableUtils.ts, packages/engine-server/src/drivers/sqlite/tables/NotePropsTableUtils.ts, packages/engine-server/src/drivers/sqlite/tables/SchemaNotesTableUtils.ts, packages/engine-server/src/drivers/sqlite/tables/VaultNotesTableUtils.ts, packages/engine-server/src/drivers/sqlite/tables/VaultsTableUtils.ts, packages/engine-test-utils/src/__tests__/engine-server/sqlite/parseAllNoteFilesForSqlite.spec.ts, packages/engine-test-utils/src/audit.ts, yarn.lock
- chore(internal): use `neverthrow` from `common-all`
- chore(internal): update neverthrow
- fix(internal): ts error
=> chore(internal): neverthrow upgrade

packages/plugin-core/assets/dendron-ws/tutorial/treatments/quickstart-skip-welcome/tutorial.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/quickstart-v1/tutorial.md, packages/plugin-core/assets/dendron-ws/tutorial/treatments/quickstart-with-lock/tutorial.md
- **braden#8857**
- [PR #696 in dendron-site](https://github.com/dendronhq/dendron-site/pull/696)
Copied
=> fix: appy to apply in tutorial

packages/plugin-core/src/commands/pods/BaseExportPodCommand.ts, packages/plugin-core/src/commands/pods/GoogleDocsExportPodCommand.ts
=> fix: gdoc parent folder prompt issue

packages/plugin-core/assets/dendron-ws/tutorial/treatments/quickstart-v1/tutorial.md
- Sorry, made this by editing on GitHub 
=> fix: Typo "Appy" -> "Apply"

README.md
Adds link to halting development annoucement
=> Update README.md to add notice of halted development
